### ISSUE TITLE
Azure Service Bus Session Recievers

### ISSUE THREAD

**Issue by davidlenthall** [Azure/azure-sdk-for-node#1147]
We're developing an app that uses a service bus to send messages between the different components. We want to use sessions to group certain messages, but according to this: http://msdn.microsoft.com/en-us/library/windowsazure/hh780771.aspx, we're unable to uses session receivers with node.js (I'm assuming REST is used behind the scenes). Is there any plan to introduce these to the SDK in the near future?<p><a href="https://github.com/Azure/azure-sdk-for-node/issues/1147">https://github.com/Azure/azure-sdk-for-node/issues/1147</a></p>

**Comment by davidlenthall** [comment]
I know this is closed, but has this been implemented, or is it just part of the backlog?

**Comment by devigned** [comment]
This is not implemented, and will likely not be implemented outside of Microsoft.ServiceBus.dll.

@djrosanova do you have any comment on this one?
