### ISSUE TITLE
Suggestion for README.md change for Compute Management

### ISSUE THREAD

**Issue by ryan1234** [Azure/azure-sdk-for-node#1180]
https://github.com/WindowsAzure/azure-sdk-for-node/blob/master/lib/services/computeManagement/README.md

On line 41:

```javascript
  pem: fs.readFileSync('')
```

I had to toString the result of the readFileSync call to make the client work.  My change looks like this:

```javascript
  pem: fs.readFileSync('').toString()
```

Got some odd errors as a result of using the example in the README.  Maybe the example works for most people, in which case ignore this. =)<p><a href="https://github.com/Azure/azure-sdk-for-node/issues/1180">https://github.com/Azure/azure-sdk-for-node/issues/1180</a></p>

**Comment by matt-gibbs** [comment]
Need to validate code samples in the README files.

**Comment by markcowl** [comment]
This is fixed.  Please reopen if you see a recurrence
