### ISSUE TITLE
File path too long

### ISSUE THREAD

**Issue by whuwb** [Azure/azure-sdk-for-node#1186]
Unable to deploy to azure!

Hi, I used vs 2013 and the node.js tools for development.

After i installed the azure package, i can run successfully in local.

But i got the errors below while deploying to azure:
Error   1   Copying file obj\Debug.\node_modules\azure\node_modules\request\node_modules\form-data\node_modules\combined-stream\node_modules\delayed-stream\test\integration\test-delayed-http-upload.js to obj\Debug\Package\PackageTmp.\node_modules\azure\node_modules\request\node_modules\form-data\node_modules\combined-stream\node_modules\delayed-stream\test\integration\test-delayed-http-upload.js failed. The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.      0   0   PersonalSite<p><a href="https://github.com/Azure/azure-sdk-for-node/issues/1186">https://github.com/Azure/azure-sdk-for-node/issues/1186</a></p>

**Comment by jdalton** [comment]
Just a heads up. [lodash v3](https://github.com/lodash/lodash/releases/tag/3.0.0) has significantly reduced the dep graphs of its modularized packages.

**Comment by gamicklisafisher** [comment]
I had this problem for a long time.
My friend recommended me Long Path Tool for fixing this.
