### ISSUE TITLE
loadBalancedEndpointSetName does not work

### ISSUE THREAD

**Issue by Baastax** [Azure/azure-sdk-for-node#1231]
When using computeManagementClient.virtualMachines.create and having something like this in inputEndpoints config:

            inputEndpoints: [
                {
                    name: &quot;ssh&quot;,
                    port: 22,
                    localPort: 22,
                    protocol: &quot;tcp&quot;
                },
                {
                    loadBalancedEndpointSetName: &quot;node&quot;,
                    port: 3000,
                    localPort: 3000,
                    protocol: &quot;tcp&quot;
                }
            ]

Will result in: 

Error: InputEndpoint has a missing, misspelled or out of order element. 

Creating normal endpoints works fine.<p><a href="https://github.com/Azure/azure-sdk-for-node/issues/1231">https://github.com/Azure/azure-sdk-for-node/issues/1231</a></p>

**Comment by amarzavery** [comment]
closing this as it is too old.
