### ISSUE TITLE
Invalid link to documentation in comment for QueueOperations.prototype.list

### ISSUE THREAD

**Issue by huguesv** [Azure/azure-sdk-for-node#1250]
From serviceBusManagementClient.js, the link to msdn gives a content not found page:
  /**
   * Enumerates the queues in the service namespace. The result is returned in
   * pages, each containing up to 100 queues. If the namespace contains more
   * than 100 queues, a feed is returned that contains the first page and a
   * next link with the URI to view the next page of data.  (see
   * http://msdn.microsoft.com/en-us/library/windowsazure/hh780759.asp for
   * more information)
   * 
   * @param {string} namespaceName The namespace name.
   * 
   * @param {function} callback
   * 
   * @returns {Stream} The response stream.
   */<p><a href="https://github.com/Azure/azure-sdk-for-node/issues/1250">https://github.com/Azure/azure-sdk-for-node/issues/1250</a></p>

**Comment by amarzavery** [comment]
closing this as it is too old.
