### ISSUE TITLE
Missing connectionstring keys

### ISSUE THREAD

**Issue by raykpontimax** [Azure/azure-sdk-for-node#1254]
servicebussettings.js (/util/Constants)  is missing connectionstring validKeys members for:

RuntimePort and ManagementPort<p><a href="https://github.com/Azure/azure-sdk-for-node/issues/1254">https://github.com/Azure/azure-sdk-for-node/issues/1254</a></p>

**Comment by vicneanschi** [comment]
Trying to connect to on-premises windows service bus. 
Using the Get-SBClientConfiguration to get connection string.
Getting _Error: Invalid connection string setting key "runtimeport"_.

Any ETA on this?
Thanks.

**Comment by ragnarol** [comment]
I am hitting this as well trying to connect to a local service bus. When I remove this two settings I get that the connection string is incomplete. 

Is this being progressed?

**Comment by vicneanschi** [comment]
I switched to RabbitMQ

**Comment by altano** [comment]
Why was this closed?  It's definitely still broken.  Can someone take a look? @amarzavery @guangyang
