### ISSUE TITLE
[ServiceBus] Can't retrieve message: ECONNRESET error

### ISSUE THREAD

**Issue by sescandell** [Azure/azure-sdk-for-node#1255]
Hi there,

I'm trying to use the Service Bus from the NodeJS SDK... but get some errors on retrieving messages posted.

My package.json dependency:

``` json
 "dependencies": {
    "azure": "^0.9.11"
 }
```

NodeJS version: 0.10.29
Here is my simplified code:

``` javascript
var azure = require('azure');
var azureServiceBus = azure.createServiceBusService();
    azureServiceBus.sendTopicMessage('default', 'test', function(err) {
        if (err) {
        console.log(process.pid + " - " + 'sendTopicMessage failed: ' + JSON.stringify(err));
    } else {
            console.log('Sent!!!');
            console.log('Retrieving message');
            azureServiceBus.receiveSubscriptionMessage('default', 'my_subscription', function(err, receivedMessage) {
                if (err) {
                    if (err !== 'No messages to receive') {
                        console.log(process.pid + " - " + 'Error receiving message: ' + JSON.stringify(err));
                    }
                    console.log(process.pid + " - " + err);
        }

                if (receivedMessage) {
                    console.log(process.pid + " - " + 'Brut: ' + receivedMessage);
                }
                console.log('Received');
            });
        }
    });
```

Result:

``` bash
Sent!!!
Retrieving message
42076 - Error receiving message: {"code":"ECONNRESET","errno":"ECONNRESET","syscall":"read"}
42076 - Error: read ECONNRESET
Received
```

Subscription and topic exist
I know the sendTopicMessage works well because, from the portal, I can see message counter in other subscriptions is incremented
From the portal, on the subscription "my_subscription" counter stay empty. Meaning that my subscription grabbed well the message from the service bus... but I don't have this result in my callback...

I'm guessing a SDK error or something badly interacting with the request object.

Any clue on that please?
Does anyone using the service bus can make it work?

Thank you,

**Comment by jjongsma** [comment]
Started seeing this a lot again just recently. Anyone else?

**Comment by federicomaffei** [comment]
@jjongsma +1 this has been happening since the last 24 hours on Service Bus. Where could we alert the Azure team?

**Comment by derekseymour** [comment]
Same here, lots of ECONNRESET errors as of late

**Comment by sye1774** [comment]
I've been experiencing this as well since 3/14/16.

**Comment by tony-gutierrez** [comment]
Experiencing this problem as well.
