### ISSUE TITLE
EADDRINUSE error on Service Bus requests

### ISSUE THREAD

**Issue by martinza78** [Azure/azure-sdk-for-node#1290]
We're putting some load through a node app on Azure using the sdk for service bus. We're getting the following error when putting messages onto, receiving them from , deleting and unlocking them. This error only happens directly on a call to service bus.

To make it worse the error is intermittent and only when we start loading the requests. If we take out the service bus there isn't a problem. 

{&quot;stack&quot;:&quot;Error: connect EADDRINUSE\n at errnoException (net.js:904:11)\n at Object.afterConnect [as oncomplete] (net.js:895:19)&quot;,&quot;message&quot;:&quot;connect EADDRINUSE&quot;,&quot;code&quot;:&quot;EADDRINUSE&quot;,&quot;errno&quot;:&quot;EADDRINUSE&quot;,&quot;syscall&quot;:&quot;connect&quot;}<p><a href="https://github.com/Azure/azure-sdk-for-node/issues/1290">https://github.com/Azure/azure-sdk-for-node/issues/1290</a></p>

**Comment by amarzavery** [comment]
Closing this issue due to age.
