### ISSUE TITLE
Slow response time when posting to service bus due to no reuse of connections

### ISSUE THREAD

**Issue by markusahlstrand** [Azure/azure-sdk-for-node#1338]
We've been experiencing long response times when posting to the service bus using the azure npm package compared to what we get using the .net nuget package. We think this might be because the https connection is terminated after each request. I tried using the keep-alive-agent inside azure-common/serviceclient.js and it drastically improved the response times. I saw some references to the forever-client in the old azure npm-package but couldn't find anything in the azure-sb package.

Is there a plan on how to handle keep-alive in the azure-npm packages?

/Markus

**Comment by djrosanova** [comment]
Check out the AMQP packages for node that allow you to use a better transport than HTTP: https://github.com/noodlefrenzy
