### ISSUE TITLE
Token example for Resource Management

### ISSUE THREAD

**Issue by McDonnellDean** [Azure/azure-sdk-for-node#1366]
Hi,

I was wondering if there was any documentation or if somebody could help me figure out how to get running with this SDK and Azure Resource Management. It seems to use a different way of authenticating than the rest of the SDK and I am finding it impossible to figure out how to generate the required token I need.

Thanks!

**Comment by markcowl** [comment]
@McDonnellDean The library is used with AD authentication in azure xplat cli here:  https://github.com/Azure/azure-xplat-cli

**Comment by McDonnellDean** [comment]
@markcowl I went deep diving and figured it out in the end. I actually have a fairly robust sample to share if anyone else is looking: https://github.com/McDonnellDean/nscale-azure-analyzer/blob/master/lib/fetchAzureData.js

It's part of a bigger project but it handles creating the token and correctly calling the service. If I get some time of the coming weeks I'll add a bear bones sample to the `/eg` and update the ServiceManagement README.md

**Comment by mkliu** [comment]
@mcdonnelldean is there a way without storing the cleartext password?

**Comment by mcdonnelldean** [comment]
@mkliu Not that I have found, it seems to need all of those items to work correctly for what I need it to do :(

**Comment by Balrog30** [comment]
Almost a year later and this is about the best example I've found so far. There seems to be very little documentation to help people using the node apis with the newer azure management systems.
