### ISSUE TITLE
broken example

### ISSUE THREAD

**Issue by mikermcneil** [Azure/azure-sdk-for-node#1373]
heads up y'all, example here is broken https://github.com/Azure/azure-sdk-for-node/tree/master/lib/services/computeManagement#manage-virtual-machine

```
Cannot call method 'list' of undefined
```

Replacing with `azureClient.virtualMachineOSImages.list(function (err, result) {` works like a charm.

**Comment by mikermcneil** [comment]
Started working on a deeper integration here: http://node-machine.org/machinepack-azure/list-images

We've had a lot of confusion about exactly what's going on w/ certs.  In case anyone else is working on this, here's where we're at so far for docs:

```
Download or generate the `.pem` certificate file associated with your Azure account.

For info on generating a new certificate file, see http://azure.microsoft.com/en-us/documentation/articles/virtual-machines-linux-use-ssh-key/.  An easy way to grab your existing certificate file is to install the Azure CLI tool with `sudo npm install -g azure-cli` (https://github.com/Azure/azure-xplat-cli) and run `azure account cert export`.  To make the command-line tool work, you\'ll need to follow the directions to set up an organizational account here: http://azure.microsoft.com/en-us/documentation/articles/xplat-cli/.  Note that the uploaded certificate is in `.cer` format, but you should use the `.pem` version here.

https://github.com/Azure/azure-sdk-for-node/tree/master/lib/services/computeManagement#authentication
```

(so far, tried the .pem and .cer w/ no luck.)

So since you have to read in a certificate file to make this work, I've been using this quick command from the node REPL to test it out (that's my subscription id for my account- don't care about it, will regenerate before doing anything important)

```js
require('machinepack-azure').listImages({subscriptionId: '30dad3ba-bc2f-4589-8bbe-0344232ff187', certificate: require('fs').readFileSync('/Users/mikermcneil/azureCert.cer', 'utf8')}).exec(console.log)
```


I used openssl to generate the cert (there's a link to the tutorial i followed in the machine- see the link I included above)


Oh one more thing- here's where I left off and what I was going to try next:

 There seems to be some thing called the "publish settings file" that's an alternative to generating and uploading the cert manually (which by the way, as far as I can tell, the second option does not work curently- at least the way I was doing it.  Also tried going through and following the instructions to set up an operational account / active directory thing)

I found it mentioned here: https://github.com/Azure/azure-xplat-cli#use-publish-settings-file-management-certificate-authentication

Also ran across this, from https://msdn.microsoft.com/library/azure/hh531793.aspx#BKMK_AccountVCert

**Comment by amarzavery** [comment]
We have recently published a new version of [azure-arm-compute](https://www.npmjs.com/package/azure-arm-compute) targeting the ARM Azure API (V2). This package exposes a better client side API compared to the previous one. Please feel free to use it and report issues if any.
