### ISSUE TITLE
serviceBusService.receiveSubscriptionMessage performance issue in v0.10.3

### ISSUE THREAD

**Issue by freshlogic** [Azure/azure-sdk-for-node#1374]
I have an app that makes around 25 simultaneous calls to serviceBusService.receiveSubscriptionMessage using something like the following:

`serviceBusService.receiveSubscriptionMessage(topic, subscription, { isPeekLock: true, timeoutIntervalInS: 60 }, callback)`

When I have topics that have a large amount of messages the throughput is fine with v0.10.2. In v0.10.3 the throughput drops to around 1 message per minute.

**Comment by arunyadavait** [comment]
I am working on a project and my project requirement wants me to receive message from topic subscription( on message )using node.js
I am following this link:- http://dl.windowsazure.com/nodedocs/servicebusservice.js.html
but confused about how to implement callback in following function :
ServiceBusService.prototype.receiveSubscriptionMessage = function (topicPath, subscriptionPath, optionsOrCallback, callback) {
  var options = null;
  if (typeof optionsOrCallback === 'function' && !callback) {
    callback = optionsOrCallback;
  } else {
    options = optionsOrCallback;
  }
  validateTopicName(topicPath);
  validateSubscriptionName(subscriptionPath);
  var subscriptionFullPath = createSubscriptionPath(topicPath, subscriptionPath);
  this._receiveMessage(subscriptionFullPath, options, callback);
};

**Comment by fooka03** [comment]
What's the status on this issue?  Has it been addressed in 0.10.4+ or is it still not resolved?

**Comment by jtaubensee** [comment]
@freshlogic - Sorry for the delay. Are you still experiencing this issue?

**Comment by freshlogic** [comment]
We've been using v0.10.6 without this issue.

**Comment by satowine1** [comment]
Same here with 0.10.6, 1 min per message. It's useless for now. Any suggestions?
