### ISSUE TITLE
List of VM's instead of VM images

### ISSUE THREAD

**Issue by rohitsahasrabudhe** [Azure/azure-sdk-for-node#1382]
Is there any way to list current VMs, something parallel to the cli command "azure vm list" ?

**Comment by markcowl** [comment]
@rohitsahasrabudhe the cli is actually using the node sdk to do this, you can find the code in the xplat repository https://github.com/Azure/azure-xplat-cli

**Comment by rohitsahasrabudhe** [comment]
@markcowl  Thanks Mark. Will try this out.
