### ISSUE TITLE
nodejs certificate from ubuntu

### ISSUE THREAD

**Issue by krislankford** [Azure/azure-sdk-for-node#1384]
I created an openssl certificate on Ubuntu 14.10 and and tried to use it with the azure and azure-mgmt modules and I always get the following error (Error: The server failed to authenticate the request. Verify that the certificate is valid and is associated with this subscription.] code: 'ForbiddenError', statusCode: 403 ). Code snippet is below:
--------------------------------------------------------------------------------------------------------------------
var fs                = require('fs'),
    computeManagement = require('azure-mgmt-compute');

var computeManagementClient = computeManagement.createComputeManagementClient(computeManagement.createCertificateCloudCredentials({
  subscriptionId: 'removed for issue post',
  pem: fs.readFileSync('mycert.pem')
}));

// List all the virtual machine images you can use.
computeManagementClient.virtualMachineOSImages.list(function (err, result) {
  if (err) {
    console.error(err);
  } else {
    console.info(result);
  }
});

**Comment by markcowl** [comment]
@krislankford Is the certificate uploaded to Azure as a management certificate for your subscription?

**Comment by krislankford** [comment]
I just verified that it was uploaded and it has the same thumbprint.

**Comment by markcowl** [comment]
@krislankford What version of the cli are you using?  We believe this was fixed last release. Can you verify you're using the latest?

**Comment by markcowl** [comment]
@krislankford Also please make sure your PEM has both a public and private key - otherwise it cannot be used to sign requests.  Please reopen if you are still seeing this issue.
