### ISSUE TITLE
Peek lock and Delete not working for service bus in Azure China

### ISSUE THREAD

**Issue by JerryBian** [Azure/azure-sdk-for-node#1398]
We are using azure node package for service bus in Azure China, during peek lock and delete message, the delete progress always fail.

```
this.peekChinaMessage = function (messageProcessorCallback) {
    var serviceBusService;
    serviceBusService = azure.createServiceBusService(chinaConnectionString);
    var message = {
        body: 'Test message'
    };
    serviceBusService.sendQueueMessage(queuePath, message, function (error) {
        if (error) {
            console.log('sendQueueMessage error: ' + error);
        }

        serviceBusService.receiveQueueMessage(queuePath, { isPeekLock: true }, function (error, lockedMessage) {
            
            if (!error) {
                // Message received and locked
                serviceBusService.deleteMessage(lockedMessage, function (deleteError) {
                    if (!deleteError) {
                        console.log('peekChinaMessage Message deleted');
                    } else {
                        console.log('peekChinaMessage Message deleteError: ' + deleteError);
                    }
                });
            } else {
                console.log(error);
            }
        });
    });  
}
```

The `deleteError` would be:
> peekChinaMessage Message deleteError: Error: 404 - No service is hosted at the s
pecified address. TrackingId:df762048-4028-42d9-b3fb-7f78d6156a88_G13,TimeStamp:
3/31/2015 6:37:19 AM

This problem also happens on Service Bus Subscription. When targeting Azure International version, it works well. And, we also tried the pure REST api, both works very fine.

So, this only happens on Azure Node package for Azure China.

**Comment by markcowl** [comment]
@JerryBian Than you for the feedback.  Reporting to the appropriate team to take a look.

**Comment by serenayuq** [comment]
Hi Jerry

as a workaround, you can navigate to  Your Project Path\node_modules\azure\node_modules\azure-common\lib\services , open serviceclientconstants.js, and update as following   CLOUD_SERVICEBUS_HOST: 'servicebus.chinacloudapi.cn' .

the reason you have to do this , is by default, the host name points to Global Azure which has a different address against China Azure. 
after change this , you should be able to Peek and Delete

**Comment by JerryBian** [comment]
Ok, so the official node package will handle this scenario in later release? We use same code for both Global Azure and China Azure. @serenayuq

**Comment by JerryBian** [comment]
Any progress on this issue? @markcowl

**Comment by djrosanova** [comment]
This is open source for a reason. Anyone should be able to issue a pull request.

**Comment by amarzavery** [comment]
Closing this issue.
