### ISSUE TITLE
Azure ServiceBus Token Expired

### ISSUE THREAD

**Issue by punitganshani** [Azure/azure-sdk-for-node#1403]
I am accessing Azure ServiceBus using NodeJS and it worked fine for several days. All of a sudden, I started receiving an error

`
Subscription Deletion Error :Error: 401 - ExpiredToken: . TrackingId:xxxxxx-xxxxxxx,TimeStamp:4/8/2015 12:32:54 PM
`

I am using the connection string to connect to ServiceBus

```javascript
var azure = require('azure');

var serviceBusConnectionString = "Endpoint=sb://somens.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=mykey";

var serviceBusService = azure.createServiceBusService(serviceBusConnectionString);

var rule = {
    deleteDefault: function () {
        serviceBusService.deleteRule(topicName,
            subscriptionName,
            azure.Constants.ServiceBusConstants.DEFAULT_RULE_NAME,
            rule.handleError);
    },
    create: function () {
        var ruleOptions = {
            sqlExpressionFilter: subscriptionCriteria
        };
        rule.deleteDefault();
        serviceBusService.createRule(topicName,
            subscriptionName,
            filterName,
            ruleOptions,
            rule.handleError);
    },
    handleError: function (error) {
        if (error) {
            console.log(error);
        }
    }
} //rule


serviceBusService.deleteSubscription(topicName, subscriptionName, function (error) {
    if (error) {
        console.log("Subscription Deletion Error :" + error);
        createMessageSubscription();
    }
    else {
        console.log('Subscription deleted : ' + subscriptionName);
        createMessageSubscription();
    }
}); //deleteSubscription

```

There is only one Shared Access Policy 'RootManageSharedAccessKey' with permissions to 'Manage, Send, Listen'

What could be wrong in this?

**Comment by prashanthmadi** [comment]
Have you tried regenerating token from config tab in online portal and use that instead ?

**Comment by punitganshani** [comment]
I have not explicitly used token.  
I am using connection string with SharedAccessKeyName=RootManageSharedAccessKey 

Sometimes I am able to connect with this connection string, and sometimes it gives me ENOTFOUND error

**Comment by punitganshani** [comment]
OK, found the reason
The machine that was running the application had got the date/time reset and it was using a date in the last year.

The fix was to sync up time using ntp or with custom Azure Web API implementation.
