### ISSUE TITLE
Error: 405 - Cannot access a disposed object.

### ISSUE THREAD

**Issue by martinza78** [Azure/azure-sdk-for-node#1408]
Getting this error under load:

{"stack":"Error: 405 - Cannot access a disposed object.\r\nObject name: 'Microsoft.ServiceBus.Messaging.BatchManager`1[Microsoft.ServiceBus.Messaging.BrokeredMessage]'. TrackingId:60e68c36-6f02-4bff-8120-2c9fd83a50f1_G23,TimeStamp:4/21/2015 9:57:22 PM\n at Function.ServiceClient._normalizeError (D:\\home\\site\\wwwroot\\node_modules\\azure\\node_modules\\azure-common\\lib\\services\\serviceclient.js:815:23)\n at Object.ServiceClient._processResponse (D:\\home\\site\\wwwroot\\node_modules\\azure\\node_modules\\azure-common\\lib\\services\\serviceclient.js:456:41)\n at Request.processResponseCallback [as _callback] (D:\\home\\site\\wwwroot\\node_modules\\azure\\node_modules\\azure-common\\lib\\services\\serviceclient.js:213:35)\n at Request.self.callback (D:\\home\\site\\wwwroot\\node_modules\\azure\\node_modules\\request\\request.js:129:22)\n at Request.emit (events.js:98:17)\n at Request.<anonymous> (D:\\home\\site\\wwwroot\\node_modules\\azure\\node_modules\\request\\request.js:873:14)\n at Request.emit (events.js:117:20)\n at IncomingMessage.<anonymous> (D:\\home\\site\\wwwroot\\node_modules\\azure\\node_modules\\request\\request.js:824:12)\n at IncomingMessage.emit (events.js:117:20)\n at _stream_readable.js:929:16","message":"405 - Cannot access a disposed object.\r\nObject name: 'Microsoft.ServiceBus.Messaging.BatchManager`1[Microsoft.ServiceBus.Messaging.BrokeredMessage]'. TrackingId:60e68c36-6f02-4bff-8120-2c9fd83a50f1_G23,TimeStamp:4/21/2015 9:57:22 PM","code":"405","detail":"Cannot access a disposed object.\r\nObject name: 'Microsoft.ServiceBus.Messaging.BatchManager`1[Microsoft.ServiceBus.Messaging.BrokeredMessage]'. TrackingId:60e68c36-6f02-4bff-8120-2c9fd83a50f1_G23,TimeStamp:4/21/2015 9:57:22 PM","statusCode":405}

**Comment by markusahlstrand** [comment]
Discussed this with support a few times and it's a incorrect error-code from the service bus. From what I understand it's a known issue so hopefully it will be fixed some day. Unfortunately I assume that since it's a 400 rather than a 500 the client won't retry the call even if you're using a retry policy?

**Comment by amarzavery** [comment]
Closing this one as it is a service side issue.
