### ISSUE TITLE
define max size limit for Azure blob stream i.e. truncate the file

### ISSUE THREAD

**Issue by sameercaresu** [Azure/azure-sdk-for-node#1410]
I am not sure if this is a `feature request` or if there is already some options available.

I am using `createBlockBlobFromStream` and I want to define a max size for the file. File should get uploaded to blob and if the max size is reached then it should be truncated.

For ex. if I am uploading a `80 Mb` fiile and I specify max size to be `50 Mb` then only `50 Mb` of the file should be uploaded to blob. (required for video uploads)

Please see the [stackoverflow question](http://stackoverflow.com/questions/29841688/define-size-limit-for-azure-blob-stream-i-e-truncate-the-file) for more details.

**Comment by gangsir** [comment]
Thanks for reporting this. We will fix this in future sprint.

**Comment by amarzavery** [comment]
closing this issue here and have opened it in the right repo.
