### ISSUE TITLE
XML namespace error in dac.importMethod

### ISSUE THREAD

**Issue by vincent** [Azure/azure-sdk-for-node#1416]
There is an XML namespace error in the [importMethod](https://github.com/Azure/azure-sdk-for-node/blob/14a19d14f1ca76766bb24d206d1f19471f9f7f16/lib/services/sqlManagement/lib/sqlManagementClient.js#L214) code

Currently the request fails with error 

```
Error: The Uri doesn't match any specific service operation.
```

When I hard-code the XML request content, taken from https://msdn.microsoft.com/en-us/library/azure/dn781284.aspx, that is with the namespaces, it works correctly.

current produced XML:

``` xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<ImportInput xmlns="http://schemas.datacontract.org/2004/07/Microsoft.SqlServer.Management.Dac.ServiceTypes">
    <AzureEdition>Business</AzureEdition>
    <BlobCredentials type="BlobStorageAccessKeyCredentials">
        <Uri>the_blob_uri</Uri>
        <StorageAccessKey>the_blob_acccesskey</StorageAccessKey>
    </BlobCredentials>
    <ConnectionInfo>
        <DatabaseName>the_db_name</DatabaseName>
        <Password>the_db_password</Password>
        <ServerName>the_db_server</ServerName>
        <UserName>the_db_user@the_db_server</UserName>
    </ConnectionInfo>
    <DatabaseSizeInGB>10</DatabaseSizeInGB>
</ImportInput>
```

hard-coded XML template:

``` xml
<ImportInput xmlns="http://schemas.datacontract.org/2004/07/Microsoft.SqlServer.Management.Dac.ServiceTypes" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
  <AzureEdition>Web</AzureEdition>
  <BlobCredentials i:type="BlobStorageAccessKeyCredentials">
    <Uri>{uriBase}</Uri>
    <StorageAccessKey>+Ka1LjBc36Pa62WOCJ9zXJjlN5qU6YU3B2JYTgSfw8xiQKlrBoOmAEcdJSO3/YPA5JcJAmMSWCyQB7w1D96k8A==</StorageAccessKey>
  </BlobCredentials>
  <ConnectionInfo>
    <DatabaseName>{dbName}</DatabaseName>
    <Password>{myPassword}</Password>
    <ServerName>{serverName}.database.windows.net</ServerName>
    <UserName>{mylogin}</UserName>
  </ConnectionInfo>
  <DatabaseSizeInGB>1</DatabaseSizeInGB>
</ImportInput>
```

code used for reproducing the bug:

``` js
var parameters = {
    connectionInfo: {
        databaseName: 'the_db_name',
        password: 'the_db_password',
        serverName: 'the_db_server.database.windows.net',
        userName: 'the_db_user'
     },
     azureEdition: 'Business',
     databaseSizeInGB: 10,
     blobCredentials: {
        storageAccessKey: 'the_blob_accesskey',
        uri: 'the_blob_uri'
     }
};

sqlmgmt.dac.importMethod(db.server, parameters, function(error, result) {
    console.log(error, result);
});
```

**Comment by vincent** [comment]
Just some thoughts..

It seems the `importMethod` do set the correct namespace [here](https://github.com/Azure/azure-sdk-for-node/blob/14a19d14f1ca76766bb24d206d1f19471f9f7f16/lib/services/sqlManagement/lib/sqlManagementClient.js#L296) so I guess the problem could be in the XML generation, maybe [here](https://github.com/Azure/azure-sdk-for-node/blob/cc78f3b38915dee2b87af0669cffd6e6fb50c650/lib/common/lib/util/js2xml.js#L162) the `attribute.namespace` is lost ?

**Comment by vincent** [comment]
Hi, could you give a status on this - and an ETA if possible - please ?

**Comment by vincent** [comment]
still no status about this ?

**Comment by amarzavery** [comment]
We have released a new sql management library. `azure-arm-sql`, in a new release today. https://github.com/Azure/azure-sdk-for-node/releases/tag/2.0.0-preview-April2017. Please let us know if that solves your problem.
