### ISSUE TITLE
error when calling serviceBusClient.createSubscription

### ISSUE THREAD

**Issue by collinsauve** [Azure/azure-sdk-for-node#1420]
```
The remote server returned an error: (404) Not Found. The incoming request is not recoginzed as a namespace policy put request: Unrecognized policy type: SubscriptionDescription, http://schemas.microsoft.com/netservices/2010/10/servicebus/connect. TrackingId:5b675ed9-5f2c-4d66-a0c0-205065974a4c_G60,TimeStamp:5/14/2015 8:32:52 PM
```

Same error as from https://github.com/Azure/azure-sdk-for-node/issues/177 which was closed as it disappeared.

This only seems to happens on one of my (recently created) service bus namespaces.

**Comment by collinsauve** [comment]
On second though this is probably not the client / sdk and doesn't belong here.

**Comment by anothar** [comment]
Hi @collinsauve I've met the same exception today. I investigated and it occured that I tried to create subscription for non existant topic(it was deleted). So this exception may occur if topic doesn'exist. Or, perhaps, is just being created.
