### ISSUE TITLE
Service Bus message encoding/decoding fails for string with double quotation

### ISSUE THREAD

**Issue by jtmilne** [Azure/azure-sdk-for-node#1422]
When using customProperties in a service bus message, if a string property contains a double quotation, the encoding/decoding fails. Which means that the output of JSON.stringify(obj) will always fail. For example:

    customProperties: {
        foo: '"'
    }

returns a message like this:

    customProperties: {
        foo: '\\"\\"\\"'
    }

**Comment by djrosanova** [comment]
Custom properties are serialized and deserialized on our service (they can, after all, be used for routing with topics). Don't put complex objects in there, that's not the intent - it should be simple values. And in .NET " is \\". JSON objects should go in the message body.

**Comment by djrosanova** [comment]
Also - if you do want to use custom properties like that, use AMQP and it will work. These AMQP libraries may help: https://github.com/noodlefrenzy
