### ISSUE TITLE
Security issue with the "validator" module in azure-common

### ISSUE THREAD

**Issue by jbinard** [Azure/azure-sdk-for-node#1425]
The "validator" module used in azure-common has a security vulnerability reported by the "nsp" tool (https://nodesecurity.io/advisories/validator-isurl-denial-of-service).

This issue has been fixed in the version 0.4.4 of azure-storage but not in azure-common (https://github.com/Azure/azure-storage-node/pull/59).

Could you do the same for azure-common ?

**Comment by yugangw-msft** [comment]
we have merged
