### ISSUE TITLE
SDK for ARM?

### ISSUE THREAD

**Issue by mkliu** [Azure/azure-sdk-for-node#1440]
I'm trying to programmatically kick off ARM templated deploy, and manage that. I know there's API for that https://msdn.microsoft.com/en-us/library/azure/dn948464.aspx. But is there any SDK provided?

**Comment by matt-gibbs** [comment]
Yes.
https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/resourceManagement/lib/resourceManagementClient.js 
and exposed in the CLI 
Documentation and samples available
https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-deploy-rmtemplates-azure-cli/
