### ISSUE TITLE
Virtual Network Management Link broken in README

### ISSUE THREAD

**Issue by activatedgeek** [Azure/azure-sdk-for-node#1449]
[https://github.com/Azure/azure-sdk-for-node/blob/dev/lib/services/networkManagement/README.md](https://github.com/Azure/azure-sdk-for-node/blob/dev/lib/services/networkManagement/README.md) link is broken in `README.md`.

**Comment by markcowl** [comment]
@activatedgeek Thank you for the report, we will fix

**Comment by markcowl** [comment]
@activatedgeek fixed.  Again, thanks for the feedback
