### ISSUE TITLE
Using promises instead of callbacks

### ISSUE THREAD

**Issue by activatedgeek** [Azure/azure-sdk-for-node#1450]
Is it possible to use promises instead of callbacks?

For instance, consider this code:
```node
var blobStorage = new storage.createBlobService(accountName, accountKey);

blobStorage.createContainerIfNotExists('assets', {
  publicAccessLevel: 'blob'
},
function(error, result, response) {
  if(error) {
    console.error(error);
    process.exit();
  }
  else if(result) {
    console.log('Container created.');
  }
  else {
    console.log('Container already exists. Moving on..');
  }
});
```

With promises such as:
```node
blobStorage.createContainerIfNotExists('assets', {
  publicAccessLevel: 'blob'
})
.then(function(success){}, function(err){});
```

**Comment by mauricionr** [comment]
I was trying to find some doc about it and i found an broken link in this page
https://github.com/Azure/azure-sdk-for-node/tree/ce887be9aa1488120cc6f257d4df490cbeb901d3/lib/services/storageManagement

here's the broken link.
https://github.com/Azure/azure-sdk-for-node/tree/master/lib/services/blob

**Comment by activatedgeek** [comment]
How does that help?

**Comment by mauricionr** [comment]
reading the method docs "createContainerIfNotExists" and check it out if support promises callbacks instead fn as parameter

**Comment by markcowl** [comment]
@activatedgeek promises are not currently supported - we use the more common callback mechanism.

The calls you are asking about are in the storage data plane library and not just the storage management library, this library may have different promises support, see:https://github.com/Azure/azure-storage-node

Please file any issues for storage data plane apis in that repo.

**Comment by mauricionr** [comment]
Thanks!

**Comment by techniq** [comment]
See the latest release: [2.0.0-preview](https://github.com/Azure/azure-sdk-for-node/releases/tag/2.0.0-preview-April2017)
