### ISSUE TITLE
Where to find management certificates?

### ISSUE THREAD

**Issue by activatedgeek** [Azure/azure-sdk-for-node#1451]
I cannot find Management certificates in the Azure portal. I have admin access. Can somebody help me find it? I am not able to interface with the Service Management API otherwise.

**Comment by markcowl** [comment]
@activatedgeek There are two mechanisms for this - the easiest is to use wither the 'azure account download' command in the azure xplat cli, or get-AzurePublishSettingsFile in Azure PowerShell.

These both just open browser windows to the followinguri, which will generate a management certificate for you and download the cert with private key:
https://manage.windowsazure.com/publishsettings/index

Alternately, in the management portal, you can upload your own management certificate under the 'Settings' widget - there is a 'management certificates' tab there
