### ISSUE TITLE
Why upload node_modules to website?

### ISSUE THREAD

**Issue by mauricionr** [Azure/azure-sdk-for-node#1453]
The node_modules path is too long some times, not only to me, but for everybody using node on azure.

I've been wasting too much time resolving this issue to deploy my site.

Will be possible in future just upload the file package.json, and the web site resolve the depencies?

Tks!

**Comment by markcowl** [comment]
@mauricionr Thank you for the report, assigning to the webapps team for investigation.  If you use the website repository for deployment, it will generally pick up your package.json and perform the npm install for you

**Comment by mauricionr** [comment]
When create a project in visual studio from nodejs starter project and publish to azure webapps the node_modules are also uploaded, and some times get the error path is too long.

Thanks @markcowl

**Comment by IvanJosipovic** [comment]
I am also having this issue, at this point I am manually uploading the node_modules separately. Its very annoying.

**Comment by mauricionr** [comment]
I've been deploying using this now

host your sources in VSO, without any build/deployment semantic (i.e. just a plain repo)
Set up your Azure Website to use 'Local Git repository'
When you need to deploy, push from your local machine to the Azure Websites repo, where the build will be handled by the Kudu engine

It's work fine for me.

**Comment by jeffwilcox** [comment]
Closing this issue... sounds like folks are unblocked and this thread is from July.

As Mark mentioned, if you use a product like web sites (Azure App Service), make sure that `node_modules/` is an entry in your `.gitignore` file: that way, you won't commit, upload, etc. your NPM modules to the cloud, and the App Service will do the `npm install` for you.

If you are building using something like an Azure Cloud Service, there are ways there as part of the init to call `npm install`, too, but admittedly that is more work.

Good luck!
