### ISSUE TITLE
RoleEnvironemnt quick stop (OnClose)

### ISSUE THREAD

**Issue by pofider** [Azure/azure-sdk-for-node#1463]
It takes 7 minutes to physically stop worker role after it receives `stopping` event. Nothing is happening during this time and service just hangs. I would like to instruct azure role environment to stop immediately. This would help me to decrease deploy time for each instance by 7 minutes.

In c# you can override `OnClose` method to control the time when is the service physically stopped. I don't see any possibility in node.js sdk. Am I missing something?

I have already tried to exit node process in "stopping" handler. I have also tried to call `clearStatus`, `setStatus`, but nothing helped.

**Comment by amarzavery** [comment]
Closing this issue due to age. Feel free to reopen the issue if this is still an issue.
