### ISSUE TITLE
createBlob - undefined is not a function

### ISSUE THREAD

**Issue by iblazevic** [Azure/azure-sdk-for-node#1464]
We are trying to stream images to Azure without having to store it locally. First we tried using createBlockBlobFromStream, but it has required size so it doesn't make sense for direct streaming.

According to https://github.com/Azure/azure-sdk-for-node/issues/1067 we should be able to use createBlob and it should work for streaming. However createBlob doesn't seem to exist it just gives undefined is not a function.

    fs.createReadStream('index.js').pipe(blobService.createBlob('taskcontainer
                                                     ^
    TypeError: undefined is not a function

Example from [docs](http://dl.windowsazure.com/nodedocs/) gives that error too:

    var blobService = azure.createBlobService();
    fs.createReadStream('task1-upload.txt').pipe(blobService.createBlob('taskcontainer', 'task1',   azure.Constants.BlobConstants.BlobTypes.BLOCK));

Also installed version of sdk is from `npm list`

    azure@0.10.6

**Comment by eltoro** [comment]
Same issue.

**Comment by amarzavery** [comment]
closing this issue here. Have opened this in the azure-storage-node repo
