### ISSUE TITLE
ResourceOperations.checkExistence bug

### ISSUE THREAD

**Issue by anweiss** [Azure/azure-sdk-for-node#1465]
If a Resource Group is not found, instead of returning `exists = false`, it throws an error as result of [line 4677](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/resourceManagement/lib/resourceManagementClient.js#L4677). For some reason, `err` is neither null nor undefined when this operation takes place, hence the execution of the returned error.

**Comment by markcowl** [comment]
@anweiss Thank you for the report, assignign appropriately for repro

**Comment by amarzavery** [comment]
@anweiss- We have published a new version of "azure-arm-resource" package which exposes a better client side API compared to the previous one. Please try it and let us know if you find any issues.
