### ISSUE TITLE
getPublishProfile and getPublishingCredentials in ARM don't execute callback

### ISSUE THREAD

**Issue by anweiss** [Azure/azure-sdk-for-node#1469]
For some reason, neither the `getPublishProfile` nor the `getPublishingCredentials` functions in the `WebSiteOperations` class in the `azure-arm-website` module are executing their callback methods. I'm unable to retrieve errors nor results.

**Comment by yugangw-msft** [comment]
please provide more details such as your client code

**Comment by anweiss** [comment]
Sure thing.

```javascript
var webSiteManagement = require('azure-arm-website'),
      tokenCreds, // Set via ADAL Node library
      rgName = '<resource_group_name>',
      siteName = '<web_app_name>';

webSiteManagementClient = webSiteManagement.createWebSiteManagementClient(tokenCreds);
webSiteManagementClient.webSites.getPublishProfile(rgName, siteName, null, function (err, result) {
  // Neither of these statements execute because this callback doesn't seem to be called
  if (err) throw err;
  console.log(result);
});
```

In the code above, the callback parameter of `getPublishProfile` never actually gets called, despite verifying that I have a valid token-based credential and valid `WebSiteManagementClient~WebSiteManagementClient#webSites` instance.

This issue also occurs with the `getPublishingCredentials` function.

**Comment by vincent** [comment]
It seems I have the same issue with `webSiteManagementClient.webSites.getAppSettings()`

**Comment by amarzavery** [comment]
@vincent, @anweiss - We have published a new version of the website client which has a better API compared to the previous one. Please use ["azure-arm-website":"0.11.0"](https://www.npmjs.com/package/azure-arm-website) and let us know if you find any issues.
