### ISSUE TITLE
get token without clear text password?

### ISSUE THREAD

**Issue by mkliu** [Azure/azure-sdk-for-node#1486]
In ASM i could use perm file, in ARM mode I see some sample code using context.acquireTokenWithUsernamePassword. Is there anyway to avoid putting passwords and get the token? 

I looked at adding application to Azure AD and suspect that's the way to go but how does authorization work?

```
http://azure.github.io/azure-sdk-for-node/azure-arm-keyvault/latest/
```

```
var context = new AdalNode.AuthenticationContext('https://login.windows.net/myorg.com');
context.acquireTokenWithUsernamePassword(resourceId, userName, password, clientId, function (err, response) {
  if (err) {
    throw new Error('Unable to authenticate: ' + err.stack);
  }

  var credentials = new AzureCommon.TokenCloudCredentials({
    subscriptionId : '<subscription GUID>',
    authorizationScheme : response.tokenType,
    token : response.accessToken
  });
```

**Comment by markcowl** [comment]
@mkliu Using application credentials is the way to go for automation using the cli.  Authentication works via an application id and secret, using authenticationContext..acquireTokenWithClientCredentials(...).  You can see samples of creating the token for use with the node library here: https://github.com/Azure/azure-xplat-cli/blob/dev/lib/util/authentication/adalAuth.js

**Comment by perseusCode** [comment]
@mkliu  As Mark pointed out, authentication using applications is the correct way to do it. Please look at the example shared by him. You may also follow the awesome article with sample code put up on awesome Azure documentation here - https://azure.microsoft.com/en-us/documentation/articles/resource-group-authenticate-service-principal/

**Comment by mkliu** [comment]
@markcowl @perseusCode thanks very much. I got applicaiton credential working already. One more question, so I login via application credential to use the cli. If I write my own node.js using SDK on the same machine, can it somehow reuse the token from the local cache instead of trying to acquire token again? 

I'll try it myself later but it's be great if you guys know the answer.

**Comment by perseusCode** [comment]
If you use the ADAL SDK to get the token, token should be cached by default. You might have to explicitly turn off the cache, if you don't want it.
