### ISSUE TITLE
Is there any way to increase timeout for provisioning a VM?

### ISSUE THREAD

**Issue by AbelHu** [Azure/azure-sdk-for-node#1491]
When we provision a VM, sometimes we get bellow errror. Is there any way to increase timeout?

{"code"=>"OSProvisioningTimedOut", "message"=>"OS Provisioning for VM '16ad1f99-9e19-44e5-aa7d-c5498a6a81ee' did not finish in the allotted time. The VM may still finish provisioning successfully. Please check provisioning state later."}

**Comment by pennylliang** [comment]
I have the same problem.
With VM size A2, OS 2012R2 with SQL2014 (SQL2014-WS2012R2).

**Comment by aatif912** [comment]
Same issue with me as well.
Error               : {
                        "Details": [],
                        "InnerError": null,
                        "Code": "OSProvisioningTimedOut",
                        "Message": "OS Provisioning for VM 'vmtest' did not finish in the allotted time. The VM may still finish provisioning successfully. Please check 
                      provisioning state later.",
                        "Target": null
                      }

**Comment by cheeseprophet** [comment]
I'm also hitting this issue.  Size A2 VMs.

**Comment by ashwanikapoor** [comment]
HI, I am trying to upload Redhat Linux VM and after running for some hours, it give following error.

"OS Provisioning for VM <VM name> did not finish in the allotted time. he VM may still finish provisioning successfully. 
  Please check provisioning state later.

Anybody has encountered this specific issue ? what is the resolutiion? how can we provision an osdisk later in new portal of Azure

**Comment by amarzavery** [comment]
@huangpf - I hit the same issue when recording the azure vm quick-create tests while porting the vm cmdlets in Xplat CLI to use AutoRest generated rest client. Can someone from the compute team respond with steps on resolving this issue.

I am not sure if this was actually related to the location of deployment. When I got this issue, I was creating a VM in SouthEast Asia. Later when I changed the location to West US, I did not see this issue.

**Comment by amarzavery** [comment]
As per the new ["azure-arm-compute package - 0.14.0"](https://www.npmjs.com/package/azure-arm-compute) the run time [ms-rest-azure](https://www.npmjs.com/package/ms-rest-azure) polls for the long running operation till it reaches one of the terminal states (Success, Failure, Cancelled).

**Comment by huangpf** [comment]
+@singhkay for the question about correlation of provisioning time and location.

**Comment by singhkay** [comment]
Folks, this is a platform limitation 

@mahthi Can you elaborate on this or the fix?

**Comment by mahthi** [comment]
No, it’s not a configurable timeout right now. Having said that, we are continuously working on improving the provisioning times on Azure and ensure that it gets done within the defined time.

It would be really helpful to understand if the VMs actually came up after the timeout and hence the request to configure this timeout?

**Comment by amarzavery** [comment]
@manthi, @singhkay, @huangpf - The VM did come up for me after that. Isn't this problem similar to a problem that a restaurant faces with its most popular dishes. Can't we pre-make (half-bake) popular set of VMs (for different OS types with a standard H/W config)? 80% of the customers would be satisfied with this. The specialized 20% would be willing to wait longer as their setup is custom.

**Comment by mahthi** [comment]
Thanks for the feedback, Amar. I’ll add this in our feature backlog for sure. Having said that, we do constantly look at these numbers and configure the timeout values . Based on our data, less than 0.5% of VMs run into this error because of the timeout values.

**Comment by amarzavery** [comment]
This is purely a service side issue. The service team has acknowledged the issue and will be looking into ways to reduce the provisioning time for VMs. Hence this issue is being closed.

**Comment by mithundevkate** [comment]
i am facing the same issue and tried all the solutions which mentioned in the discussion but no luck. Can someone address me what is the workaround  ?

**Comment by farahgara1794** [comment]
please did you find the solution and why is this problem.
I'm facing the same issue

**Comment by amarzavery** [comment]
@farahgara1794 - This is purely a service side issue. No matter what timeout one would configure in the sdk, if the service is having issues with VM deployment then nothing can be done from the sdk side.

From prior experience, I would suggest filing a support ticket with snapshot about the request and the response and the error that you see w.r.t timeout. Make sure to provide all the request headers as well. That should make it easier for service team to track what happened with that specific request.

This should help you get the fastest response to the problem.
