### ISSUE TITLE
Is the Event Hub service support available?

### ISSUE THREAD

**Issue by NNM11** [Azure/azure-sdk-for-node#1493]
Is the Event Hub support in this Azure SDK for node available?  Any timeline for this support?

Thx,

**Comment by punitganshani** [comment]
+1 for this feature

**Comment by DenisBiondic** [comment]
Another +1

**Comment by amarzavery** [comment]
@NNM11 @punitganshani @DenisBiondic - 
The first version of the arm servicebus management plane client [azure-arm-sb](https://github.com/Azure/azure-sdk-for-node/tree/master/lib/services/serviceBusManagement2) and eventhub management plane client [azure-arm-eventhub](https://github.com/Azure/azure-sdk-for-node/tree/master/lib/services/eventHubManagement) is out. Please try it out and provide feedback.

**Comment by punitganshani** [comment]
Awesome, thanks :+1:
