### ISSUE TITLE
Broken Link in http://azure.github.io/azure-storage-node/FileService.html#FileService

### ISSUE THREAD

**Issue by mauricionr** [Azure/azure-sdk-for-node#1494]
I'm studing about files and i've found this broken link
http://azure.microsoft.com/en-us/documentation/articles/storage-nodejs-how-to-use-file-storage/

**Comment by jeffwilcox** [comment]
Do you think this is the resource you were looking for there?

https://azure.microsoft.com/en-us/documentation/articles/storage-nodejs-how-to-use-blob-storage/
