### ISSUE TITLE
Azure TableUtilities is not exported

### ISSUE THREAD

**Issue by SofianHn** [Azure/azure-sdk-for-node#1507]
Per the docs of azure storage, you need to use the entity generator in order to insert a new item to azure table storage. Looking at azure.js, TableUtitlities is not exported. It should be a small fix.

**Comment by amarzavery** [comment]
Creating this issue in the [azure-storage-node](https://github.com/Azure/azure-storage-node/issues/101) repo and closing it here.

**Comment by peterblazejewicz** [comment]
This is `azure.js` module issue:
https://github.com/Azure/azure-sdk-for-node/blob/master/lib/azure.js#L28
I cannot run samples from this repo as `TableUtilities` is not exported.
Will make PR
Thanks!
