### ISSUE TITLE
Propose removing old file CONTRIBUTORS.TXT

### ISSUE THREAD

**Issue by jeffwilcox** [Azure/azure-sdk-for-node#1517]
Hi,
Contributors.txt is not very often kept up-to-date in any open source project; we added the file when MS Open Tech requested so, but with that entity spun down, there's little need for this file to remain.

I propose removing it.

See also: https://github.com/Azure/azure-sdk-for-node/blob/master/CONTRIBUTORS.txt

It would also be worth triaging an update of header files at that time; the copyright header guidance may have shifted recently. Feel free to loop me in on corporate e-mail if you have any questions about details there.

Thanks!

**Comment by amarzavery** [comment]
issue resolved.
