### ISSUE TITLE
Receive message from session enabled queue or subscription

### ISSUE THREAD

**Issue by dani-g** [Azure/azure-sdk-for-node#1518]
Hi,

I have several partitioned queues where we set the "SessionId" to guarantee FIFO with several concurrent consumers but we usually use workers in C# using a session handler.

Using node sdk, I get this error trying to get a message from such a queue:
`It is not possible for an entity that requires sessions to create a non-sessionful message receiver.`

Is there a way to do this in node?

**Comment by jared-cxz** [comment]
We got the same issue when using azure for node.

Is there any update for this issue?

**Comment by jtaubensee** [comment]
There is not currently a way to do this in the node client, as it uses HTTP not AMQP. In order to support this, we will have to re-write it.
