### ISSUE TITLE
Service bus message processing exception

### ISSUE THREAD

**Issue by sureshdesai** [Azure/azure-sdk-for-node#1525]
Hello GitHub Support,
we need your help urgently regarding service bus message processing.

we are getting following exception all the time during processing SignUp message in service bus..

please help us to get rid of this exception soon, your help will be highly appreciated.

Thanking you..

shown below is actual exception

Exception:

System.AggregateException: One or more errors occurred. ---> Microsoft.ServiceBus.Messaging.MessagingEntityNotFoundException: The remote server returned an error: (404) Not Found. The incoming request is not recoginzed as a namespace policy put request: Unrecognized policy type: SubscriptionDescription, http://schemas.microsoft.com/netservices/2010/10/servicebus/connect.

Exception:
The remote server returned an error: (404) Not Found. The incoming request is not recoginzed as a namespace policy put request: Unrecognized policy type: SubscriptionDescription, http://schemas.microsoft.com/netservices/2010/10/servicebus/connect.

**Comment by otaviosoares** [comment]
+1

**Comment by jtaubensee** [comment]
Closing due to age. Please reopen if necessary.
