### ISSUE TITLE
Incorrect Worker Count

### ISSUE THREAD

**Issue by mcollier** [Azure/azure-sdk-for-node#1526]
A Standard web site scaled to 4 instances shows a "Worker Count" value of 1. I would assume the correct value should be 4. Interestingly, the PowerShell cmdlet Get-AzureWebsite returns the same value - 1 worker. This seems wrong as well.

The Instance ID value returns 4 values - 4 very long values that are a sequence of numbers and letters. What are those values? What do they represent?

![cli_azure_website_incorrect_number_of_workers](https://cloud.githubusercontent.com/assets/1142273/10838513/d649bb9e-7e9d-11e5-88f3-157b013a8118.png)

**Comment by amarzavery** [comment]
This is an xplat cli issue. Opening this in the right repo.

**Comment by amarzavery** [comment]
https://github.com/Azure/azure-xplat-cli/issues/2516
