### ISSUE TITLE
_normalizeError obliterates original stack trace

### ISSUE THREAD

**Issue by danderson00** [Azure/azure-sdk-for-node#1538]
The error message is also not very useful in some cases - for some exceptions thrown by azure-sb NotificationHubService, the exception contains NO useful information. I can't tell where the exception is raised without debugging the code.

**Comment by romangromov** [comment]
+1 for the same, also output for -vv is not useful anymore

**Comment by ankurkul** [comment]
Thanks guys. We agree that exception traces are not helpful descriptive enough. We shall be fixing it soon.
