### ISSUE TITLE
Ensure released version numbers are consistent, or tag repo for each release

### ISSUE THREAD

**Issue by danderson00** [Azure/azure-sdk-for-node#1539]
For example, it is extremely difficult to find the exact commit that correlates with the 0.9.16 release of azure-common. The version of azure-common at the 0.9.16 release tag is 0.9.8.

**Comment by amarzavery** [comment]
@danderson00 - Thanks for letting us know about it. We used to tag releases when we used to ship the entire sdk. Now, we have moved to a different model where we don't release new versions of the node SDK frequently. Each service team publishes its packages to npm as and when required. That being said we shall update the release tags whenever we ship azure-common.
