### ISSUE TITLE
How to set the ServiceObjectiveId when using DacOperations.importMethod ?

### ISSUE THREAD

**Issue by vincent** [Azure/azure-sdk-for-node#1547]
It seems the ServiceObjectiveId is not taken into account in the `DacOperations.importMethod` method.
It is possible to include it ?

I see it is used in the `DatabaseOperations.update` method.
If I use this method, just after launching the `importMethod`, will it scale properly without breaking the import ?

**Comment by amarzavery** [comment]
@yaakoviyun - This is a sql specific question. Can you please help the customer with his issue?

**Comment by yaakoviyun** [comment]
+ Uriel and Adam for help

???? ?- Outlook Mobile<https://aka.ms/qtex0l>

_____________________________

**Comment by akromm** [comment]
@vincent the work around would to be to send the scale operation first, wait for it to finish, then send the import request.
