### ISSUE TITLE
storageManagementClient.storageAccounts.listKeys callback never called

### ISSUE THREAD

**Issue by nosretep** [Azure/azure-sdk-for-node#1585]
It feels like the HTTP response back from Azure REST API is too fast for the request and subsequent stream, created in request-pipeline.js # requestLibrarySink, to be read from.

If I make the following change in request-pipeline.js # requestLibrarySink, then my callback is called once.

```
    request(options, function (err, response, body) {
      if (err) { return callback(err); }
      return callback(null, response, body);
    });

    return request(options, function (err, response, body) {
      if (err) { return callback(err); }
      return callback(null, response, body);
    });
```
Basically, not returning the request object allows the callback to be called.

This does not happen for any other API that I have tried. For example resourceManagementClient.resources.list works as expected. The callback is called, and the resulting stream can be used to read streamed data via on('data') listener. I'm assuming it's because that HTTP response, back from Azure REST API, is slightly slower.

Using StorageManagementClient from 'azure/node_modules/azure-arm-storage'.

**Comment by amarzavery** [comment]
@nosretep - Can you please let us know the version of azure-arm-storage?
Did you try version 0.12.1-preview ?
Do take a look at [this test](https://github.com/Azure/azure-sdk-for-node/blob/autorest/test/services/storageManagement/storageManagementClient-tests.js#L158) as an example and let me know if that helps.

**Comment by amarzavery** [comment]
Please feel free to open this issue if the problem persists with the new version of azure-arm-storage.
