### ISSUE TITLE
ARM application gateway set errors

### ISSUE THREAD

**Issue by MikhailTryakhov** [Azure/azure-sdk-for-node#1603]
Every set commands failed because of incorrect requireServerNameIndication parameter checking.
SDK checks for string type, but it's boolean value
![](https://camo.githubusercontent.com/47508c216c13ffeb469568b5d2a9523289db634d/687474703a2f2f692e696d6775722e636f6d2f6e4d6e73476f392e706e67)

**Comment by amarzavery** [comment]
The generated code checks for string type because the swagger spec says it is a string. Check [this out](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-network/2015-06-15/swagger/network.json#L4181).
```json
"requireServerNameIndication": {
  "type": "string", 
  "description": "Gets or sets the requireServerNameIndication of http listener" 
}
```
