### ISSUE TITLE
Where can I find documentation / example of how to create Virtual Machine plus documentation for all the parameters?

### ISSUE THREAD

**Issue by dukedougal** [Azure/azure-sdk-for-node#1605]
I go to the reference documentation for the ComputeManagementClient here

http://azure.github.io/azure-sdk-for-node/azure-asm-compute/latest/ComputeManagementClient-ComputeManagementClient.html

and click on the HostServiceOperations link:

http://azure.github.io/azure-sdk-for-node/azure-asm-compute/latest/-HostedServiceOperations.html

But it gives a 404!

I *really* need to find the reference documentation for all of the parameters that can be supplied when creating a Virtual Machine.

thanks!

**Comment by amarzavery** [comment]
Is this what you were trying to find http://azure.github.io/azure-sdk-for-node/azure-asm-compute/latest/HostedServiceOperations-HostedServiceOperations.html ?
It seems "HostedServiceOperations" this part was missing in the link. 

Btw, why are you using the ASM (V1) version of the azure api for creating vm and not the ARM V2 api ?
This is the V2 api doc http://azure.github.io/azure-sdk-for-node/azure-arm-compute/latest/ . It is published as a package under the name "azure-arm-compute"
