### ISSUE TITLE
Documentation problem - links on this page lead to 404 errors.

### ISSUE THREAD

**Issue by dukedougal** [Azure/azure-sdk-for-node#1606]
http://azure.github.io/azure-sdk-for-node/azure-asm-compute/latest/ComputeManagementClient-ComputeManagementClient.html

**Comment by jaysingh** [comment]
Which links?

**Comment by dukedougal** [comment]
Half the links on the page - did you click on any?

**Comment by amarzavery** [comment]
I agree. @devigned - We need to do a better job at generating these docs. For example this link does not work http://azure.github.io/azure-sdk-for-node/azure-asm-compute/latest/-DeploymentOperations.html .

@dukedougal - Why are you not using the V2 version of the Azure API to create a VM. The package name is: azure-arm-compute.

We are working on improving the documentation. However, feel free to look at the source code for documentation over [here](https://github.com/Azure/azure-sdk-for-node/tree/autorest/lib/services/computeManagement2/lib).

**Comment by analytically** [comment]
Do you have an example of how to authenticate using azure-arm-compute? I have my subscription id, what else do I need and where can I find it?

**Comment by devigned** [comment]
@amarzavery agreed. We need to add the documentation generation script in https://github.com/azure/ref-docs and add some better examples / samples for usage.

**Comment by amarzavery** [comment]
@devigned - I agree, we need onboarding samples ASAP. Looks like a 6-9 project :santa: 
@analytically - You can use the sample provided over storageManagement library over [here](https://github.com/Azure/azure-sdk-for-node/tree/autorest/lib/services/storageManagement2#authentication). The Authentication sample would be useful. After creating the credentials object, you can create the compute client.

Another useful resource would be a [test that was written for listing vm images and vn extension images] (https://github.com/Azure/azure-sdk-for-node/blob/autorest/test/services/computeManagement/computeManagementClient-tests.js).

**Comment by analytically** [comment]
@amarzavery previously I could use my subcription id and pem to authenticate, how does this work with the sample provided by storageManagement library that you mention? Going from CertificateCloudCredentials to UserTokenCredentials...

```
var computeManagementClient = computeManagement.createComputeManagementClient(computeManagement.createCertificateCloudCredentials({
    subscriptionId: '8ff2dc1b-1ac5-484f-9ab6-ea48365ee4a9',
    pem: fs.readFileSync('8ff2dc1b-1ac5-484f-9ab6-ea48365ee4a9.pem', 'utf-8')
}));
```

**Comment by amarzavery** [comment]
@analytically - The new ARM API (V2) uses token based authentication and the old ASM API (V1) used certificate based authentication. You can login as a user or you can create a service principal in your Active directory and use it for Authentication purpose.

```
var msrestAzure = require('ms-rest-azure');
 //user authentication
 var credentials = new msRestAzure.UserTokenCredentials('your-client-id', 'your-domain', 'your-username', 'your-password', 'your-redirect-uri');
 //service principal authentication
 var credentials = new msRestAzure.ApplicationTokenCredentials('your-client-id', 'your-domain', 'your-secret');
```

Steps on how to create a service principal can be found [here](https://azure.microsoft.com/en-us/documentation/articles/resource-group-create-service-principal-portal/)

**Comment by analytically** [comment]
Thanks. The document isn't very clear about what the different values are that I need to pass to: 

``` var credentials = new msRestAzure.UserTokenCredentials('your-client-id', 'your-domain', 'your-username', 'your-password', 'your-redirect-uri');```

What's `your-domain` referring to? And why does it need to redirect-uri?

**Comment by amarzavery** [comment]
The document shows the steps to create a service principal.
```
var credentials = new msRestAzure.ApplicationTokenCredentials('your-client-id', 'your-domain', 'your-secret');
```
where: 
'your-client-id' - the client id of the application
'your-domain' - the tenant id or the domain of the application
'your-secret' - the application's secret.

**Comment by amarzavery** [comment]
As far as user authentication is concerned, 
You will have to create a user in the Active directory via portal. Make the user an admin and link it to your subscription.

```
var credentials = new msRestAzure.UserTokenCredentials('your-client-id', 'your-domain', 'your-username', 'your-password', 'your-redirect-uri');
```
your-client-id
'your-domain' - tenant id (a GUID) or the part after the @ in the user's email address user@contosocop.com then domain is contosocorp.com
redirect-uri - can be an empty string


I would suggest you to create a service principal for authentication rather than trying to create a user-id in an org.

**Comment by CtrlDot** [comment]
This still isn't super clear.  What is 'your-client-id" and how does that relate to "your-username".  Why would I need both for user authentication?

**Comment by amarzavery** [comment]
@CtrlDot - https://github.com/Azure/azure-sdk-for-node/blob/master/Documentation/Authentication.md#using-user-authentitcation-in-your-nodejs-script
'your-client-id' - is the id provided by Azure Active Directory for your application.

**Comment by amarzavery** [comment]
@analytically @CtrlDot - The authentication process has been made super simple for users with the latest version of runtime `ms-rest-azure: 1.14.2`.
Please take a look at this [updated doc](https://github.com/Azure/azure-sdk-for-node/blob/master/Documentation/Authentication.md#using-authentication-in-your-nodejs-script) and let me know if you have any issues.

**Comment by sushmita94** [comment]
Hi, where can i find the secret?

**Comment by amarzavery** [comment]
Are you talking about the application secret? If yes, then if you follow the instructions of creating the service principal mentioned over [here](https://github.com/Azure/azure-sdk-for-node/blob/master/Documentation/Authentication.md#via-xplatcli-in-3-simple-steps) then you will see that you have to set the secret while creating the sp.
