### ISSUE TITLE
Is AutoRest generated API going to replace this API?

### ISSUE THREAD

**Issue by rnrneverdies** [Azure/azure-sdk-for-node#1608]
Hello, i want to know if this api is going to be replaced by another one generated with AutoRest.exe 

Could you please provide some insight on this?

**Comment by amarzavery** [comment]
As of today, compute, network , storage, intune and rediscache have shipped their libraries using autorest. Other service teams are onboarding and are gearing towards shipping the AutoRest generated API. Majority of the teams should be done moving in a couple of months. Are you looking for some specific services ?

**Comment by rnrneverdies** [comment]
@amarzavery we are interested on media services API.

**Comment by amarzavery** [comment]
@rnrneverdies - Are you talking about the management or the data plane? Autorest current generates code for managment plane ARM (Azure Resource Manager) APIs. 
@emgerner-msft , @yaxia - Emily and Yang from the storage team would be in a better to position to answer or route this to the right person.

**Comment by rnrneverdies** [comment]
@amarzavery I am talking about data plane, i.e. Create Assets, Trans-code, Protect, etc.

**Comment by amarzavery** [comment]
We will do every bit in AutoRest to make this possible. However, it is purely upto the service teams to onboard AutoRest for their data plane offering.
