### ISSUE TITLE
Should file be name to app.js?

### ISSUE THREAD

**Issue by EasonWang01** [Azure/azure-sdk-for-node#1620]
I saw a article from microsoft it says entry file should be name app.js so that azure can identify it.
Is it only for web app which contain websocket?

Do we need a web config file?

**Comment by amarzavery** [comment]
I don't think there is any requirement as such. Can you provide the link to the document as that will provide more context on the problem?

**Comment by EasonWang01** [comment]
I just change server.js to app.js to solve websocket problem.

see here  https://azure.microsoft.com/zh-tw/documentation/articles/web-sites-nodejs-chat-app-socketio/

http://stackoverflow.com/questions/21243500/socket-io-runs-fine-locally-but-not-found-on-azure

the second one says need to have a config file,but I follow the firt one just change the entry file name,and hope this help someone who have the same problem.

**Comment by amarzavery** [comment]
The article talks about using [azure-xplat-cli](https://github.com/Azure/azure-xplat-cli) for deploying a webapp from a github repo. I think the file name should be app.js for the command to pick it up.
