### ISSUE TITLE
config.json for ServiceBus namespace, endpoint, access key

### ISSUE THREAD

**Issue by cataquil** [Azure/azure-sdk-for-node#1627]
azure-sdk-for-node/examples/samples/sbqueue.js

this sample creates a new queue.  how can I have the service bus use an existing queue that
is set from config.json or other config file, whatever it is to be called.

I cannot find this in the documentation.
I want to get my c# code talk to nodejs on microservices. thanks

**Comment by amarzavery** [comment]
@djrosanova - Can you take a look at this issue?

**Comment by jtaubensee** [comment]
The sample that you are mentioning, does not create a queue from a configuration file. If you wanted to do that, you would need to read the file on your own and pass those properties as values during the queue creation. We do not offer any api to do that for you.
