### ISSUE TITLE
Could you please expand this example to show how to start, stop, reboot and terminate virtual machines?

### ISSUE THREAD

**Issue by dukedougal** [Azure/azure-sdk-for-node#1628]
It's hard to find documentation that demonstrates how to actually do things with the node.js SDK

This is the closest I have found but it would be alot more useful if it showed how to:
 list (filtered by tag), start (created with tags), stop, reboot and terminate virtual machines

https://github.com/Azure/azure-sdk-for-node/tree/autorest/lib/services/computeManagement2

**Comment by amarzavery** [comment]
@dukedougal - I want to write some samples for Compute. I will be updating the repo very soon with samples.

**Comment by amarzavery** [comment]
@dukedougal - This PR https://github.com/Azure/azure-sdk-for-node/pull/1634 provides a sample for different vm operations that can be performed using the node sdk

**Comment by dukedougal** [comment]
@amarzavery thanks for that - what link do I click to see it?

**Comment by amarzavery** [comment]
Here is the sample: https://github.com/Azure/azure-sdk-for-node/blob/autorest/examples/compute/vm-sample.js

**Comment by dukedougal** [comment]
Awesome great work.

If you created examples to show how to create tagged blob store containers and create and delete objects in them that would also be awesome.

**Comment by amarzavery** [comment]
For starters this should be sufficient. As time permits we will add more samples. However, this is an open source project. Please feel free to contribute :)
