### ISSUE TITLE
How do I get credentials / token to use the SDK?

### ISSUE THREAD

**Issue by dukedougal** [Azure/azure-sdk-for-node#1629]
I have searched the console but I am lost - how do I get credentials?

The following code is from this link https://github.com/Azure/azure-sdk-for-node/issues/1606#issuecomment-181405138

```
var msrestAzure = require('ms-rest-azure');
 //user authentication
 var credentials = new msRestAzure.UserTokenCredentials('your-client-id', 'your-domain', 'your-username', 'your-password', 'your-redirect-uri');
 //service principal authentication
 var credentials = new msRestAzure.ApplicationTokenCredentials('your-client-id', 'your-domain', 'your-secret');
```

Two methods are shown in the code to get credentials.

It would be great if someone could explain step-by-step how to get credentials using each of these methods.

I do wish the documentation for this stuff was easier to find and more obvious......

**Comment by amarzavery** [comment]
I  just created this sample on github. Hope this helps:https://github.com/Azure/azure-sdk-for-node/blob/autorest/Documentation/Authentication.md
It shows how to create a service principal via CLI, link it to a subscription and then login silently using sp authentication.

Thanks,
Amar Zavery

On Feb 16, 2016, at 11:54 AM, "dukedougal" <notifications@github.com<mailto:notifications@github.com>> wrote:


I have searched the console but I am lost - how do I get credentials?

The following code is from this link #1606 (comment)<https://github.com/Azure/azure-sdk-for-node/issues/1606#issuecomment-181405138>

var msrestAzure = require('ms-rest-azure');
 //user authentication
 var credentials = new msRestAzure.UserTokenCredentials('your-client-id', 'your-domain', 'your-username', 'your-password', 'your-redirect-uri');
 //service principal authentication
 var credentials = new msRestAzure.ApplicationTokenCredentials('your-client-id', 'your-domain', 'your-secret');


Two methods are shown in the code to get credentials.

It would be great if someone could explain step-by-step how to get credentials using each of these methods.

I do wish the documentation for this stuff was easier to find and more obvious......

-

**Comment by dukedougal** [comment]
Thanks for this.

I recommend you post this on the front page, first item of the documentation like here https://github.com/Azure/azure-sdk-for-node

**Comment by amarzavery** [comment]
Thanks for the feedback. I shall do this right away.

**Comment by amarzavery** [comment]
@dukedougal - Here is the [updated README](https://github.com/Azure/azure-sdk-for-node/tree/autorest#non-interactive-authentication).
