### ISSUE TITLE
Large number of errors when building with webpack

### ISSUE THREAD

**Issue by dukedougal** [Azure/azure-sdk-for-node#1631]
I get all these errors when I build with webpack:

```
ERROR in ./~/tough-cookie/package.json
Module parse failed: C:\Users\blah\devel\nextshot\node_modules\tough-cookie\package.json Line 2: Unexpected toke
n :
You may need an appropriate loader to handle this file type.
| {
|   "_args": [
|     [
|       "tough-cookie@~2.2.0",
 @ ./~/tough-cookie/lib/cookie.js 38:14-40

ERROR in ./~/ms-rest/~/mime-db/db.json
Module parse failed: C:\Users\blah\devel\nextshot\node_modules\ms-rest\node_modules\mime-db\db.json Line 2: Unex
pected token :
You may need an appropriate loader to handle this file type.
| {
|   "application/1d-interleaved-parityfec": {
|     "source": "iana"
|   },
 @ ./~/ms-rest/~/mime-db/index.js 11:17-37

ERROR in ./~/mime-db/db.json
Module parse failed: C:\Users\blah\devel\nextshot\node_modules\mime-db\db.json Line 2: Unexpected token :
You may need an appropriate loader to handle this file type.
| {
|   "application/1d-interleaved-parityfec": {
|     "source": "iana"
|   },
 @ ./~/mime-db/index.js 11:17-37

ERROR in ./~/har-validator/lib/schemas/cache.json
Module parse failed: C:\Users\blah\devel\nextshot\node_modules\har-validator\lib\schemas\cache.json Line 2: Unex
pected token :
You may need an appropriate loader to handle this file type.
| {
|   "properties": {
|     "beforeRequest": {
|       "$ref": "#cacheEntry"
 @ ./~/har-validator/lib/schemas/index.js 4:9-32

ERROR in ./~/har-validator/lib/schemas/cacheEntry.json
Module parse failed: C:\Users\blah\devel\nextshot\node_modules\har-validator\lib\schemas\cacheEntry.json Line 2:
 Unexpected token :
You may need an appropriate loader to handle this file type.
| {
|   "oneOf": [{
|     "type": "object",
|     "optional": true,
 @ ./~/har-validator/lib/schemas/index.js 5:14-42

ERROR in ./~/har-validator/lib/schemas/content.json
Module parse failed: C:\Users\blah\devel\nextshot\node_modules\har-validator\lib\schemas\content.json Line 2: Un
expected token :
You may need an appropriate loader to handle this file type.
| {
|   "type": "object",
|   "required": [
|     "size",
 @ ./~/har-validator/lib/schemas/index.js 6:11-36

ERROR in ./~/har-validator/lib/schemas/entry.json
Module parse failed: C:\Users\blah\devel\nextshot\node_modules\har-validator\lib\schemas\entry.json Line 2: Unex
pected token :
You may need an appropriate loader to handle this file type.
| {
|   "type": "object",
|   "optional": true,
|   "required": [
 @ ./~/har-validator/lib/schemas/index.js 9:9-32

ERROR in ./~/har-validator/lib/schemas/cookie.json
Module parse failed: C:\Users\blah\devel\nextshot\node_modules\har-validator\lib\schemas\cookie.json Line 2: Une
xpected token :
You may need an appropriate loader to handle this file type.
| {
|   "type": "object",
|   "required": [
|     "name",
 @ ./~/har-validator/lib/schemas/index.js 7:10-34

ERROR in ./~/har-validator/lib/schemas/page.json
Module parse failed: C:\Users\blah\devel\nextshot\node_modules\har-validator\lib\schemas\page.json Line 2: Unexp
ected token :
You may need an appropriate loader to handle this file type.
| {
|   "type": "object",
|   "optional": true,
|   "required": [
 @ ./~/har-validator/lib/schemas/index.js 12:8-30

ERROR in ./~/har-validator/lib/schemas/creator.json
Module parse failed: C:\Users\blah\devel\nextshot\node_modules\har-validator\lib\schemas\creator.json Line 2: Un
expected token :
You may need an appropriate loader to handle this file type.
| {
|   "type": "object",
|   "required": [
|     "name",
 @ ./~/har-validator/lib/schemas/index.js 8:11-36

ERROR in ./~/har-validator/lib/schemas/log.json
Module parse failed: C:\Users\blah\devel\nextshot\node_modules\har-validator\lib\schemas\log.json Line 2: Unexpe
cted token :
You may need an appropriate loader to handle this file type.
| {
|   "type": "object",
|   "required": [
|     "version",
 @ ./~/har-validator/lib/schemas/index.js 11:7-28

ERROR in ./~/har-validator/lib/schemas/pageTimings.json
Module parse failed: C:\Users\blah\devel\nextshot\node_modules\har-validator\lib\schemas\pageTimings.json Line 2
: Unexpected token :
You may need an appropriate loader to handle this file type.
| {
|   "type": "object",
|   "properties": {
|     "onContentLoad": {
 @ ./~/har-validator/lib/schemas/index.js 13:15-44

ERROR in ./~/har-validator/lib/schemas/postData.json
Module parse failed: C:\Users\blah\devel\nextshot\node_modules\har-validator\lib\schemas\postData.json Line 2: U
nexpected token :
You may need an appropriate loader to handle this file type.
| {
|   "type": "object",
|   "optional": true,
|   "required": [
 @ ./~/har-validator/lib/schemas/index.js 14:12-38

ERROR in ./~/har-validator/lib/schemas/record.json
Module parse failed: C:\Users\blah\devel\nextshot\node_modules\har-validator\lib\schemas\record.json Line 2: Une
xpected token :
You may need an appropriate loader to handle this file type.
| {
|   "type": "object",
|   "required": [
|     "name",
 @ ./~/har-validator/lib/schemas/index.js 15:10-34

ERROR in ./~/har-validator/lib/schemas/response.json
Module parse failed: C:\Users\blah\devel\nextshot\node_modules\har-validator\lib\schemas\response.json Line 2: U
nexpected token :
You may need an appropriate loader to handle this file type.
| {
|   "type": "object",
|   "required": [
|     "status",
 @ ./~/har-validator/lib/schemas/index.js 17:12-38

ERROR in ./~/har-validator/lib/schemas/har.json
Module parse failed: C:\Users\blah\devel\nextshot\node_modules\har-validator\lib\schemas\har.json Line 2: Unexpe
cted token :
You may need an appropriate loader to handle this file type.
| {
|   "type": "object",
|   "required": [
|     "log"
 @ ./~/har-validator/lib/schemas/index.js 10:7-28

ERROR in ./~/har-validator/lib/schemas/request.json
Module parse failed: C:\Users\blah\devel\nextshot\node_modules\har-validator\lib\schemas\request.json Line 2: Un
expected token :
You may need an appropriate loader to handle this file type.
| {
|   "type": "object",
|   "required": [
|     "method",
 @ ./~/har-validator/lib/schemas/index.js 16:11-36

ERROR in ./~/har-validator/lib/schemas/timings.json
Module parse failed: C:\Users\blah\devel\nextshot\node_modules\har-validator\lib\schemas\timings.json Line 2: Un
expected token :
You may need an appropriate loader to handle this file type.
| {
|   "required": [
|     "send",
|     "wait",
 @ ./~/har-validator/lib/schemas/index.js 18:11-36
```

**Comment by amarzavery** [comment]
@dukedougal - We have never tried building with webpack for clientside javascript. The primary use case is node.js. We have experimented with browserify for swaggerpetstore client and that worked. [This github issue](https://github.com/Azure/autorest/issues/639) has the browserified code in a zip file.

**Comment by dukedougal** [comment]
I'm doing node.js with webpack, not for web browser development but for electron desktop application development.

Webpack is an extremely common build tool - probably the primary build tool in use. It would be a real problem if it isn't supported.

If you are willing to try to get it to work with webpack that would be much appreciated because without webpack support our Azure support cannot be implemented.

**Comment by amarzavery** [comment]
Ah I see.. Can you share the script/command that you used to build with webpack? I will look into this at the earliest.

**Comment by dukedougal** [comment]
Hello @amarzavery

The best thing I can recommend is that you try to build this: https://github.com/chentsulin/electron-react-boilerplate

And then do npm install azure-arm-compute

And then somewhere in the electron-react-boilerplate code, put:

import computeManagementClient from 'azure-arm-compute'

**Comment by dukedougal** [comment]
Hello @amarzavery just wondering if this is something you're looking at?  At the moment I can't use Azure node.js because of the webpack errors.

thanks!

**Comment by JamesTheHacker** [comment]
Is there a solution for this because I too am using webpack for Electron app development. I've ran into exactly the same problem.

**Comment by JamesTheHacker** [comment]
Wait, I see what I did wrong. The solution is here: http://stackoverflow.com/questions/35915376/sqlite3-electron-webpack-cannot-find-module-abi-crosswalk-json

Basically, if like me you're including sqlite3 in the main `entry.js` file it will fail:

    const db = new Sqlite3.Database('../data/app.db')

Instead include it in the main Electron process and it will work :)

**Comment by d0ruk** [comment]
> You may need an appropriate loader to handle this file type.

 You need a .json loader for webpack to process those files. 

Also, for reference, if you will bundle node.js apps with webpack, [this lib](https://www.npmjs.com/package/webpack-node-externals) might save you some hours.

**Comment by amarzavery** [comment]
We are coming up with a new repo altogether that will have isomorphic javascript sdks with crisp typescript type definitions. They will work in the browser and in node.js environment.

**Comment by d0ruk** [comment]
While you're here:

I've been playing around with aws, gcloud and azure node.js SDKs for the past month. Azure's is the one with the steepest learning curve. I think it's because most of the docs out there are geared towards using some UI.

Just a heads up.

**Comment by d0ruk** [comment]
@amarzavery 

Yes, I found the docs you linked to. That's where I figured out how to auth (interactiveLogin) the client. I can't utilize interaction in runtime, though, so I'm now exploring service principals. 

I was referring to a more fundamental learning curve. So much of the sdk's examples are tied to VS, and portal UI. For instance: for blob storage, it is not apparent how one can set it up programmatically. I'm sure there is a way to just provide a string (or a key file in gcloud case), and let the sdk take care of the container creation/permissions process. However, most of the examples out there are on using the portal.

p.s. I don't mean to *pollute* the issues section with a UX (DX) concern. It took objectively more time to upload a file to storage.

**Comment by amarzavery** [comment]
@d0ruk - I get what you are saying. We need to make the docs more discoverable and have things in one place for easy access. For uploading blobs, etc. take a look at this repo https://github.com/Azure/azure-storage-node. You will find relevant documentation and other useful stuff over there.

**Comment by amarzavery** [comment]
Please take a look at the new isomorphic sdks over here https://github.com/Azure/azure-sdk-for-js/blob/master/sdk. The sdks can run in the browser and also on the server side (node.js).

All the new sdks are published to npm under the `@azure/<sdk-name>` org structure.
