### ISSUE TITLE
Cannot read DeadLetterQueue using auzure-sb

### ISSUE THREAD

**Issue by thewizster** [Azure/azure-sdk-for-node#1633]
azure-sb docs do not describe a way to access the DeadLetterQueue using ServiceBusService.

Is there another way to access DeadLetterQueue?

**Comment by amarzavery** [comment]
@thewizster - I am not sure about this either. @djrosanova - Can you please respond?

**Comment by thewizster** [comment]
@amarzavery I did not ever find a solution. I'm not sure if it's possible using nodejs.

**Comment by jtaubensee** [comment]
So it doesn't look like this API supports accessing the deadletter queue, but you should be able to create a new receiver object, and append the following to the entity path to receive from the deadletter queue: `/$DeadLetter`

**Comment by amarzavery** [comment]
Please try out the new servicebus sdk `npm i @azure/service-bus`. The sdk has been moved to https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/servicebus/service-bus . The specific example of receiving messages from a DeadLetter Queue can be found [here](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/servicebus/service-bus/samples/typescript/advancedFeatures/processMessageFromDLQ.ts).

In future please open service bus related issues in the new repo https://github.com/Azure/azure-sdk-for-js
