### ISSUE TITLE
Run 'npm install' to install SDK dependencies failed - miami module

### ISSUE THREAD

**Issue by NNM11** [Azure/azure-sdk-for-node#1635]
In a Windows 10 terminal, clone the SDK (0.10.6) git, then run the command 'npm install' in the \azure-sdk-for-node folder to install dependencies.  It failed

The dependency "minami": "git://github.com/devigned/minami#master" in package.json is invalid,  there is no such public folder.
* Is there a legit Miami module to pull?  Thanks,
--
C:\Users\nnm11\OneDrive\Archive-Azure\azure-sdk-for-node>npm install
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:203:12)
npm WARN addRemoteGit     at emitTwo (events.js:87:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:172:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:818:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:319:11)
npm WARN addRemoteGit     at emitOne (events.js:77:13)
npm WARN addRemoteGit     at Socket.emit (events.js:169:7)
npm WARN addRemoteGit     at Pipe._onclose (net.js:469:12)
npm WARN addRemoteGit  git://github.com/devigned/minami.git#master resetting remote C:\Users\nnm11\AppData\Roaming\npm-cache\_git-re
motes\git-github-com-devigned-minami-git-master-a1aed290f75ba06c969a2cb4969cee66 because of error: { [Error: Command failed: git -c cor
e.longpaths=true config --get remote.origin.url
_

**Comment by amarzavery** [comment]
It works well on my windows box.
We are pulling a git module from here : https://github.com/devigned/minami#master

**Comment by NNM11** [comment]
I ran the command behind firewall, with HTTPS_PROXY and HTTP_PROXY vars set.
For a work-around, I removed the Miami reference in package.json to let the 'npm install' finished the dependencies installation.  Once it is completed, the 'npm test' command runs..

**Comment by amarzavery** [comment]
That module is used for generating documentation.

**Comment by NNM11** [comment]
To run the SDK test, the work-around of temporarily removing the Miami module from the package.json to install dependencies, will be fine.
