### ISSUE TITLE
Is that possible to run this yeoman angular project in Azure web app?

### ISSUE THREAD

**Issue by alexliubj** [Azure/azure-sdk-for-node#1660]
https://github.com/yeoman/generator-angular

I tried but not working, it has a grunt file and doesn't have server.js as start.

**Comment by amarzavery** [comment]
Seems like this is a related issue https://github.com/Azure/azure-sdk-for-node/issues/1620

**Comment by amarzavery** [comment]
Can you make app.js as the start file and see if that solves your issue?
