### ISSUE TITLE
[Question] Is storageAccounts.create asynchronous or synchronous in storageManagement2?

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-sdk-for-node#1669]
https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/storageManagement2/lib/operations/storageAccounts.js

I notice there are `create` and `beginCreate` in the above lib. Are they both asynchronous?
In my understanding, `beginCreate` is asynchronous and `create` is synchronous.
Thanks.

**Comment by amarzavery** [comment]
@bingosummer - When beginCreate() method is called directly, it returns a 201 if the account was created for the first time. It will return a 200 if the account was already created.
When create() method is called, it polls based on the response given by the beginCreate() method.
Both methods accept last parameter as a callback (hence they are async in that sense). However, create() does the polling for you and beginCreate() returns after the intial response from the server.

**Comment by bingosummer** [comment]
Thanks @amarzavery 
I totally agree that "Both methods accept last parameter as a callback (hence they are async in that sense)."
Will create() keep polling until the provisioning state is `succeeded`? If so, create() may take more than 1 minute because the storage account will go through the state `creating`, `resolvingdns` and `succeeded`.

**Comment by amarzavery** [comment]
Yup, create() will poll till the provisioning state is succeeded. Hence, we have two methods for users beginCreate() if they want to poll themselves or create() if they want the generated code to poll(). Based on my experience with Storage API, the account creation is faster. 
create operations in Compute/Network libraries are actually long running.
