### ISSUE TITLE
ARM network commands fails setting dependencies with the subnets in SDK version 0.13.0

### ISSUE THREAD

**Issue by MikhailTryakhov** [Azure/azure-sdk-for-node#1673]
Server returns error trying to create items, which depends on subnets.
Error contains information in format "... Cannot set property 'subnet' of undefined" occurred in serializing the payload - "*parameter name & value pairs here*" ..."
You can review detailed issues in Azure CLI external issues [#580](https://github.com/MSOpenTech/azure-xplat-cli/issues/580), [#581](https://github.com/MSOpenTech/azure-xplat-cli/issues/581), [#582](https://github.com/MSOpenTech/azure-xplat-cli/issues/582), [#583](https://github.com/MSOpenTech/azure-xplat-cli/issues/583).

I assume there is a small issue on the server side - maybe camel case error?

**Comment by amarzavery** [comment]
@MikhailTryakhov -should this be closed ?

**Comment by MikhailTryakhov** [comment]
Sure it's fixed
Thank you @amarzavery
