### ISSUE TITLE
Creating and updating notification registrations aren't being created or updated

### ISSUE THREAD

**Issue by WillAnd31** [Azure/azure-sdk-for-node#1682]
This issue exists in `azure-sb`.
This happens when using `updateRegistration`, `createRegistrationId`, `createOrUpdateRegistration` methods, as far as I can tell. These methods should be able to create and update notification registrations.

The data passed back from these methods are correct, for instance when using `createRegistrationId` it returns a new registration ID. However, after I use `getRegistration` with the newly created registration ID it returns an error: `{ [Error: NotFound] code: 'NotFound', statusCode: 404 }`.

The data passed back from the `updateRegistration` is also correct. This is how I'm using it:
- Get a registration ID using `listRegistrationsByTag`
- Use the registration ID I just got to update it using `updateRegistration` with the following information:

```
{ 
  RegistrationId: '7291832229515971243-3697628122912108107-6',
  _: {
    ContentRootElement: 'GcmRegistrationDescription'
  },
  GcmRegistrationId: '< inserted registration here >',
  Tags: 'willand31,example,sometag' 
}
```
- The data received is:

```
{
  ETag: '10',
  ExpirationTime: '2016-06-29T09:36:40.964Z',
  RegistrationId: '7291832229515971243-3697628122912108107-6',
  GcmRegistrationId: '< the same registration id I used >',
  Tags: 'willand31,example,sometag',
  _: {
    ContentRootElement: 'GcmRegistrationDescription',
    id: 'https://< notification hub >.servicebus.windows.net/< notification hub name >/registrations/7291832229515971243-3697628122912108107-6?api-version=2013-07',
    title: '7291832229515971243-3697628122912108107-6',
    published: '2016-03-31T09:36:40Z',
    updated: '2016-03-31T09:36:40Z',
    link: ''
  } 
}
```
- Use `getRegistration` with the same registration ID I've been using, and I receive:

```
{
  ETag: '10',
  ExpirationTime: '2016-06-29T09:36:40.964Z',
  RegistrationId: '7291832229515971243-3697628122912108107-6',
  GcmRegistrationId: '< the same registration id I used >',
  _: {
    ContentRootElement: 'GcmRegistrationDescription',
    id: 'https://< notification hub >.servicebus.windows.net/< notification hub name >/registrations/7291832229515971243-3697628122912108107-6?api-version=2013-07',
    title: '7291832229515971243-3697628122912108107-6',
    published: '2016-03-31T09:36:40Z',
    updated: '2016-03-31T09:36:40Z',
    link: ''
  } 
}
```
- And If I use `listRegistrationsByTag` with any of the tags I tried to update it doesn't list the registration I tried to update

I have a Java version of what I'm trying to do here in this NodeJS app and the Java version works just fine, because of this it's stalling me and the company I work for from moving to a NodeJS backend. I've tried to debug it as much as I know how to, but haven't been able to figure out what's going on. 

Please fix ASAP.

**Comment by WillAnd31** [comment]
Also, some other information:

The call that is sent when trying to use `updateRegistration ` is sending the following XML:
```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<entry xmlns="http://www.w3.org/2005/Atom"><updated>2016-03-31T09:53:52.135Z</updated>
  <content type="application/xml"><RegistrationDescription xmlns:i="http://www.w3.org/2001/XMLSchema-instance" i:type="GcmRegistrationDescription" xmlns="http://schemas.microsoft.com/netservices/2010/10/servicebus/connect">
      <RegistrationId>7291832229515971243-3697628122912108107-6</RegistrationId>
      <GcmRegistrationId>gcm registration id was inserted here</GcmRegistrationId>
      <Tags>will,2659,2314d54f7e673543,android</Tags> 
    </RegistrationDescription>
  </content>
</entry>
```

**Comment by amarzavery** [comment]
@djrosanova - Can you take a look at this issue?

**Comment by tony-gutierrez** [comment]
It probably has something to do with the node sdk using an ancient service bus api version. Where the hell is MS on this?

**Comment by amolr** [comment]
Hi,

We have a release a new npm package of azue-sb. Can you please update with the new npm package and checks if its working now

Thanks,
Amol

**Comment by mozehgir** [comment]
If the error persists feel free to re-open this issue in the https://github.com/Azure/azure-sdk-for-js repository .
