### ISSUE TITLE
Interact with Recovery Services

### ISSUE THREAD

**Issue by jdc0589** [Azure/azure-sdk-for-node#1683]
Is there any way to interact with Recovery Services via the SDK? I need to be able to list machines in backup vaults, backup statuses, etc...

All I'm seeing is `Microsoft.Backup` listed via the provider list. But I haven't been able to get much more than that.

**Comment by amarzavery** [comment]
@sriramvu - Can you respond to this issue?

**Comment by sriramvu** [comment]
RecoveryServices includes Azure Site Recovery and Azure BackUp, 
Regarding this issue, we have communicated to Backup team (@dragonfly91, @AditTulasi, @mkherani).

**Comment by jdc0589** [comment]
For what it's worth, It *seems* doable via the `management.azure.com` API. Granted, I figured that out from sniffing network traffic of powershell commands; I can't actually find documentation on it anywhere.

**Comment by AditTulasi** [comment]
@jdc0589 - It is not completely clear what you are trying to do. Currently there are two types of vaults which support backup. 
1. Backup vault - These are the vaults you deal with when you use our PowerShell cmdlets or when you are dealing with old portal (manage.windowsazure.com).
2. Recovery services vault - Currently this is in preview. It is not generally available yet. We are working towards it.

Now, could you please explain which vault you are dealing with? To make it more clear, please specify how you are using it currently (PS/OldPortal/NewPortal).

**Comment by jdc0589** [comment]
@AditTulasi I'm refering to BackupVaults. I'm just looking to see if there is an easy way to list and get info on backup vaults, protected items (status, last backup, etc..)

**Comment by AditTulasi** [comment]
@jdc0589 - Hi Davis. We released .Net SDK and Powershell support for Backup vaults last year. Here is the link to powershell documentation: https://azure.microsoft.com/en-us/documentation/articles/backup-azure-vms-automation/ 

We will be releasing .Net SDK and powershell support for Recovery services vaults shortly.

**Comment by jdc0589** [comment]
@AditTulasi Should I interpret that to mean "this functionality does not exist in the nodejs sdk"?

I opened this issue here specifically because I was asking about this functionality with the NodeJs SDK, not powershell or .net

**Comment by eduardkoller** [comment]
@AditTulasi Can you please provide the timeline for adding recovery services to the Node SDK?

**Comment by AditTulasi** [comment]
@jdc0589 Hi Davis, That's on our current roadmap. However, please keep monitoring our site for future updates. :)

**Comment by eduardkoller** [comment]
Thank you both. I will close this issue for now.
