### ISSUE TITLE
eol api version broke computemanagement2

### ISSUE THREAD

**Issue by pauldallen** [Azure/azure-sdk-for-node#1684]
./lib/services/computeManagement2/lib/operations/containerServiceOperations.js

apiVersion = '2015-11-01-preview';

This version is no longer supported by azure.

The api-version '2015-11-01-preview' is invalid. The supported versions are '2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.]

**Comment by amarzavery** [comment]
The container service was just published last week using this [spec](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-compute/2015-11-01-preview/swagger/containerService.json).

@huangpf, @hyonholee  - Can you take a look at this?

**Comment by huangpf** [comment]
@pauldallen Can we get the full request/response payloads?

The API version should only be for ACS, not other services under Compute.

**Comment by huangpf** [comment]
Add @sauryadas

**Comment by huangpf** [comment]
@sauryadas

I can't reproduce the error using my subscription which should have this feature enabled. Does the users need to sign up for using ACS?

Request:
```
silly:   requestOptions
silly:   {
silly:       method: 'GET',
silly:       url: 'https://management.azure.com/subscriptions/x/providers/Microsoft.ContainerService/locations/westus/operations/3205391d-7870-47fb-a076-d3a210b5c19b?api-version=2015-11-01-preview'
```

Response:
```
silly:   returnObject
silly:   {
silly:       statusCode: 200,
```

**Comment by sauryadas** [comment]
No it's in public preview .

Best
{Saurya}

On Apr 1, 2016, at 10:22 AM, huangpf <notifications@github.com<mailto:notifications@github.com>> wrote:


@sauryadas<https://github.com/sauryadas>

I can't reproduce the error using my subscription which should have this feature enabled. Does the users need to sign up for using ACS?

Request:

silly:   requestOptions
silly:   {
silly:       method: 'GET',
silly:       url: 'https://management.azure.com/subscriptions/x/providers/Microsoft.ContainerService/locations/westus/operations/3205391d-7870-47fb-a076-d3a210b5c19b?api-version=2015-11-01-preview'


Response:

silly:   returnObject
silly:   {
silly:       statusCode: 200,


-

**Comment by pauldallen** [comment]
`{ [Error: The api-version '2015-11-01-preview' is invalid. The supported versions are '2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.]
  statusCode: 400,
  request: 
   { rawResponse: false,
     queryString: {},
     method: 'DELETE',
     headers: 
      { 'x-ms-client-request-id': '564246c4-de2d-42b0-9c51-b1d6d6f1fc6e',
        'accept-language': 'en-US',
        'Content-Type': 'application/json; charset=utf-8' },
     url: 'https://management.azure.com/subscriptions/<subscription id>/resourceGroups/%2Fresourcegroups%2Ftestcluster-g-52b4682e6b9a937d1f00000b/providers/Microsoft.ContainerService/containerServices/cc52b4682e6b9myinstance123428467?api-version=2015-11-01-preview',
     body: null },
  response: 
   { body: '{"error":{"code":"InvalidApiVersionParameter","message":"The api-version \'2015-11-01-preview\' is invalid. The supported versions are \'2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04\'."}}',
     headers: 
      { 'cache-control': 'no-cache',
        pragma: 'no-cache',
        'content-type': 'application/json; charset=utf-8',
        expires: '-1',
        'x-ms-failure-cause': 'gateway',
        'x-ms-request-id': '609c5a9b-6d86-48e5-8055-44b683f42af8',
        'x-ms-correlation-request-id': '609c5a9b-6d86-48e5-8055-44b683f42af8',
        'x-ms-routing-request-id': 'WESTUS:20160401T210407Z:609c5a9b-6d86-48e5-8055-44b683f42af8',
        'strict-transport-security': 'max-age=31536000; includeSubDomains',
        date: 'Fri, 01 Apr 2016 21:04:07 GMT',
        connection: 'close',
        'content-length': '242' },
     statusCode: 400 },
  code: 'InvalidApiVersionParameter' }
`

**Comment by huangpf** [comment]
The RG name doesn't seem to be right with the ```%2F``` characters:
```
resourceGroups/%2Fresourcegroups%2Ftestcluster-g-52b4682e6b9a937d1f00000b
```

And the error is from ```gateway```, so I guess it's returned from ARM, and not necessarily hitting ACS. 

@amarzavery Thoughts?

@pauldallen Can you try another RG name, and the containerServiceOperations.List() method?

**Comment by pauldallen** [comment]
That was it - thank you! not sure why i'm getting the invalidapiversionparameter message... but you solved it for me!
