### ISSUE TITLE
ResourceManagementClient Code Sample Incorrect

### ISSUE THREAD

**Issue by sedouard** [Azure/azure-sdk-for-node#1697]
Hey! The [README](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/resourceManagement/README.md) for the [`azure-arm-resource`](https://npmjs.com/azure-arm-resource) module is incorrect.

Version: 1.12.0

Here's what it currently says:

```js
var resourceManagement = require("azure-arm-resource");
var client = new resourceManagement.ResourceManagementClient(credentials);
```

Here's what it actually is:

```js
var rgClient = require("azure-arm-resource").ResourceManagementClient;
var client = new rgClient.ResourceManagementClient(credentials);
```

It feels a bit awkward but that's what I'm seeing.

**Comment by sedouard** [comment]
Looks like the README is based on the 1.14.0-preview version which isn't what install on `npm install` by default. Closing out. hope this helps someone else!

**Comment by amarzavery** [comment]
Hey @sedouard The [README.md](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/resourceManagement/README.md) is correct. As per https://www.npmjs.com/package/azure-arm-resource, the latest version is 1.42-preview.

Both the versions 1.12 and 1.14 are very old versions. How did you end up getting such old versions?

**Comment by sedouard** [comment]
sorry @amarzavery I meant to type `1.4.1-preview`. However yeah a regular `npm install` gave me `1.12`.
