### ISSUE TITLE
Error Message : this._cache.find is not a function

### ISSUE THREAD

**Issue by paritosh16** [Azure/azure-sdk-for-node#1703]
I have used the `computeClient.virtualMachines.start` using [this](https://github.com/Azure/azure-sdk-for-node/blob/master/examples/ARM/compute/vm-sample.js) reference. Authentication is correct. The API call gives an error message that says `this._cache.find is not a function`

The code snippet looks like the following
    
    computeClient.virtualMachines.start('abc','xyz',function(err, result){
      if(err) {
        console.log("API error : ");
        console.log(err);
      } else {
        console.log("API success : ");
        console.log(result)
      }
    });

It doesn't even log error in the `if` block. The process snaps out right where the API call is made.

Need help on this as soon as possible.

**Comment by amarzavery** [comment]
@paritosh16 
- What version of azure-arm-compute, ms-rest and ms-rest-azure package are you using (You should find them in node_modules folder) ?
- What version of node are you using?
From this it is hard to tell. It would be nice if you could provide the entire stack trace.

**Comment by eduardkoller** [comment]
@paritosh16 - can you please provide more details, to help the team investigate?

**Comment by paritosh16** [comment]
Sorry for the delayed response folks, was caught up with work.

Following are the versions of the modules I am using -
```
azure-arm-compute :  ^0.17.0 
ms-rest-azure :  ^1.12.0
ms-rest : ^1.12.0
node version : 5.3.0
```

Let me know if you guys need any more information.

**Comment by eduardkoller** [comment]
@paritosh16 - can you take a look a this sample script, and see it that can work for you? https://github.com/Azure/azure-sdk-for-node/blob/master/examples/ARM/compute/vm-sample.js

**Comment by paritosh16** [comment]
I tried listing all the VMs in the subscription, starting/stopping the VM on the same lines as the sample script. I am still getting the same error `this._cache.find is not a function`. 

I am also unable to find which part of the code in the sdk throws this exception !

**Comment by amarzavery** [comment]
@paritosh16 - Can you provide us the error stack trace?

**Comment by amarzavery** [comment]
The error object should have the stack. Try printing the stack `console.log(error.stack);` in the callback.

**Comment by paritosh16** [comment]
Prior to the API call `computeClient.virtualMachines.listAll()`, I instantiate the computeClient object. The object instantiation itself throws the `this._cache.find is not a function` error. 

If I do a `console.log("Hello world !")` just before the instantiation, the log works. If I do `console.log("Hello world !")` after the instantiation, the log no longer works because of the error.

**Comment by amarzavery** [comment]
Hi @paritosh16  I found the problem. 

We depend on [adal-node](https://github.com/AzureAD/azure-activedirectory-library-for-nodejs) for authentication with azure. The ApplicationTokenCredentials class takes an optional parameter `tokenCache` that has a default value null.

In the vm sample we are using the file token cache. The file token cache is a utility that is used by the people who clone the node sdk and want to contribute. It is not shipped as a part of the runtime.

Adal node calls the find() on the cache. Since this is null it throws.

Ideally, we should have used the [MemoryCache()](https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/blob/master/lib/adal.js#L36) as the default option. We will fix this bug ASAP in the upcoming release.

Until then to unblock yourself, please create the memory cache by refering the adal-node module.
Since ms-rest-azure depends on it, it should be present inside the node_modules folder.
```
var adal = require('adal-node');
var tokenCache = new adal.MemoryCache();
var credentials = new msRestAzure.ApplicationTokenCredentials('clientId', 'domain', 'secret', { 'tokenCache': tokenCache });
```

That should solve the issue.

**Comment by paritosh16** [comment]
I am using the following function to get the token.
```
function getAzureTokenId(callback) {
  var adal=require('adal-node');
  var AuthenticationContext= adal.AuthenticationContext;
  var tenantID="tenant_Id";
  var clientID="client_Id";
  var resource="https://management.azure.com/";
  var authURL="https://login.windows.net/" + tenantID;
  var secret="application_secret";
  var context=new AuthenticationContext(authURL);
  context.acquireTokenWithClientCredentials(resource, clientID, secret, function(err,tokenResponse) { 
    callback(tokenResponse);
  });
}
```
The above function gives `tokenResponse` which is then used for obtaining the credentials.

```
var credentials = new msRestAzure.ApplicationTokenCredentials(clientId, domainName, secret, { 'tokenCache': tokenResponse });
```

The credentials are used to make the final API call for listing the Azure VMs

```
var computeClient = new computeManagementClient(credentials, subscriptionId);
    computeClient.virtualMachines.listAll(function(err, result){
      if(err) {
        console.log("List API error : ")
        console.log(err.stack);
      } else {
        console.log("List API success : ")
        console.log(result)
      }
    });
```

Could you please help me as to where the changes you mentioned should happen? My sense says that the `tokenCache` is returned by the function `acquireTokenWithClientCredentials` and I still have to figure out how to generate that token using the `MemoryCache()` approach that was suggested.

**Comment by amarzavery** [comment]
Why are you using `getAzureTokenId()`. The stuff that you are doing in that function is already being done for you when you new up ApplicationTokenCredentials(). All you need to do is provide the memory token cache from adal.

As I suggested, you only need to pass the token cache. What you are passing now is the tokenResponse received from adal. The context that you have created in getAzureTokenId() has an _cache property. If you pass that to ApplicationTokenCredentials then this will work.

If you wish to get the token yourself as you do in getAccessTokenId() that is fine.

In that case, you should use the simple TokenCredentials() object that is exported from msRestAzure.

```
var credentials = new msRestAzure.TokenCredentials(tokenResponse.tokenType, tokenResponse.accessToken);
```
Now you can pass this credentials object to the compute client.


I  am making all of this much simpler in the next version. Check the new API in this [PR](https://github.com/Azure/autorest/pull/1066/files#diff-0f739a1d3fa20ab141bcac8db4ae6689R20) for the new mechanism and let me know your thoughts about it. This will be published mostly by next week.

**Comment by amarzavery** [comment]
@paritosh16 - The authentication process has been made super simple for users with the latest version of runtime `ms-rest-azure: "1.14.2"`.
Please take a look at this [updated doc](https://github.com/Azure/azure-sdk-for-node/blob/master/Documentation/Authentication.md#using-authentication-in-your-nodejs-script) and let me know if you have any issues.

**Comment by eduardkoller** [comment]
@paritosh16 - does this answer your question?

**Comment by paritosh16** [comment]
Apologies for the delay in the response. 
@amarzavery Thanks for the updated documentation and it mentions the steps pretty much clearly.

I did the following - 

```
msRestAzure.loginWithServicePrincipalSecret(clientId, secret, domainName, function(err, credentials) {
   if (err) {
    console.log("This is error login with service principal secret !!")
    console.log(err);
    return;
   } else {
    var computeManagementClient = require('azure-arm-compute');
    computeClient.virtualMachines.listAll(function(err, result){
      if(err) {
        console.log("List API error : ")
        console.log(err.stack);
      } else {
        console.log("List API success : ")
        console.log(result)
      }
    });
   }
 });
}
``` 

I am getting the following response - 
```
This is error login with service principal secret !!
Error: Failed to acquire token for application with the provided secret.
Error: Get Token request returned http error: 404
    at /Users/paritosh/Github/app/node_modules/ms-rest-azure/lib/credentials/applicationTokenCredentials.js:123:29
    at /Users/paritosh/Github/app/node_modules/adal-node/lib/token-request.js:150:11
    at Request._callback (/Users/paritosh/Github/app/node_modules/adal-node/lib/util.js:133:7)
    at Request.self.callback (/Users/paritosh/Github/app/node_modules/request/request.js:200:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/paritosh/Github/app/node_modules/request/request.js:1067:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/paritosh/Github/app/node_modules/request/request.js:988:12)
```

I am sure that the values for `clientId`, `secret`, `domain` and `subscriptionId` are correct. I don't know what I am missing out on.

Thank you for bearing with me.

**Comment by paritosh16** [comment]
@amarzavery Any updates ?

**Comment by amarzavery** [comment]
@paritosh16 - I tried the sample with the values for clientId, secret and domain and it worked for me. Please make sure that the values are correct. Were you able to [login to the CLI, as a service principal](https://github.com/Azure/azure-sdk-for-node/blob/master/Documentation/Authentication.md#step-3-login-as-a-serviceprincipal)?
