### ISSUE TITLE
Add values in AzureEnvironment

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-sdk-for-node#1707]
`resourceManagement.ResourceManagementClient` needs a parameter `baseUri` which can be `https://management.chinacloudapi.cn/` or `https://management.azure.com/`.
I think, they should be part of Azure Environments. Can we add these values into AzureEnvironment?

**Comment by amarzavery** [comment]
Yes we can. Initially, we had kept it simple to only have endpoints related to login. However, we can have a full set of end points defined for each endpoint as we do in xplat cli.
We will update this in new version of client-runtime.

**Comment by amarzavery** [comment]
@bingosummer - The new version of ms-rest-azure has all the updated values for supported environments.
