### ISSUE TITLE
Authentification Issue (ServiceBus)

### ISSUE THREAD

**Issue by Felix-N** [Azure/azure-sdk-for-node#1708]
Hi,

we had several issue being rate limited using the Azure ServiceBus.
We opened a support case with Microsoft, as the issue appeared to be not in our code but somewhere underlying.

Amit from Microsoft was so kind evaluating the issue further and pinned it to the ACS implementation in the Azure-SDK-for-Node.

**Here is the research from Amit (quote from the email communication):**

Following the plan, I created the simple repro which creates the queue and sends/receives the messages. Capturing the network traces for the repro, I see that Node.js SDK doesn’t cache the ACS token and reuse it, as confirmed before.

Further, I don’t see that there’s any specific API which initiates authenticating to ACS instead I see client authenticating to ACS on calling any operation i.e. createqueue, Send message or receive message. However, not all calls to send/receive/create are authenticated to ACS but it seems more specific to scope / websource in which operation is being called. For example, following code sends 3 messages calling SendQueueMessage. However, I notice that authentication to ACS is just once for these calls.

```
serviceBusClient.sendQueueMessage(queue, 'Send Message Works', function(error1) {
    if (error1) {
      console.log(error1);
    } else {
      console.log('Sent first Message');
      serviceBusClient.sendQueueMessage(queue, 'Send Message Still Works', function(error2) {
        if (error2) {
          console.log(error2);
        } else {
          console.log('Sent Second Message');
            //receiveMessages();

          serviceBusClient.sendQueueMessage(queue, 'Send Message Still Works', function (error3) {
              if (error3) {
                  console.log(error3);
              } else {
                  console.log('Sent Third Message');
                  //receiveMessages();
              }
          });

        }
      });
    }
  });

```

And if I put following code just below above code, I see another ACS authentication, though it’s using same serviceBusClient.

```
serviceBusClient.sendQueueMessage(queue, 'Send Message Works', function (error2) {
      if (error2) {
          console.log(error2);
      } else {
          console.log('Sent first Message');
          serviceBusClient.sendQueueMessage(queue, 'Send Message Still Works', function (error3) {
              if (error3) {
                  console.log(error3);
              } else {
                  console.log('Sent Second Message');
                  //receiveMessages();
              }
          });
      }
  });
```

So, it’s unpredictable when request to Service Bus will be going through ACS.

I’ve attached the sample script which I used for the repro. The script creates a queue and sends around 5 messages, so there’re 6 requests made to Service Bus (CreateQueue + 5 send messages). Capturing the network traces, we indeed see 6 different connections to Service Bus over different connections. However, there’re only 3 connections to ACS i.e. client script requested token only 3 times!

As Node SB APIs are third-party APIs, we don’t have team which can confirm the details of the behaviour, you may want to evaluate community based support.

So, as discussed initially, using SAS Key for authenticating with Service Bus should be better option unless you’ve any specific requirement to authenticate Service and Client through ACS. As SAS uses symmetric key, it reduces round trips to other service and should improve performance too.
[sbqueue_2.zip](https://github.com/Azure/azure-sdk-for-node/files/219134/sbqueue_2.zip)

**Comment by Felix-N** [comment]
Any idea on this? From our point of view this appears to be a root cause for other issues.

**Comment by eduardkoller** [comment]
@djrosanova - can you please take a look?

**Comment by jtaubensee** [comment]
@Felix-N - Is this still an issue?

**Comment by Felix-N** [comment]
Hi John,

I've no reason to assume it is solved, however we've build around it - the
problem was (is?) production critical for us.

Sorry I can't give you more details about the issue than that. Only
feedback I can give is that it would be worth (in my opinion) to solve it,
as everything load related will fail in the node sdk due to the
authentication throtteling way before​ the intended quotas are reached.

Best,

Felix

**Comment by jtaubensee** [comment]
@Felix-N - So were you able to authenticate using SAS then?

**Comment by Felix-N** [comment]
Hi John,

I'm not sure if SAS were included in the node sdk 11 months ago, I recall
that we looked into the sdk and the authentification scheme, but eventually
decided to work around the problem reducing the amount of messages heavily
in addition to a failover which is independent of the serviceus.

Cheers,

Felix

**Comment by jtaubensee** [comment]
@Felix-N - Glad to hear. SAS is definitely the way to go, as it prevents you from taking a dependency on another service, and is the preferred route of Service Bus. As such, I don't think that we will investigate this issue further.
