### ISSUE TITLE
MX Preference of 0 causes validation failure

### ISSUE THREAD

**Issue by Mobius5150** [Azure/azure-sdk-for-node#1711]
It appears that the CLI encounters problems when there exists an MX record with a `preference` of `0`. This is because the Azure DNS API returns an object of the form `{ exchange: "..." }` when `preference` == `0`, instead of the expected `{ exchange: "...", preference: 0 }`.

The effect of this is that if you have a record with preference 0 in your record set then _you will be unable to add or remove any further records from the record set until you remove this record._ [0 is indeed a valid value for preference.](https://support.office.com/en-us/article/What-is-MX-priority-2784cc4d-95be-443d-b5f7-bb5dd867ba83)

Steps to repro (using the xplat cli for an example, but the issue is indeed with the SDK):

``` bash
> azure network dns record-set add-record dnsgroup mysite.com @ MX
info:    Executing command network dns record-set add-record
Preference for MX record type: 0
Exchange for MX record type: exchange.example.com

> azure network dns record-set list dnsgroup mysite.com MX
info:    Executing command network dns record-set list
+ Looking up the DNS Record Sets                                               
data:    Name  TTL   Type  Records                                Tags
data:    ----  ----  ----  -------------------------------------  ----
data:    @     3600  MX    undefined exchange.example.com
info:    network dns record-set list command OK

> azure network dns record-set add-record dnsgroup mysite.com @ MX
info:    Executing command network dns record-set add-record
Preference for MX record type: 1
Exchange for MX record type: exchange2.example.com
+ Looking up the dns zone "mysite.com"                                       
+ Looking up the DNS Record Set "@" of type "MX"                               
+ Updating record set "@"                                                      
error:   parameters.recordSet.properties.mxRecords.preference cannot be null.
info:    Error information has been recorded to /Users/mblouin/.azure/azure.err
error:   network dns record-set add-record command failed
```

Note the `undefined` value in the `Records` column after the second command, and the object validation failure in the third command.

It seems the solution would be either to have the service return a more correct JSON object and/or add the preference key with value `0` to the received object [when parsing here](https://github.com/Azure/azure-sdk-for-node/blob/33aa375a4c3d781b341b8d302d3281dd33ccbde4/lib/services/dnsManagement/lib/dnsManagementClient.js#L1872).

**Comment by amarzavery** [comment]
This is a bug on the service side. The node sdk for network is autogenerated from this [spec](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-network/2016-03-30/swagger/network.json). Either the service needs to do a good job or spec needs to modified to generate correct code.
Adding folks from the network team.
@deepakswifty @romangromov - please take a look at this issue.

**Comment by amarzavery** [comment]
@t-alguer - from dns can you take a look at this issue as well.

**Comment by romangromov** [comment]
@Mobius5150 which version of Xplat-CLI used? (use  `azure -v`)

**Comment by Mobius5150** [comment]
@romangromov I tested using 0.9.19

**Comment by amarzavery** [comment]
@romangromov - Just for reference, the dns arm node library is still hyak generated.

**Comment by t-alguer** [comment]
I am not working on DNS anymore. Adding @jtuliani, @vladrai and @karravi-msft

**Comment by amarzavery** [comment]
Closing this due to age. Feel free to reopen the issue, if you are still seeing this problem.
