### ISSUE TITLE
Azure Automation Management support?

### ISSUE THREAD

**Issue by nirhadassi** [Azure/azure-sdk-for-node#1714]
Hey,
Looking to create some automation jobs (using Runbooks) on my node app.
Does Azure Automation support exist? Or is it coming soon maybe?

**Comment by amarzavery** [comment]
@jodoglevy - Can you please take a look at this issue?

**Comment by jodoglevy** [comment]
@nirhadassi no plans right now, but I will bring this up with the team and see what we can do. If you can post an ask for this on our UserVoice (https://feedback.azure.com/forums/246290-automation) and upvote it, that would help us prioritize this work.

**Comment by amarzavery** [comment]
@jodoglevy - Thank you for the prompt response. I shall be closing the issue, based on the response.
