### ISSUE TITLE
Get Billing info.

### ISSUE THREAD

**Issue by Leeh91** [Azure/azure-sdk-for-node#1717]
Hi,

I would like to know if there's any way I can get Billing and storage size info to make this information available to the customers.

**Comment by amarzavery** [comment]
@Matt-Westphal - Does the Commerce API provide billing info? If not, then do you know who is the right person to contact?

**Comment by moinak3** [comment]
There are 2 APIs involved here: Azure Usage API (REST API that provides hourly or daily level usage aggregates (e.g. 50 GB SQL, 24 hours of A1 VM) and the Azure RateCard API (REST API that provides the list of all resources available to be consumed at an Azure offer level, along with marketing information and pricing details.

The two in combination can provide callers with a rated estimate of what their Azure consumption would cost, but we don't have an API that provides the "exact" charges. hope this helps?

**Comment by Leeh91** [comment]
Thank you for your attention,

I have a blob storage with some differents containers, Is it possible to get the used size of an specific one?

**Comment by amarzavery** [comment]
@yaxia - is it possible to get this from the storage management or data plane libraries. If so, can you point to a method that does that or give an example ?

Thanks,
Amar Zavery

On Apr 22, 2016, at 3:40 AM, "Leandro de Castilho" <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you for your attention,

I have a blob storage with some differents containers, Is it possible to get the used size of an specific one?

-

**Comment by yaxia** [comment]
@amarzavery  The storage cost can consist of: bandwidh, transactions and capacity. There is no library can get the billing info directly. You may need to enumrate the blobs and blocks/pages in it. Please refer to this [article](http://blogs.msdn.com/b/windowsazurestorage/archive/2010/07/09/understanding-windows-azure-storage-billing-bandwidth-transactions-and-capacity.aspx) for more details.

**Comment by amarzavery** [comment]
@yaxia - Thank you for sharing the article. It would be nice if the link to this article is part of the readme of https://github.com/Azure/azure-storage-node repo. This will help in easy discovery.
@Leeh91 - Hope this article helps you get some billing information. There is an ongoing effort, to get the a client side library for the billing API. We should be able to get this out in few weeks.

**Comment by jdc0589** [comment]
@moinak3 does the RateCard api support EA rates?

**Comment by Leeh91** [comment]
Thanks again for the answers,

I understand there's no way I can show to my customers the billing info based on its storage container. But what if I just want to show the size of the container, without billing info. Is it possible?

**Comment by amarzavery** [comment]
@Leeh91 - We have two packages for billing and usage that you can use
- https://www.npmjs.com/package/azure-arm-billing
- https://www.npmjs.com/package/azure-arm-commerce.

Feel free to open another issue, if you have any questions about it.

**Comment by quaijamiro** [comment]
Hello, I have two tasks to do:

1. Extracting cost estimation for Virtual Macine
2. Extracting cost estimation for App Service

Which library would be useful for accomplishing these two tasks?
