### ISSUE TITLE
How to deploy a deployment template? 

### ISSUE THREAD

**Issue by arafato** [Azure/azure-sdk-for-node#1737]
Hi--, 

is there an API / function for deploying an ARM deployment template written in JSON (analog to the CLI command  `azure group deployment create -f azuredeploy.json -g ExampleResourceGroup -n ExampleDeployment`)? 
I've looked through the API but couldn't find an according function (only for validating a template). Thanks!

Best regards
--Oliver.

**Comment by amarzavery** [comment]
@arafato 
- [CreateOrUpdate a deployment](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/resourceManagement/lib/resource/operations/deployments.js#L428)
- [Validate a deployment](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/resourceManagement/lib/resource/operations/deployments.js#L1055)
- [A test that will act as a sample](https://github.com/Azure/azure-sdk-for-node/blob/master/test/services/resourceManagement/resourceManagementClient-tests.js#L159) The test is skipped as the deployment template needs to be replaced. However, it will act as a good starting point.
- This sample for [VM](https://github.com/Azure/azure-sdk-for-node/blob/master/examples/ARM/compute/vm-sample.js) will act as a good starting point for authentication, etc. It also has a VS sln file in [the folder above](https://github.com/Azure/azure-sdk-for-node/tree/master/examples/ARM).

For authentication via node sdk we support 
- a user account that is an orgid (school/work account) that is 2FA disabled
- a service principal for scripting scenarios.
  - It is very easy to create an sp via CLI once. Please take a look at the docs over [here](https://github.com/Azure/azure-sdk-for-node/blob/master/Documentation/Authentication.md#creating-a-serviceprincipal-for-scripting-scenarios).

If you use, VisualStudio with [nodejs](https://github.com/Microsoft/nodejstools/releases) and [typescript](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Editor-Support) plugins, or vscode

**Comment by arafato** [comment]
Thank you so much, exactly what I was looking for!

Am 8. Mai 2016, um 19:48, Amar Zavery <notifications@github.com> schrieb:

@arafato
- [CreateOrUpdate a deployment](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/resourceManagement/lib/resource/operations/deployments.js#L428)
- [Validate a deployment](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/resourceManagement/lib/resource/operations/deployments.js#L1055)
- [A test that will act as a sample](https://github.com/Azure/azure-sdk-for-node/blob/master/test/services/resourceManagement/resourceManagementClient-tests.js#L159) The test is skipped as the deployment template needs to be replaced. However, it will act as a good starting point.
- This sample for [VM](https://github.com/Azure/azure-sdk-for-node/blob/master/examples/ARM/compute/vm-sample.js) will act as a good starting point for authentication, etc. It also has a VS sln file in [the folder above](https://github.com/Azure/azure-sdk-for-node/tree/master/examples/ARM).

For authentication via node sdk we support
- a user account that is an orgid (school/work account) that is 2FA disabled
- a service principal for scripting scenarios.
  - It is very easy to create an sp via CLI once. Please take a look at the docs over [here](https://github.com/Azure/azure-sdk-for-node/blob/master/Documentation/Authentication.md#creating-a-serviceprincipal-for-scripting-scenarios).

If you use, VisualStudio with [nodejs](https://github.com/Microsoft/nodejstools/releases) and [typescript](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Editor-Support) plugins, or vscode

---

**Comment by arafato** [comment]
@amarzavery is it possible to reference a locally stored JSON templates? `createOrUpdate` only seems to accept absolute URIs (`file://path/to/file` is also not working). Thanks!

**Comment by amarzavery** [comment]
You need to use [parameters.properties.template](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/resourceManagement/lib/resource/operations/deployments.js#L377) for local file and [parameters.properties.templatelink.uri](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/resourceManagement/lib/resource/operations/deployments.js#L383) for uri.
