### ISSUE TITLE
User and Service Credentials

### ISSUE THREAD

**Issue by nvsoares** [Azure/azure-sdk-for-node#1743]
Hi.
I'm trying to Initialise the client, according to the documentation, but I have trouble understanding where to get some information like:
```javascript
//user authentication
var credentials = new msRestAzure.UserTokenCredentials('my-client-id', 'my-domain', 'my-username', 'my-password', 'my-redirect-uri');
//service principal authentication
var credentials = new msRestAzure.ApplicationTokenCredentials('my-client-id', 'my-domain', 'my-secret');
```

Where can I get?
'my-client-id' - do not know;
'my-secret') - do not know;
'my-domain' - Azure Management, Active Directory, Domains?
'my-username' - Azure Account User Name?
'my-password' - Azure Account Password?
'my-redirect-uri' - do not know;

The closer I was to get, I think, got error that the user does not have permissions to read;
Is there any tutorial? Can anyone explain, clearly, how to get information and where?

**Comment by amarzavery** [comment]
You either need A) user credentials or you need B) service principal credentials for authentication purpose, to talk to Azure.
A) User account(You must using this user account to login to the azure portal). 
- There are  two types of users. 
    - Users with work school account (also known as **org id**)
    - Users with gmail/Hotmail/outlook account (also known as **live id**). 
- Users with **live id need interactive authentication** (browser pop or giving a url and code to paste in the browser and authenticate over there).
- The node sdk only supports users with org id as they usually do not require interactive auth.

B) Service Principal account
This account is used for scripting/automation scenarios. You can give access rights to an application at a designated scope. (Entire subscription, A resource group in a subscription, or resources in a resource group inside a subscription).

We have node.js based cross platform CLI that can be used to create a service principal or you can use the portal to create the service principal. This [document](https://github.com/Azure/azure-sdk-for-node/blob/master/Documentation/Authentication.md) walks you through that and also answers the questions you asked about domain, password, secret, etc.

**Comment by amarzavery** [comment]
@nvsoares - The authentication process has been made super simple for users with the latest version of runtime `ms-rest-azure: 1.14.2`.
Please take a look at this [updated doc](https://github.com/Azure/azure-sdk-for-node/blob/master/Documentation/Authentication.md#using-authentication-in-your-nodejs-script) and let me know if you have any issues.

**Comment by eduardkoller** [comment]
@nvsoares - does this answer your questions

**Comment by nvsoares** [comment]
Hello. Yes , that link above clarified my doubts
Thank you
