### ISSUE TITLE
Strange property names for Subscription metrics object

### ISSUE THREAD

**Issue by NoelAbrahams** [Azure/azure-sdk-for-node#1746]
Hi,

**Azure NPM version**: 0.10.6

I'm using the Azure npm to access a service bus topic via HTTP.

The `ServiceDescription.CountDetails` object returned from a `getSubscription` call looks like this:

![image](https://cloud.githubusercontent.com/assets/1106823/15272960/bb074b28-1a81-11e6-82ad-bdac53c21ef6.png)

Is there any reason why the properties are prefixed with `d3p1:`?

Shouldn't that be stripped out?

Also all the property values for the `ServiceDescription` and nested objects are string. I would expect the boolean and numeric values to be converted accordingly.

Thanks.

**Comment by amarzavery** [comment]
That is weird. This looks like a servicebus question. The service bus node sdk client library has not been updated since a long time. @djrosanova Can you take a look at this issue?

**Comment by jtaubensee** [comment]
@amarzavery - I'm not aware of anything on the Service Bus service side that would cause this. Do you know if there are any other services in this sdk that have seen this?

**Comment by amarzavery** [comment]
I haven't seen any service in Azure returning that. Since the customer is using Service bus package, I assumed it had something to do with SB.

In any case, @NoelAbrahams can you please share your script?

**Comment by NoelAbrahams** [comment]
@amarzavery, thanks for the prompt response - after all it has only been less than a year.

I have now completely lost track of what I was doing when this happened. So I'm afraid I'm not able to provide further information at this point.

**Comment by cjthompson** [comment]
I found out that the `CountDetails` objects in the XML responses from the server include an `xmlns`.  The `d3p1:` part is the XML namespace.  I'm not certain of the purpose.
