### ISSUE TITLE
Azure service bus Node client permits setting of invalid `LockDuration` value.

### ISSUE THREAD

**Issue by NoelAbrahams** [Azure/azure-sdk-for-node#1747]
Hi,

**Azure NPM version**: 0.10.6

According to the Azure portal, the minimum value for the `LockDuration` property for a subscription is 5 seconds. But the service bus node npm permits creating a subscription with a 1 second value:

``` ts
const options = {
             LockDuration: 'PT1S',
             AutoDeleteOnIdle: 'PT5M'
 };

serviceBus.createSubscription(topic, subscription, options, (error, result, related) => {
    });
```

After the subscription is created all calls to `receiveSubscriptionMessage` fail with "No messages to receive" in spite of there being messages in the topic.

Attempting to set a zero `LockDuration` correctly fails to create the subscription and returns an error.

I believe this should be fixed on the server-side.

**Comment by eduardkoller** [comment]
@djrosanova - can you please investigate?

**Comment by mozehgir** [comment]
Please try the new SDK by installing @azure/service-bus from npm. If the error persists feel free to re-open this issue in the https://github.com/Azure/azure-sdk-for-js repository .

**Comment by NoelAbrahams** [comment]
Really impressed by the prompt attention.
