### ISSUE TITLE
'listsecrets' available in Microsoft.Web?

### ISSUE THREAD

**Issue by arafato** [Azure/azure-sdk-for-node#1748]
Hello--, 

I've looked through the APIs but wasn't able to find the function 'listsecrets' in the library (only KeyVault related which is not what I need). Please see below link for details:
https://github.com/projectkudu/kudu/wiki/Functions-API#getting-a-functions-secrets

Is that function already supported? If not is there a good document that explains how to properly craft an according POST request? Thanks!

Best regards
--Oliver.

**Comment by amarzavery** [comment]
I am not sure if that operation is available. 
@naveedaz @davidebbo - Can you please confirm?

**Comment by davidebbo** [comment]
It's available in the ARM API, but not in the node sdk, so you'll have to call it via raw REST request. Here is an example of what that looks like in C#: https://github.com/davidebbo/AzureWebsitesSamples/blob/master/HttpClientSample/Program.cs. Others may have Node samples to share.

**Comment by amarzavery** [comment]
@davidebbo 
These operations 
- post /subscriptions/{sub}/resourceGroups/{rg}/providers/Microsoft.Web/functions/MyFunction/listsecrets?api-version=2015-08-01

- post /subscriptions/{sub}/resourceGroups/{rg}/providers/Microsoft.Web/sites/{functionapp}/functions/MyFunction/listsecrets?api-version=2015-08-01

are not defined in the [websites swagger spec] (https://github.com/Azure/azure-rest-api-specs/blob/master/arm-web/2015-08-01/swagger/service.json).

If they are defined over there, then this functionality will be a part of C#, node, python, ruby and go sdk.

Can this be added there by the websites team?

Adding Navy to the conversation as well. @naveedaz.

**Comment by davidebbo** [comment]
I know they're not, and the swagger is missing a number of other things. Hence the suggestion to target ARM directly.

But yes, we should add this.

**Comment by eduardkoller** [comment]
@devigned - what's your take on this? (adding these to the swagger spec, versus  calling directly)

**Comment by arafato** [comment]
Thanks for your help! Really appreciate it!
For those using Node here's a working sample:
```
const rp = require('request-promise');

function acquireAccessTokenBySPN(tenantId, clientId, pwd) {
    let payload = `resource=https://management.core.windows.net/&client_id=${clientId}&grant_type=client_credentials&client_secret=${pwd}`;
    let adress = `https://login.windows.net/${tenantId}/oauth2/token`;
    
    let options = {
        method: 'POST',
        uri: adress,
        body: payload,
        headers: { "Content-Type": "application/x-www-form-urlencoded" },
        json: true 
    };
    
    return rp(options)
        .then(function (parsedBody) {
            return parsedBody.access_token;
        });
}

function getFunctionSecret(sub, rg, functionapp, funcname, token) {
    let adress = `https://management.azure.com/subscriptions/${sub}/resourceGroups/${rg}/providers/Microsoft.Web/sites/${functionapp}/functions/${funcname}/listsecrets?api-version=2015-08-01`;
    let options = {
        method: 'POST',
        uri: adress,
        headers: { "Content-Type": "application/x-www-form-urlencoded", "Authorization": "Bearer " + token },
        json: true
    };
    
    return rp(options)
        .then((data) => {
            // data.key, data.trigger_url
           return data;   
        });
}
```

**Comment by davidebbo** [comment]
Thanks for sharing your sample, which can be useful to others!

The goal is still to get things in the library, but sometimes it takes a little bit of time.

**Comment by devigned** [comment]
I'd imagine these features would be useful for developers in other languages, so I'd recommend giving priority to adding them to a new API version of: https://github.com/Azure/azure-rest-api-specs/blob/master/arm-web/2015-08-01/swagger/service.json.

@davidebbo I thought your team was auto generating the swagger spec. Is this not the case any longer?

**Comment by davidebbo** [comment]
@devigned yes, but some APIs are not part of it. This is something we need to solve.

**Comment by eduardkoller** [comment]
@davidebbo - do you have a timeline for addressing this?

**Comment by davidebbo** [comment]
Need to chat with @suwatch about best way to achieve this.

**Comment by eduardkoller** [comment]
@davidebbo ,@suwatch - do you have a plan/timeline for this?
