### ISSUE TITLE
API reference for azure-storage

### ISSUE THREAD

**Issue by danderson00** [Azure/azure-sdk-for-node#1751]
There is no API reference documentation for any of the storage service (and likely other services), at least it is not easily discovered. http://dl.windowsazure.com/nodedocs/ (this does not cover anything other than creating containers and individual blobs, not the rest of the API) is not an API reference document, nor is https://azure.microsoft.com/en-us/documentation/articles/storage-nodejs-how-to-use-blob-storage/.

**Comment by amarzavery** [comment]
@danderson00 - The storage data plane has a repo of its own. https://github.com/Azure/azure-storage-node. When you view the repo in browser at the top you will see this link http://azure.github.io/azure-storage-node/ that points to the client API ref docs.

**Comment by amarzavery** [comment]
This is the client API ref doc link for the node sdk http://azure.github.io/azure-sdk-for-node/. It is visible at the top of the repo when you open the repo in the browser.

**Comment by danderson00** [comment]
It is not clear from that page where the API reference is located. I can find http://azure.github.io/azure-sdk-for-node/azure-storage-legacy/latest/, but this seems to refer to "classic" storage. Is it up to date for the latest azure-storage module? If not, where can one find up to date API reference for current azure-storage?

**Comment by danderson00** [comment]
The second link you provided, http://azure.github.io/azure-sdk-for-node/ provides samples for a very small subset of the API, does not describe parameters, etc. It's not even close to an API reference.

**Comment by eduardkoller** [comment]
@emgerner-msft - do we have a better ref documentation for storage data plane?

**Comment by emgerner-msft** [comment]
Storage data plane is http://azure.github.io/azure-storage-node/ as already stated. This is the most current for the data plane which does not have a concept of classic vs new accounts.

**Comment by danderson00** [comment]
This is not an API reference - it is more like a simple guide. It only documents a small subset of the API surface. 

Is http://azure.github.io/azure-sdk-for-node/azure-storage-legacy/latest/ valid and current for azure-storage? If so, can we make it more visible, like add a link from http://azure.github.io/azure-storage-node/?

**Comment by emgerner-msft** [comment]
http://azure.github.io/azure-sdk-for-node/azure-storage-legacy/latest/ is not at all current -- hence legacy. It's for a very old and outdated version of the library and exists so folks that have not upgraded yet can still look at the docs as this older version is very different than the new one.

If you look at the top of http://azure.github.io/azure-storage-node/ you'll see tabs for 'Namespaces', 'Classes' and 'Global'. If you click on these you'll get stuff like http://azure.github.io/azure-storage-node/BlobService.html which is my understanding of what you're looking for. This covers every API in the library. We can discuss with azure-sdk-for-node folks to unify on format (it looks like each of us used different theming defaults), but I do believe both them and us have relatively full reference documentation if not necessary organized the same way.

If this is not what you're looking for, could you clarify?

**Comment by danderson00** [comment]
This is indeed what I was looking for. It's rather well hidden! I strongly suggest we make it more visible.

Many thanks for the pointer.

**Comment by emgerner-msft** [comment]
Great! I'll close this thread then as it looks like we've solved the immediate problem. For the long term, we'll discuss how we can unify on theme and come up with something much clearer. I agree completely that what we have now for storage is not very visible and should be changed. :)
