### ISSUE TITLE
Service bus message `customProperties` format on the wire should be stringified JSON

### ISSUE THREAD

**Issue by NoelAbrahams** [Azure/azure-sdk-for-node#1754]
Hi,

**Azure NPM version**: 0.10.6

I enqueued the following message on a topic:

``` ts
const message = {
   body: 'foo',
   customProperties: {
   bool: true,
   num: 10,
   // undef: undefined, // failed
   // null: null, // failed
   str: 'string',
   date: new Date(),
   arr: [1, 'two', true, new Date(), undefined, null]
  }
};
```

When this message is received via a subscription it is converted into the following

``` json
{
 "body":"foo",
 "customProperties": { 
    "bool":true,
    "num":10,
    "str":"string",
    "arr":"1,two,true,Wed May 18 2016 10:53:42 GMT+0100 (GMT Summer Time),,"
}
```

A few observations
- The date value sent in the original payload is missing in the dequeued message.
- The array is converted into a string and cannot be parsed meaningfully.
- I also tried setting properties to `null` or `undefined` in the original payload but that failed with a null reference exception (in [servicebusService.js](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/serviceBus/lib/servicebusservice.js#L90))

**Expected behaviour**

I would simply expect `JSON.stringify/parse` to be used here:

``` ts
case 'customProperties': 
 value = JSON.stringify(message.customProperties);

// etc
```

**Comment by eduardkoller** [comment]
@djrosanova - can you please take a look?

**Comment by thdeltei** [comment]
also, when passing data as stringified JSON in the custom properties, for example a stringified array:
```js
{
 "body":"foo",
 "customProperties": { 
    "payload": JSON.stringify([processingString]),
}
```
I get back in the python sdk
```python
print(message.custom_properties['payload'])
>'"["data"]"'
```
i.e an extra double quote around the stringified array, which I have to strip out before I can JSON parse it.

**Comment by camous** [comment]
facing same issue with azure-sb 0.10.5 when my nodejs job tries to copy DateTime `customProperties` from an incoming message to an outgoing one.
customProperties is then converted to string
![image](https://user-images.githubusercontent.com/8566299/34213466-9d6b8468-e59f-11e7-8358-a8a0bc8791a9.png)

 and can't be used in subscription SqlFilter
![image](https://user-images.githubusercontent.com/8566299/34213482-a8c0b5cc-e59f-11e7-8e1b-a77d1d7a5032.png)

any suggestion ?

**Comment by camous** [comment]
setRequestHeaders function in setRequestHeaders(webResource, message) (servicebusservice.js) is actually doing a check on date and convert it this string representation (to be supported by HTTP header). I have to investigate more to pin point where it fails :)

```
            var value = message.customProperties[customProperty];
            if (azureutil.objectIsString(value)) {
              value = '\"' + value.toString() + '\"';
            } else if (azureutil.stringIsDate(value)) {
              value = '\"' + RFC1123.format(value) + '\"';
            } else {
              value = value.toString();
            }

            webResource.withHeader(customProperty, value);
```

using service bus explorer for creating a new msg with DateTime customProperties, I'm getting different result in DateTime representation and data type kept
![image](https://user-images.githubusercontent.com/8566299/34214303-5e54cb24-e5a2-11e7-8f20-74f79c092509.png)

**Comment by camous** [comment]
beware, you are stringify the whole message object rather only the body.

```
const messageToTopic = {
     body: JSON.stringify(request.body),
     customProperties: {
        prop1: 'value1',
        prop2: 'value2'
     }
};
...
serviceBusServiceClient.sendTopicMessage(topicName, messageToTopic, function(error) {}
```

**Comment by amarzavery** [comment]
Please try out the new servicebus sdk `npm i @azure/service-bus`. 

The sample to send a message to a topic can be found [here](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/servicebus/service-bus/samples/typescript/advancedFeatures/topicFilters.ts#L69).

Source code for the new servicebus sdk can be found [here](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/servicebus/service-bus).

In future please open service bus related issues in the new repo https://github.com/Azure/azure-sdk-for-js
