### ISSUE TITLE
List deployments in WebApp

### ISSUE THREAD

**Issue by arafato** [Azure/azure-sdk-for-node#1762]
Hi--, 

is there an API available for listing all deployments in a WebApp? Also to re-deploy a specific deployment? Thanks!

Best regards
--Oliver.

**Comment by amarzavery** [comment]
[All the operations listed here](https://github.com/Azure/azure-sdk-for-node/tree/master/lib/services/webSiteManagement2/lib/operations)
[All the site related operations over here](https://raw.githubusercontent.com/Azure/azure-sdk-for-node/master/lib/services/webSiteManagement2/lib/operations/sites.js)

Some useful operations for you.

Sites.prototype.getDeployments
Sites.prototype.getDeploymentsSlot
Sites.prototype.getInstanceDeployments
Sites.prototype.getInstanceDeploymentsSlot

**Comment by amarzavery** [comment]
The API docs http://azure.github.io/azure-sdk-for-node/azure-arm-website/latest/ can be helpful as well.

**Comment by eduardkoller** [comment]
@arafato - does this answer your question? Do you need more info?

**Comment by arafato** [comment]
@eduardkoller @amarzavery thanks a lot for the information! All good, you can close this issue.
