### ISSUE TITLE
azure-arm-website: createDeployment

### ISSUE THREAD

**Issue by arafato** [Azure/azure-sdk-for-node#1767]
Hi--, 

according to [http://azure.github.io/azure-sdk-for-node/azure-arm-website/latest/Sites.html#createDeployment](http://azure.github.io/azure-sdk-for-node/azure-arm-website/latest/Sites.html#createDeployment), the `location` property of parameter `deployment` is optional. If you do not specify the location, however, the call results in an error saying that you need to specify the location. Is this a bug (why do you need to specify the location if you specified the resource group?) or is the documentation not in sync? Thanks!

Best regards
--Oliver.

**Comment by eduardkoller** [comment]
Looks like documentation is not in sync. @haocs can you take a look

**Comment by haocs** [comment]
@arafato , Location is a required parameter for createDeployment. The documentation was not in sync and it caused by a bug in our node documentation generator. Doc will be updated once the fix gets merged.
