### ISSUE TITLE
Restructure file and folders for all modules or use package file to move away dependencies

### ISSUE THREAD

**Issue by RaviVadera** [Azure/azure-sdk-for-node#1769]
When installing azure SDK on a Windows machine, moving and deleting packages from explorer becomes cumbersome as the file path are too longer. Is there a solution to that?

**Comment by amarzavery** [comment]
@RaviVadera - couple of questions and suggestions

- Are you using the latest version of npm? and 4.x version of node.js? Newer versions of npm automatically flatten dependencies
   - If that does not happen for some reason, then you can execute [`npm dedupe`](https://docs.npmjs.com/cli/dedupe) to flatten dependencies

- Why do you need to install the all up azure module? If you can give more information then I can help you in a better way.

**Comment by RaviVadera** [comment]
Yes I am using latest version of npm.
Haven't tried `npm dedupe`, will give it a shot.
I had installed azure-storage module but the path to my root directory is adding up 100 characters and the explorer is hitting path limit. For example, I was deleting test directories from explorer when I hit the long path error. The path was something like, 

> E:\Team Projects\GIT Versioning\Some Project Name 2\Backend\Node WebAPI Services with Mongo\node_modules\azure-storage\node_modules\request\node_modules\form-data\node_modules\combined-stream\node_modules\delayed-stream\test\integration\test-delayed-stream-auto-pause

As you would know, had to rename folders to remove these files, which is messy.

I think this type of cleanup should be done before publishing to npm. Let me know if there are other options by which, we can avoid these problems.

**Comment by eduardkoller** [comment]
Please let us know ip npm dedupe helps.
Closing this for now, feel free to reactivate if you think there is anything that needs to be fixed in the CLI.

**Comment by eduardkoller** [comment]
Please let us know ip npm dedupe helps.
Closing this for now, feel free to reactivate if you think there is anything that needs to be fixed in the SDK.
