### ISSUE TITLE
Getting/Setting/Updating deployment credentials

### ISSUE THREAD

**Issue by arafato** [Azure/azure-sdk-for-node#1773]
Hi--, 

is there an API available for getting/setting/updating the deployment credentials (Git username / password) of a subscription? I couldn't find anything in the API docs. Thanks!

Best regards
--Oliver.

**Comment by amarzavery** [comment]
Are you talking about WebApp deployment or ARM template deployment?

**Comment by arafato** [comment]
@amarzavery I'm talking about the deployment credentials for WebApp deployment as described here [https://azure.microsoft.com/en-us/documentation/articles/app-service-deploy-local-git/](https://azure.microsoft.com/en-us/documentation/articles/app-service-deploy-local-git/
)

**Comment by amarzavery** [comment]
[this is the operation](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/webSiteManagement2/lib/operations/global.js#L214) that looks close to that; corresponding doc [link](http://azure.github.io/azure-sdk-for-node/azure-arm-website/latest/Global_.html#updateSubscriptionPublishingCredentials).

[this one for getting the creds](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/webSiteManagement2/lib/operations/global.js#L53); corresponding doc [link](http://azure.github.io/azure-sdk-for-node/azure-arm-website/latest/Global_.html#getSubscriptionPublishingCredentials)

**Comment by eduardkoller** [comment]
@arafato - do you need an more assistance on this?

**Comment by arafato** [comment]
nope, can be closed! Thanks a lot!
