### ISSUE TITLE
Use of insecure dependencies

### ISSUE THREAD

**Issue by Alex-Wauters** [Azure/azure-sdk-for-node#1775]
The azure library uses 7 dependencies for which vulnerability advisories have been published (and for which patches are available)

https://nodesecurity.io/advisories/

output from nsp:

    (+) 7 vulnerabilities found
┌───────────────┬─────────────────────────────────────────────────────────────────┐
│               │ Regular Expression Denial of Service                            │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Name          │ hawk                                                            │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Installed     │ 1.1.1                                                           │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Vulnerable    │ < 3.1.3  || >= 4.0.0 <4.1.1                                     │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Patched       │ >=3.1.3 < 4.0.0 || >=4.1.1                                      │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Path          │ lemur@1.0.0 > azure@0.10.6 > request@2.45.0 > hawk@1.1.1        │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ More Info     │ https://nodesecurity.io/advisories/77                           │
└───────────────┴─────────────────────────────────────────────────────────────────┘
┌───────────────┬─────────────────────────────────────────────────────────────────┐
│               │ Insecure Entropy Source - Math.random()                         │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Name          │ node-uuid                                                       │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Installed     │ 1.2.0                                                           │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Vulnerable    │ <1.4.4                                                          │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Patched       │ >=1.4.4                                                         │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Path          │ lemur@1.0.0 > azure@0.10.6 > node-uuid@1.2.0                    │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ More Info     │ https://nodesecurity.io/advisories/93                           │
└───────────────┴─────────────────────────────────────────────────────────────────┘
┌───────────────┬─────────────────────────────────────────────────────────────────┐
│               │ Regular Expression Denial of Service                            │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Name          │ validator                                                       │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Installed     │ 3.1.0                                                           │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Vulnerable    │ <3.22.1                                                         │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Patched       │ >=3.22.1                                                        │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Path          │ lemur@1.0.0 > azure@0.10.6 > azure-common@0.9.12 > validator@3… │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ More Info     │ https://nodesecurity.io/advisories/42                           │
└───────────────┴─────────────────────────────────────────────────────────────────┘
┌───────────────┬─────────────────────────────────────────────────────────────────┐
│               │ Denial-of-Service Extended Event Loop Blocking                  │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Name          │ qs                                                              │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Installed     │ 0.6.6                                                           │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Vulnerable    │ <1.0.0                                                          │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Patched       │ >= 1.x                                                          │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Path          │ lemur@1.0.0 > azure@0.10.6 > azure-storage@0.3.3 > request@2.2… │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ More Info     │ https://nodesecurity.io/advisories/28                           │
└───────────────┴─────────────────────────────────────────────────────────────────┘
┌───────────────┬─────────────────────────────────────────────────────────────────┐
│               │ Denial-of-Service Memory Exhaustion                             │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Name          │ qs                                                              │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Installed     │ 0.6.6                                                           │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Vulnerable    │ <1.0.0                                                          │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Patched       │ >= 1.x                                                          │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Path          │ lemur@1.0.0 > azure@0.10.6 > azure-storage@0.3.3 > request@2.2… │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ More Info     │ https://nodesecurity.io/advisories/29                           │
└───────────────┴─────────────────────────────────────────────────────────────────┘
┌───────────────┬─────────────────────────────────────────────────────────────────┐
│               │ Regular Expression Denial of Service                            │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Name          │ hawk                                                            │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Installed     │ 1.0.0                                                           │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Vulnerable    │ < 3.1.3  || >= 4.0.0 <4.1.1                                     │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Patched       │ >=3.1.3 < 4.0.0 || >=4.1.1                                      │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Path          │ lemur@1.0.0 > azure@0.10.6 > azure-storage@0.3.3 > request@2.2… │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ More Info     │ https://nodesecurity.io/advisories/77                           │
└───────────────┴─────────────────────────────────────────────────────────────────┘
┌───────────────┬─────────────────────────────────────────────────────────────────┐
│               │ Regular Expression Denial of Service                            │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Name          │ moment                                                          │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Installed     │ 2.6.0                                                           │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Vulnerable    │ <2.11.2                                                         │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Patched       │ >=2.11.2                                                        │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Path          │ lemur@1.0.0 > azure@0.10.6 > azure-scheduler@0.10.0 > moment@2… │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ More Info     │ https://nodesecurity.io/advisories/55                           │
└───────────────┴─────────────────────────────────────────────────────────────────┘

**Comment by quentez** [comment]
Of all the packages that we use in production (~200 of them), Azure is the only one with very outdated dependencies and known vulnerabilities that have been there for months.

**Comment by amarzavery** [comment]
We shall fix this in the upcoming release. thanks for notifying.

**Comment by quentez** [comment]
I'm happy to hear that. Apart from this one this, using the SDK has been smooth sailing for us and I'd readily recommend it.

**Comment by amarzavery** [comment]
@quentez @Alex-Wauters - Please install 1.1.1-preview version of azure and nsp check should tell you that there are no vulnerabilities.
Do let me know if you find any issues.

**Comment by quentez** [comment]
Awesome! Thank you for the quick update.
