### ISSUE TITLE
Authentication_MissingOrMalformed error using graph API example

### ISSUE THREAD

**Issue by jamesabbottsmith** [Azure/azure-sdk-for-node#1782]
Hi, 

I'm trying to authenticate a user (with username + password) from a CLI and return the user object from the graph API. I keep getting Authentication_MissingOrMalformed errors. 

To simplify the situation, I've tried using the example on https://github.com/Azure/azure-sdk-for-node/tree/master/lib/services/graphManagement, using interactive login, but got the same result. 

Is there any additional setup I need to do in Azure AD? 

I'm also a little confused about the differences between a subscription-id and tenant-id. I used what I believe is the tenant-id from the Azure AD URL.
https://manage.windowsazure.com/example.com#Workspaces/ActiveDirectoryExtension/Directory/<<THIS BIT>>/users

(PS. The example contains a minor typo: msrestAzure in the first line should be msRestAzure).

Output below...
`
Attila:aad-openid-testing jwa$ node test.js 
To sign in, use a web browser to open the page https://aka.ms/devicelogin. Enter the code yyyyyy to authenticate.
{ [Error: {"odata.error":{"code":"Authentication_MissingOrMalformed","message":{"lang":"en","value":"Access Token missing or malformed."},"values":null}}]
  statusCode: 401,
  request: 
   { rawResponse: false,
     queryString: {},
     method: 'POST',
     headers: 
      { 'x-ms-client-request-id': 'xxxxx-xxxx-xxxx-xxxx-xxxxxxxx',
        'accept-language': 'en-US',
        'Content-Type': 'application/json; charset=utf-8' },
     url: 'https://graph.windows.net/xxxxxxx-xxxx-xxxx-xxxxx-xxxxxx/users?api-version=1.6',
     body: '{"accountEnabled":true,"displayName":"Jon Snow","passwordProfile":{"password":"WinterisComing!","forceChangePasswordNextLogin":false},"userPrincipalName":"OfficialStark@GOT.com","mailNickname":"OfficialStark"}' },
  response: 
   { body: '{"odata.error":{"code":"Authentication_MissingOrMalformed","message":{"lang":"en","value":"Access Token missing or malformed."},"values":null}}',
     headers: 
      { 'cache-control': 'private',
        'content-type': 'application/json;odata=minimalmetadata;charset=utf-8',
        server: 'Microsoft-IIS/8.5',
        'ocp-aad-diagnostics-server-name': 'ExxxxxxxxY=',
        'request-id': 'zzzzzz-zzzz-zzzzz-zzzzzz-zzzzzzz',
        'client-request-id': 'xxxxx-xxxxx-xxxx-xxxx-xxxxxxxx',
        'x-ms-dirapi-data-contract-version': '1.6',
        'x-ms-gateway-rewrite': 'false',
        'strict-transport-security': 'max-age=31536000; includeSubDomains',
        'access-control-allow-origin': '*',
        'x-aspnet-version': '4.0.30319',
        'x-powered-by': 'ASP.NET, ASP.NET',
        duration: '2219246',
        date: 'Thu, 23 Jun 2016 00:22:20 GMT',
        connection: 'close',
        'content-length': '143' },
     statusCode: 401 },
  body: {} }
`

**Comment by arafato** [comment]
I'm getting the same error. Please, any hints on this? Thanks!
Here's my sample code
```
var msRestAzure = require('ms-rest-azure');
var graphRbacManagementClient = require('azure-graph');

msRestAzure.interactiveLogin(function (err, credentials) {
    var client = new graphRbacManagementClient(credentials, <tenantId>);
    client.applicationOperations.list(function(err, result) {
        if (err) { 
            console.log(err);
        } else {
            console.log(result);
        }
    })
});
```

**Comment by amarzavery** [comment]
@jamesabbottsmith @arafato - Thanks for reporting this issue. The root cause of the issue is the token audience. Active Directory Graph service is tenant based and has a different token audience (5% scenario). All other Azure services are subscription based and have the standard token audience (95% scenario). The token that is acquired will work for other Azure Services like webapps, compute, ResourceManager, etc. but not for Graph. Hence you get the above message. 

I am working on providing a mechanism to specify the tokenAudience or somehow indicate that the user intends to acquire the credentials for talking to the graph service, so that correct tokens are acquired. Thereafter the flow should be seamless.

**Comment by arafato** [comment]
Thanks @amarzavery - is there a time frame you can give?

**Comment by amarzavery** [comment]
@jamesabbottsmith @arafato - The updated [Readme.md](https://github.com/Azure/azure-sdk-for-node/tree/master/lib/services/graphManagement) should provide you info about the auth mechanism for tenant based graph client.
Please delete the node_modules folder, make sure you have "azure-graph":"1.0.1" in the package.json of your script. This will install the new version of `"ms-rest-azure": "1.14.5"`  and `"ms-rest": "1.14.4"` that have the latest updates.
Let me know if you have any issues.

**Comment by jamesabbottsmith** [comment]
Thanks @arafato - this works now :)

I've copied the code from the interactive login example on the Readme, and added my tenantId as appropriate. I no longer get the `Authentication_MissingOrMalformed` error.

A couple of minor documentation improvements you could make (particularly helpful for a good first run experience)
1. Its still helpful to extract out something like
`var tenantId='abcd-efgh-ijk-lmno-12345'
// Enter your tenant ID here which can be found from your Azure AD URL
//   Eg. https://manage.windowsazure.com/example.com#Workspaces/ActiveDirectoryExtension/Directory/<TenantId>/users`

2. Also, the first time I ran the example I got another error `Request_BadRequest - Property userPrincipalName is invalid.`. This was because I was adding a user at contosocorp, rather than my own domain. Again, some documentation around this would be helpful for first time users.

Thanks :)

**Comment by amarzavery** [comment]
@jamesabbottsmith - I have updated the doc as per your suggestion https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/graphManagement/README.md. Thanks 👍

**Comment by arafato** [comment]
Thanks a lot @amarzavery @jamesabbottsmith !
