### ISSUE TITLE
Installation API

### ISSUE THREAD

**Issue by ztrange** [Azure/azure-sdk-for-node#1783]
Is the installation API supported? If not, will it be supported? is there an ETA?

Im talking about the installation API mentioned here:
https://azure.microsoft.com/en-us/pricing/details/notification-hubs/

**Comment by amarzavery** [comment]
@ztrange - Are you talking about the billing API?

**Comment by ztrange** [comment]
@amarzavery not at all, I'm talking about the new wat of registration management for azure notification hubs, that is using installations instead of registrations

https://azure.microsoft.com/en-us/documentation/articles/notification-hubs-push-notification-registration-management/

**Comment by amarzavery** [comment]
@smithab - Can you take a look at this request? Is this a dataplane or a management plane API? What are the plans to provide an sdk for this?

**Comment by ztrange** [comment]
I think I just found out that it already is implemented on the sdk. At least that is what the SDK documentation implies:

http://azure.github.io/azure-sdk-for-node/azure-sb/latest/NotificationHubService.html#createOrUpdateInstallation

Only, it is not documented anywhere how to use those methods. I think I can figure it out.

**Comment by eduardkoller** [comment]
@ztrange - do you need any further assistance on this?
