### ISSUE TITLE
RoleEnvironment events do not seem to work at all

### ISSUE THREAD

**Issue by drcmda** [Azure/azure-sdk-for-node#1789]
``` js
azure.RoleEnvironment.isAvailable((error, available) => {
    if (available) {
        azure.RoleEnvironment.getCurrentRoleInstance((error, instance) => {
            if (!error && instance['endpoints']) {
                let ip = instance['endpoints']['PublicEndpoint']['address'];
                let publicport = instance['endpoints']['PublicEndpoint']['port'];
                let privateport = instance['endpoints']['InternalEndpoint']['port'];

                // ???
                azure.RoleEnvironment.on('changed', () => myfunction(ip, privateport));
```

I have tried to listen to them all (started, stopped, changing, etc.), nothing. Things even get weird if they're placed elsewhere, it causes the role to be started twice.

I haven't found any examples or public ducuments regarding this and really wish the npm markdown or official docs would be a bit more descriptive.

**Comment by eduardkoller** [comment]
Thank you for bringing this up, we'll investigate.
Btw, can you share some details about your scenario? What are you trying to build?

**Comment by drcmda** [comment]
@eduardkoller 

We deploy two worker roles based on Node. One with a public endpoint that users connect to. Another is internal and gets scaled up and down by Azure. Whenever the role environment changes (number of instances, etc.), the public role needs to browse the role environment and contact the other roles instances to make certain requests. Also, Start, Stop, Starting, Stopping, Changed, Changing would be good to have. In Asp.Net this came right out of the box. But in Node nothing ever seems to fire for anything.

It is also not clear where the event-listeners need to be placed as they curiously do not seem to belong to the role as in Asp.Net, they seem to belong to azure.roleEnvironment. Moving them up and down causes the weirdest issues in the Azure emulator and perhaps also online, though i haven't dared push it when it already looked wrong in the emulator.

**Comment by amarzavery** [comment]
This stuff is too old and is not supported in Azure anymore
