### ISSUE TITLE
Get public ip address from vm info returned by virtualMachines.listAll.

### ISSUE THREAD

**Issue by henryzhang888888** [Azure/azure-sdk-for-node#1791]
I am trying to get public ip address and resource group information with the vm information returned by 
 virtualMachines.listAll()
But didn't figure an good way. The only way is that I list all the resource group and public ip address information and compare the id by myself.

**Comment by eduardkoller** [comment]
@huangpf @hyonholee - can you please assist?

**Comment by huangpf** [comment]
It's by design of ARM that the network specific details are in network resources, only reference IDs are shown by VMs. So, you would have to do cross queries, but a more efficient way is to directly query Network's list function, other than traversing all groups and their sub resources.
