### ISSUE TITLE
Info - Service Bus SDK 

### ISSUE THREAD

**Issue by OlivierAlbertini** [Azure/azure-sdk-for-node#1799]
Hi,

In .NET, you have SendBatchAsync method but I don't see it in node.js ... Is there a reason ? Or I mssed something ?

**Comment by amarzavery** [comment]
The servicebus team has stopped maintaining their node.js libraries as they are developing a new one for the data plane.
@sazeesha @djrosanova from the servicebus team can provide you more info on this.

**Comment by molant** [comment]
@amarzavery @sazeesha @djrosanova any news about this? Is there an ETA for the new library? We are migrating from queues to service bus and it will be great to know if we should wait or not.

Thanks!

**Comment by sazeesha** [comment]
@molant We are working on our swagger doc that is used to generate the clients. So far we have tested the SDK client. You can use AutoRest with the swagger spec [here ](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-servicebus/2015-08-01/swagger/servicebus.json)to generate the Node SDK.

**Comment by amarzavery** [comment]
@molant - The first version of the arm servicebus management plane client [azure-arm-sb](https://github.com/Azure/azure-sdk-for-node/tree/master/lib/services/serviceBusManagement2) and eventhub management plane client [azure-arm-eventhub](https://github.com/Azure/azure-sdk-for-node/tree/master/lib/services/eventHubManagement) is out. Please try it out and provide feedback.
