### ISSUE TITLE
azure-storage version

### ISSUE THREAD

**Issue by kobelb** [Azure/azure-sdk-for-node#1801]
The current version of azure-storage that is a dependency of this project is very old, and has a number of bugs that have been resolved. 

I happened across a specific bug in azure-storage@0.3.3 that sets the http.globalAgent.maxSockets equal to 1, which was having detrimental effects on my application.

Is there a reason why the old version is continued to be relied upon?

**Comment by amarzavery** [comment]
@kobelb - We no longer ship rollup package of the node sdk. Individual service packages are shipped as and when required. Apart from that azure-storage has moved to a [different repo](https://github.com/Azure/azure-storage-node) and also has its own release cadence.

**Comment by kobelb** [comment]
@amarzavery That seems to contradict this statement from the main README.md:

We provide both fine-grained modules for different Microsoft Azure services which you can install separately, and an all-up module which contains everything.

**Comment by kobelb** [comment]
I apologize if my previous comment was rather terse, and it was made out of frustration.

**Comment by amarzavery** [comment]
We are sorry for leading you in the wrong direction. The statement in README.md is by and large true for most of the individual services. azure-storage code base was a part of this repo initially. The storage team decided to manage this in a separate repo. The storage package remained as a part of the package.json for backwards compatibility. 

We shall remove this from the rollup package.json moving forward.

**Comment by kobelb** [comment]
Thanks @amarzavery, I appreciate everything that you're doing to make node on azure a first-class experience. I'll go ahead and close this issue. Thank you for your prompt response.
