### ISSUE TITLE
Upgrade version of request npm package to address security vulnerability in tough-cookie package

### ISSUE THREAD

**Issue by danderson00** [Azure/azure-sdk-for-node#1832]
A warning is displayed when installing azure-storage that a child dependency, tough-cookie, contains a security vulnerability, as described at https://nodesecurity.io/advisories/130.

**Comment by danderson00** [comment]
https://github.com/Azure/azure-sdk-for-node/blob/master/lib/common/package.json - request dependency needs to be updated to 2.74.1

**Comment by molant** [comment]
@haocs any ETA to fix this?
Thanks!

**Comment by haocs** [comment]
@molant working on it. A new package will be published later.

**Comment by eduardkoller** [comment]
@molant - what is the ETA to have this fix in the SDK?

**Comment by molant** [comment]
@eduardkoller I dont know, I don't work in this team :)
Maybe @haocs knows.

**Comment by eduardkoller** [comment]
The issue is fixed in the last version of the runtime, and will be propagate in the next release of tha all-up release for the Node SDK
