### ISSUE TITLE
KeyVault client: incorrect comments in getSecrets method

### ISSUE THREAD

**Issue by jeffwilcox** [Azure/azure-sdk-for-node#1842]
The documentation in the code for the `maxresults` parameter of the `getSecrets` is incorrect.

It states that the `maxresults` parameter is a limiter on the "total" number of secrets/results, and not a paging indicator, but in fact it is the first page limit parameter.

Here is the line that is incorrect:
https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/keyVault/lib/keyVault.js#L376

And here is the official KeyVault REST endpoint documentation:
https://msdn.microsoft.com/en-us/library/azure/dn903614.aspx

I have validated that the REST documentation is correct.

**Comment by eduardkoller** [comment]
@msfcolombo Can you please investigate

**Comment by eduardkoller** [comment]
@pomortaz - has this fix been included in an SDK release? If so, we can close this issue

**Comment by pomortaz** [comment]
Yes, thanks!
