### ISSUE TITLE
Confused by the comments of accessTier

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-sdk-for-node#1855]
https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/storageManagement2/lib/models/storageAccountCreateParameters.js#L76-L81

It seems that access tier can only be set for StandardLRS, StandardGRS and StandardRAGRS.

From https://azure.microsoft.com/en-us/documentation/articles/storage-introduction/
>If there is a change in the usage pattern of your data, you can also switch between these access tiers at any time.

**Comment by amarzavery** [comment]
@hasonmsft @yaxia - Can you make sure that the documentation is clear and reflects what the API does by updating the [storage swagger spec](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-storage/2016-01-01/swagger/storage.json)

**Comment by hasonmsft** [comment]
@JasonYang-MSFT, could you help take a look at this issue?

**Comment by JasonYang-MSFT** [comment]
Yes, access tier is only available for Blob Storage Accounts, which only supports StandardLRS, StandardGRS and StandardRAGRS. Also the claim about the changing period is incorrect. You can follow https://azure.microsoft.com/en-us/documentation/articles/storage-introduction/. We will fix the comments in the code.

**Comment by eduardkoller** [comment]
@JasonYang-MSFT - what is the timeline for this fix?

**Comment by JasonYang-MSFT** [comment]
@eduardkoller 
This fix will be in our next release, which we are currently working on.
