### ISSUE TITLE
Use of unsecure dependency

### ISSUE THREAD

**Issue by quentez** [Azure/azure-sdk-for-node#1857]
According the Snyk.io, the version of `request` used by the `azure` package has some vulnerabilities.

https://snyk.io/test/npm/azure

`request` should be updated to the latest version.

**Comment by danderson00** [comment]
This is a duplicate of https://github.com/Azure/azure-sdk-for-node/issues/1832

**Comment by quentez** [comment]
Indeed. My bad.
