### ISSUE TITLE
Getting the ILPIP information within node.js application

### ISSUE THREAD

**Issue by Laro88** [Azure/azure-sdk-for-node#1864]
I have a problem getting the ILPIP inside a Node.JS application running on an Ubuntu 16.04LTS server.
All I need is the assigned dns name of the server "xyzserver.westeurope.cloudapp.azure.com"
I need it to dynamically tell some web clients to open sockets to other servers to get some realtime data from IoT devices - and I would like to avoid hardcoding anything :-)

```
var azure = require('azure');
 azure.RoleEnvironment.getCurrentRoleInstance(function (error, instance) {
     if (!error && instance['endpoints']) {
         //You can get information about "endpoint1" such as its address and port via
         console.log(instance)
     } else {
         console.log(error);
     }
 });
```

However I keep getting the following error:

```
{ [Error: connect ENOENT \\.\pipe\WindowsAzureRuntime]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'connect',
  address: '\\\\.\\pipe\\WindowsAzureRuntime',
  fileName: '\\\\.\\pipe\\WindowsAzureRuntime' }
```

Server is ubuntu 16.04 LTS node version is 4.5.0
Any suggestions?

**Comment by Laro88** [comment]
It might be correct to fail as pr. the documentation in which it is stated that the RoleEnvironment requires "Microsoft Azure Cloud Service" - see "azure-sdk-for-node / lib / serviceruntime / roleenvironment.js"
Is there any other way to get a public dns / ILPIP information from within an ubuntu machine running node.js?

**Comment by amarzavery** [comment]
@Laro88 - Is there a reason to use the [old/classic](https://azure.microsoft.com/en-us/documentation/articles/virtual-networks-instance-level-public-ip/) way of doing things(ASM)? 

[V2 version (ARM) of the Azure API](https://azure.microsoft.com/en-us/documentation/articles/virtual-network-ip-addresses-overview-arm/) has it named as PIP (public IP).

I understand that you are trying to get information about a Public IP, is that correct?
Is this Public IP associated to VM or something else?

**Comment by Laro88** [comment]
@amarzavery  - I just need to obtain a DNS label inside Node.JS - the node code just need to know on which server it is running. It is probably trivial with the right api call - but I can't find it.
The entire DNS label exposed in an Azure api with everything would be perfect :-)

![dns label azure](https://cloud.githubusercontent.com/assets/12495700/18376393/04ca9e70-765f-11e6-9fb9-55545a15f652.jpg)

**Comment by eduardkoller** [comment]
@MikhailTryakhov - can you assist with this?
