### ISSUE TITLE
Could not find module 'azure-arm-trafficmanager'

### ISSUE THREAD

**Issue by benjsicam** [Azure/azure-sdk-for-node#1869]
Error

```javascript
Error: Cannot find module 'azure-arm-trafficmanager'
```

Due to package.json:

```
"main": "./lib/trafficManager.js",
```

Should be:

```
"main": "./lib/trafficManagerManagementClient.js",
```

**Comment by amarzavery** [comment]
@benjsicam - thanks for reporting this issue. We have fixed this and have published the new version (0.11.0) of [azure-arm-trafficmanager](https://www.npmjs.com/package/azure-arm-trafficmanager).
Please let us know if you find any further issues.
