### ISSUE TITLE
Requiring unknown module "fs"

### ISSUE THREAD

**Issue by jrmcdona** [Azure/azure-sdk-for-node#1874]
I am trying to get push notifications working using azure notification hub.  I have installed npm azure which installs many dependencies.  

When I run the app I cannot get passed this error.
Requiring unknown module "fs".

It is coming from this file:
node_modules\azure-storage\lib\common\util\utility.js

And this line of code seems to be the issue;
var fs = require('fs');

What do I need to install to get this to work and is will this all work with react-native?

Thanks

**Comment by amarzavery** [comment]
['fs' is a native node.js module](https://nodejs.org/api/fs.html) and should be present if you have node.js installed on your system

**Comment by jrmcdona** [comment]
Thanks amarzavery.  Doesn't react-native run using node.js?  I am running apps in the Android emulator and so far not having any trouble with that.    So I am confused why the issue now.   Thanks

**Comment by amarzavery** [comment]
I am not very well versed with react native, however some basic searching gave me this [SO link](http://stackoverflow.com/questions/39046429/react-native-unable-to-resolve-module-fs) which might be helpful to you.
