### ISSUE TITLE
Create or updating loadbalancers

### ISSUE THREAD

**Issue by brunoriscado** [Azure/azure-sdk-for-node#1880]
Looking at the model for loadbalancers, there's just no way I can get a load balancer to be created passing in an array of rules or probes, ex:

```
var component = process.env["COMPONENT_ID"];
var resourceGroup = process.env["RESOURCE_GROUP"];
var loadBalancerName = process.env["RESOURCE_GROUP"];

var clientId = process.env['CLIENT_ID'];
var tenantId = process.env['TENANT_ID'];
var secret = process.env['APPLICATION_SECRET'];
var subscriptionId = process.env['AZURE_SUBSCRIPTION_ID'];

var testResource = "my-testResource-lb-westeurope-dev";
var testLBName = "myLB";


msRestAzure.loginWithServicePrincipalSecret(clientId, secret, tenantId, function(err, credentials) {
    //if (err) return fs.appendFileSync("deploy.log", "Error in login to azure:" + err);
    //logged in perform load balancer updates
    var networkMngClient = new NetworkManagementClient(credentials, subscriptionId);
    
    // networkMngClient.loadBalancers.list("ess-api-lb-westeurope-dev", function(err, results) {
    //     console.log(JSON.stringify(results));
    // });

    var lb = {
        resourceType:"loadBalancers",
        location: "westeurope", 
        loadBalancingRules: [
            {
                id: "rule1",
                protocol: "TCP",
                frontendPort: 8000,
                backendPort: 9003
            }
        ]
    };

    networkMngClient.loadBalancers.beginCreateOrUpdate(testResource,
            testLBName, 
            lb,
            function(err, result) {
                if (err) {
                    console.log(err);
                }
                return console.log(result);
            });
});
```

I always end up with the following response:

```
{ [Error: Cannot parse the request.]
  statusCode: 400,
  request: 
   { rawResponse: false,
     queryString: {},
     method: 'PUT',
     headers: 
      { 'x-ms-client-request-id': '7faf347a-5230-4f76-a234-b1e244bea9c4',
        'accept-language': 'en-US',
        'Content-Type': 'application/json; charset=utf-8' },
     url: 'https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/my-testResource-lb-westeurope-dev/providers/Microsoft.Network/loadBalancers/myLB?api-version=2016-06-01',
     body: '{"location":"westeurope","properties":{"loadBalancingRules":[{"id":"rule1","properties":{"protocol":"TCP","frontendPort":8000,"backendPort":9003}}]}}' },
  response: 
   { body: '{\r\n  "error": {\r\n    "code": "InvalidRequestFormat",\r\n    "message": "Cannot parse the request.",\r\n    "details": []\r\n  }\r\n}',
     headers: 
      { 'cache-control': 'no-cache',
        pragma: 'no-cache',
        'content-length': '124',
        'content-type': 'application/json; charset=utf-8',
        expires: '-1',
        'x-ms-request-id': '330c6f95-a0c9-4803-ab60-4ed054c96081',
        'strict-transport-security': 'max-age=31536000; includeSubDomains',
        server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
        'x-ms-ratelimit-remaining-subscription-writes': '1199',
        'x-ms-correlation-request-id': '735e95d6-b3e1-4567-8b63-19ce76c7b55e',
        'x-ms-routing-request-id': 'UKWEST:20160914T135922Z:735e95d6-b3e1-4567-8b63-19ce76c7b55e',
        date: 'Wed, 14 Sep 2016 13:59:22 GMT',
        connection: 'close' },
     statusCode: 400 },
  code: 'InvalidRequestFormat',
  body: 
   { code: 'InvalidRequestFormat',
     message: 'Cannot parse the request.',
     details: [] } }
```

Is this an issue one the load balancer service? I can't find any examples for this type of request or tests... I'm following the model for the instance and if I wrap the loadBalancingRules in properties then I am able to create the load balancer but with an empty list of rules.

**Comment by amarzavery** [comment]
@brunoriscado - 
In Azure every thing is a resource which is uniquely identifiable. The id has a structure that needs to be followed. I agree that this is not documented and is simply mentioned that it is of type string hence a customer who is new to Azure V2 (ARM - Azure Resource Manager) API has no idea about it. Parts of the `lb` object that you created as the payload for createOrUpdate is incorrect. 

Please take a look at this [lb sample](https://github.com/Azure-Samples/network-node-manage-loadbalancer). You can clone the sample repo and follow the instructions in README.md to run it. Let me know if you have any further questions.

**Comment by brunoriscado** [comment]
Hi @amarzavery, thank you for the reply, I did the mistake of assuming that by default, since the id is not required in the model class, that it would be generated internally if it was not specified.

Will give the samples you sent me a try. Thanks

**Comment by amarzavery** [comment]
@brunoriscado 
I see. Just fyi,
The network service does not have PATCH operations. So one has to do a GET and then a PUT if one has to update a network resource. There are two ways to create a LB - 
  1. Create an empty LB and then do a get and put every time you want to add/remove something from the LB
  2. Create the entire LB payload by populating the right stuff all at once and the service will create everything all up.

Depending on the situation, one would select the desired approach.

**Comment by brunoriscado** [comment]
@amarzavery - understood, my use case will probably fall under the first option, but for now I was just try a straightforward creation.

Again, thanks for the quick and helpful reply.
