### ISSUE TITLE
Cognitive Services included in SDK

### ISSUE THREAD

**Issue by SharePointing** [Azure/azure-sdk-for-node#1882]
Are there plans to include the Cognitive Services APIs to the node.js SDK ? 

I'm aware of the project oxford packages in NPM but they are incomplete as well as still having a "Project Oxford" moniker which doesn't allude to production level use. 

Currently utilizing direct REST calls today. Would love to see us integrate into this SDK.

**Comment by amarzavery** [comment]
@SharePointing - Are you talking about this [API](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-cognitiveservices/2016-02-01-preview/swagger/cognitiveservices.json) ?

**Comment by SharePointing** [comment]
Well that looks promising! Any eta when it will make it into the SDK itself ? When I install (npm install azure) it's not included (apologies if this is a newbie question)

**Comment by amarzavery** [comment]
The model is such that the rollup module "azure" with all the packages is published less frequently. Most of the client libraries are auto generated. Hence, individual service teams have the capability to push their client library packages whenever they make a change to their rest api spec. We will have it published before the end of this week.

**Comment by SharePointing** [comment]
Got It! The help is much appreciated ! 

Looking forward to being able to replace all my direct REST calls with some SDK goodness. 

I think this closes this issue out. Thanks again !
