### ISSUE TITLE
[ServiceBus] Create topic does not support all options

### ISSUE THREAD

**Issue by princjef** [Azure/azure-sdk-for-node#1893]
I'm am using the Service Bus portion of the SDK to try to create a partitioned topic, among other things. However, [`createTopicIfNotExists()`](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/serviceBus/lib/servicebusservice.js#L754) does not allow either the SupportOrdering or EnablePartitioning options to be set.

From the [REST API docs](https://msdn.microsoft.com/en-us/library/hh780749.aspx), it looks like SupportOrdering should be available, and [this example using the C# SDK](https://azure.microsoft.com/en-us/documentation/articles/service-bus-partitioning/#_enable-partitioning) specifies the EnablePartitioning property, so it seems like that should be available too.

[This section](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/serviceBus/lib/models/topicresult.js#L24) appears to be the culprit, since it filters out any properties that aren't explicitly listed.

**Comment by eduardkoller** [comment]
@sazeesha - Can you take a look at this issue? /c: @djrosanova

**Comment by sazeesha** [comment]
Please refer to the Swagger [here](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-servicebus/2015-08-01/swagger/servicebus.json) and use the SDK from [here](https://github.com/Azure/azure-sdk-for-net/tree/AutoRest/src/ResourceManagement/ServiceBus). This has support for SupportOrdering and EnablePartitioning.
