### ISSUE TITLE
Currently published azure-arm-storage contains unwanted .ntvs_analysis.dat file

### ISSUE THREAD

**Issue by sandorfr** [Azure/azure-sdk-for-node#1906]
The currently published package `0.13.3-preview` (https://registry.npmjs.org/azure-arm-storage/-/azure-arm-storage-0.13.3-preview.tgz) contains an `.ntvs_analysis.dat` files (which I think is created by node.js visual studio tooling). 

This file is around `40 Mo` so this is not a small overhead...

**Comment by amarzavery** [comment]
Oops. We have published `0.13.4-preview` of the `azure-arm-storage` package that should not have the .ntvs file. We have also updated the README to point to a link that provides a clone able and ready to use sample over [here](https://www.npmjs.com/package/azure-arm-storage#a-working-sample).

**Comment by sandorfr** [comment]
That was fast thanks :)
