### ISSUE TITLE
Update Article for Creating Service-Principal over REST using User Credentials

### ISSUE THREAD

**Issue by solvingJ** [Azure/azure-sdk-for-node#1907]
https://github.com/Azure/azure-sdk-for-node/blob/master/Documentation/Authentication.md

This SDK supports creating the service principal with login-based authentication via the REST API. 

Is it possible for someone to provide instructions for this in the document above?   

Really, it would seem beneficial and simple to include such a fundamental tutorial in the Azure SDK projects for each of the major languages.  The portal, xplat-cli, or powershell methods are all less than ideal.

**Comment by amarzavery** [comment]
@solvingJ - Just trying to understand the question.

Are you suggesting that we provide a sample of how to login using user credentials and then create a service principal using the node.js graph management library and then login as that service principal in the same node.js script?

Did you take look at the section below in the same doc link that you mentioned in the issue that provides a sample of how to use authentication in your node.js script: 
 https://github.com/Azure/azure-sdk-for-node/blob/master/Documentation/Authentication.md#using-authentication-in-your-nodejs-script ?

**Comment by solvingJ** [comment]
Yes, but actually I was just referring to the first part of what you said:  adding a fourth equivalent option in the : "Creating a ServicePrincipal for scripting scenarios" section that shows how to do it using the SDK.  

Yes, I was trying to implement option 2 in your example, and I felt it pretty awkward to go to some other system to create the SP, when I know it can be done right in the code I'm working on.   Sure it's probably a one-time thing for most people, but it could be copy/paste/run if there were a sample of this on the documentation.

**Comment by amarzavery** [comment]
I see. You are absolutely correct. We will create a sample script for that. Thanks for the suggestion.

**Comment by amarzavery** [comment]
@solvingJ - Please find the script for creating an SP over [here](https://github.com/Azure/azure-sdk-for-node/tree/master/Documentation/ServicePrincipal). The folder has a package.json that is not published. You can still use it install the dependencies.

Let me know if you find any issues with this script.

Happy coding :)

**Comment by amarzavery** [comment]
updated the doc [link](https://github.com/Azure/azure-sdk-for-node/blob/master/Documentation/Authentication.md#3-via-running-a-simple-nodejs-script) as well.

**Comment by solvingJ** [comment]
This looks really awesome!  I had just reached the point of being able to call applications.list and was going to try to tackle this today.  I will take this for a test drive this morning and report back. Thank you very much for this!

**Comment by solvingJ** [comment]
It looks like there's no way to authenticate with a LiveID that is not interactive, is that correct?  (Trying to create and delete a service principal using a LiveID within a Mocha test).

**Comment by amarzavery** [comment]
Nope. Live ID(Non organizational user id) does not have a non-interactive (silent) way to authenticate.

There is a current limitation with service-principals. It can be used to do CRUD on resources(VM, storage accounts, virtual network, etc.) but it cannot do the same on Active Directory stuff (applications, users, serviceprincipals) because the Graph team does not provide a programmable way to at least provide read access to Graph. 

One has to go to the old portal over [here](https://manage.windowsazure.com)
- from the left menu bar select ActiveDirectory and go inside the Directory you created. 
- Select Applications and find the application.(If the list is big then search by name or Id).
- Once you find the app, click on it and go to the configure section and scroll below.
- You need to set all the permissions in the Windows Active Directory.

![image](https://cloud.githubusercontent.com/assets/4521223/18816864/38033fcc-8307-11e6-9e67-dc6e949e81bf.png)

**Comment by amarzavery** [comment]
I agree that writing tests helps you find out if something is broken. However, servicePrincipal setup is mostly a one time thing. Once done, a customer hardly modifies it, until and unless the app secret expires.

One question: What is the overall scenario you are trying to achieve? May be I can point you to some existing samples or with some other help.

**Comment by solvingJ** [comment]
Thanks for the explanation. 

I'd really like to share our use case with you, because then my past (and future questions) will make much more sense.  However, I'd prefer to send privately.  If you have an email you can share, I will be happy to send.

**Comment by amarzavery** [comment]
Sure. my email address is amzavery@microsoft.com

**Comment by solvingJ** [comment]
Also, I forgot to add, as you know, the service principals expire (we'll be
setting default to 1 year).  So we're going to monitor the expiration date
of the service principal and alert the customer when it gets down to a week
or so.  That way the credential doesn't expire and stop working.  So, we'll
also have a function in our GUI to refresh or recreate the service
principals on demand.

Gerald R. Wiltse
jerrywiltse@gmail.com

**Comment by amarzavery** [comment]
Closing this as the article specifies a link to a script.
