### ISSUE TITLE
[servicebus] method Renewlock() not available in node version

### ISSUE THREAD

**Issue by camous** [Azure/azure-sdk-for-node#1921]
I've looked into lib folder (searching for exact same wording as C# (https://msdn.microsoft.com/library/en-us/JJ673240.aspx) and github issue list without success. 

is it due to a design reason ?
regards,

**Comment by camous** [comment]
I'm a little bit lost. After digging a little bit more, I've found this PR (https://github.com/Azure/azure-sdk-for-node/pull/1336) related to renewlock. does this PR wasn't integrated in master afterward ?

**Comment by eduardkoller** [comment]
@sazeesha - Can you please take a look at this issue? /c @djrosanova

**Comment by sazeesha** [comment]
@jtaubensee @arundsouza

**Comment by jtaubensee** [comment]
@camous - Here is the code in master.
https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/serviceBus/lib/servicebusservice.js#L363

**Comment by camous** [comment]
@jtaubensee mixed up with C# way of getting a method on message itself...
however, does renewLockForMessage supposed to increase the LockUntilUtc value by the queue/topic lock duration time ?

![image](https://cloud.githubusercontent.com/assets/8566299/19593692/1c8e8352-9782-11e6-9bfe-689870b15e38.png)

message.brokerProperties.LockedUntil before & after renewLockForMessage are the same. Or I'm missing a point ?
