### ISSUE TITLE
Node SDK shall convert 'true' or 'false' string values to boolean

### ISSUE THREAD

**Issue by huangpf** [Azure/azure-sdk-for-node#1929]
Please refer to: https://github.com/Azure/azure-xplat-cli/issues/3248

**Comment by amarzavery** [comment]
The sdk will not convert a string to a Boolean. If a string is expected, then it should be a string. 
I will add type validation during deserialization. I was told that clients need not perform extra validation during deserialization as we expect the server to do the right thing. However, if this is not the case then I can very easily add type validation during deserialization as well.

**Comment by huangpf** [comment]
Maybe the service side wants a special type like ```booleanOrTrueFalseString```, but I don't think your current spec supports that. The integer use case is similar and worth more careful consideration before jumping to the conclusion. Yes, PS/.NET may fall apart because of that simple mismatch, and it's also why we suggest you to consider a fix on the spec/client side.

Anyhow, please help review and merge. Thanks.
* https://github.com/Azure/azure-xplat-cli/pull/3250

**Comment by amarzavery** [comment]
closing this issue as the requirement is incorrect.
