### ISSUE TITLE
Docs at http://azure.github.io/azure-sdk-for-node/ are incorrect

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-sdk-for-node#1931]
1. It seems like all of the links to model types are broken and 404 when clicked. For example on [this page](http://azure.github.io/azure-sdk-for-node/azure-batch/latest/ComputeNodeOperations.html#get) in the `Returns` section it links to `ComputeNode`, but the link it uses is [this one](http://azure.github.io/azure-sdk-for-node/azure-batch/latest/ComputeNode.html)
2. `optional` vs `required` is not correctly surfaced. For example, look [here](http://azure.github.io/azure-sdk-for-node/azure-batch/latest/Pool.html#add) -- under the parameter `pool.virtualMachineConfiguration.imageReference` the parameters `publsher`, `offer`, and `sku` are all listed as optional, but if you look at the Swagger specification for our service on `imageReference` you'll see that they are actually all required by the spec (see [here](https://github.com/Azure/azure-rest-api-specs/blob/master/batch/2016-07-01.3.1/swagger/BatchService.json#L11637))

**Comment by matthchr** [comment]
@amarzavery The above are just examples, I think they actually describe classes of problems that are happening all over the documentation

**Comment by amarzavery** [comment]
Closing this since we are moving to new JS repo (https://github.com/azure/azure-sdk-for-js) whichwill have isomorphic JS packages and better API documentation.
