### ISSUE TITLE
Not able to compile under typescript 2.0.3

### ISSUE THREAD

**Issue by shrimpy** [Azure/azure-sdk-for-node#1937]
Encounter below error when try to compile.

npm/typings install uuid or node-uuid didn`t help

what kind of UUID library does azure-storage reference?

```
Using tsc v2.0.3
node_modules/azure-storage/typings/azure-storage/azure-storage.d.ts(5166,32): error TS2304: Cannot find name 'UUID'.
node_modules/azure-storage/typings/azure-storage/azure-storage.d.ts(5166,68): error TS2304: Cannot find name 'UUID'.
node_modules/azure-storage/typings/azure-storage/azure-storage.d.ts(5343,68): error TS2304: Cannot find name 'UUID'.

```

**Comment by amarzavery** [comment]
@yaxia @hasonmsft - Can you take a look at this?
@shrimpy - https://github.com/azure/azure-storage-node is the right repo for this issue.

**Comment by eduardkoller** [comment]
@yaxia @hasonmsft - Can you please assist with this?

**Comment by hasonmsft** [comment]
@shrimpy , thanks for raising this. We are working on this and get it addressed soon. 

BTW, currently the active repo for azure-storage is https://github.com/Azure/azure-storage-node/. Could you create GitHub issue there in the future. :)

**Comment by hasonmsft** [comment]
https://github.com/Azure/azure-storage-node/issues/208
