### ISSUE TITLE
User Can Login to Azure Portal and has full access but SDK can't acquire token

### ISSUE THREAD

**Issue by dmtroll** [Azure/azure-sdk-for-node#1953]
Strangely, this problem seems to occur to one user in our organization and we have yet to find anything wrong or incorrect in his Active Directory profile/policy. We enable his active directory as a Co-Admin within the web portal. He is able to log in successfully using his credentials and fully access everything. However, we have a tool we have built against this set of APIs and he is unable to login calling loginWithUsernamePassword. With valid hard-coded credentials, we get:

## Error
```
Error: Failed to acquire token for the user.
Error: WS-Trust RST request returned http error: 500 and server response: <s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://www.w3.org/2005/08/addressing" xmlns:u="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"><s:Header><a:Action s:mustUnderstand="1">http://www.w3.org/2005/08/addressing/soap/fault</a:Action><o:Security s:mustUnderstand="1" xmlns:o="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"><u:Timestamp u:Id="_0"><u:Created>2016-10-31T21:53:15.822Z</u:Created><u:Expires>2016-10-31T21:58:15.822Z</u:Expires></u:Timestamp></o:Security></s:Header><s:Body><s:Fault><s:Code><s:Value>s:Sender</s:Value><s:Subcode><s:Value xmlns:a="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">a:FailedAuthentication</s:Value></s:Subcode></s:Code><s:Reason><s:Text xml:lang="en-US">ID3242: The security token could not be authenticated or authorized.</s:Text></s:Reason></s:Fault></s:Body></s:Envelope>
    at C:\Users\kylec\Desktop\azuretest\node_modules\ms-rest-azure\lib\credentials\u
```serTokenCredentials.js:108:27
    at C:\Users\kylec\Desktop\azuretest\node_modules\adal-node\lib\token-request.js:150:11
    at C:\Users\kylec\Desktop\azuretest\node_modules\adal-node\lib\token-request.js:313:7
    at C:\Users\kylec\Desktop\azuretest\node_modules\adal-node\lib\token-request.js:288:7
    at Request._callback (C:\Users\kylec\Desktop\azuretest\node_modules\adal-node\lib\util.js:133:7)
    at Request.self.callback (C:\Users\kylec\Desktop\azuretest\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Users\kylec\Desktop\azuretest\node_modules\request\request.js:1060:10)
    at emitOne (events.js:96:13)
```

For reference,
## Code
```
var msRestAzure = require('ms-rest-azure');

msRestAzure.loginWithUsernamePassword('username','password',function(err, credentials) {
if (err) return console.log(err);
console.log('Successfully acquired token');
});
```

**Comment by yugangw-msft** [comment]
The issue might comes from 2 sources
1. Make sure your AD tenant doesn't enforce 2fa 
2. It is clear your AD tenant is federated, which means the user should come from your on-premise ADFS server. The error shows the library is trying to connect to your on-premise server to authenticate that user, but failed. So the question whether the user belong to your org?

For both of issues, you can use device flow to overcome it

**Comment by dmtroll** [comment]
@yugangw-msft Thank you for your reply. I'm currently working with our Ops team to check on the second point you raised. As for your suggestion of using interactiveLogin. While this is true in a standard command line program, it is difficult to use such a function in a GUI aspect like a browser front end or using something like electron.

**Comment by amarzavery** [comment]
@dmtroll - Any updates on this issue?

**Comment by dmtroll** [comment]
@amarzavery Unfortunately we were unable to determine why his AD profile doesn't work. Our AD profiles are identical. We have moved on from trying to use this solution as it just isn't working in our specific context. Thank you for providing the support.
