### ISSUE TITLE
Service Bus brokered properties contain string values, not proper dates

### ISSUE THREAD

**Issue by jeffwilcox** [Azure/azure-sdk-for-node#1961]
Service Bus returns the brokered properties metadata for a message as JSON to the library as a header which is being directly parsed with `JSON.parse` inside of `queuemessageresult.js#34`. As a result, the dates are not fun or intuitive to work with - it feels like the developer experience could be better here, interpreting official Service Bus property values [API spec here](https://msdn.microsoft.com/en-us/library/azure/hh780742.aspx?f=255&MSPPError=-2147217396).

- `1.2.0-preview` npm, but likely a long-time behavior

## Scenario

As a developer, I can use interesting properties such as `message.brokerProperties.EnqueuedTimeUtc` without needing to consider and parse the date/time value, OR if parsing is required, I would expect a format like ISO 8601 to be used.

## Expected

I would expect `typeof message.brokerProperties.EnqueuedTimeUtc` to be object (which is a JavaScript Date object).

## Actual

The standard message metadata date/time property is a string conforming to the RFC2616 standard.

Raw header example value, which is simply parsed:

```
"{\"DeliveryCount\":1,\"EnqueuedSequenceNumber\":25358,\"EnqueuedTimeUtc\":\"Sat, 05 Nov 2016 16:44:43 GMT\",\"LockToken\":\"93347da9-96cb-4e93-b98b-8ad1afd6e338\",\"LockedUntilUtc\":\"Sat, 05 Nov 2016 16:46:16 GMT\",\"MessageId\":\"7b6484e6dd64452ba782a4e98cab6bca\",\"SequenceNumber\":25314,\"State\":\"Active\",\"TimeToLive\":259200}"
```

**Comment by mj1856** [comment]
I would expect it to be a string in ISO8601 / [RFC 3339](https://tools.ietf.org/html/rfc3339) format, not a JS `Date` object.

```json
 "EnqueuedTimeUtc": "2016-11-05T16:44:43Z"
```

Note, [Microsoft's API Guidelines section 11.2.1](https://github.com/Microsoft/api-guidelines/blob/master/Guidelines.md#112-guidelines-for-dates-and-times) currently state:

> Services MUST produce dates using the DateLiteral format, and SHOULD use the Iso8601Literal format unless there are compelling reasons to do otherwise.

Additionally, the other formats mentioned in the guidelines (StructuredDateLiteral) will soon be removed, per Microsoft/api-guidelines/issues#22 (as soon as I can get a PR in. 😉 )

**Comment by maggiepint** [comment]
As an additional note, @mj1856 and I are both maintainers on the [moment](https://github.com/moment/moment) team and Redmond FTEs. If you want help adjusting date formats in this SDK, let one of us know. We're happy to get you moving in the right direction.

**Comment by jeffwilcox** [comment]
Hi, is the Service Bus SDK no longer being maintained?

**Comment by cjthompson** [comment]
In `queuemessageresult.js` there is [already a function](https://github.com/Azure/azure-sdk-for-node/blob/71ff4be1064b5ef9da17711b7e7668caecd31ecf/lib/services/serviceBus/lib/models/queuemessageresult.js#L75) that replaces strings with proper types (date, boolean, number).

I'm curious why this code is only in `queuemessageresult` rather than in `resourceresult`, where it would do that transform for all result models.

Currently I'm using a Proxy wrapper to do this transform for me.  I'd be happy to submit a PR to change this behavior for all Result models.  Of course there is a concern that this would break everyone's code that's already expecting these values to be strings.

**Comment by amarzavery** [comment]
Please try out the new servicebus sdk `npm i @azure/service-bus`. The sdk has been moved to https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/servicebus/service-bus . 

The new sdk does solve this issue.

In future please open service bus related issues in the new repo https://github.com/Azure/azure-sdk-for-js
