### ISSUE TITLE
azure-servicefabric versus azure-arm-servicefabric

### ISSUE THREAD

**Issue by moncapitaine** [Azure/azure-sdk-for-node#1986]
both are mixed up I guess:

https://www.npmjs.com/package/azure-servicefabric
https://www.npmjs.com/package/azure-arm-servicefabric

The first is the right one?

Documentation exists only for "-arm-" (http://azure.github.io/azure-sdk-for-node/azure-arm-servicefabric/latest/)

With other words:
[Documentation](http://azure.github.io/azure-sdk-for-node/azure-arm-servicefabric/latest/serviceFabricClient.js.html) does not match [source](https://github.com/Azure/azure-sdk-for-node/blob/38d69f4f35acab80a758eccf712935b83b70fa06/lib/services/serviceFabric/lib/serviceFabricClient.js). 

I know that packages are different, but ...

Any hint whats going on?

Regards,
Michael

**Comment by amarzavery** [comment]
@msjeffreychen - Can you take a look at this issue?

**Comment by msjeffreychen** [comment]
azure-servicefabric is the correct one.
