### ISSUE TITLE
Fix bug in GraphAPI.prototype._requestWithRetry

### ISSUE THREAD

**Issue by kbajalc** [Azure/azure-sdk-for-node#2007]
Correct segment, in original code 'content' variable is undefined

if (data) {
        if (Buffer.isBuffer(data)) {
            options.headers['Content-Type'] = contentType;
        } else if (!contentType) {
            if (typeof data === 'string') {
                options.headers['Content-Type'] = 'application/x-www-form-urlencoded';
                options.headers['Content-Length'] = data.length;
            } else if (data !== null && typeof data === 'object') {
                data = JSON.stringify(data);
                options.headers['Content-Type'] = 'application/json';
                options.headers['Content-Length'] = data.length;
            }
        }
    }

**Comment by amarzavery** [comment]
@kbajalc - Can you please point a reference to the source code of the package that you were using?
