### ISSUE TITLE
[ServiceBus] Cannot read property 'toLowerCase' of undefined when setting proxy on ServiceBusService

### ISSUE THREAD

**Issue by minhio** [Azure/azure-sdk-for-node#2016]
to reproduce:

```javascript
'use strict';

const azure = require('azure');

let sbService = azure.createServiceBusService("Endpoint=sb://somenamespace.servicebus.windows.net/;SharedAccessKeyName=somesharedkeyname;SharedAccessKey=someaccesskey=");
sbService.setProxy('http://myproxy', 8080);
sbService.sendTopicMessage('my-topic', {body: 'hello'}, function(err) {
    if(err) {
        console.log(err);
        process.exit(1);
    }
    process.exit();
});
```

error:

`Cannot read property 'toLowerCase' of undefined` 

on this line https://github.com/Azure/azure-sdk-for-node/blob/master/lib/common/lib/util/util.js#L249

**Comment by jtaubensee** [comment]
@minhio - Does this work without the proxy? I'm pretty sure that you don't need the `Endpoint=` part of the connection string.

**Comment by minhio** [comment]
@jtaubensee - It works fine without the proxy.  If I remove `Endpoint=` it throws an "Invalid connection string setting" error.

**Comment by mozehgir** [comment]
Please try the new SDK by installing @azure/service-bus from npm. If the error persists feel free to re-open this issue in the https://github.com/Azure/azure-sdk-for-js repository .
