### ISSUE TITLE
missing implementation of service bus message deadletter function

### ISSUE THREAD

**Issue by camous** [Azure/azure-sdk-for-node#2019]
C# package provide few extra methods for handling with more granularity message.

such
```
message.DeadLetter();
message.Defer();
message.Abandon();
```

In my scenario, I have messages which I know I won't be able to proceed and I would like to prevent that those messages goes 10 times (default) over the queue before going to the deadletter queue.

I had a look into azure-sb module and wasn't able to find a prototype for these actions. I had a look into the C# implementation & dependency with https://github.com/Azure/azure-amqp/ + a specific class 
https://github.com/Azure/azure-amqp/search?utf8=%E2%9C%93&q=Rejected%28%29

```
namespace Microsoft.Azure.Amqp.Framing
{
	using System.Text;	
	public sealed class Rejected : Outcome
	{
		public static readonly string Name = "amqp:rejected:list";
		public static readonly ulong Code = 0x0000000000000025;
...
```

and try to find if there was already similar calls into the nodejs module for implemented behavior, but with no luck and unfortunately it seems a little out of my league in terms of coding skills :/

any helps or direction would be greatly appreciated.
I can even imagine stupid workaround with external webservices in C# doing the deadletter move :)

**Comment by jtaubensee** [comment]
I just created a new issue in order to track this functionality in the REST API, which this would be dependent on.

**Comment by amarzavery** [comment]
@camous - Please try out the new servicebus sdk `npm i @azure/service-bus`. The sdk has been moved to https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/servicebus/service-bus . The specific example of receiving messages from a DeadLetter Queue can be found [here](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/servicebus/service-bus/samples/typescript/advancedFeatures/processMessageFromDLQ.ts).

In future please open service bus related issues in the new repo https://github.com/Azure/azure-sdk-for-js
