### ISSUE TITLE
Strange tokenAudience restriction

### ISSUE THREAD

**Issue by proll** [Azure/azure-sdk-for-node#2025]
According to this lines options.tokenAudience MUST be 'graph':
https://github.com/Azure/azure-sdk-for-node/blob/master/runtime/ms-rest-azure/lib/credentials/applicationTokenCredentials.js#L56-L58
and it can't be undefined by default

I tried to comment this code and set tokenAudience to 'https://management.core.windows.net' it works.
```javascript
msRestAzure.loginWithServicePrincipalSecret(clientid, secret, tenanatid, {tokenAudience: tokenAudience}, function(err, credentials) {
        if (err) {
            console.log(err);
            return;
        }

        var client = new CDNManagementClient(credentials, subscriptionid);
        client.endpoints.purgeContent(esourceGroupName, profileName, endpointName, purgeContentPaths, function(err, result, request, response) {
            if (err) {
                console.log(err);
                return;
            }
            logger.ok('visuals CDN purged');
        });
     });
```
What did I do wrong? Or it's a logical bug I mean with lock of tokenAudience to 'graph'

**Comment by amarzavery** [comment]
You are right. We have opened up the tokenAudience to be graph, batch or any other resource for a given service. https://github.com/Azure/azure-sdk-for-node/blob/master/runtime/ms-rest-azure/lib/credentials/applicationTokenCredentials.js#L66.
