### ISSUE TITLE
npm warning: node-uuid@1.4.7: use uuid module instead

### ISSUE THREAD

**Issue by Alex-Wauters** [Azure/azure-sdk-for-node#2026]
warning azure > node-uuid@1.4.7: use uuid module instead
warning azure > request > node-uuid@1.4.7: use uuid module instead
warning azure > azure-storage > node-uuid@1.4.7: use uuid module instead
warning azure > ms-rest-azure > adal-node > node-uuid@1.4.7: use uuid module instead

node-uuid hasn't been updated in over a year and is superseded by uuid
https://www.npmjs.com/package/uuid

**Comment by fiveisprime** [comment]
There are quite a few sub modules in here that need some dependency updates. Some
of the Azure dependencies are still on preview versions rather than on the GA.

There should be an audit and update sweep done for every module.

**Comment by amarzavery** [comment]
We have replaced node-uuid with uuid everywhere that we could.

```bash
azure@2.0.0-preview /Users/amarz/sdk/azure-sdk-for-node
├─┬ adal-node@0.1.22
│ └── node-uuid@1.4.7
├─┬ azure-common@0.9.18
│ └─┬ request@2.74.0
│   └── node-uuid@1.4.8
├─┬ azure-storage@1.3.0
│ ├── node-uuid@1.4.8
│ └─┬ request@2.74.0
│   └── node-uuid@1.4.8  deduped
└─┬ azure-storage-legacy@0.9.14
  └─┬ azure-common@0.9.11
    └─┬ request@2.45.0
      └── node-uuid@1.4.8
```

We can upgrade the request.js library in azure-common as that is in our control.

However, adal-node, azure-storage and azure-storage-legacy are maintained by other teams.
