### ISSUE TITLE
[ServiceBus] Create queue does not support Enable Partitioning

### ISSUE THREAD

**Issue by geneh** [Azure/azure-sdk-for-node#2028]
This issue is related to https://github.com/Azure/azure-sdk-for-node/issues/1893.
`createQueue` & `createQueueIfNotExists` should support partitioning.
Pull request to address this issue: https://github.com/Azure/azure-sdk-for-node/pull/2027

**Comment by jtaubensee** [comment]
@amarzavery - Would you check out @geneh's PR? It looks good to me.

**Comment by jtaubensee** [comment]
@amarzavery - Please merge the PR above. Closing this issue in the meantime.
