### ISSUE TITLE
.from missing from Azure.TableQuery

### ISSUE THREAD

**Issue by atrauzzi** [Azure/azure-sdk-for-node#2040]
```
        const query = new Azure.TableQuery();
        console.log(query.where); // [Function]
        console.log(query.from); // undefined
```

Using `1.2.0-preview` via TypeScript.

**Comment by atrauzzi** [comment]
If I look at my copy of `tablequery.js`,  I don't see [these lines of code](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/legacyStorage/lib/table/tablequery.js#L67-L70) anywhere.

**Comment by 1N50MN14** [comment]
This is actually an issue in the *already* published version on npm as well!

**Comment by amarzavery** [comment]
@atrauzzi @1N50MN14 - I think you have posted the issue in the wrong repo. This repo maintains the storage management plane sdk (CRUD on the storage account and storageaccount keys). I think the issue should be filed here https://github.com/Azure/azure-storage-node

In any case: @hasonmsft - Can you please take a look at this issue?

**Comment by atrauzzi** [comment]
I linked issue #262 from their repository.  I was worried I might have the wrong spot.  Let's close this one and continue there.

Thank you @amarzavery.
