### ISSUE TITLE
Module is slow to load.

### ISSUE THREAD

**Issue by fiveisprime** [Azure/azure-sdk-for-node#2053]
```shell
npm i azure
time node -e "require('azure')"
```

I've seen it take up to 2.40s to just load the module. I'm guessing this is from
the high amount of I/O being used because so many dependent modules are being
loaded (there are 48 azure modules being loaded).

Is it possible to lazy load the modules rather just requiring them immediately?

**Comment by amarzavery** [comment]
With the new changes the load time is way better. Output of three successive runs..
```
Amars-MacBook-Pro:foo amarz$ time node -e "require('azure')"

real	0m0.780s
user	0m0.715s
sys	0m0.081s
Amars-MacBook-Pro:foo amarz$ time node -e "require('azure')"

real	0m0.749s
user	0m0.691s
sys	0m0.076s
Amars-MacBook-Pro:foo amarz$ time node -e "require('azure')"

real	0m0.742s
user	0m0.685s
sys	0m0.075s
```

**Comment by amarzavery** [comment]
A new version of the SDK has been published. Please check the [release page](https://github.com/Azure/azure-sdk-for-node/releases/tag/2.0.0-preview-April2017).
