### ISSUE TITLE
Azure Graph API - Can't create local account

### ISSUE THREAD

**Issue by cosminonea** [Azure/azure-sdk-for-node#2063]
I am trying to create a "LocalAccount" in a B2C domain as documented in here: https://msdn.microsoft.com/en-us/library/azure/ad/graph/api/users-operations#CreateLocalAccountUser

I am using the azure-graph node package and the payload of my request looks like in the MSDN article.

The request is:

    POST https://graph.windows.net/myorganization/users
    {
      "accountEnabled": true,
      "creationType": "LocalAccount",
      "displayName": "Alex Wu",
      "passwordProfile": {
        "password": "Test1234",
        "forceChangePasswordNextLogin": false
      },
      "signInNames": [
        {
          "type": "userName",
          "value": "AlexW"
        },
        {
          "type": "emailAddress",
          "value": "AlexW@example.com"
        }
      ]
    }

The error I am getting is:

> Error: Error "'userPrincipalName' cannot be null or undefined in 'parameters'." occurred in serializing the payload

I think the error comes from the node package. Does the node graph api client support LocalAccounts?

**Comment by cosminonea** [comment]
I ended up not using the azure-graph.
I am creating my own POST request and send it.

**Comment by amarzavery** [comment]
A new version of the SDK has been published. Please check the [release page](https://github.com/Azure/azure-sdk-for-node/releases/tag/2.0.0-preview-April2017).

**Comment by c-eliasson** [comment]
@amarzavery Was this issue solved? 

I use version 2.2 of the SDK, and i still can't create a LocalAccount for a B2C tenant. Getting the same error as @cosminonea got. 

Looking at the [documentation](https://docs.microsoft.com/en-us/javascript/api/azure-graph/users?view=azure-node-latest#functions), both `userPrincipalName` and `mailNickname` are required, which I guess indicate that LocalAccount isn't supported? Is it on the roadmap to support it?
