### ISSUE TITLE
Invalid unicode character

### ISSUE THREAD

**Issue by fiveisprime** [Azure/azure-sdk-for-node#2070]
There's an invalid unicode character on [L227 of serviceclient.js](https://github.com/Azure/azure-sdk-for-node/blob/c98fd8ff9310f688a7ff6a227015876cd1f722ab/lib/common/lib/services/serviceclient.js#L227) (between the `)` and `{`).
If you have whitespace visible in your editor, you will see that this isn't actually a space.

_browser-rendering of the char_
![image](https://cloud.githubusercontent.com/assets/1186948/23177056/58889872-f81a-11e6-8da8-acdfa7bff4ce.png)

_visible indication of char in editor_
![image](https://cloud.githubusercontent.com/assets/1186948/23177131/90d5635e-f81a-11e6-8eb9-1f87c3969001.png)

The Node.js runtime knows how to handle this character, but browsers don't so
the issue is pretty transpartent until you run the script through a
parsing/compilation tool such as browserify and attempt to run within a browser
(doesn't work, but that's a TOTALLY separate issue).

I would correct this in the source, but I'm sure this file is generated and will be
overwritten later if I do. I'm also unsure of where to fix this so II'll leave it to you. :)

**Comment by amarzavery** [comment]
Closing this in favor of the new isomorphic JS sdks
