### ISSUE TITLE
Error  TS2307: Cannot find module 'http'

### ISSUE THREAD

**Issue by shilpivenaik** [Azure/azure-sdk-for-node#2087]
After Installing "npm install Power-api" through npm and using "import * as pbiapi from 'powerbi-api';" in  typescript file gives the following error:
Error - typescript - node_modules\ms-rest\lib\index.d.ts(1,22): error
TS2307: Cannot find module 'http'.

**Comment by balajikris** [comment]
Hi @shilpivenaik , our typescript support for node sdk currently has some issues (see https://github.com/Azure/azure-sdk-for-node/issues/2083). We're working on this to make this better. 

Meanwhile, I'm trying to understand the nature of the problem you reported and I have some questions.
1. > "npm install Power-api" 

    I think you meant "powerbi-api"

2. I hope you ran `npm install` to install all dependencies specified in your package.json

3. could you share a short piece of code that is required to reproduce this build issue? 

4. Also , I think this package has its own repo [here](https://github.com/Microsoft/PowerBI-Node). So, feel free to file an issue there as well.
I'm still interested to take a look here, because the error seems to originate at "ms-rest" which indeed belongs to this repo.

**Comment by shilpivenaik** [comment]
Hi @balajikris 

Thanks for the quick response.
Yes, you are correct, the command is npm install Powerbi-api.
I'm trying to develop a client side webpart for SharePoint Online environment. This webpart would embed a powerbi report from powerbi workspace.

While developing the webpart, below steps are taken:
1. From command line instance, created a folder “PowerBI_WebPart”, and navigated to it.

2. Then I ran the yeoman SharePoint generator with “`yo @microsoft/sharepoint`” and stick to the default values.

3. Added the additional dependencies via:
```
npm install powerbi-client
npm install powerbi-api
```

4. Then, I ran `npm install` command to install all dependencies.

5. In webpart.ts file, following libraries are included 
```
import * as pbi from 'powerbi-client';
import * as pbiapi from 'powerbi-api';
```

6. And finally I ran` gulp serve` command to debug the webpart.

7. As I run the gulp serve command, I got the below errors:
```
Error - typescript - node_modules\ms-rest\lib\index.d.ts(0,24): error TS2307: Cannot find module 'stream'.
Error - typescript - node_modules\ms-rest\lib\index.d.ts(1,22): error TS2307: Cannot find module 'http'.
```
This seems that some of the dependencies for powerbi-api in ms-rest library are not getting installed in the solution.

**Comment by shilpivenaik** [comment]
hi @balajikris 
Any Update on the reported error .If you need i can share the code with you.
Thanks

**Comment by balajikris** [comment]
Hey @shilpivenaik - Given the issue stems from `powerbi-api` package, I recommend filing a bug [here](https://github.com/Microsoft/PowerBI-Node). This package doesn't seem to belong in this repo and appears to ship be shipped and maintained by the powerbi team. I'm also tagging a contributor from that repo, so he might be able to guide you. tagging @ali-hamud

**Comment by balajikris** [comment]
Let me investigate a bit more on what's going on here. It also possible that typescript support in ms-rest package could be broken. This error is not something we know of, but it would make this a dupe/part of https://github.com/Azure/azure-sdk-for-node/issues/2083. 

@shilpivenaik: can you share a minimal piece of code that reproduces the problem with me? I'll take a look.

**Comment by balajikris** [comment]
I tried compiling a TS sample that refers to ms-rest and it works well for me. So, ms-rest is not broken. Notice that 'http' is part of built-in library provided by nodejs. you need to have typings for node installed to be able to build in typescript. See if this helps: http://stackoverflow.com/questions/38434864/typescript-cannot-find-module-http-on-visual-studio-code
