### ISSUE TITLE
Error "InvalidHeaderValue" "x-ms-version" on storage

### ISSUE THREAD

**Issue by julsburgs** [Azure/azure-sdk-for-node#2095]
I am starting with azure storage to save an read file but I' m having some problems 
Firtst is there  any difference between azure-storage-legacy and  azure-storage
Then if use azure-storage i can't set publicAccessLevel to private why ?
Moreover when i use the other module azure-storage-legacy I obtain this error **"The value for one of the HTTP headers is not in the correct format. RequestId:ae10c3e7-0001-00cd-4486-99a28b000000 Time:2017-03-10T10:08:23.8176442Z"**
I am using latest versions of these modules 

this is my code:

`var storage= require("azure-storage-legacy"); // or "azure-storage"
const uri="my uri" // obtained by portal
var blob =storage.createBlobService(uri);
blob.createContainerIfNotExists('taskcontainer', {  publicAccessLevel: 'Private'}, function(error, result, response) {
  if (!error) {
   console.log(result)
  }

})`
I hope some answer

**Comment by amarzavery** [comment]
This is not the correct repo. The right repo is: https://github.com/Azure/azure-storage-node. I have filed an issue https://github.com/Azure/azure-storage-node/issues/283 for you over there.
