### ISSUE TITLE
BlobService.createBlockBlobFromText encodes blob name in URL format when it is already properly escaped

### ISSUE THREAD

**Issue by doodlefolks** [Azure/azure-sdk-for-node#2104]
In my example I am passing a string for a blob name that I have already escaped using encodeURIComponent(). The URL created for the blob for REST access is then escaped again (specifically the '%' characters). I don't think this should be default behavior if the blob name is correctly escaped to begin with.

**Comment by amarzavery** [comment]
@doodlefolks - The source code has moved to a different repo https://github.com/Azure/azure-storage-node.  Have created an issue over there https://github.com/Azure/azure-storage-node/issues/288
