### ISSUE TITLE
virtualMachines.get does not return VM status (stopped, running, deallocated, etc.)

### ISSUE THREAD

**Issue by brennaman** [Azure/azure-sdk-for-node#2119]
I've made the call to virtualMachines.get to retrieve instance information about my VM.  In the output I don't see where you get the status of the VM (stopped, running, deallocated).  Is there another way to get the status that I'm looking for?

**Comment by amarzavery** [comment]
- you need to use the optional query parameter `$expand=instanceView`.

```javascript
//assuming you have instantiated the client ...
let options = {expand: 'instanceView'};
client.virtualMachines.get('rg-name', 'vm-name', options).then((vminfo) => {
  console.dir(vminfo, {depth: null, colors: true});
}).catch((err) => {
  console.dir(err, {depth: null, colors: true});
});
```
Here is the [documentation reference](http://azure.github.io/azure-sdk-for-node/azure-arm-compute/latest/VirtualMachines.html#get).

**Comment by brennaman** [comment]
Thank You!  That worked.

**Comment by amarzavery** [comment]
Nice to know. Closing the issue :).
