### ISSUE TITLE
Please fix typo in KeyVaultCredentials constructor (keyvault.d.ts file)

### ISSUE THREAD

**Issue by benekk** [Azure/azure-sdk-for-node#2124]
Please fix the typo: it should be spelled "constructor" instead "cosntructor". Also if the authenticator parameter is changed to Any it could actually work when following readme doc.

Here is the code:
export class KeyVaultCredentials implements msRest.ServiceClientCredentials {
  cosntructor(authenticator: Authenticator);
  signRequest(webResource: msRest.WebResource, callback: { (err: Error): void }): void;
}

**Comment by amarzavery** [comment]
@benekk - Thanks for pointing out. We discovered that 2 days ago. We are writing a TS sample as well. Will publish the new version and the sample in a day or two.
/cc @balajikris

**Comment by balajikris** [comment]
This is good feedback (on auth part), thank you @benekk - these were the same two things I ran into when writing a TS sample. I'm looking for things we can improve here and we'll publish an update with those changes.

**Comment by balajikris** [comment]
@benekk : published `2.0.1-preview` to npm. hopefully this unblocks you. If you find issues, please get in touch and thank you for filing this issue 👍

**Comment by benekk** [comment]
@balajikris Thanks a lot for fixing this! It works great now!
