### ISSUE TITLE
clean way to manipulate interval and/or timespan values (eg PT12H)

### ISSUE THREAD

**Issue by camous** [Azure/azure-sdk-for-node#2127]
google got me 0 answer, is there a way to cleanly work with azure timespan & interval such 'PT12H', 'PT30M' without reinventing the whell.

my requirement based on Azure Service Bus is to wait as much as possible, based on the lock duration, before re-processing a message, and the lockDuration time provided by the queue is in 'PTxxx' format. I could parse it but if there is better way ...

**Comment by amarzavery** [comment]
@camous - By Azure Timespan, do you mean the C# .net timespan format as mentioned [here](https://msdn.microsoft.com/en-us/library/ee372286(v=vs.110).aspx)? 
I think the PTxxx format is a standard duration format.

Did you try using the popular [moment.js library](https://momentjs.com/). It has a [bunch of functions with duration](https://momentjs.com/docs/#/durations/) that can be used to convert a duration to a DateTime object and vice-versa.

Please explain
- why do you need to do this conversion
- an example of input and the output (format to be converted to)

for more clarity.

@jtaubensee - Please take a look into this

**Comment by camous** [comment]
I wasn't aware that it was a standard format. But according to your suggestion, I've tried moment.duration('PTxxx') with success in my requirement.

Regarding my exact requirement, I was trying to re-process my SB message with a delay of = current datetime (date) + queue lockduration (PTxxxx duration format).
