### ISSUE TITLE
ms-rest 2.0.0 is missing use strict declarations

### ISSUE THREAD

**Issue by LoulG** [Azure/azure-sdk-for-node#2129]
ms-rest npm package in its version 2.0.0 is missing some `use strict` declarations, at least in webResource.js, utils.js, constants.js

**Comment by amarzavery** [comment]
Thanks for reporting. We shall fix this and publish a new version in the coming week.

**Comment by amarzavery** [comment]
New version of ms-rest "2.1.0" has been published. Please feel free to let us know if you find other issues.
