### ISSUE TITLE
Docs are missing azure-arm-website

### ISSUE THREAD

**Issue by benc-uk** [Azure/azure-sdk-for-node#2133]
The main read the docs page for this SDK at http://azure.github.io/azure-sdk-for-node/
is missing the *azure-arm-website* module, so I didn't actually think it existed until I checked the github repo.

**Comment by tony-gutierrez** [comment]
That url is now dead.

**Comment by watt** [comment]
It's not linked, but it does seem to exist: http://azure.github.io/azure-sdk-for-node/azure-arm-website/latest/

**Comment by tony-gutierrez** [comment]
Yeah, they just restored it yesterday. Only took months.
