### ISSUE TITLE
Sample for Message Bus Sessions and Correllation ?

### ISSUE THREAD

**Issue by datauduong** [Azure/azure-sdk-for-node#2135]
Here is my code sending message to the Sessions Enable Queue.
var queueName = 'samplequeue'; // This queue has been created with Session Enable.

var azure = require('azure');
var uuid = require('node-uuid');

// Create a unique OrderId
var sessionId = uuid.v4();
console.log(sessionId);

var connectionstring = '';

var serviceBusService = azure.createServiceBusService(connectionstring);

serviceBusService.createQueueIfNotExists(queueName, function (error) {
    if (!error) {
        // Queue exists
        console.log('Queue Named: ' + queueName + ' Already Exist')
    }
});

var message = {
  body: 'Test message',
  customProperties: {
    testproperty: 'TestValue'
  },
  brokerProperties: {
    SessionId: sessionId
  }
};

serviceBusService.sendQueueMessage(queueName, message, function (error) {
    if (!error) {
        // message sent
    }
});

2 Question:
1. After Sending Message from the above code, how to wait for the message return ?
2. After Consumer finish processing how to return the data into the same queue ?

Do you have a complete sample of Request / Reply pattern using Sessions/Correlation.

Found something like AcceptMessageSession in c#, but don't know how to use it in NodeJs

Thanks in Advance.

**Comment by amarzavery** [comment]
@jtaubensee - Please have a look at this issue.

**Comment by jtaubensee** [comment]
@datauduong - This Node library is built on top of Service Bus' REST API, which does not have the ability to receive sessions. This functionality will not be added to this library, but would instead be added to a future library that is based on AMQP, and not HTTP.

**Comment by amarzavery** [comment]
The new service bus sdk `npm i @azure/service-bus` solves this issue. The source code can be found here https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/servicebus

the sample can be found here: https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/servicebus/service-bus/samples/typescript/advancedFeatures/sessionState.ts
