### ISSUE TITLE
Uploading build folder to blob

### ISSUE THREAD

**Issue by tomalex0** [Azure/azure-sdk-for-node#2143]
As part of  build process of front end js and css,   i was looking into approach of  uploading  all files to blob after minification is done.  Do you recommend  using this sdk to do the upload of folder ?

Currently build process is done through webpack.

**Comment by amarzavery** [comment]
@tomalex0 - You would want to take a look at the https://github.com/Azure/azure-storage-node repo. That has performant apis specific to upload/download
