### ISSUE TITLE
Module request: Cloud service (classic)

### ISSUE THREAD

**Issue by Dominik-K** [Azure/azure-sdk-for-node#2156]
It would be good to have "Cloud service (classic)" as a module. Then we could use this SDK for the  [deleting one specific instance API](https://blogs.msdn.microsoft.com/sriharsha/2017/02/21/how-to-delete-a-specific-instance-from-a-running-cloud-service-paas-v1/).

With this SDK it's really easy to manage the authentication in comparison to the many needed steps what I've found in some MSDN blogs:

* [Certificate-based auth with Azure Service Principals from Linux command line](https://blogs.msdn.microsoft.com/arsen/2015/09/18/certificate-based-auth-with-azure-service-principals-from-linux-command-line/)
* [Authenticating Azure Service Management API with Azure AD User Credentials](https://blogs.msdn.microsoft.com/cloud_solution_architect/2015/03/01/authenticating-azure-service-management-api-with-azure-ad-user-credentials/)
* [Using Postman to call Azure REST APIs](https://blogs.msdn.microsoft.com/benjaminperkins/2017/01/03/using-postman-to-call-azure-rest-apis/)

I focus on the **Node.js SDK** as we want to start with ChatOps in the short future, mostly with [Hubot](https://hubot.github.com/).

**Comment by amarzavery** [comment]
@Dominik-K - I agree, node sdk has simplified the authentication process as described [here](https://github.com/Azure/azure-sdk-for-node/blob/master/Documentation/Authentication.md).

We are currently focusing on ARM (Azure Resource Manager), the V2 version of Azure APIs. Cloud Service (classic) is a part of ASM (Azure Service Management) the old V1 version of Azure APIs.

Is there a reason for you to not use the ARM based APIs but the ASM ones?
/cc @balajikris , @mayurid
