### ISSUE TITLE
possible conflict between client.on and client.onDeviceMethod

### ISSUE THREAD

**Issue by michaelheyd** [Azure/azure-sdk-for-node#2161]
I am hoping that I'm using the SDK incorrectly, but I'm having trouble setting up my client to receive Messages when I'm also receiving Methods.  I've attached the complete file, but here are the snippets...

When I have the following code, the 'onMessage' never fires.  When i comment the .onDeviceMethod functions, then the 'onMessage' fires.

// register handler for the message queue
console.log('registering message handler');
client.on('message', onMessage);
		
// register handlers for all the method names we are interested in
console.log('registering custom methods');
client.onDeviceMethod('blinkLight', onBlinkLight);
		
Here is the complete file...
[iotTest.txt](https://github.com/Azure/azure-sdk-for-node/files/987574/iotTest.txt)

**Comment by amarzavery** [comment]
This is a wrong repo. Please file the issue over here https://github.com/Azure/azure-iot-sdk-node
