### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by BigYu** [Azure/azure-sdk-for-node#2172]
Is there any plan for an available Javascript sdk. I mean, is it possible to allow front-end developers access to the Azure services directly from the browser, without forwarding the request from the private server? As far as I know we only have SDKs for sever-side, do we have any security concerns or worries?

Or how can I search for some docs which can coach me to talk to the restful api and unblock my web application to the azure service. Possibly I need to resolve the cross-domain the credential problems.

**Comment by balajikris** [comment]
Hey @BigYu 

We're currently exploring options to support clientside javascript. See this workitem (https://github.com/Azure/azure-sdk-for-node/issues/2138) and its related ones. This work is still in its early stages, so I could not comment on a specific timeline, but this is our top priority currently. So, stay tuned 👍 

/cc : @fiveisprime @amarzavery

**Comment by BigYu** [comment]
Thanks @balajikris and it's cool!

**Comment by amarzavery** [comment]
Please take a look at the new isomorphic sdks over here https://github.com/Azure/azure-sdk-for-js The sdks can run in the browser and also on the server side (node.js).

All the new sdks are published to npm under the @azure/<sdk-name> org structure.
