### ISSUE TITLE
Add support for role environment in web roles

### ISSUE THREAD

**Issue by matthewbhall** [Azure/azure-sdk-for-node#2176]
roleenvironment.js states:

> * __Note__: RoleEnvironment will only work if your code is running in a worker role
> * inside the Azure emulator or in a Microsoft Azure Cloud Service!

Can this support be extended to web roles? Currently I have to call C# or other managed code to get the information I need in my web role. 

The information obviously exists, so it is an external dependency that is blocking this?

**Comment by balajikris** [comment]
is this a thing for ARM as well or is it ASM (azure legacy) specific ? adding @fiveisprime and @amarzavery to the conversation as well.

**Comment by amarzavery** [comment]
This is legacy stuff and we don't plan to support it anymore.
