### ISSUE TITLE
Service Bus Queues Batch Send and Batch Receive

### ISSUE THREAD

**Issue by christophersw** [Azure/azure-sdk-for-node#2184]
According to this Azure Service Bus Queues support Batch Send, and Batch Receive, among other things. I know this is implemented in the C# library, but I am hoping to use it on a Node server.

I am not seeing these in the SDK, or the examples. Are these implemented in the azure SDK for node?

**Comment by amarzavery** [comment]
@jtaubensee - Can you please take a look at this request?

**Comment by rmelo** [comment]
Hey guys!
Is there any way to do that? I'm a Premier Microsoft customer and there's a lot of things that we don't know how to do. It's make our decisions to be hard.
How can you let us (community) without a feedback for 29 days? Is it a Microsoft SLA?

**Comment by amarzavery** [comment]
Please try the new sdk `npm i @azure/service-bus`.

Source code for new sdk can be found here https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/servicebus/service-bus

Sample for receiving a batch of messages can be found here https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/servicebus/service-bus/samples/typescript/gettingStarted/receiveMessagesLoop.ts#L26

Moving forward please file service bus related issues in the new repo https://github.com/Azure/azure-sdk-for-js
