### ISSUE TITLE
[Info needed] MQTT implementation azure-iot-device'.Client

### ISSUE THREAD

**Issue by Kapster17** [Azure/azure-sdk-for-node#2185]
Is there any documentation about the MQTT implementation for the 'azure-iot-device'.Client
How reliable is QoS=1 support for MQTT (How long does it buffer and retry ?). I have observed when there is internet connection loss.  I DO NOT get any error for the Event Send call, and the Event is NOT delivered. What would be the best practice to ensure reliability ?

Another query is how would be the best way to check if the connection is alive before I attempt client.open(connectCallback) again.
On my Rp 3 in case of connection drops (I turn of my wifi), It takes more than 5 minutes to get a call back to client.on('disconnect', function ().

I would need to have a open connection at all time. Would reopening the connection in  client.on('disconnect', function () the correct way out ? This is assuming disconnect will always be called.

**Comment by amarzavery** [comment]
@Kapster17 - The issue has been opened in the wrong repo. Opened an issue for you over here https://github.com/Azure/azure-iot-sdk-node/issues/105.
