### ISSUE TITLE
Protect special/reserved internal variable names, such as "pipeline"

### ISSUE THREAD

**Issue by begoldsm** [Azure/azure-sdk-for-node#2193]
This PR breaks the Azure Node SDK: https://github.com/Azure/azure-sdk-for-node/pull/2188

The reason for this is because ADLA added a new operation group called `pipeline`. This then overwrites the internal pipeline object which is used for all requests, causing all service calls to fail afterwards with:
`TypeError: client.pipeline is not a function`

My recommended fix for this is to create a robust list of reserved "keywords" for node in the AutoRest code gen and replace them if they are discovered, depending on their location. This is already done for the "delete" keyword which renames `delete` to `deleteMethod`. In this case, because pipeline is an operation group for ADLA, it should be renamed from `pipeline` to `pipelineOperations` or something similar. I am going to manually rename it in the pr to `pipelineOperations` , but this should become automated by AutoRest quickly, to avoid more breaking changes when code gen re-runs.

**Comment by amarzavery** [comment]
This has been fixed. pipeline is now a reserved word.
