### ISSUE TITLE
Implement Managed Service Identity for the sdk

### ISSUE THREAD

**Issue by amarzavery** [Azure/azure-sdk-for-node#2224]

**Comment by lostintangent** [comment]
What exactly would this item include?

**Comment by amarzavery** [comment]
Please read this [comment from Yugang](https://github.com/Azure/azure-xplat-cli/issues/3200#issuecomment-316126109) to get an overview about MSI. The work that is being done in az-cli will be done for other sdks as well.

**Comment by balajikris** [comment]
i'll take this, for now.
