### ISSUE TITLE
Make ms-rest-azure accept the credentials file generated by az cli

### ISSUE THREAD

**Issue by amarzavery** [Azure/azure-sdk-for-node#2225]

**Comment by lostintangent** [comment]
This will be amazing :)

**Comment by amarzavery** [comment]
Please read this [comment from Yugang](https://github.com/Azure/azure-xplat-cli/issues/3200#issuecomment-316126109) to get an overview about MSI. The work that is being done in az-cli will be done for other sdks as well.
