### ISSUE TITLE
add support to gulpfile.js to consume new changes in Autorest and changes in azure-rest-api-specs repo

### ISSUE THREAD

**Issue by amarzavery** [Azure/azure-sdk-for-node#2226]
- update readme.md/config file with node.js codegen settings by reading the mapper in gulpfile.js
- update autorest execution command based on the new model
- update the default root path for azure-rest-api-spec repo
- add a section that updates the mapper (if required take the mapper out and put it in a separate file)
  - for newer api-versions of the existing spec
  - for new services

**Comment by balajikris** [comment]
I'm working on this.
