### ISSUE TITLE
Bug with interactive login and FileTokenCache

### ISSUE THREAD

**Issue by brendandburns** [Azure/azure-sdk-for-node#2229]
```
.../node_modules/async/lib/async.js:123
        if (!arr.length) {
                ^

TypeError: Cannot read property 'length' of undefined
    at Object.async.eachSeries (.../node_modules/async/lib/async.js:123:17)
    at .../node_modules/ms-rest-azure/lib/login.js:61:11
    at client.pipeline.error (.../node_modules/ms-rest-azure/lib/subscriptionManagement/operations/tenants.js:93:14)
    ...
```

**Comment by brendandburns** [comment]
Repro details:

use `interactiveLogin({ 'tokenCache': FileTokenCache(...)})`

It works the first time, but throws that exception the second time.

**Comment by amarzavery** [comment]
Interesting. We do not support FileTokenCache. Only in-memory token cache from adal is currently supported. I am not sure if [adal-node](https://github.com/AzureAD/azure-activedirectory-library-for-nodejs) supports FileTokenCache.
- Can you share the code for FileTokenCache?
