### ISSUE TITLE
 The contentDisposition does not work with the createWriteStreamToBlockBlob method option.

### ISSUE THREAD

**Issue by capt-youngkyu** [Azure/azure-sdk-for-node#2243]
```
file.pipe(m).pipe(blobStorage.createWriteStreamToBlockBlob(container, `${random}/${filename}`, {
        contentSettings: { contentType: mimetype, contentDisposition: `attachment; filename="${encodeURIComponent(filename)}"` },
      }, (error) => {
```

I wrote this. But it does not work. I wrote it exactly as written in the document. 

It seems a bug. I would appreciate it if azure team fix it.

**Comment by amarzavery** [comment]
Please file this issue over here https://github.com/azure/azure-storage-node. The storage data plane library has been moved over here.
