### ISSUE TITLE
Content Type not being set for createBlockBlobFromFile or createBlockBlobFromLocalFile in 2.0.0-preview

### ISSUE THREAD

**Issue by wjohnsto** [Azure/azure-sdk-for-node#2244]
When using the SDK to upload a file to blob storage I'm trying to set contentType as follows:

```
storage.createBlockBlobFromFile(container, name, filePath, {
    contentType: 'application/pdf',
    cacheControl: 'no-cache'
}, (error: Error, result: azure.BlobResult, response: azure.WebResponse) => {
    if (isObject(error)) {
        reject(error);
        return;
    }

    resolve(name);
});
```

This used to work in previous versions of the SDK, but it seems that since we updated to 2.0.0-preview it has since stopped working, so now all our blobs are getting `application/octet-stream` as the content type.

Is there some new way to pass in content type, or is there some configuration property I have to set on the blob container?

**Comment by amarzavery** [comment]
@hasonmsft - Can you take a look at this?

**Comment by hasonmsft** [comment]
@XiaoningLiu, could you take a look at this?
