### ISSUE TITLE
Supported Azure Environments has outdated links

### ISSUE THREAD

**Issue by whiskeyjay** [Azure/azure-sdk-for-node#2245]
[azureEnvironments.js](https://github.com/Azure/azure-sdk-for-node/blob/master/runtime/ms-rest-azure/lib/azureEnvironment.js) has a bunch of pre-defined well-known environments. However, the 'portalUrl' values of Azure, Azure China and Azure US Government are still pointing to the 'classic' portals instead of the new portals.

Also using fwlinks as portalUrl values could bring extra burdens on the SDK users when they try to construct a portal deep link URL. Since the portal URL is unlikely to change for at least every a few years, it would make things easier to just use the direct URL instead of a fwlink.

**Comment by amarzavery** [comment]
@whiskeyjay - Thanks for pointing this out. We shall fix this in the upcoming release.
/cc @balajikris

**Comment by amarzavery** [comment]
This has been fixed with version of 2.3.0 of ms-rest-azure
