### ISSUE TITLE
AzureEnvironment type is missing properties for endpoints

### ISSUE THREAD

**Issue by chrmarti** [Azure/azure-sdk-for-node#2247]
This looks like an omission, aren't these properties part of the API?

**Comment by amarzavery** [comment]
Can you provide information about the Environment and the properties that are missing?

**Comment by chrmarti** [comment]
The class declaration in https://github.com/Azure/azure-sdk-for-node/blob/fb1d276bb2dd94e46f64b06db4cbf41cfd918269/runtime/ms-rest-azure/index.d.ts#L167 shows the properties being passed as the parameters object. I assume the class should have the same properties so these can be read. Examples are: `managementEndpointUrl`, `activeDirectoryEndpointUrl`, `activeDirectoryResourceId`.

**Comment by amarzavery** [comment]
Ah I see. Got your point. Will fix that in the upcoming release.
On a side note, in the actual javascript code we are adding some supported environments to the prototype of AzureEnvironment class. https://github.com/Azure/azure-sdk-for-node/blob/master/runtime/ms-rest-azure/lib/azureEnvironment.js#L156 . I was wondering how would I add those supported environments to the class definition in d.ts file.

**Comment by chrmarti** [comment]
I think you can add static properties to do that.

**Comment by amarzavery** [comment]
This has been fixed with 2.3.0 version of ms-rest-azure.
