### ISSUE TITLE
Json Object NOT deserializing

### ISSUE THREAD

**Issue by flauckner** [Azure/azure-sdk-for-node#2250]
I used Autorest (2.2.1) to generate a Node.JS client layer.  When I execute a simple API call, a valid json object is returned.

When the deserialze function is called (client.deserialize), the result object does not contain the properties and valid.  The deserialize calls the deserializeCompositeType function which never seems to read the values of the property.

I have attached the object definition and operator classes.

Here is the json returned from the API Server.

```json5
[
  {
    "CompanyKeywordID": 5,
    "CompanyKeyword": "ASSOC",
    "CompanyKeywordDesc": "Association",
    "ActiveYN": "Y",
    "ModifiedDT": "2016-06-24T10:19:09.820",
    "ModifiedByID": 1,
    "CreatedDT": "2016-06-24T10:19:09.820",
    "CreatedByID": 1
  }
]
```

Thank you for your feed back.

**Comment by flauckner** [comment]
[SampleFiles.zip](https://github.com/Azure/azure-sdk-for-node/files/1235206/SampleFiles.zip)

Sorry, files did not attach

**Comment by amarzavery** [comment]
From what I can see the service is returning an `Array<CompanyKeywordGETReturn>`, whereas the generated sdk is expecting an object of type `CompanyKeywordGETReturn`. 
```javascript
if (statusCode === 200) {
  let parsedResponse = null;
  try {
    parsedResponse = JSON.parse(responseBody);
    result = JSON.parse(responseBody);
    if (parsedResponse !== null && parsedResponse !== undefined) {
 >>>>>> let resultMapper = new client.models['CompanyKeywordGETReturn']().mapper(); //<<<<<<<<<<<<<<<<
      result = client.deserialize(resultMapper, parsedResponse, 'result');
    }
  } catch (error) {
    let deserializationError = new Error(`Error ${error} occurred in deserializing the responseBody - ${responseBody}`);
    deserializationError.request = msRest.stripRequest(httpRequest);
    deserializationError.response = msRest.stripResponse(response);
    return callback(deserializationError);
  }
}
```

Hence deserialization would not work correctly. Please make sure that the swagger spec is a complete and correct representation of what happens on the wire/internet.

If possible, please provide your swagger spec.

**Comment by flauckner** [comment]
Attached is my swagger definition.
Fred Lauckner(713) 471-5873FredLauckner@Yahoo.com


On Saturday, August 19, 2017, 12:16:47 AM CDT, Amar Zavery <notifications@github.com> wrote:


From what I can see the service is returning an Array<CompanyKeywordGETReturn>, whereas the generated sdk is expecting an object of type CompanyKeywordGETReturn.
if (statusCode === 200) {
  let parsedResponse = null;
  try {
    parsedResponse = JSON.parse(responseBody);
    result = JSON.parse(responseBody);
    if (parsedResponse !== null && parsedResponse !== undefined) {
 >>>>>> let resultMapper = new client.models['CompanyKeywordGETReturn']().mapper(); //<<<<<<<<<<<<<<<<
      result = client.deserialize(resultMapper, parsedResponse, 'result');
    }
  } catch (error) {
    let deserializationError = new Error(`Error ${error} occurred in deserializing the responseBody - ${responseBody}`);
    deserializationError.request = msRest.stripRequest(httpRequest);
    deserializationError.response = msRest.stripResponse(response);
    return callback(deserializationError);
  }
}
Hence deserialization would not work correctly. Please make sure that the swagger spec is a complete and correct representation of what happens on the wire/internet.

If possible, please provide your swagger spec.

**Comment by amarzavery** [comment]
closing this as this is resolved.
