### ISSUE TITLE
GraphRbacManagementClient does not return all User information

### ISSUE THREAD

**Issue by MichaelBurgess** [Azure/azure-sdk-for-node#2260]
Hi,

I am retrieving User information via the GraphRbacManagementClient, however I am noticing that the information returned is only a subset of the Graph information available for Users.

We are using 2.0.0-preview, which I can see internally uses azure-graph 2.0.0-preview. We have also tried the latest commit for the azure-sdk-for-node library ("azure": ""github:Azure/azure-sdk-for-node#fc19a0d9a7be1aa705bc891c381374d778211ad9"), which I can see uses azure-graph 2.1.0-preview.

When I retrieve users, either via list:

```
client.users.list()
```

...or get for a single user:

```
client.users.get(userId)
```

...from the graph client, we get the following info:

```
{
  objectId: '<ObjectId>',
  objectType: 'User',
  userPrincipalName: 'joe.bloggs@somedomain.com',
  displayName: 'Joe Bloggs',
  mailNickname: 'joe.bloggs'
}
```

However, if I retrieve user info via the [Graph Explorer](https://graphexplorer.azurewebsites.net/#), it brings back lots more information:

```
  {
    "odata.type": "Microsoft.DirectoryServices.User",
    "objectType": "User",
    "objectId": "<ObjectId>",
    "deletionTimestamp": null,
    "accountEnabled": true,
    "assignedLicenses": [],
    "assignedPlans": [],
    "city": "Somewhere",
    "companyName": null,
    "country": null,
    "creationType": null,
    "department": null,
    "dirSyncEnabled": null,
    "displayName": "Joe Bloggs",
    "employeeId": null,
    "facsimileTelephoneNumber": null,
    "givenName": "Joe",
    "immutableId": null,
    "isCompromised": null,
    "jobTitle": null,
    "lastDirSyncTime": null,
    "mail": null,
    "mailNickname": "joe.bloggs",
    "mobile": null,
    "onPremisesDistinguishedName": null,
    "onPremisesSecurityIdentifier": null,
    "otherMails": [
      "joe.bloggs@somedomain.com"
    ],
    "passwordPolicies": null,
    "passwordProfile": null,
    "physicalDeliveryOfficeName": null,
    "postalCode": "99999",
    "preferredLanguage": null,
    "provisionedPlans": [],
    "provisioningErrors": [],
    "proxyAddresses": [],
    "refreshTokensValidFromDateTime": "2017-01-01T00:00:00Z",
    "showInAddressList": null,
    "signInNames": [],
    "sipProxyAddress": null,
    "state": "ZZ",
    "streetAddress": "123 Some Place",
    "surname": "Bloggs",
    "telephoneNumber": "123456789",
    "usageLocation": null,
    "userIdentities": [],
    "userPrincipalName": "joe.bloggs@somedomain.com",
    "userType": "Member"
  }
```

In particular, I need to be able to identify the `userType` of a user via the SDK so I can determine if the user is a `Member` or a `Guest`.

Please can you advise if it's possible to retrieve all the user information (in particular the `userType`) via the Node.js SDK? If not this SDK, please can you advise how we could retrieve this from Node.js?

**Comment by amarzavery** [comment]
@MichaelBurgess - We are only exposing a small set of properties from the Graph api that are important for resource management scenarios in Azure. You can try using [this library for Graph](https://github.com/microsoftgraph/msgraph-sdk-javascript).
However, in this library we also provide the raw response in the callback or Promise. You can do JSON.parse(response.body) and get the properties you are interested in.
- callback based
```javascript
client.users.get("upn OR objectId", (err, result, request, response) => {
        if (err) {
            return console.log(err);
        }
        console.log("result");
        console.dir(result);
        console.log("actual response");
        console.log(JSON.parse(response.body)); // The actual response body from the 4th parameter in the callback
        return;
    }); 
```
- promise based
```javascript
client.users.getWithHttpOperationResponse("upn OR objectId").then((operationRes) => {
//operationRes contains the actual request, raw response and the deserialized result
  console.log(JSON.parse(operationRes.response.body));
}).catch((err) => { 
  console.log(err); 
});
```

Hope this helps.

**Comment by MichaelBurgess** [comment]
@amarzavery - thank you, I am able to get the information I need from the response object. Good tip to know!

**Comment by amarzavery** [comment]
@MicahelBurgess - Please use the new version of azure-graph (2.2.0). It contains the relevantIfo you need for AD User. You do not need to use the raw response object.
