### ISSUE TITLE
In azureEnvironment.js please update the activeDirectoryEndpointUrl

### ISSUE THREAD

**Issue by milope** [Azure/azure-sdk-for-node#2262]
Hello Team,

I've been writing samples for Azure Gov in all SDK languages for our reference and noticed the activeDirectoryEndpointUrl is "login.microsoftonline.com" while this works fine for now, the following document https://docs.microsoft.com/en-us/azure/azure-government/documentation-government-developer-guide#endpoint-mapping recommends changing to login.microsoftonline.us. At the very least it uses login-us.microsoftonline.com as well.

**Comment by amarzavery** [comment]
Closing this as the issue has been fixed with new version of the runtime.
