### ISSUE TITLE
No listing of valid timezones for windowsProfile

### ISSUE THREAD

**Issue by mrled** [Azure/azure-sdk-for-node#2266]
I have a template that deploys, among other things, a Windows VM, and I want to set the timezone in the template. However, the documentation is missing a list of valid values.

I found [documentation for the windowsConfiguration object](http://azure.github.io/azure-sdk-for-node/azure-arm-compute/latest/models_windowsConfiguration.js.html), but the only thing it says about the `timeZone` property is: `@member {string} [timeZone] The time zone of the VM`.

Is there a list of valid values somewhere? The value I tried was `CDT`, but that failed with an error like `The value of parameter windowsConfiguration.timeZone is invalid`.

Where can I find a complete list of acceptable values? Could this be added to the documentation? 

My apologies if this is the wrong place to report this error. I looked in several places, including official Azure template documentation on docs.microsoft.com, but didn't found an enumeration of values anywhere. If you can tell me a better place to report this, I'll happily open an issue there.

Thanks

**Comment by amarzavery** [comment]
You have filed an issue at the right place. The sdk is auto generated from a [swagger spec](https://github.com/Azure/azure-rest-api-specs/blob/current/specification/compute/resource-manager/Microsoft.Compute/2017-03-30/compute.json#L4246). The latest version of the spec had an updated description and the sdk reflects that. however, the documentation site was not updated. We shall fix that.
This is the updated description that can get you unblocked.
> "Specifies the time zone of the virtual machine. e.g. \"Pacific Standard Time\""

**Comment by amarzavery** [comment]
This REST API documentation can also help https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/virtualmachines-create-or-update

**Comment by mrled** [comment]
Thank you - that is very helpful.

Is there also a full enumeration of allowed values somewhere? I have another program that invokes the Azure API to deploy the template, and my goal is to be able to set the timezone of the new Azure VM to be the same as the timezone on the host deploying it. (Kinda weird, perhaps, but it makes sense in my use case.) Of particular concern is that my program is designed to run on multiple operating systems, not just Windows, so I'm trying to figure out how I can convert a timezone name from the IANA format that Linux uses to the format that Windows uses, and a definitive enumeration of permitted values would be very helpful.

In particular, I've been having trouble with DST values. For instance, right now, my timezone is observing DST, and on my Windows machine `[System.TimeZoneInfo]::Local.DaylightName` returns `Central Daylight Time`, but that doesn't seem to be a valid value in the ARM template.

**Comment by amarzavery** [comment]
I understand your problem. However I am not sure if there is any enumeration available for all the timezone values. The example in the previous comment gives you an idea of what the API expects.

Looping in folks from the Compute team.
@hyonholee @huangpf @singhkays - Can one of you please help over here?

**Comment by huangpf** [comment]
@mrled @amarzavery
I'm guessing it's probably difficult to maintain to inject all Windows system time zone strings into the contract/specification, rather than directly refer to what Windows system takes as the norm. Here are some PS output that may help:
```
PS C:\windows\system32> [System.TimeZoneInfo]::GetSystemTimeZones()|?{$_.Id -like "Pacific*"}|select -ExpandProperty Id
Pacific Standard Time (Mexico)
Pacific Standard Time
Pacific SA Standard Time

PS C:\windows\system32> [System.TimeZoneInfo]::GetSystemTimeZones()|select -ExpandProperty Id
Dateline Standard Time
UTC-11
Aleutian Standard Time
Hawaiian Standard Time
Marquesas Standard Time
Alaskan Standard Time
...
```
