### ISSUE TITLE
Cannot specify oauth2AllowImplicitFlow option when calling create or patch for Azure Graph

### ISSUE THREAD

**Issue by ppathan** [Azure/azure-sdk-for-node#2267]
There is no way to currently specify **oauth2AllowImplicitFlow** property when creating application or updating it when calling through GraphRbacManagementClient. The properyty can be added to [ApplicationCreateParameters.js](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/graphManagement/lib/models/applicationCreateParameters.js) and [ApplicationUpdateParameters](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/graphManagement/lib/models/applicationUpdateParameters.js) and then the create method will attach it to the body before making the request.

**Comment by amarzavery** [comment]
I am not sure if the service supports this. Please open an issue in the https://github.com/azure/azure-rest-api-specs repo as all the sdks are autogenerated from the specs in that repo. You can reference this issue over there.

**Comment by amarzavery** [comment]
closing this as we released a new version with this and other updates.
