### ISSUE TITLE
TypeError: function createARMStorageManagementClient() does not exist

### ISSUE THREAD

**Issue by ionSolutions** [Azure/azure-sdk-for-node#2273]
Hey guys,

i tried to copy your example from https://github.com/Azure/azure-sdk-for-node/blob/master/Documentation/Authentication.md and could not run this, because i get the following error
`TypeError: Azure.createARMStorageManagementClient is not a function
    at MsRest.loginWithUsernamePassword (c:\ION Solutions\shasha\Testing-Api\app\services\azure.server.js:12:40)
    at c:\ION Solutions\shasha\Testing-Api\node_modules\ms-rest-azure\lib\login.js:325:14
    at c:\ION Solutions\shasha\Testing-Api\node_modules\ms-rest-azure\lib\login.js:105:5
    at c:\ION Solutions\shasha\Testing-Api\node_modules\ms-rest-azure\node_modules\async\lib\async.js:130:21
    at c:\ION Solutions\shasha\Testing-Api\node_modules\ms-rest-azure\lib\login.js:102:14
    at client.pipeline (c:\ION Solutions\shasha\Testing-Api\node_modules\ms-rest-azure\lib\subscriptionManagement\operations\subscriptions.js:368:14)
    at retryCallback (c:\ION Solutions\shasha\Testing-Api\node_modules\ms-rest\lib\filters\systemErrorRetryPolicyFilter.js:89:9)
    at retryCallback (c:\ION Solutions\shasha\Testing-Api\node_modules\ms-rest\lib\filters\exponentialRetryPolicyFilter.js:140:9)
    at handleRedirect (c:\ION Solutions\shasha\Testing-Api\node_modules\ms-rest\lib\filters\redirectFilter.js:39:9)
    at c:\ION Solutions\shasha\Testing-Api\node_modules\ms-rest\lib\filters\signingFilter.js:19:18
    at c:\ION Solutions\shasha\Testing-Api\node_modules\ms-rest-azure\lib\credentials\deviceTokenCredentials.js:102:23
    at c:\ION Solutions\shasha\Testing-Api\node_modules\ms-rest-azure\lib\credentials\deviceTokenCredentials.js:88:23
    at c:\ION Solutions\shasha\Testing-Api\node_modules\adal-node\lib\token-request.js:150:11
    at TokenRequest.<anonymous> (c:\ION Solutions\shasha\Testing-Api\node_modules\adal-node\lib\token-request.js:524:5)
    at c:\ION Solutions\shasha\Testing-Api\node_modules\adal-node\lib\token-request.js:147:20
    at c:\ION Solutions\shasha\Testing-Api\node_modules\adal-node\lib\cache-driver.js:359:7`

After some analysis, i found out that the function `Azure.createARMStorageManagementClient` really doesn't exist - the correct function would be `Azure.createASMStorageManagementClient(credentials, subscription_id);`

Seems to be a typo in https://github.com/Azure/azure-sdk-for-node/blob/master/Documentation/Authentication.md  

Hopefully, this can help somebody out :)

Br,
Edvin

**Comment by amarzavery** [comment]
Thanks Edvin for pointing this. We replaced `createARMStorageManagementClient` with `createStorageManagementClient`. create**ASM**StorageManagementClient will target V1 version of the Azure API. It is the old way of doing things. ARM (Azure Resource Manager) is the defacto standard. 
We will update the sample. `Azure.createStorageManagementClient` should work.

**Comment by amarzavery** [comment]
https://github.com/Azure/azure-sdk-for-node/blob/master/lib/azure.js#L998
