### ISSUE TITLE
Read the Docs link is 404

### ISSUE THREAD

**Issue by mfowlewebs** [Azure/azure-sdk-for-node#2283]
The read the docs link [on your readme](https://github.com/Azure/azure-sdk-for-node#need-help) is 404.

**Comment by amarzavery** [comment]
Thanks for pointing that. Here is the correct link https://docs.microsoft.com/en-us/nodejs/api/overview/azure/?view=azure-node-2.0.0. Will update that

**Comment by amarzavery** [comment]
The documentation may not be upto date. We just release 2.2.0-preview version of the azure package and are in the process of updating the documentation.
 Using vscode as the IDE for development provides good experience. All the packages ship with typescript type definitions. This should provide good intellisense and you can also develop your app in TypeScript.

**Comment by mfowlewebs** [comment]
I'm afraid VScode is not really an option for me at the moment.

Just trying to find easy stuff in the current docs is really hard- I can't find anywhere that mentions what I can do with a [SQLManagementClient](https://docs.microsoft.com/en-us/nodejs/api/azure-arm-sql/sqlmanagementclient?view=azure-node-2.0.0). Based off the top level docs I see I can [call .server.list() on it](https://docs.microsoft.com/en-us/nodejs/api/overview/azure/sql?view=azure-node-2.0.0#management-package) but I don't see .server in the docs and I haven't found any object where .list() might be.

Now that I have a list of servers, I'd like a list of databases on each server. Then I want to be able to pause/resume each server. I hope these online docs improve to where I can figure out what I need to do, short of going into a repl & tab-completeing my way forwards.

**Comment by amarzavery** [comment]
@mfowlewebs - I agree with you. Will come up with a better solution for documentation. For now to unblock you, I would like to give you some tips. 
- If you take a look at the sql management client or the code inside `node_modules/azure-arm-sql`, you will find the [client inside the lib folder](https://github.com/Azure/azure-sdk-for-node/tree/master/lib/services/sqlManagement2/lib), all the operations inside [`lib/operations`](https://github.com/Azure/azure-sdk-for-node/tree/master/lib/services/sqlManagement2/lib/operations) folder and all the models inside [`lib/models`](https://github.com/Azure/azure-sdk-for-node/tree/master/lib/services/sqlManagement2/lib/models) folder.
- The instantiated client also has all the models on it: [`client.models`](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/sqlManagement2/lib/sqlManagementClient.js#L111)
- [The instantiated client will have all the logical operation groups like servers, databases, etc. as properties of the client](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/sqlManagement2/lib/sqlManagementClient.js#L74-L110).
- The operations on the servers can be found inside`client.servers`.list()/createOrUpdate()/get, etc. so on and so forth.

That being said we will definitely work on improving the documentation. Hope the above tips help for now.
