### ISSUE TITLE
What happened to the documentation?

### ISSUE THREAD

**Issue by ztrange** [Azure/azure-sdk-for-node#2291]
I used to use the documentation at 
https://azure.github.io/azure-sdk-for-node/azure-sb/latest/global.html

But it is not there anymore. Was it moved or it is no longer available?

Edited: typo

**Comment by tony-gutierrez** [comment]
Our MS reps said they would get back to us on this about 2 weeks ago. No movement.

**Comment by tony-gutierrez** [comment]
https://github.com/Azure/azure-sdk-for-node/issues/2133

**Comment by watt** [comment]
It seems absolutely unreal that this could be broken for two weeks. I *think* the replacement is supposed to be this link?

https://docs.microsoft.com/en-us/javascript/api/overview/azure/?view=azure-node-2.2.0

**Comment by tony-gutierrez** [comment]
That is just the documentation for the management parts of the sdk (create a service bus as opposed to INTERACT with a service bus). MS current suggestion to me via twitter was to continue to use the way back archive. See: https://stackoverflow.com/questions/47082160/where-is-the-azure-notification-hubs-node-sdk-usage-documentation

**Comment by amarzavery** [comment]
@watt @tony-gutierrez @ztrange - We are extremely sorry for the inconvenience. We have restored the http://azure.github.io/azure-sdk-for-node/ repo.

**Comment by Squiggle** [comment]
@amarzavery Again, I don't see any mention of the NotificationHubService or equivalent - the library we need to list _actual device registrations_ in a notification hub.

All the documentation which exists - even that which has just been restored - only describes how to manage the hubs, not how to list the devices registered therein. This is *crucial* functionality for development. Without this we're basically working blind.

Are you able to advise?

**Comment by ankurkul** [comment]
@Squiggle : You can use the [listRegistrations ](http://azure.github.io/azure-sdk-for-node/azure-sb/latest/NotificationHubService.html#listRegistrations) API to list registrations in a hub. For nodejs sdk usage for notification Hubs, you may refer to our documentation [here](https://docs.microsoft.com/en-us/azure/notification-hubs/notification-hubs-nodejs-push-notification-tutorial). 

Moreover, you can find some samples in our github repo [here](https://github.com/Azure/azure-sdk-for-node/blob/master/test/services/serviceBus/apnsservice-registrations-tests.js).

If you still have questions, leave a comment here and we would be happy to answer them.

**Comment by Squiggle** [comment]
Excellent!

It should be noted that when browsing the documentation, it is almost impossible to locate. I didn't know that I needed to look at `azure-sb` to find the NotificationHubService documentation. Thanks for clarifying this.

**Comment by amarzavery** [comment]
@ramya-rao-a - Closing this issue for now. The documentation for the package has been restored at http://azure.github.io/azure-sdk-for-node/azure-sb/latest/

Whenever you decide to re-implement the CRUD on ATOM based service bus HTTP APIs, you can make sure that the documentation for thew package is up to date.
