### ISSUE TITLE
MSI: support appservice(web app, function app)

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-sdk-for-node#2292]
Please check out the [document](https://docs.microsoft.com/en-us/azure/app-service/app-service-managed-service-identity)
In case it helps, I tested out with [a sample](https://github.com/yugangw-msft/azure-site-test/tree/msi) in my repository.
I suggest SDK `MSITokenCredentials` can detect the `MSI_xxx` environment variable, then does the heavy lifting to acquire the token.
(To enable MSI on webapps, for now, do it in portal. CLI will expose the support by the end of October)

//cc: @amarzavery, @mayurid, @skwan

**Comment by yugangw-msft** [comment]
Linking to the Python's counter part with more discussions: https://github.com/Azure/msrestazure-for-python/issues/50

**Comment by yugangw-msft** [comment]
@amarzavery, could you please prioritize the work and get it released by the end of this year?

**Comment by gunzip** [comment]
I dig this. 

for example, the following code hardcode the MSI_ENDPOINT as 
`http://localhost:${this.port}/oauth2/token`;

https://github.com/Azure/azure-sdk-for-node/blob/3121a07c98b34cac22942f7403bcaaa0002dd44f/runtime/ms-rest-azure/lib/credentials/msiTokenCredentials.js#L44

but in my current App Service the endpoint is dynamic and contained in the
MSI_ENDPOINT variable (ie. MSI_ENDPOINT=http://127.0.0.1:41335/MSI/token/).
Note that the MSI_ENDPOINT environment variable contains the port and the path

**Comment by amarzavery** [comment]
@gunzip - I still have to add support for MSI tokens for an App Service. The code that we have currently supports MSI token for a VM. The internal logic for VM and App Service is completely different. Give me a day or two to implement and test this e2e.

**Comment by yugangw-msft** [comment]
@amarzavery, thanks! Please incorporate the detection logic and ensure the `MSITokenCredentials` can work for both VM and AppService

**Comment by amarzavery** [comment]
@gunzip - Please install new version of `"ms-rest-azure": "^2.4.2"`  and use
```javascript
const msRestAzure = require("ms-rest-azure");
// make sure to set the following env variables or ensure that they are set some how
// https://docs.microsoft.com/en-us/azure/app-service/app-service-managed-service-identity
// set MSI_ENDPOINT=something
//set MSI_SECRET=something
msRestAzure.loginWithAppServiceMSI().then((creds) => {
  console.log(creds);
}).catch((err) => {
console.log(creds);
})

**Comment by gunzip** [comment]
I'm getting the following error with typescript 2.6.1:

```
tsc --outDir build
node_modules/ms-rest-azure/index.d.ts(525,15): error TS1039: Initializers are not allowed in ambient contexts.
```

it looks it does not like this line:

`  resource? = "https://management.azure.com/";
`

**Comment by jdneo** [comment]
I got the same error as @gunzip said

**Comment by amarzavery** [comment]
Thanks for reporting this. #2315 fixes this. Please install `2.4.3` version of `ms-rest-azure`.

**Comment by gunzip** [comment]
still does not work, it looks i needs one more slash after token:

i guess

`http://127.0.0.1:41921/MSI/token?resource=https://management.azure.com/&api-version=2017-09-01`

should be

`http://127.0.0.1:41921/MSI/token/?resource=https://management.azure.com/&api-version=2017-09-01`

**Comment by amarzavery** [comment]
interesting. Looks like the service is implemented to accept a malformed uri.

**Comment by amarzavery** [comment]
@gunzip - Can you modify [this line](https://github.com/Azure/azure-sdk-for-node/blob/master/runtime/ms-rest-azure/lib/credentials/msiAppServiceTokenCredentials.js#L67) with this code.
```javascript
const endpoint = this.msiEndpoint.endsWith('/') ? this.msiEndpoint : `${this.msiEndpoint}/`;
```

**Comment by amarzavery** [comment]
I tested this fix on the webapp and it is working as expected.

**Comment by amarzavery** [comment]
Sorry for the inconvenience. `"ms-rest-azure": "2.4.4"`, works as expected.

**Comment by gunzip** [comment]
works for me, thank you :)
