### ISSUE TITLE
Most properties in the "azure-arm-website" data models are optional

### ISSUE THREAD

**Issue by nturinski** [Azure/azure-sdk-for-node#2293]
Hi, I'm on the dev team working on VS Code Azure App Service extension (linked below):
https://github.com/Microsoft/vscode-azureappservice

While using the azure-arm-website API, we have run into the issue that most properties are optional which causes our TS linter to throw compile time errors.  Because the properties can be either strings | undefined, TSLint forces validation checks on each individual property of a data model.

Is there a way that the API could guarantee some properties, such as site.name, site.resourceGroup, and other properties that are unlikely to be undefined?

**Comment by nturinski** [comment]
![image](https://user-images.githubusercontent.com/5290572/31363894-856fd47a-ad16-11e7-8de1-b2be7eda3526.png)

**Comment by amarzavery** [comment]
If the swagger spec does not describe it accurately then we cannot do much in the sdk that gets generated from it. https://github.com/Azure/azure-rest-api-specs/blob/current/specification/web/resource-manager/Microsoft.Web/2016-08-01/WebApps.json#L19532
@naveedaz - Can you please respond?

**Comment by amarzavery** [comment]
There is a proposal in typescript for optional property checking with the '?' operator. https://github.com/Microsoft/TypeScript/issues/16. However, with Typescript 2.0 there is a [non-null assertion operator](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#non-null-assertion-operator) and the [expression operator](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#expression-operators) that may be of some help . Did you have a chance to take a look at that?

**Comment by amarzavery** [comment]
@nturinski - Did the above comment help?

**Comment by nturinski** [comment]
@amarzavery - The non-null assertion will get the tslinter to stop yelling at us so it's a good enough work around.  Thank you!
