### ISSUE TITLE
Ability to filter results from a VM API call 

### ISSUE THREAD

**Issue by sanjeevsudarshan** [Azure/azure-sdk-for-node#2294]
Hi,
I'm trying to filter the output of the List VM's API call, I was not able to do that, and it did not look like there is support for the "top" and "filter" flags in azure-arm-compute VM API.

https://docs.microsoft.com/en-us/nodejs/api/azure-arm-compute/virtualmachines?view=azure-node-2.2.0&viewFallbackFrom=azure-node-2.0.0#azure_arm_compute_VirtualMachines_list

Is there any way to do that?.

**Comment by amarzavery** [comment]
Yes, it looks like the API does not support that feature. Here is the corresponding swagger spec for that operation from which the SDK was generated https://github.com/Azure/azure-rest-api-specs/blob/current/specification/compute/resource-manager/Microsoft.Compute/2017-03-30/compute.json. It does not describe top, filter query parameters.

@hyonholee  @huangpf - Can you confirm?

**Comment by huangpf** [comment]
@amarzavery It's correct that VM list doesn't have those query parameters.

**Comment by amarzavery** [comment]
Closing this issue since the service does not support this.
