### ISSUE TITLE
Dependency on momentjs

### ISSUE THREAD

**Issue by timswinkels** [Azure/azure-sdk-for-node#2295]
The [dependency on moment](https://github.com/Azure/azure-sdk-for-node/blob/master/package.json#L122) should be pinned at 2.18.x. Currently package.json is using a `^`, which allows updating to 2.19.X. This version [causes webpack to explode](https://github.com/moment/moment/issues/4216) when bundling.

Please consider registering moment like `"moment": "~2.18.1"` in package.json. So the 2.19.x version is being avoided.

**Comment by amarzavery** [comment]
Thanks for letting us know. We are working on releasing a quick fix with 2.2.1-preview for the rollup package "azure" and some other packages that have a direct dependency on moment.

**Comment by amarzavery** [comment]
https://github.com/Azure/azure-sdk-for-node/pull/2296

**Comment by amarzavery** [comment]
This has been fixed with 2.2.1-preview version that was published right now. https://www.npmjs.com/package/azure
