### ISSUE TITLE
Changing property 'customData' is not allowed

### ISSUE THREAD

**Issue by golh30** [Azure/azure-sdk-for-node#2297]
Why am I not able to update customData of Virtual Machine in Azure?
When I try to do so with using computeClient.virtualMachines.createOrUpdate method with 
var vmParameters = {
            osProfile: {
                computerName: this._vmName,
                adminUsername: this._adminUserName,
                adminPassword: this._adminPassword,
                **customData: "Updated Custom Data"**
            }
}
results into error saying "**Changing property 'customData' is not allowed**".

**Comment by amarzavery** [comment]
Intresting. I don't see this being marked as a readonly property in the [spec](https://github.com/Azure/azure-rest-api-specs/blob/current/specification/compute/resource-manager/Microsoft.Compute/2017-03-30/compute.json#L4554). So update should have worked.
Can you please provide the actual request and the response snapshot. If this error is being given by the server then the error object should have the request and response property.
Can you please print 
- `console.dir(error, {depth: null})`

Please fill free to camouflage any sensitive data with ***

**Comment by golh30** [comment]
Please find API response as below.

"{\"code\":6,\"description\":{\"statusCode\":409,\"request\"
:{\"rawResponse\":false,\"queryString\":{},\"url\":\"https:/
/management.azure.com/subscriptions/***/resourceGroups/***/
providers/Microsoft.Compute/virtualMachines/***?api-version=2017-03-30\
<https://management.azure.com/subscriptions/e81e35d6-2a68-458f-be07-0018aafed895/resourceGroups/chromotifVirtualMachineGroup8316/providers/Microsoft.Compute/virtualMachines/chromotifVM8316?api-version=2017-03-30%5C>
",\"method\":\"PUT\",\"headers\":{\"Content-Type\":\"application/json;
charset=utf-8\",\"x-ms-client-request-id\":\"***\",\"accept-
language\":\"en-US\",\"user-agent\":\"Node/v6.9.5 (x64-Windows_NT-6.3.9600)
ms-rest/2.2.3 ms-rest-azure/2.4.1 azure-arm-compute/4.0.0
Azure-SDK-For-Node\"},\"body\":\"{\\\"location\\\":\\\"home\
\\",\\\"properties\\\":{\\\"osProfile\\\":{\\\"computerName\
\\":\\\"****\\\",\\\"adminUsername\\\":\\\"****\\\"
,\\\"adminPassword\\\":\\\"****\\\",\\\"customData\\\":\\\"\
\\"}}}\"},\"response\":{\"body\":\"{\\r\\n  \\\"error\\\": {\\r\\n
\\\"code\\\": \\\"PropertyChangeNotAllowed\\\",\\r\\n    \\\"target\\\":
\\\"customData\\\",\\r\\n    \\\"message\\\": \\\"Changing property
'customData' is not allowed.\\\"\\r\\n  }\\r\\n}\",\"headers\":{\"cach
e-control\":\"no-cache\",\"pragma\":\"no-cache\",\"content-
length\":\"158\",\"content-type\":\"application/json;
charset=utf-8\",\"expires\":\"-1\",\"strict-transport-security\":\"max-age=31536000;
includeSubDomains\",\"x-ms-served-by\":\"*****\",\"x-ms-
request-id\":\"*****\",\"server\":\"Microsoft-HTTPAPI/
2.0\",\"x-ms-ratelimit-remaining-subscription-writes\
":\"***\",\"x-ms-correlation-request-id\":\"***\",\"x-ms-ro
uting-request-id\":\"WESTINDIA:*****\",\"date\":\"Thu, 12 Oct 2017 06:57:52
GMT\",\"connection\":\"close\"},\"statusCode\":409},\"code\":\"
*PropertyChangeNotAllowed*\",\"body\":{\"code\":\"PropertyC
hangeNotAllowed\",\"message\":\"*Changing property 'customData' is not
allowed.*\",\"target\":\"customData\"}}}"


On Oct 12, 2017 11:27 PM, "Amar Zavery" <notifications@github.com> wrote:

Intresting. I don't see this being marked as a readonly property in the spec
<https://github.com/Azure/azure-rest-api-specs/blob/current/specification/compute/resource-manager/Microsoft.Compute/2017-03-30/compute.json#L4554>.
So update should have worked.
Can you please provide the actual request and the response snapshot. If
this error is being given by the server then the error object should have
the request and response property.
Can you please print

   - console.dir(error, {depth: null})

Please fill free to camouflage any sensitive data with ***

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Azure/azure-sdk-for-node/issues/2297#issuecomment-336216454>,
or mute the thread

**Comment by amarzavery** [comment]
@golh30 - Thanks for providing the info. Why have you set the location property in request body as "home" ?
@huangpf, @hyonholee  - Irrespective of the above question that I have asked can you provide some insight into why customData property cannot be set? As you can see in the comment I made above, customData is not marked as readOnly. So why would the service give a 409 with the above error message?

**Comment by huangpf** [comment]
I don't have the trace, but what I remember is that this field used to be editable after creation, but in the not so recent release, it became not editable after creation.

Can Swagger spec handle this type of specification in the uber ```CreateOrUpdate``` API?

**Comment by amarzavery** [comment]
Swagger does not have a mechanism to say that something is createOnly. For example - location cannot be changed once it is created. There is a proposal for x-ms-mutability extension. However, Autorest does not understand this as of now. Moreover, the sdk does not have context in the createOrUpdate() method. We do not know whether the resource already exists. The generator would have to be modified to do a GET and if the resource exists then it is an update else it is a create. It can be more complex when coupled with etags.

For now the best way to reflect this info is to provide this info in the description that it is create only, if that is indeed the case.

**Comment by panmanphil** [comment]
I just ran into this with a template generated by acs-engine for kubernetes virtual machines. Basically it means you can only run the generated template once, not really a tenable solution. The generated part was part of the kubernetes startup.

**Comment by jurajsucik** [comment]
I'm facing the same issue with the checkpoint template from Azure Marketplace. This is the error I get after the template deployment:
"error": {
    "code": "PropertyChangeNotAllowed",
    "message": "Changing property 'customData' is not allowed.",
    "target": "customData"
  }

**Comment by jontreynes** [comment]
same

**Comment by amarzavery** [comment]
This is a service issue and has nothing to do with the sdk.
