### ISSUE TITLE
Data Lake Store "Open" does not return file contents

### ISSUE THREAD

**Issue by victoriau** [Azure/azure-sdk-for-node#2300]
When trying to read from a file in the data lake after creating a new DataLakeStoreFileSystemClient 
when you call the open function on a file an object is returned that contains request and headers but does not contain the actual contents of the file from the data lake.

**Comment by amarzavery** [comment]
can you provide the following info
- what version of the package are you using?
- can you provide a code snippet of the problematic call?
- can you also provide the result?

This will help us help you.

**Comment by victoriau** [comment]
**Version**: azure-arm-datalake-store version 3.10.3 
**Code**: 
msRestAzure.loginWithUsernamePassword(removed, removed, function (err, credentials) {
    var accountName = 'removed';
    var pathToEnumerate = '/2Enhance/ENT/SAPBW/MasterData/BUS_AREA.tsv';
    var acccountClient = new adlsManagement.DataLakeStoreAccountClient(credentials, removed);
    var filesystemClient = new adlsManagement.DataLakeStoreFileSystemClient(credentials);
    filesystemClient.fileSystem.open(accountName, pathToEnumerate, { length: 1000 }, function (err, result, request, response) {
        if (err) {
            console.log(err);
        } else {
            //console.log('result is: ' + util.inspect(result, { depth: 1 }));
            console.log(result.toJSON());
        }
    });
});

**Result**: 
{ statusCode: 200,
  body: undefined,
  headers: 
   { 'cache-control': 'no-cache, no-cache, no-store, max-age=0',
     pragma: 'no-cache',
     'transfer-encoding': 'chunked',
     'content-type': 'application/octet-stream',
     expires: '-1',
     'x-ms-request-id': '13635f27-e237-4049-aff3-46fecc0d4c2a',
     'x-ms-webhdfs-version': '17.04.22.00',
     status: '0x0',
     'x-content-type-options': 'nosniff',
     'strict-transport-security': 'max-age=15724800; includeSubDomains',
     date: 'Mon, 23 Oct 2017 18:14:22 GMT',
     connection: 'close' },
  request: 
   { uri: 
      Url {
        protocol: 'https:',
        slashes: true,
        auth: null,
        host: 'removed.azuredatalakestore.net',
        port: 443,
        hostname: 'removed.azuredatalakestore.net',
        hash: null,
        search: '?length=1000&read=true&op=OPEN&api-version=2016-11-01',
        query: 'length=1000&read=true&op=OPEN&api-version=2016-11-01',
        pathname: '/webhdfs/v1/%2F2Enhance%2FENT%2FSAPBW%2FMasterData%2FBUS_AREA.tsv',
        path: '/webhdfs/v1/%2F2Enhance%2FENT%2FSAPBW%2FMasterData%2FBUS_AREA.tsv?length=1000&read=true&op=OPEN&api-version=2016-11-01',
        href: 'https://removed.azuredatalakestore.net/webhdfs/v1/%2F2Enhance%2FENT%2FSAPBW%2FMasterData%2FBUS_AREA.tsv?length=1000&read=true&op=OPEN&api-version=2016-11-01' },
     method: 'GET',
     headers: 
      { 'Content-Type': 'application/json; charset=utf-8',
        'x-ms-client-request-id': 'a0aa3f1f-ae61-4a79-b499-35926349a35b',
        'accept-language': 'en-US',
        authorization: 'Bearer removed' } } } 

**Notes:**
**used "removed" to replace sensitive pieces of code and response 
You can see the "body" property of the response object is undefined, and it is set that way in  your source code.

**Comment by amarzavery** [comment]
@victoriau - Thanks for providing the code snippet and the relevant info. That helped me debug the issue. There could be two cases:
1. Please make sure that the content is actually present in the file from which you are trying to read. You can take a look at that file in the portal (https://ms.portal.azure.com/#blade/Microsoft_Azure_DataLakeStore/WebHdfsFolderBlade/endpoint/**Your_account_name**.azuredatalakestore.net/path/%2F). If the content is **not present** then please **add some test content**.
2. Now that the content is present then we should be able to read it. The content is returned back as  a stream. Hence we need to convert the stream into a buffer and then stringify it. I wrote a simple function named `readStreamToBuffer` to do that. I have it in the following test snippet that worked as expected.

```javascript
var msRestAzure = require("ms-rest-azure");
var adlsManagement = require("./lib/dataLakeStore");

// This function will read the stream and convert it to a buffer.
function readStreamToBuffer (strm, callback) {
  var bufs = [];
  strm.on('data', function (d) {
    bufs.push(d);
  });
  strm.on('end', function () {
    callback(null, Buffer.concat(bufs));
  });
}

msRestAzure.interactiveLogin(function (err, credentials) {
  var accountName = 'testacfoo';
  var pathToEnumerate = '/2Enhance/ENT/SAPBW/MasterData/BUS_AREA.tsv';
  var filesystemClient = new adlsManagement.DataLakeStoreFileSystemClient(credentials);
  filesystemClient.fileSystem.open(accountName, pathToEnumerate, { length: 1000 }, function (err, result, request, response) {
    if (err) {
      console.log(err);
    } else {
      readStreamToBuffer(result, function (err, buff) {
        if (err) return console.log(err);
        console.log(buff.toString());
      });
    }
  });
});
```

The output is:
```
foo bar foo fooo fooooooo fooooooooo fooooo fooooo foooo
```
which was the content that I had added to the file.

Let me know if you have any questions.

**Comment by victoriau** [comment]
This works - I appreciate your help. You may consider adding an example of how to read to your documentation to help people use this. Thank you!
