### ISSUE TITLE
linkedServices.createOrUpdate() what is the format of the linkedService parameter?

### ISSUE THREAD

**Issue by kitsonswannff** [Azure/azure-sdk-for-node#2301]
Hi There,

I'm trying to create a Data Factory with an Amazon Redshift linked service. I can successfully create the data factory, but can't get the linked services working. 

I'm calling the `dataFactoryManagement.linkedServices.createOrUpdate()` method, but I cannot seem to get the right format for the `linkedService` parameter. It says it's an object. I've looked at the REST api documentation which seems to indicate this is the format:

```
{
    "name": "AmazonRedshiftLinkedService",
    "properties":
    {
        "type": "AmazonRedshift",
        "typeProperties":
        {
            "server": "< The IP address or host name of the Amazon Redshift server >",
            "port": <The number of the TCP port that the Amazon Redshift server uses to listen for client connections.>,
            "database": "<The database name of the Amazon Redshift database>",
            "username": "<username>",
            "password": "<password>"
        }
    }
}
```

I've created a function that calls this method like so

```
function createRedshiftLinkedService(callback) {

  var linkedServiceName = "SourceRedshiftLinkedService";

  var redshiftLinkedServiceProperties =  {
      properties: {
        type: "AmazonRedshift",
        typeProperties: {
            server: redshiftServer,
            port: redshiftServerPort,
            database: redshiftDatabase,
            username: redshiftUserName,
            password: redshiftPassword
        }
    }
  };

  console.log(redshiftLinkedServiceProperties);

  return dfClient.linkedServices.createOrUpdate(resourceGroupName, dataFactoryName, linkedServiceName, redshiftLinkedServiceProperties, callback);

}
```

When it runs I get the following error:

`Error: Error "server" cannot be null or undefined in "linkedService.properties".`

I've tried changing the format and moving the `server` variable to the next level up. I then complains that there's no `server` variable under `typeProperties`. If I put it in both places, it says `typeProperties.server should be an object`

Can you give me any guidance on the proper format to provide the linkedService parameter? Ideally, could you give a minimum example of actually creating a data factory using the node.js sdk, including the linked services. The only example in the docs just lists the data factories, which isn't helpful.

Thanks.

**Comment by amarzavery** [comment]
Hi @kitsonswannff - Thanks for reporting the issue. There is a bug in serialization in the sdk.

To give you some context, we autogenerate our sdks from an Open API specification for a given service. The [spec](https://github.com/Azure/azure-rest-api-specs/blob/current/specification/datafactory/resource-manager/Microsoft.DataFactory/2017-09-01-preview/entityTypes/LinkedService.json#L579) says that (for example) the "server" property is of type "object". However, in the description it is mentioned that this can either be a string or some expression object that returns a string. 

The spec conforms to [2.0 version of openapi specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md) which does not support "oneOf", "anyOf". Hence it is difficult to model that in swagger.

We create a mapper for a given model based on the definition in the spec. The mapper says that this is of type "object". Hence the check `typeof value !== "object"` fails and the sdk throws an error. Since it is expecting an object over there. Ideally what we should be checking is that `if (value === null || value === undefined)` then throw. This will ensure that something is present when the type is specified as "object". 
For now to be unblocked, please modify the [line that checks whether the type is an object](https://github.com/Azure/azure-sdk-for-node/blob/master/runtime/ms-rest/lib/serialization.js#L270) in `node_modules/ms-rest/lib/serialization.js` to 

```javascript
if (value === null || value === undefined) {    // <<<<<<<<<<<<<<<<<<
 throw new Error(`${objectName} must be of type object.`);
}
```

> I modified this locally in the runtime and was able to create a linkedService successfully.

Here is my sample script in **TypeScript** that gives good intellisense and type validation. For simplicity I have assumed that the datafactory account has already been created. I am focusing on creating the linked service.

```javascript
import * as msRestAzure from "ms-rest-azure";
import DataFactoryManagementClient = require("azure-arm-datafactory");
import Models = require("./node_modules/azure-arm-datafactory/lib/models");

const subscriptionId = "<your-subscription-id>";

// Interactive Login
// It provides a url and code that needs to be copied and pasted in a browser 
// and authenticated over there. If successful, 
// the user will get a DeviceTokenCredentials object.

msRestAzure.interactiveLogin(function (err, credentials) {
  let client = new DataFactoryManagementClient(credentials, subscriptionId);
  const lsr : Models.LinkedServiceResource = {
    properties: <Models.AmazonRedshiftLinkedService> {
      type: "AmazonRedshift",
      server: "10.20.30.40",
      port: 8080,
      database: "foodb",
      username: "foouser",
      password: <Models.SecureString> {
        value: "foopwd"
      }
    }
  };
  client.linkedServices.createOrUpdate("amar", "testf15", "ls12", lsr).then((linkedServices) => {
    console.log('Created linkedService:');
    console.dir(linkedServices, { depth: null, colors: true });
  }).catch((err) => {
    console.log('An error ocurred');
    console.dir(err, { depth: null, colors: true });
  });
});
```

The output is as follows:
```javascript
Created linkedService:
{ id: '/subscriptions/<subscriptionId>/resourceGroups/amar/providers/Microsoft.DataFactory/factories/testf15/linkedservices/ls12',
  name: 'ls12',
  etag: '000081ba-0000-0000-0000-59ee7e370000',
  properties: 
   { type: 'AmazonRedshift',
     server: '10.20.30.40',
     username: 'foouser',
     password: { type: 'SecureString', value: '**********' },
     database: 'foodb',
     port: 8080 } }
```

Will test this a bit more and provide a fix in the runtime within a day or two with a minor version bump in "ms-rest". Once the patch version is published, you can delete the `node_modules/ms-rest` folder and execute `npm install` again which will bring a new version of ms-rest with the above mentioned fix. However, let me test this a little and get back to you. In the meantime, please feel free to patch things locally and let me know if you see further issues.

**Comment by kitsonswannff** [comment]
Thanks for getting back to me quickly here. The temporary fix you provided worked. Based on your example it also looks like I wasn't creating the resource object properly either. I appreciate the responsiveness here.

Just some feedback on the node.js API as well:

It's a bit confusing to me that you don't form the JSON in the format that matches the REST API documentation, but instead use these models to create a resource object that later down the line gets serialized into the correct format for the REST API.

It would be great if there was documentation on the node.js API and how to do this, not just for linked services but for all the other components of the data factory. I think I've managed to fumble my way through it by reading the function documentation and following a trail to the correct models, but I don't think I would have gotten there without your example above showing the pattern.

It's also a bit unintuitive to me that if you say create for example a `var redshiftLinkedService = new Models.AmazonRedshiftLinkedService;` that you still have to manually say that the `redshiftLinkedService.type = "AmazonRedshift";` seems like this should be handled for you and leaves opportunity to stuff some conflicting linked service type in there.

Cheers.

**Comment by amarzavery** [comment]
> It's a bit confusing to me that you don't form the JSON in the format that matches the REST API documentation, but instead use these models to create a resource object that later down the line gets serialized into the correct format for the REST API.

So we flatten some nested properties in the sdk to make it easier for users to populate parameters. I agree that, if the sdk documentation was solid this would not have been a big problem. However, this is the [current datafactory sdk documentation](https://docs.microsoft.com/en-us/nodejs/api/azure-arm-datafactory/linkedservices?view=azure-node-2.2.0). We are working on improving that.

> It would be great if there was documentation on the node.js API and how to do this, not just for linked services but for all the other components of the data factory. I think I've managed to fumble my way through it by reading the function documentation and following a trail to the correct models, but I don't think I would have gotten there without your example above showing the pattern.

Thanks for the feedback. We are working on improving the sdk documentation. Mostly we autogenerate sdks from an open api spec. With Datafactory the biggest problem is that properties can be primitve types like a string or an Expression object that has a returns a string. There is no way to model that in the spec. Thus the service team has specified it as an object (but actually the service accepts a string as well).

**Btw, did you try TypeScript? It should give you good validation and intellisene. That should help.**


> It's also a bit unintuitive to me that if you say create for example a var redshiftLinkedService = new Models.AmazonRedshiftLinkedService(); that you still have to manually say that the redshiftLinkedService.type = "AmazonRedshift"; seems like this should be handled for you and leaves opportunity to stuff some conflicting linked service type in there.

In Javascript world, we would not expect customers to instantiate `new()` classes for models. Developers are used to providing json objects. Hence the model classes in the sdk only have mappers that tell the serializer how to [de]serialize. The experience improves greatly by using TypeScript as it tells you the type of the properties, whether they are required or not and provides intellisense for what to expect.
We have designed all the [models as interfaces in the type definition](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/datafactoryManagement/lib/models/index.d.ts) which helps in the above mentioned scenario.

that being said, we can further look into how we can add defaults for obvious things.

**Comment by amarzavery** [comment]
ms-rest version 2.2.4 has been published with the fix for validating "object" type. Please delete the node_modules/ms-rest folder and try to execute `npm install ms-rest` and you should get the latest version `npm list ms-rest` with the fix.

**Comment by hvermis** [comment]
@kitsonswannff It seems that this issue has been resolved. Can I close it now?
