### ISSUE TITLE
Azure Data Factory V2: Pipeline run failing with: Error: InternalServerError executing request

### ISSUE THREAD

**Issue by kitsonswannff** [Azure/azure-sdk-for-node#2303]
Hi Again,

I'm creating an Azure Data Factory V2 using node.js. I'm getting successful responses from the REST API using the SDK to create the:

- Data Factory
- Linked services for Redshift Source and Azure SQL Sink
- Datasets for 16 different tables
- Pipeline with 16 copy activities

When I try to actually run the pipeline with:

```
DataFactoryManagementClient.pipelines.createRun(resourceGroupName, dataFactoryName, pipelineName, function (err, result, request, response) {
				if (err) {
					return callback(err);
				}
				callback(null, result);
			});
```

I get general `Error: InternalServerError executing request`

Few questions:

1. Is there any way to get more info about the error, so I at least know where to start looking?
2. Is it possible that the REST API would respond successfully to the factory, linked services, datasets and pipeline calls, even though they were incorrect in some way? What kinds of things can I look for here?
3. Is there a simple way I can print out the entire JSON ARM definition for the whole data factory including the linked services, datasets and pipeline?
4. In the Azure portal and GUI tool (that opens after clicking Manage and Monitor) I can see the Data Factory v2 I've created, but I can't see the linked services, datasets or pipelines. In V1 I could see all of this. Is this just limited functionality during the preview, or do I have some kind of issue?

**Comment by amarzavery** [comment]
The `err` object that you are returning from the callback has the actual request, response, message, and a body that should give you more information.
Try doing, `console.dir(err, {depth: null})`. That should provide you good information. The error object should also have some correlationId (some guid). This will help the service team to find out what went wrong on the service side. 

- Can you please provide a snapshot of the err object as mentioned above. Feel free to sanitize any info that you feel is private.

For questions 2, 3, 4 I will ask someone from the datafactory team to provide a better answer.

**Comment by kitsonswannff** [comment]
I found a more detailed error in the azure portal that I think has the information you're looking for. Let me know if this helps - I cut out some things from the top for privacy.

```
{
    "correlationId": "b083164e-0568-450c-b454-d5a5a696cabe",
    "description": "",
    "eventDataId": "211c243e-d5e8-442d-8adc-4cd5413e4ec4",
    "eventName": {
        "value": "EndRequest",
        "localizedValue": "End request"
    },
    "category": {
        "value": "Administrative",
        "localizedValue": "Administrative"
    },
    "eventTimestamp": "2017-10-26T03:29:31.5232292Z",
    "id": "/subscriptions/1e161adc-caaa-4814-b907-aff486baea8d/resourceGroups/chipripfieldResourceGroup/providers/Microsoft.DataFactory/factories/chipripfielddatafactory/pipelines/AmazonRedshiftToAzureSQLPipeline/events/211c243e-d5e8-442d-8adc-4cd5413e4ec4/ticks/636445853715232292",
    "level": "Error",
    "operationId": "b083164e-0568-450c-b454-d5a5a696cabe",
    "operationName": {
        "value": "Microsoft.DataFactory/factories/pipelines/createRun/action",
        "localizedValue": "Microsoft.DataFactory/factories/pipelines/createRun/action"
    },
    "resourceGroupName": "chipripfieldResourceGroup",
    "resourceProviderName": {
        "value": "Microsoft.DataFactory",
        "localizedValue": "Microsoft.DataFactory"
    },
    "resourceType": {
        "value": "Microsoft.DataFactory/factories/pipelines",
        "localizedValue": "Microsoft.DataFactory/factories/pipelines"
    },
    "resourceId": "/subscriptions/1e161adc-caaa-4814-b907-aff486baea8d/resourceGroups/chipripfieldResourceGroup/providers/Microsoft.DataFactory/factories/chipripfielddatafactory/pipelines/AmazonRedshiftToAzureSQLPipeline",
    "status": {
        "value": "Failed",
        "localizedValue": "Failed"
    },
    "subStatus": {
        "value": "InternalServerError",
        "localizedValue": "Internal Server Error (HTTP Status Code: 500)"
    },
    "submissionTimestamp": "2017-10-26T03:29:49.9106866Z",
    "subscriptionId": "1e161adc-caaa-4814-b907-aff486baea8d",
    "properties": {
        "statusCode": "InternalServerError",
        "serviceRequestId": "a9598040-2844-4575-af63-884b09d797b5",
        "statusMessage": "{\"code\":\"InternalServerError\",\"message\":\"InternalServerError executing request\",\"target\":\"pipeline/AmazonRedshiftToAzureSQLPipeline/runid/a9598040-2844-4575-af63-884b09d797b5\"}"
    },
    "relatedEvents": []
}
```

**Comment by kitsonswannff** [comment]
I also simplified the data factory to just one table and printed out all of the details of the data factory. By calling:```

factories.get()
linkedServices.listByFactory()
datasets.listByFactory()
pipelines.listByFactory()

```

I removed the redshift server and table names for privacy but otherwise these are the results I get. Does anything look incorrect here?

```
[
  {
    "id": "/subscriptions/1e161adc-caaa-4814-b907-aff486baea8d/resourceGroups/kitsonswannresourcegroup/providers/Microsoft.DataFactory/factories/kitsonswanndatafactory",
    "name": "kitsonswanndatafactory",
    "type": "Microsoft.DataFactory/factories",
    "location": "East US",
    "tags": {},
    "provisioningState": "Succeeded",
    "createTime": "2017-10-27T17:23:37.509Z",
    "version": "2017-09-01-preview"
  },
  [
    {
      "id": "/subscriptions/1e161adc-caaa-4814-b907-aff486baea8d/resourceGroups/kitsonswannResourceGroup/providers/Microsoft.DataFactory/factories/kitsonswanndatafactory/linkedservices/SourceRedshiftLinkedService",
      "name": "SourceRedshiftLinkedService",
      "etag": "00002eb3-0000-0000-0000-59f36b9f0000",
      "properties": {
        "type": "AmazonRedshift",
        "server": <removed for privacy>,
        "username": <removed for privacy>,
        "password": {
          "type": "SecureString",
          "value": "**********"
        },
        "database": "datawarehouse",
        "port": "5439"
      }
    },
    {
      "id": "/subscriptions/1e161adc-caaa-4814-b907-aff486baea8d/resourceGroups/kitsonswannResourceGroup/providers/Microsoft.DataFactory/factories/kitsonswanndatafactory/linkedservices/DestinationAzureSQLLinkedService",
      "name": "DestinationAzureSQLLinkedService",
      "etag": "00002fb3-0000-0000-0000-59f36b9f0000",
      "properties": {
        "type": "AzureSqlDatabase",
        "connectionString": {
          "type": "SecureString",
          "value": "**********"
        }
      }
    }
  ],
  [
    {
      "id": "/subscriptions/1e161adc-caaa-4814-b907-aff486baea8d/resourceGroups/kitsonswannResourceGroup/providers/Microsoft.DataFactory/factories/kitsonswanndatafactory/datasets/InputDataset-placeholder_tablename",
      "name": "InputDataset-placeholder_tablename",
      "etag": "00002cb3-0000-0000-0000-59f36b9f0000",
      "properties": {
        "structure": [
          {
            "name": "connection_id",
            "type": "Int32"
          },
          {
            "name": "company_id",
            "type": "String"
          },
          {
            "name": "page_id",
            "type": "String"
          },
          {
            "name": "title",
            "type": "String"
          }
        ],
        "linkedServiceName": {
          "type": "LinkedServiceReference",
          "referenceName": "SourceRedshiftLinkedService"
        },
        "type": "RelationalTable",
        "tableName": "\"datawarehouse\".\"public\".\"placeholder_tablename\""
      }
    },
    {
      "id": "/subscriptions/1e161adc-caaa-4814-b907-aff486baea8d/resourceGroups/kitsonswannResourceGroup/providers/Microsoft.DataFactory/factories/kitsonswanndatafactory/datasets/OutputDataset-placeholder_tablename",
      "name": "OutputDataset-placeholder_tablename",
      "etag": "00002db3-0000-0000-0000-59f36b9f0000",
      "properties": {
        "structure": [
          {
            "name": "connection_id",
            "type": "Int32"
          },
          {
            "name": "company_id",
            "type": "String"
          },
          {
            "name": "page_id",
            "type": "String"
          },
          {
            "name": "title",
            "type": "String"
          }
        ],
        "linkedServiceName": {
          "type": "LinkedServiceReference",
          "referenceName": "DestinationAzureSQLLinkedService"
        },
        "type": "RelationalTable",
        "tableName": "[dbo].[placeholder_tablename]"
      }
    }
  ],
  [
    {
      "id": "/subscriptions/1e161adc-caaa-4814-b907-aff486baea8d/resourceGroups/kitsonswannResourceGroup/providers/Microsoft.DataFactory/factories/kitsonswanndatafactory/pipelines/AmazonRedshiftToAzureSQLPipeline",
      "name": "AmazonRedshiftToAzureSQLPipeline",
      "etag": "00002ab3-0000-0000-0000-59f36b9f0000",
      "activities": [
        {
          "name": "AmazonRedshift-AzureSqlCopyActivity-placeholder_tablename",
          "type": "Copy",
          "source": {
            "type": "AmazonRedshiftSource",
            "query": "select * from \"datawarehouse\".\"public\".\"placeholder_tablename\""
          },
          "sink": {
            "type": "SqlSink"
          },
          "translator": {
            "type": "TabularTranslator",
            "columnMappings": "connection_id:connection_id, company_id:company_id, page_id:page_id, title:title"
          },
          "inputs": [
            {
              "type": "DatasetReference",
              "referenceName": "InputDataset-placeholder_tablename"
            }
          ],
          "outputs": [
            {
              "type": "DatasetReference",
              "referenceName": "OutputDataset-placeholder_tablename"
            }
          ]
        }
      ]
    }
  ]
]
```

**Comment by kitsonswannff** [comment]
I wrote a script to inspect the pipeline and activity runs, and through that found this error:

```
"Activity AmazonRedshift-AzureSqlCopyActivity-table_name failed: Failure happened on 'Source' side. ErrorCode=UserErrorFailedToConnectOdbcSource,'Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=ERROR [08S01] [Microsoft][Amazon Redshift] (10) Error occurred while trying to connect: [SQLState 08S01] SSL error: certificate verify failed,Source=Microsoft.DataTransfer.ClientLibrary.Odbc.OdbcConnector,''Type=Microsoft.DataTransfer.ClientLibrary.Odbc.Interop.OdbcException,Message=ERROR [08S01] [Microsoft][Amazon Redshift] (10) Error occurred while trying to connect: [SQLState 08S01] SSL error: certificate verify failed,Source=Microsoft.DataTransfer.ClientLibrary.Odbc.Native,'"
```

Can you provide more information from that?

**Comment by chelsea-jones-ff** [comment]
As of October 23 (Monday), Redshift requires that clients connecting over SSL either use recent versions of their ODBC drivers or else install Redshift root certificates:
http://docs.aws.amazon.com/redshift/latest/mgmt/connecting-transitioning-to-acm-certs.html

**Comment by wenbof** [comment]
The new root cert has been updated.  would you please check whether you still have that issue? My testing looks good. Thanks.

**Comment by kitsonswannff** [comment]
It appears to have worked for me now. Thank you.
