### ISSUE TITLE
dataFactoryManagement defaults to Data Factory V2 any way to change to V1

### ISSUE THREAD

**Issue by kitsonswannff** [Azure/azure-sdk-for-node#2307]
Hi Again,

The the dataFactoryManagement module defaults to V2 using the node sdk. Is there a way to instead use V1? The azure portal interface for V2 is not working and is making it very difficult to debug issues.

**Comment by amarzavery** [comment]
I don't think there is a V1 datafactory node module. @wenbof any ideas?

**Comment by wenbof** [comment]
V1 also has SDKs: https://docs.microsoft.com/en-us/azure/data-factory/v1/data-factory-copy-activity-tutorial-using-dotnet-api

**Comment by hvermis** [comment]
Confirming that there is no node SDK for Azure Data Factory V1.
