### ISSUE TITLE
Media Services starting jobs

### ISSUE THREAD

**Issue by re-jim** [Azure/azure-sdk-for-node#2313]
In https://github.com/Azure/azure-sdk-for-node/issues/1797, it seems like Azure Media Services is supported, but looking at the [azure-arm-mediaservices](https://www.npmjs.com/package/azure-arm-mediaservices) module, I'm not seeing anything about creating assets, or encoding jobs.

Are these actions supported, or would I have to use the REST API?

Also related https://github.com/Azure/azure-sdk-for-node/issues/171

**Comment by amarzavery** [comment]
@re-jim - This package/sdk only has method calls for management plane. It supports CRUD on the mediaservice and regenerating, listing keys and syncing storage keys.
My guess is that creating assets or encoding jobs is data-plane (that is the base url may not be starting with `https://management.azure.com` but with the name of the media service you would have created).

@johndeu from the Media Service team can provide more info on this.

**Comment by johndeu** [comment]
That's correct - this is just autogenerated from our Management plane REST API's Swagger file. 
It does not have complete Data plane operation support.

That said, we have a few community built Node.js SDKs that wrap our API.  Most of them are "partial" and not really complete or supported.  

On the positive side, we are refreshing our REST APIs this year and have plans to provide generated SDKs for Node.js, Python, Ruby, GO, and Java.  The new SDK will be ARM based and will include both Management and Operations in a single API set.   Happy to get your feedback on the new API/SDK when it is ready. Targeting April for a public preview currently.

**Comment by johndeu** [comment]
Also @re-jim (Grant), 
If this is for the hackathon next week - ping William Zhang and me directly on email.

**Comment by mozehgir** [comment]
Looks like the issue has been addressed as per the comment above. If the error persists feel free to re-open this issue in the https://github.com/Azure/azure-sdk-for-js repository .
