### ISSUE TITLE
ms-rest-azure SDK 2.4.2 typings are resulting in compilation error in typescript projects

### ISSUE THREAD

**Issue by ksachdeva** [Azure/azure-sdk-for-node#2314]
The error is 
```
node_modules/ms-rest-azure/index.d.ts(525,15): error TS1039: Initializers are not allowed in ambient contexts
```

This is happening because in ms-rest-azure/index.d.ts [(line 525)](https://github.com/Azure/azure-sdk-for-node/blob/master/runtime/ms-rest-azure/index.d.ts#L525) the property resource has been assigned a value i.e. (https://management.azure.com). Instead it should be 

```
resource?: string;
```

**Comment by amarzavery** [comment]
Thanks for reporting this. #2315 fixes this. Please install `2.4.3` version of `ms-rest-azure`.

**Comment by ksachdeva** [comment]
Thanks for the quick fix and release. It good on my end now.
