### ISSUE TITLE
Required permissions to allow an application to assign itself subscription owner role

### ISSUE THREAD

**Issue by MichaelBurgess** [Azure/azure-sdk-for-node#2325]
Hi,

If I create an Application & Service principal via the Graph API, once this is created I am unable to assign itself the Owner role for a Subscription via the Azure Node SDK.

What permissions or settings can I change during the creation of the Application / Service Principal that will allow us to programmatically assign itself Subscription Owner role, without needing to manually go into the Azure Portal UI and assign this to the service principal?

Thanks,
Mike.

**Comment by amarzavery** [comment]
@MichaelBurgess - 
> unable to assign itself the Owner role for a Subscription

Trying to understand what do you mean by this?
I don't think you can assign the service principal as an owner if you are logged in as that service principal. 

Following can be done:
- If you have enough rights to create a service principal and assign roles or someone who is a global admin in the tenant can create an sp and assign roles to it.
- An SP can have different roles.
- While you are creating a service principal you can assign the sp a role of an owner at the (scope) subscription level.

The SP is an owner as well as a contributor at the same scope
```
D:\sdk\azure-sdk-for-node>azure role assignment list --spn http://adtestsp
info:    Executing command role assignment list
+ Searching for role assignments
data:    RoleAssignmentId     : /subscriptions/00000000-1111-1111-2222-333333333333/providers/Microsoft.Authorization/roleAssignments/ef32bbaf-c67a-452a-9f2b-cef46652bc12
data:    RoleDefinitionName   : Owner
data:    RoleDefinitionId     : 8e3af657-a8ff-443c-a75c-2fe8c4bcb635
data:    Scope                : /subscriptions/00000000-1111-1111-2222-333333333333
data:    Display Name         : adtestsp
data:    SignInName           : undefined
data:    ObjectId             : aaaaaaaa-ddddd-3333-2222-gggggggggggg
data:    ObjectType           : ServicePrincipal
data:
data:    RoleAssignmentId     : /subscriptions/00000000-1111-1111-2222-333333333333/providers/Microsoft.Authorization/roleAssignments/cba2ea09-051e-476b-9679-cc07d7b20415
data:    RoleDefinitionName   : Contributor
data:    RoleDefinitionId     : b24988ac-6180-42a0-ab88-20f7382dd24c
data:    Scope                : /subscriptions/00000000-1111-1111-2222-333333333333
data:    Display Name         : adtestsp
data:    SignInName           : undefined
data:    ObjectId             : aaaaaaaa-ddddd-3333-2222-gggggggggggg
data:    ObjectType           : ServicePrincipal
data:
info:    role assignment list command OK
```

**Comment by amarzavery** [comment]
Forgot to mention one more thing. You need to use `azure-arm-authorization` sdk for assigning/listing/deleting roles.

**Comment by amarzavery** [comment]
@MichaelBurgess - Is this still an issue for you? Did the above suggestions help?
