### ISSUE TITLE
ContainerInstanceManagement should support restart policies

### ISSUE THREAD

**Issue by rtyler** [Azure/azure-sdk-for-node#2334]
Currently the node package only supports the `Always` restart policy for creation of container groups.

This means the node package cannot be used to [run tasks with containers](https://docs.microsoft.com/en-us/azure/container-instances/container-instances-restart-policy) which would be absolutely brilliant  😄

**Comment by rtyler** [comment]
It looks like you can work around this for now by changing the API version the `client` is using.

Presently it's at: `2017-08-01-preview`, if you change it to a later version, it works!

```javascript
    const ACI   = require('azure-arm-containerinstance');
    const AZ    = require('ms-rest-azure');

    AZ.loginWithServicePrincipalSecret(
        process.env.AZURE_CLIENT_ID,
        process.env.AZURE_CLIENT_SECRET,
        process.env.AZURE_TENANT_ID,
        (err, credentials) => {
            if (err) {
                throw err;
            }
            let client = new ACI(credentials, process.env.AZURE_SUBSCRIPTION_ID);
            client.apiVersion = '2017-10-01-preview';
            /* hilarity ensues */
       });
```

![hack the planet](https://qph.ec.quoracdn.net/main-qimg-533c98ca5615d3ba6c65d60f960c4f11-c)

**Comment by amarzavery** [comment]
That is not the recommended way of using the client. It works by chance in this case. Every client is tied to an API version and will follow the request resposne contract for (de) serialization as per that API version. If the new API version has some additions or breaking changes then those won't be honored by the client as it does not know about it.

**Comment by amarzavery** [comment]
1.1.0-preview version of ["azure-arm-containerinstance"](https://www.npmjs.com/package/azure-arm-containerinstance) has been published which has the latest api-version changes for you.
