### ISSUE TITLE
Interactive login with key vault client

### ISSUE THREAD

**Issue by malafreniere** [Azure/azure-sdk-for-node#2338]
The sample for the key vault client shows how to login using a clientId and a clientSecret,

[https://github.com/Azure/azure-sdk-for-node/tree/master/lib/services/keyVault](https://github.com/Azure/azure-sdk-for-node/tree/master/lib/services/keyVault)

Is there a way to login using the interactive client like with the web site management api:

```js
const msRestAzure = require('ms-rest-azure');
const webSiteManagementClient = require('azure-arm-website');

// Interactive Login
msRestAzure.interactiveLogin(function(err, credentials) {
 let client = new webSiteManagementClient(credentials, 'your-subscription-id');
 client.webApps.list(function(err, result) {
   if (err) return console.log(err);
   return console.log(result);
 });
});
```

That way, we can log in with our own credentials instead of passing by a service principal ?

Thanks.

**Comment by mnadeau2** [comment]
having the same issue.

**Comment by amarzavery** [comment]
Thanks for letting us know. We are working on an improvement where you should be able to pass in any of the below mentioned credentials: 
1. `DeviceTokenCredentials` (`msRestAzure.interactiveLogin()`)
2. `ApplicationTokenCredentials` (`msRestAzure.loginWithServicePrinicpalSecret()`)
3. `UserTokenCredentials` (`msRestAzure.loginWithUsernamePassword()`)
4. `MSIVmTokenCredentials` (`msRestAzure.loginWithVmMSI()`)
5. `MSIAppServiceTokenCredentials` (`msRestAzure. loginWithAppServiceMSI()`)

**OR**
- `KeyVaultCredentials` itself.

We shall internally convert `1-5` into `KeyVaultCredentials`, thus making it easy for you.
We should have something ready in the coming 2 weeks.
/cc @williexu

**Comment by malafreniere** [comment]
Thanks !

**Comment by amarzavery** [comment]
We have a new version of the keyvault sdk and a new version of the runtime (ms-rest-azure) with the above features implemented. 
We have two samples with the updated sdks
- https://github.com/Azure-Samples/key-vault-node-deploy-certificates-to-vm
- https://github.com/Azure-Samples/app-service-msi-keyvault-node

Please let us know if this solves your issue.

**Comment by amarzavery** [comment]
closing this issue based on the above comment. The issue has been resolved.
