### ISSUE TITLE
[Performance] Listing resource items takes long time

### ISSUE THREAD

**Issue by formulahendry** [Azure/azure-sdk-for-node#2339]
Hi, I am using `azure-arm-resource` and `azure-arm-iothub` npm APIs to get subscriptions and IoT Hubs list in VS Code [Azure IoT Toolkit extension](https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.azure-iot-toolkit)

- get subscriptions list: https://github.com/Microsoft/vscode-azure-iot-toolkit/blob/396fcbbd2ab8a8dd5e21795901881a28052fa764/src/iotHubResourceExplorer.ts#L70
- get IoT Hubs list: https://github.com/Microsoft/vscode-azure-iot-toolkit/blob/396fcbbd2ab8a8dd5e21795901881a28052fa764/src/iotHubResourceExplorer.ts#L87

Some users meet with performance issues: it takes long time (over 10 seconds or even more) to load the list. And there is a similar issue in VS Azure Account extension: https://github.com/Microsoft/vscode-azure-account/issues/14
In VS Azure Account extension, they cache the subscription list as workaround. But it our extension, the IoT Hub list may change often. 

So my question is: Will it be able to improve the performance of these APIs ?(I am not sure why the API sometime takes long time, maybe the network issue or others?) Thank you!

**Comment by amarzavery** [comment]
@formulahendry - How many tenants and how many subscriptions within those tenants does the customer have on an average? It will obviously take O(n*m) + network delay to populate the entire list.

If the customer knows what tenant he is interested in , then he/she can provide the tenantId in options.domain = "tenantId" and we shall get subscriptions only from that tenant.

As far as getting the list of iothubs is concerned, how many iothubs do customers usually have in the list?

**Comment by amarzavery** [comment]
@formulahendry - Any updates on the above asked questions and suggestions?

**Comment by formulahendry** [comment]
@amarzavery Sorry for the late response. For the count of subscriptions and iot hubs, it is usually less than 10.
But currently not sure whether it is due to service performance issue or VS Code issue.

We use node SDK to get subscriptions or IoT Hubs list, then we use vscode API `vscode.window.showQuickPick` to show the subscriptions or IoT Hubs list.

However, There is an issue in VS Code API: https://github.com/Microsoft/vscode/issues/39465#issuecomment-354060988. If we get a `reject` Promise, the spinner of the dropdown list is always showing the loading status.

So there would be two reasons for this issue:

1. It is the node SDK to take long time to get the subscriptions or IoT Hubs list
2. In some situation, we may get a `reject` Promise from the node SDK. Then we meet with the VS Code API bug: the spinner of the dropdown list is always showing the loading status. Which let us or users feel that it is always querying the subscriptions or IoT Hubs list

I guess reason #2 may have the possibility. And do you know when the two APIs may return a `reject` Promise? We may narrow down the root cause.

**Comment by amarzavery** [comment]
Please use the new `@azure/arm-iothub` package and the new resource manger packages `@azure/arm-resources`
