### ISSUE TITLE
Documentation for authenticating with azure government locations

### ISSUE THREAD

**Issue by zachgatesak** [Azure/azure-sdk-for-node#2341]

**Comment by amarzavery** [comment]
@zachgatesak - This [link](https://github.com/Azure/azure-sdk-for-node/blob/master/Documentation/Authentication.md) should provide information on different ways to login. All the login methods take a [bunch of optional parameters as an options object](https://github.com/Azure/azure-sdk-for-node/blob/master/runtime/ms-rest-azure/lib/login.js#L246) which has an optional property called environment. It defaults to Azure (public cloud). You can set it to a different one. Here is a [list](https://github.com/Azure/azure-sdk-for-node/blob/master/runtime/ms-rest-azure/lib/azureEnvironment.js#L49) of supported environments.

**Comment by amarzavery** [comment]
Closing this issue based on the above comments. Please feel free to reopen if required.
