### ISSUE TITLE
Feature Request: Raw JSON printout.

### ISSUE THREAD

**Issue by kitsonswannff** [Azure/azure-sdk-for-node#2342]
In the node.js sdk the format you specify the JSON in before calls to the rest API doesn't match that of the actual REST Api. It then gets serialized to the proper format before the request is made. And, when you query the api using node.js, you get the "node SDK" json format back, not the actual REST Api format. This makes it very hard to troubleshoot issues.

I understand from our previous discussion that this is to make it easier to define the objects as the node sdk structure is flatter. But, as an example the first thing Microsoft support asks for when you're having a problem is the JSON you're sending the API, which there is no easy way to get it (at least for Data Factories).

Given that the documentation for the node.js SDK isn't currently complete and many of the examples for interacting with Azure services only show the REST Api JSON format, it would be great if there was an easy way to get the raw JSON rather than the flattened version.

**Comment by amarzavery** [comment]
Hi @kitsonswannff,

I completely understand your point. We do provide the raw request and the raw response. You can get the stringified response body from the raw response and the request body from the request (if applicable).

If you are calling the sdk methods using callbacks, then the `third` and `fourth` parameters are the actual `request` and `response` respectively. => `(err, result, request, response)`.
- An example over [here](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/datafactoryManagement/lib/operations/pipelines.js#L423)
To get the actual response given by the server you can access `response.body`. from your callback

If you are using Promise then every method has a `*WithHttpOperationResponse()` flavor that returns a `Promise<HttpOperationResponse>`. This object, contains the raw request, the raw response and the body (deserialized  (flattened) result).
- An example over [here](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/datafactoryManagement/lib/operations/pipelines.js#L1296)
To get the actual response given by the server you can access `HttpOperationResponse.response.body`. from the resolved Promise.

If the callback returns an error `callback(err)` or the Promise is rejected with an `error`, then the `error` object contains the raw `request` and the raw `response` as properties of the `error` object.
- An example over [here](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/datafactoryManagement/lib/operations/pipelines.js#L379)

One more thing:
- SDK has a request pipeline. The pipeline has some filters/hooks that get executed before sending the request and after receiving the response. 
- The constructor of the client takes an [optional parameter filters. It is of type Array](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/datafactoryManagement/lib/dataFactoryManagementClient.js#L33). You can provide your custom filters and we will hook them to the pipeline. These filters will be executed in the request/response dance.
- We have a simple logging filter that can be useful to you for logging the request and response. By default this filter logs to console. You can provide an instance of your logger `ex: Winston` and it will log the request and response using that logger.
- You can find the logFilter over [here](https://github.com/Azure/azure-sdk-for-node/blob/master/runtime/ms-rest/lib/filters/logFilter.js#L9).
- If you want to write more filters for some custom stuff then you can find some examples over [here](https://github.com/Azure/azure-sdk-for-node/blob/master/runtime/ms-rest/lib/filters).

```
var msRestAzure = require('ms-rest-azure');
var msRest = require('ms-rest'); // <<<<<<<<<<<<<<<<<<<<<<<<<<
var DataFactoryManagementClient = require("azure-arm-datafactory");

// Interactive Login
// It provides a url and code that needs to be copied and pasted in a browser and authenticated over there. If successful, 
// the user will get a DeviceTokenCredentials object.
msRestAzure.interactiveLogin(function(err, credentials) {
 const options = {
   filters: [ new msRest.logFilter()] //<<<<<<<<<<<<<<<<<<<<<<<<<
  };
 let client = new DataFactoryManagementClient(credentials, 'your-subscription-id', null, options); // <<adding the options object.
 client.factories.list().then((factories) => {
   console.log('List of factories:');
   console.dir(factories, {depth: null, colors: true});
  });
 }).catch((err) => {
  console.log('An error ocurred');
  console.dir(err, {depth: null, colors: true});
 });
});
```

**Comment by kitsonswannff** [comment]
This is great! I'm printing out the request and response using the callback and that works perfectly. Thank you.
