### ISSUE TITLE
[Powerbi-v2] Add support for getting/setting app workspaces (groups)

### ISSUE THREAD

**Issue by zimmermanw84** [Azure/azure-sdk-for-node#2349]
The `azure-arm-powerbiembedded` package is outdated even though the Powerbi Embedded website is describing the new power bi flow (App workspace model).

Can we add support for the new powerbi interface?

**Comment by amarzavery** [comment]
@zimmermanw84 - We auto generate the node sdk from the [Open API spec for powerbi embedded](https://github.com/Azure/azure-rest-api-specs/blob/current/specification/powerbiembedded/resource-manager/Microsoft.PowerBI/2016-01-29/powerbiembedded.json). We haven't seen an update on this spec in the last 7 months. There is no open PR as well. We will sync up with the service team and get back to you.

Can you point us to the website link that describes the workflow?

**Comment by zimmermanw84** [comment]
@amarzavery Thanks for your quick response, and sorry for taking a week to get back to you.

The closes thing I can find to a single source of truth is the C# SDK
[https://github.com/Microsoft/PowerBI-CSharp](url)
I am writing a client to get us by in the mean time, but running into all sorts of issues due to lack of technical documentation around the V2 spec. For instance even authenticating was a hassle due to needing an App (client_id, client_secret) and User creds (username, password) to get a bearer token to access the api. Case in point [https://msdn.microsoft.com/en-us/library/dn877544.aspx](url), the first link (Authentication) returns a 404.

Let me know what the service teams says, and/or if there is documentation I am missing that you could point me to.

Thanks again for your time regarding this matter.

**Comment by amarzavery** [comment]
@zimmermanw84 - 
- Based on the link specified by you https://msdn.microsoft.com/en-us/library/dn877544.aspx 
This is the data plane of the PowerBI service. The current azure-sdk-for-node repo only maintains the control plane of all Azure services.

- There is also a Javascript SDK for powerBI in that github org, did you take a look at that? I am pretty sure you need to take a look at this one - https://github.com/Microsoft/PowerBI-JavaScript. 
Also file an issue in the PowerBI-Javascript repo (owned by the service team) and do point them to the https://github.com/Microsoft/PowerBI-CSharp/tree/master/sdk/PowerBI.Api/Source/V2 source code in the C# sdk repo. They would be in a better position to help you.

**Comment by amarzavery** [comment]
closing this issue for now based on the above comments. Please feel free to reopen if required.
