### ISSUE TITLE
vm example for managed disk

### ISSUE THREAD

**Issue by Thiamael** [Azure/azure-sdk-for-node#2355]
hello, i saw the example for creating a VM with azure sdk for node (https://github.com/Azure/azure-sdk-for-node/blob/master/examples/ARM/compute/vm-sample.js) and it help a lot. But i need a similar example that use managed disks instead of storage accounts.
i didn't find any by looking around here, nor on google.

Could you provide one, please ?

**Comment by amarzavery** [comment]
@Thiamael 
As seen in [this old sample](https://github.com/Azure-Samples/compute-node-manage-vm/blob/master/index.js#L307) we are providing the osDisk in the storageProfile property while creating the VM.

In the newer sample that illustrates how to create a VM with MSI (Managed Service Identity), [we are not providing the osDisk in the storageProfile](https://github.com/Azure-Samples/compute-node-msi-vm/blob/master/lib/index.ts#L210). This is an indication to the service that it should use managed disks for creating a VM.

**OR**
You can pre create a managed disk and then assign it while creating a VM as shown in the REST API doc over [here](https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/virtualmachines-create-or-update#managedDisk).

**Comment by Thiamael** [comment]
Thank you very much. i've been able to create a vm with a managed disk thanks to your samples.
