### ISSUE TITLE
SDK support for Azure Active Directory reporting API

### ISSUE THREAD

**Issue by kaidaguerre** [Azure/azure-sdk-for-node#2364]
Does the node SDK support the [reporting API](https://docs.microsoft.com/en-us/azure/active-directory/active-directory-reporting-api-getting-started-azure-portal)? I am specifically wanting to get information about user sign-ins. 

I could not find reference to this within the documentation or code.

**Comment by amarzavery** [comment]
This SDK supports the basic AD graph related stuff for managing resources in ARM (Azure Resource Manager). For complex and detailed scenarios please take a look at the [javascript library](https://github.com/microsoftgraph/msgraph-sdk-javascript) provided by Microsoft Graph.
