### ISSUE TITLE
querying user MFA status

### ISSUE THREAD

**Issue by kaidaguerre** [Azure/azure-sdk-for-node#2365]
Is there a means of querying the MFA (multi factor authentication) status of a user using the node SDK?

**Comment by amarzavery** [comment]
If the user authenticated successfully then you get the credentials object, which means the status is successful otherwise it is not. 

What is it that you are trying to achieve? What are you looking for in the MFA status?

**Comment by kaidaguerre** [comment]
Thanks for your reply. 

We are looking to programmatically confirm whether users have MFA enabled, based on policy values within our software.  We apply a set of checks to the cloud resources to confirm compliance with our policies.

**Comment by amarzavery** [comment]
@kaidaguerre - I get what you are saying. Unfortunately, I am not able to find a programmatic way of knowing the MFA status. You can go to the portal and find that.

![image](https://user-images.githubusercontent.com/4521223/34131086-129e5fe6-e3ff-11e7-85e6-83511f578cb9.png)

**Comment by kaidaguerre** [comment]
ok thanks for the info

**Comment by amarzavery** [comment]
closing this issue. please feel free to reopen if required.
