### ISSUE TITLE
ms-rest-azure missing dependency

### ISSUE THREAD

**Issue by jsevedge** [Azure/azure-sdk-for-node#2367]
As of (at least) 2.4.5 it appears that ms-rest-azure pulls in the request module in the file under /lib/filters/ called rpRegistrationFilter.js.  However the request module is not provided as a dependency in the package.json resulting in request needing to already exist globally or in an upstream node_modules directory, otherwise using ms-rest-azure results in an error exception for the requests module not existing.

 Can you confirm that this is a bug and if so if it is possible to get fixed?  Or if i missed something in the expected dependency structure could you let me know the correct way to get around this issue?

Thanks,

Error thrown: 
module.js:327
    throw err;
    ^

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/<some_dir>/node_modules/azure-arm-appinsights/node_modules/ms-rest-azure/lib/filters/rpRegistrationFilter.js:6:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

**Comment by amarzavery** [comment]
@jsevedge - That should not happen. ms-rest-azure -> (depends on) ms-rest which has a dependency on "request". Hence "request" should be present at the top level inside the node_modules directory.

I suspect that the version of node.js and npm on your system will be an old one. (`node -v` and `npm -v`).
node <= 8.x and npm <=4.x.

FYI, You can install the latest version from https://nodejs.org. For a linux distro, you can follow the instructions [here](https://nodejs.org/en/download/package-manager/#installing-node-js-via-package-manager).

**Comment by jsevedge** [comment]
Ah, i am using an older version of both node and npm and do see that when using a newer version of npm it is sophisticated enough to figure out a dependency has a dependency that should be top level.  I will add to top level myself to get around this since stuck with older version of npm for now.

It still seems strange though to have a direct dependency of ms-rest-azure (request is being called directly in ms-rest-azure) be pulled in by virtue of another dependency (ms-rest) being dependent on it :)

**Comment by jtbarker** [comment]
I have npm install -g installed request, ms-rest, and ms-rest-azure and am still not able to find module ms-rest-azure in a short script with these requirements that looks like this:
const msRestAzure = require('ms-rest-azure');
const ContainerRegistryManagement = require('azure-arm-containerregistry');

const subscriptionId = 'REDACTED';

msRestAzure
  .interactiveLogin()
  .then(credentials => {
              const manager = new ContainerRegistryManagement(
                            credentials,
                            subscriptionId
                          );
              return manager.registries.list();
            })
  .then(registries => {
              console.log('List of registries:');
              console.dir(registries, { depth: null, colors: true });
            });

**Comment by amarzavery** [comment]
Why are you installing these libraries globally (-g) ? Usually in the package.json of your application, I would expect that there is a dependency on `"azure-arm-containterregistry": "^2.0.0-preview"`. This [package](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/containerRegistryManagement/package.json#L21) already has a dependency on ms-rest and ms-rest-azure. So npm should install everything for you in the node_modules folder of your application.

**Comment by jtbarker** [comment]
@amarzavery I am installing them globally so that I can use node repl to run one-off jobs.  Is this not common?

**Comment by amarzavery** [comment]
@jtbarker - That is not a common use case. If you have the modules installed locally let's say in a directory
"d:/foo/node_modules" and you enter the node repl from `d:/foo>node` then you will be able to require all the modules.

I found an issue that some filed in the node.js repo where they were not able to require packages that were installed globally.  https://github.com/nodejs/node-v0.x-archive/issues/5431 
The issue has links to some blogs and solutions posted by other people. I would still recommend having a local package.json and have dependencies installed in that folder.
```
d:/>mkdir playground
d:/>cd d:/playground
d:/playground>notepad package.json // Just put empty curly braces {} and save the file
d:/playground>npm i -s ms-rest
d:/playground>npm i -s ms-rest-azure
d:/playground>npm i -s request
. . . 

and then 
d:/playground>node
var msrest = require('ms-rest');
```

**Comment by freedumb** [comment]
I have this exact same problem with node v8.9.4 npm v5.6.0 also tried node v9.5.0

**Comment by amarzavery** [comment]
Thanks for reporting this issue. We shall fix this in the upcoming release.

**Comment by amarzavery** [comment]
#2431 fixes it. New versions of ms-rest and ms-rest-azure have been published.
