### ISSUE TITLE
OnMessage equivalent of C# SDK

### ISSUE THREAD

**Issue by DanielDziubecki** [Azure/azure-sdk-for-node#2377]
I am looking for `OnMessage`  callback equivalent functionallity like C# SDK have. Now for recieve message automically I have to call `serviceBusService.receiveSubscriptionMessage` in some kind of CRON like mechanism or inifnite loop ?

**Comment by amarzavery** [comment]
@DanielDziubecki  Please try the new sdk `npm i @azure/service-bus`. 

Sample for the above mentioned usecase can be found here https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/servicebus/service-bus/samples/typescript/gettingStarted/receiveMessagesStreaming.ts#L33

Please file service bus related issues in the new repo https://github.com/Azure/azure-sdk-for-js
