### ISSUE TITLE
Cannot get built-in Azure policy via Node SDK

### ISSUE THREAD

**Issue by MichaelBurgess** [Azure/azure-sdk-for-node#2378]
Hi,

If I perform a list operation on policies, I am able to list all policies (built-in and custom):

```coffeescript
client = azure.createResourcePolicyClient creds, subscriptionId
client.policyDefinitions.list (err, result) -> callback err, result
```

If I then try to get a built-in policy via:

```coffeescript
client = azure.createResourcePolicyClient creds, subscriptionId
client.policyDefinitions.get "e56962a6-4747-49cd-b67b-bf8b01975c4c", (err, result) -> callback err, result
```

I get the following error:

`Error: The policy definition e56962a6-4747-49cd-b67b-bf8b01975c4c could not be found.`

I am able to get custom roles using the same code and the name of the custom policy.

Is it possible to get a built-in policy? I have some code that needs to be able to get both built-in and custom policies to check their assignments.

Thanks,
Mike.

**Comment by MichaelBurgess** [comment]
Thanks @amarzavery - I was able to get the above code working to retrieve a built-in role, the only diff is I had to create an instance of `PolicyDefinition` in order to get at the mapper function:

`deserializationMapper: new client.models.PolicyDefinition().mapper()`

I'll keep my eye out for the new package.

Mike.

**Comment by amarzavery** [comment]
Oh yes, my bad. That is correct.

**Comment by amarzavery** [comment]
@MichaelBurgess - ["azure-arm-resource": "3.1.0-preview"](https://www.npmjs.com/package/azure-arm-resource) version has been published with updates.

**Comment by amarzavery** [comment]
We have not published a new version of the rollup package `azure`. Instead have published the individual package. Just letting you know. Please take an explicit dependency on `azure-arm-resource` and use the client from that package.

**Comment by amarzavery** [comment]
closing this issue. It appears to have been fixed with the new version. Please feel free to reopen if the problem persists.
