### ISSUE TITLE
Bug in Azure Key Vault module

### ISSUE THREAD

**Issue by iricigor** [Azure/azure-sdk-for-node#2380]
In [keyVaultClient.js](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/keyVault/lib/keyVaultClient.js) there is this code repeating at multiple places:

```TypeScript
// Construct URL
let baseUrl = this.baseUri;
let requestUrl = baseUrl + (baseUrl.endsWith('/') ? '' : '/') + 'keys/{key-name}/create';
requestUrl = requestUrl.replace('{vaultBaseUrl}', vaultBaseUrl);
```
And code from class constructor says
```TypeScript
this.baseUri = '{vaultBaseUrl}';
```

This is checking constant value ```baseUrl``` for ending with "/". Like this if I pass value ending with "/" it will anyway append another "/".

Proper would be to check parameter ```vaultBaseUrl```.

```TypeScript
// Construct URL
let baseUrl = this.baseUri;
let requestUrl = baseUrl + (vaultBaseUrl.endsWith('/') ? '' : '/') + 'keys/{key-name}/create';
requestUrl = requestUrl.replace('{vaultBaseUrl}', vaultBaseUrl);
```

**Comment by amarzavery** [comment]
Closing this in favor of the new packages being created for key vault control and data plane https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/keyvault
