### ISSUE TITLE
SDK for CRUD operations on recovery services vault backup policies

### ISSUE THREAD

**Issue by MichaelBurgess** [Azure/azure-sdk-for-node#2384]
Hi,

I can see there are list operations for listing backup policies: https://docs.microsoft.com/en-gb/javascript/api/azure-arm-recoveryservicesbackup/backuppolicies?view=azure-node-2.2.0

However I can't find any way to get, create, update or delete a backup policy - do these exist? In the past you have suggested calling APIs directly with `sendRequest`, so I'm wondering if that's an option here?

Also, are there SDK functions to attach backup policies to a VM?

Thanks,
Mike.

**Comment by amarzavery** [comment]
> However I can't find any way to get, create, update or delete a backup policy - do these exist? 

Yes they do exist. For some odd reason, the service team has named them as `ProtectionPolicies`.
You can find the documentation for CRUD on them over [here](https://docs.microsoft.com/en-gb/javascript/api/azure-arm-recoveryservicesbackup/protectionpolicies?view=azure-node-2.2.0).
The corresponding operation in the swagger specification is defined over [here](https://github.com/Azure/azure-rest-api-specs/blob/current/specification/recoveryservicesbackup/resource-manager/Microsoft.RecoveryServices/stable/2016-12-01/backupManagement.json#L1416).

> Also, are there SDK functions to attach backup policies to a VM?

I think this refers to the `ProtectedItems` operation group. Please refer to the [documentation](https://docs.microsoft.com/en-gb/javascript/api/azure-arm-recoveryservicesbackup/protecteditems?view=azure-node-2.2.0#azure_arm_recoveryservicesbackup_ProtectedItems_createOrUpdate_parameters) for `backupManagementType` and `workloadType` in `parameters.properties` in `createOrUpdate()` method

**Comment by MichaelBurgess** [comment]
Thanks @amarzavery, great help as ever. The `ProtectionPolicies` gave me what I needed for the CRUD operations on the backup policies.

For the protected items, is there a list operation like there is in the REST API? https://docs.microsoft.com/en-us/rest/api/site-recovery/protecteditems/list

I'm able to call list using `sendRequest`, so if there isn't an SDK function for it, it's not a blocker for me, but would be nice if I could call list via the SDK. I can't see the list operation for protectedItems in the swagger link you send above.

**Comment by amarzavery** [comment]
@MichaelBurgess - I apologize for this mess. It seems the service team changed the name of the operationgroup from `ProtectedItems` to `BackupProtectedItems` when they moved from `api-version` `2016-06-01` to `2016-12-01`.

The sdk was generated for the new api version but the [documention for REST API](https://docs.microsoft.com/en-us/rest/api/site-recovery/protecteditems/list) still shows things as of 2016-06-01 (the old api version) as can be seen in the url

> GET https://management.azure.com/Subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.RecoveryServices/vaults/{vaultName}/backupProtectedItems?api-version=**2016-06-01**
 
@dend - Can you please take a look into this? Why is the REST API [doc](https://docs.microsoft.com/en-us/rest/api/site-recovery/protecteditems/list) not pointing to the latest api-version? 
/cc @salameer

We have this api under `BackupProtectedItems` operation group over [here](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/recoveryServicesBackupManagement/lib/operations/backupProtectedItems.js#L397).

**Comment by amarzavery** [comment]
@MichaelBurgess - I have published a patch version of azure-arm-recoveryservicesbackup@2.0.1-preview with minor updates. Please use the latest version.

Thanks,
Amar

**Comment by MichaelBurgess** [comment]
Thanks @amarzavery, I've pulled that version down now, will check it out.

Don't suppose you know which SDK function I can use to create a container? In order to create a protectedItem, I need to provide a container, but I can only find the get and refresh functions for protection containers on both the SDK and REST API?

Thanks,
Mike.

**Comment by amarzavery** [comment]
Yes, I am not aware in detail about the function to create a container. I looked up and could not find any method that does that.

> May be the service auto creates the container if it does not exist. Try providing some container name to the  client.protectedItems.createOrUpdate() method. It may work.

@dragonfly91 @avneeshrai - Can you please help with this?

**Comment by amarzavery** [comment]
@DheerendraRathor - Can you take a look at this issue?

I saw a test written by the service team in Azure CLI 2.0 where they are creating the unique container name by joining the container type, vm name, resourcegroup name with semicolon over [here](https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt/tests/recoveryservicesbackup_testcase.py#L32-L55).

Hope that helps.

**Comment by MichaelBurgess** [comment]
That link looks very promising thanks @amarzavery.

**Comment by DheerendraRathor** [comment]
@MichaelBurgess Containers actually refer to Azure Vm for VM protection scenarios. So "Create" container API is not part of this SDK. Though a specific format for container name is required `protectedItems.CreateOrUpdate()` as pointed by @amarzavery.

**Comment by amarzavery** [comment]
> Though a specific format for container name is required protectedItems.CreateOrUpdate()

@DheerendraRathor -  Thanks for confirming this. Unless I wouldn't have bothered to talk to my colleagues in python CLI team and take a look at the test written by you over there, I would have never figured out what is it that one should do in this scenario. This is clearly not the ideal way. It would be **great**, if in the description for containerName in the azure-rest-apis-specs repo please provide
- an example of a specific format
- clear explanation that container refers to an Azure VM and that there is no REST API to create this artifact.

If this is documented correctly, it will be reflected in
- the rest api documentation and
- the sdk documentation on docs.microsoft.com website.

/cc @salameer @johanste.

**Comment by MichaelBurgess** [comment]
+1 on suggestion by @amarzavery. I have finally managed to get this working thanks, but have to admit that it's pretty opaque right now as to how to work with these backup APIs.

Thanks for your help so far.

**Comment by mozehgir** [comment]
Looks like the issue has been fixed as the above user got it working. If the error persists feel free to re-open this issue in the https://github.com/Azure/azure-sdk-for-js repository .
