### ISSUE TITLE
Get / Update Managed service identity of Web App

### ISSUE THREAD

**Issue by malafreniere** [Azure/azure-sdk-for-node#2386]
Is there a way to GET and UPDATE the MSI of a Web App ?

On the REST documentation web site, there is an "identity" field in the GET site endpoint: https://docs.microsoft.com/en-us/rest/api/appservice/webapps/get#managedserviceidentity

This field doesn't seem to be returned in the Site object when calling:

```Typescript
let client = new WebsiteManagementClient(webAppCredentials, "subscriptionId", azureEnvironment.resourceManagerEndpointUrl);

const site = await client.webApps.get(resourceGroupName, webAppName);
site.identity??????
```

I would also expect to be able to do, to activate MSI on a webapp:

```Typescript
client.webApps.createOrUpdate(resourceGroupName, webAppName, {
                ...
                identity: {
                    type: "SystemAssigned"
                }
                ...
            });
```
Based on this documentation: https://docs.microsoft.com/en-us/azure/app-service/app-service-managed-service-identity

Thanks !!!

**Comment by amarzavery** [comment]
@malafreniere - The sdk was not auto generated with the latest version of the WebApp swagger spec. Please install `3.0.0-preview` version of `azure-arm-website` to get the latest changes.

**Comment by malafreniere** [comment]
Thanks !
