### ISSUE TITLE
Updating a storage account always includes properties.supportsHttpsTrafficOnly

### ISSUE THREAD

**Issue by MichaelBurgess** [Azure/azure-sdk-for-node#2390]
Hi,

I have noticed an issue where when I update a storage account, say for example to set the `accessTier` to `Hot` using this SDK function:

  https://docs.microsoft.com/en-gb/javascript/api/azure-arm-storage/storageaccounts?view=azure-node-2.2.0 -> `update`

Then `"supportsHttpsTrafficOnly: false"` is always added to the request body:

  `body: '{"properties":{"accessTier":"Hot","supportsHttpsTrafficOnly":false}}' }`

We have an Azure policy in place that denies any storage accounts without encryption in transit enabled, so this request is then denied due to the policy restriction.

I can see from the source here:

  node_modules/azure-arm-storage/lib/models/storageAccountUpdateParameters.js

That there is a default value assigned of `false`, which I assume means this will always be added to any update request, unless the request is to update `supportsHttpsTrafficOnly`?

```
enableHttpsTrafficOnly: {
  required: false,
  serializedName: 'properties.supportsHttpsTrafficOnly',
  defaultValue: false,
  type: {
    name: 'Boolean'
  }
}
```

If I use https://resources.azure.com, I am able to patch a storage account sending an account body of just this:

```
{
  "properties": {
    "accessTier": "Hot"
  }
}
```

Is there a requirement for this additional field to be sent via the SDK?

Many thanks,
Mike.

**Comment by MichaelBurgess** [comment]
Although now I've just been denied patching of a storage account via the REST API due to not providing encryption in transit and the patch request violating Azure policy.

I think I may need to raise this up with Azure support and ask what the correct solution is to be able to patch existing resources that were created before Azure policy was applied.

Our code patches things in isolation, but if this isn't possible without including all other parameters to satisfy a policy, then we may not be able to use Azure policy.

**Comment by amarzavery** [comment]
This is a bug in the [swagger spec for storage management](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/storage/resource-manager/Microsoft.Storage/stable/2017-10-01/storage.json#L1493). There is nothing wrong with the Azure Policy that you have set. They have a separate model for Updating properties of a StorageAccount which is used in a **PATCH** operation. However, they have incorrectly specified `"default": false` for the `"supportsHttpsTrafficOnly"` property. 

> The request body for a **PATCH** operation **MUST NOT** have any **required properties** or **default value** for any _top level or nested_ property. 

This causes a side effect of setting the property with the default value when the user is not interested in updating those properties.

@blueww @JasonYang-MSFT - Can you please fix the spec?
/cc @lmazuel for python sdk.

@salameer @johnaste - Not sure why the linter did not catch this in the PR?

@MichaelBurgess - Until we update the sdk, you can 
- either locally remove the `defaultValue: false` from the mapper of `StorageAccountUpdateParameters` for property `supportsHttpsTrafficOnly`
- OR use `client.sendRequest()` and make the request manually.

I believe the first option would be easier as the updated sdk would have the same change.

**Comment by lmazuel** [comment]
@amarzavery If we follows closely the Swagger spec, we are not supposed to send Swagger default values :/. We discussed already this point with @olydis , currently we mix-up two kinds of default values:
1- Required properties that we want to suggest a default to customer, and send them on the wire. Like VMSize is required, but let's suggest to use standard_v2
2- Default values if the server does not return the value. If we don't receive "supportsHttpsTrafficOnly" from Azure, let's show to customer that it was implicitly `false`

However, I agree with you that this particular model "StorageAccountPropertiesUpdateParameters" is a one way model (from customer to Azure). Meaning the best fix considering current Autorest behavior is to remove the default.

**Comment by amarzavery** [comment]
@lmazuel - I agree with what you are saying. However, I am not sure if removing the auto setting of default values in general will cause a breaking change in the SDK (specifically for query, header parameters, etc.). 

Special case:
> For request body of a PATCH operation we must not set the default value in the sdk if the property  was not set. 

I think we should consider adding the above feature in the serializer (runtime). What do you think?

**Comment by lmazuel** [comment]
Removing auto default is super dangerous, and I don't suggest any runtime changes right now. These two scenario would need to be separated, with maybe a "x-ms-default" for scenario 1 (required, but suggestion), and no extension for scenario 2 (do not sent on the wire, but present the value to customer). And the entire specs set needs to be reviewed before :-( (that was the conclusion we got with @olydis ...)

**Comment by amarzavery** [comment]
This should now be fixed. The SDK will not send the default value of a property while sending the request. https://github.com/Azure/azure-sdk-for-node/pull/5097
