### ISSUE TITLE
Unable to get list of virtual machines that have a particular tag 

### ISSUE THREAD

**Issue by sanjeevsudarshan** [Azure/azure-sdk-for-node#2392]
Hello,

I've been trying to get a list of virtual machines that are associated with a tag. I have not found a way to do this and wasn't sure if this is not supported in azure or if i was missing something/if there is a workaround that I have missed ?.

This is what I have tried so far,

I was looking at the VM API documentation at https://docs.microsoft.com/en-us/javascript/api/azure-arm-compute/virtualmachines?view=azure-node-2.2.0&viewFallbackFrom=azure-node-2.2.0

It doesnt look like theres anyway of filtering on tags using that API.

I tried the resource API and used the filter parameter to get all resources with a tag, but trying to filter on both resourceType(VM) and tags gives an error saying "Invalid filter"

I also see similar errors when using azure rest api

Is there anyway/workaround to get this information ?.

**Comment by amarzavery** [comment]
- There are [CRUD methods for tags](https://docs.microsoft.com/en-us/javascript/api/azure-arm-resource/tags?view=azure-node-2.2.0) in `azure-arm-resource` package. 
- While listing resources you can provide a filter for tags **OR** the resource type, **but not both**, using the `azure-arm-resource` package. 
- For `tags` you can set the [options.filter](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/resourceManagement/lib/resource/operations/resources.js#L355) as
`tagname eq 'CreatedBy'` and for resource type `resourceType eq 'Microsoft.KeyVault/vaults'`.
Again both cannot be provided at the same time.

Verfied with the service team that the error is misleading. It should have been combination not supported rather than incorrect filter.

**Comment by sanjeevsudarshan** [comment]
Thanks @amarzavery , did the service team indicate why this use case or combination was not supported ?. 

Are Individual resources not meant to be tagged together( as in  a set of vms have same tag..etc).? 
I see that we can get resourceGroups that have tag or all resources that have a tag , but not individual resources

**Comment by amarzavery** [comment]
> did the service team indicate why this use case or combination was not supported ?.

I believe that could be resource intensive operation to execute hence the service team has not enabled it.


> Are Individual resources not meant to be tagged together( as in a set of vms have same tag..etc).?
I see that we can get resourceGroups that have tag or all resources that have a tag , but not individual resources

As I said, you can definitely do that. There is nothing wrong in that. However, while listing resources, simply filter by the tagName. You **cannot** filter by tagName **&&** resourceType.

> Also , do you know if there is a combination of APIs that would allow this use case and let us specify page size?

You can make two separate rest calls. Once to filter by tagName/tagValue and the second time to filter by resourceType. You can then find an intersection of both the lists.

```javascript
const msrestAzure = require('ms-rest-azure');
const ArmResource = require('azure-arm-resource');

async function run() {
  try {
    const creds = await msrestAzure.loginWithServicePrincipalSecret('clientId', 'secret', 'tenantId');
    const client = new ArmResource.ResourceManagementClient(creds, subscriptionId);
    let tagName = 'foo';
    let resourcesByTags = await client.resources.list({filter: `tagName eq '${tagName}'`});
    let resourcesByType = await client.resources.list({filter: `resourceType eq '${tagName}'`});

    let filteredResourcesByTagsAndType = resourcesByTags.filter( x=> { return resourcesByType.some(y =>{ return y.id === x.id; } });
    console.log(filteredResourcesByTagsAndType);
    return Promise.resolve();
  } catch (err) {
    console.log(err);
  }
}

run();
```

**Comment by amarzavery** [comment]
@vivsriaus - Can you please take a look at this issue?

**Comment by sanjeevsudarshan** [comment]
Thanks for the workaround @amarzavery , 

@vivsriaus @amarzavery apart from filtering based on parameters, I also had a couple of questions about paging.

Did the service team indicate if this API would ever support the ability to limit page size.

I've found the options that are available for the resource API to be really useful
Do you know if there are any plans to make the sub-resource (vms, disks etc) APIs replicate the options that the resource API provides ?

**Comment by amarzavery** [comment]
> Did the service team indicate if this API would ever support the ability to limit page size.

I am not sure if that is supported. If the api supports an optional query parameter called top or $top then you can provide a value to it and it will return you the top__ results.

> FYI

The way we have paging implemented in the node sdk is that there will be a `list` method and a `listNext` method for that API. The list method will return an array of items. This array will also have a property called nextLink. If that is present, then provide that as an input to `listNext` method and you get the next page.. so on and so forth.. till the returned list does not have the nextLink or nextLink is null.

> I've found the options that are available for the resource API to be really useful. Do you know if there are any plans to make the sub-resource (vms, disks etc) APIs replicate the options that the resource API provides ?

There are some services that have odata query parameters like filter, top, expand, etc. and there are some that do not. Taking a look at the REST API doc and sdk documentation for a particular API can provide you more information.

@huangpf - Do we support filter, top, expand for vms and disks?

**Comment by sanjeevsudarshan** [comment]
Thanks for the information @amarzavery , do you know what the default page size for vms /disk listing is ?.

**Comment by huangpf** [comment]
For the default page size question, please find it from the REST API documentation:
```
https://docs.microsoft.com/en-us/rest/api/compute/manageddisks/disks/disks-list-by-subscription
```

If you can't find this info please 1) create a support ticket to query based on your subscription, or 2) post a question at the Swagger spec repo below, because that's the source of these SDK code.

For the filter question, please find it from the Swagger spec, & if you can't find those filters, they are not supported:
```
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2017-12-01/compute.json
```

**Comment by amarzavery** [comment]
Closing this issue. I haven't heard back from the service team. Looks like the above workaround provided by me is a probable solution for now.
