### ISSUE TITLE
Access Key Vault from functions using MSI

### ISSUE THREAD

**Issue by subesokun** [Azure/azure-sdk-for-node#2395]
Hi, I'd like to know if it's possible to access the Azure Key Vault from functions using MSI (Managed Service Identity). [This C# example](https://blogs.msdn.microsoft.com/cloud_solution_architect/2017/12/22/using-managed-service-identities-in-functions-to-access-key-vault/) worked for me but so far I had no luck with Node.

I was able to get the MSI token via `ms-rest-azure.MSIAppServiceTokenCredentials` within my function but I'm not sure if `azure-keyvault` accepts this token as credential for fetching the secrets from the Key Vault.

If that is not possible yet, are there any plans to add this feature in near future?

Thanks a lot!

**Comment by amarzavery** [comment]
@williexu - Is this possible with new keyvault changes that you have done in the keyvault branch?

**Comment by williexu** [comment]
Yes, this will be possible with our upcoming changes. We have a [issue](https://github.com/Azure/azure-sdk-for-node/issues/2393) out for it. 
In the meantime, you can take a look at a sample we have of the same scenario you described: https://github.com/Azure-Samples/app-service-msi-keyvault-node

Note the sample depends on code that I have on my own public [repo](https://github.com/Azure-Samples/app-service-msi-keyvault-node/blob/master/package.json#L15) at the moment, and will be changed once we merge in our keyvault work.

**Comment by subesokun** [comment]
Awesome, thanks for the quick reply! I'll follow the issue #2393 and close this one 👍  Looking forward to the feature!

**Comment by jbonet07** [comment]
using **azure-keyvault@3.0.4** and **ms-rest-azure@3.0.0**

Hi, I tried to use MSI to access Key Vault following the [https://github.com/Azure-Samples/app-service-msi-keyvault-node](https://github.com/Azure-Samples/app-service-msi-keyvault-node) example, but when I pass the credentials that I get from loginWithAppServiceMSI to the KeyVaultClient I keep getting this error (the credentials object that I get is **MSIAppServiceTokenCredentials** ):

![image](https://user-images.githubusercontent.com/36271817/61224043-200b9c00-a71e-11e9-816f-8f9f5603b681.png)

I even tried to use the loginWithUsernamePassword method in order to get a UserTokenCredentials but I keep getting the same error.


`function getKeyVaultCredentials(){
        return msRestAzure.loginWithAppServiceMSI({resource: 'https://vault.azure.net'});
    }

    function getKeyVaultSecret(credentials) {
        let keyVaultClient = new KeyVault.KeyVaultClient(credentials);
        return keyVaultClient.getSecret(vaultUri, 'secret', "");
    }

    await getKeyVaultCredentials().then(
        getKeyVaultSecret
    ).then(function (secret){
        console.log(`Your secret value is: ${secret.value}.`);
    }).catch(function (err) {
        throw (err);
    });`

**Comment by amarzavery** [comment]
Can you execute `npm list ms-rest`?
I am guessing there are multiple versions of ms-rest. Hence the instanceof check is failing

**Comment by jbonet07** [comment]
Yes, it looks like I have several versions of ms-rest. So ms-rest is also a azure-keyvault dependency?

![image](https://user-images.githubusercontent.com/36271817/61228165-01110800-a726-11e9-89f7-16bfc2c5d8a6.png)

**Comment by amarzavery** [comment]
- `ms-rest` is the runtime package that is responsible for making requests on the wire. 
- `ms-rest-azure` is the runtime for Azure specific stuff (authentication, polling asynchronous operations, etc.)
- `azure-keyvault` depends on `ms-rest-azure` which depends on `ms-rest`.
As you can see `azure-keyvault@3.0.4` brings with it `ms-rest-azure@2.6.0` which brings with it `ms-rest@2.5.3`.
So what is happening is:
> When you `require("ms-rest-azure")` in your app it is using `3.0.0` version of it. `azure-keyvault` internally uses `2.6.0` version of it to convert `MSIAppServiceTokenCredentials` to `KeyvaultClientCredentials`. When it does the `instanceof`check it has the `MSITokenCredentials` from the `2.6.0` version whereas in you app you have it from the `3.0.0` version which are different instances. Hence the `instanceof` check fails. Thus the error...

So, yhy do you have top level `ms-rest-azure@3.0.0` ? Why do you need to have an explicit dependency on `3.0.0` version of `ms-rest-azure`? Can you remove that from your package.json, delete the node_modules folder and the package-lock.json file and execute `npm i` again from the root folder of your app? I am sure the problem will go away.
