### ISSUE TITLE
Broken links: Node.js API documentation for Batch AI

### ISSUE THREAD

**Issue by hxlnt** [Azure/azure-sdk-for-node#2397]
Node.js API documentation link (http://azure.github.io/azure-sdk-for-node/azure-batchai/latest/) results in a 404 error.

Broken link found at http://azure.github.io/azure-sdk-for-node/azure-arm-batchai/latest/ and https://www.npmjs.com/package/azure-arm-batchai.

**Comment by amarzavery** [comment]
You can find the documentation over here https://docs.microsoft.com/en-us/javascript/api/azure-arm-batchai/autoscalesettings?view=azure-node-latest

**Comment by amarzavery** [comment]
Closing this issue as we have ported the docs to docs.ms.com
