### ISSUE TITLE
getKey of Azure Key Vault doesn't return JWK public key info, while .NET SDK does

### ISSUE THREAD

**Issue by tmarkovski** [Azure/azure-sdk-for-node#2399]
I was wondering if this is intentional or a bug. With the .NET SDK, retrieving an EC key using GetKey returns a JWK with X and Y fields populated. This is not the case when using the Node SDK. I tested it on the same key, and the results are different.

**Comment by amarzavery** [comment]
We are working on updating the node sdk for keyvault. The in progress source code is in the [keyvault branch](https://github.com/Azure/azure-sdk-for-node/tree/keyvault) of this repo. 
However, I am not sure if your specific ask is covered in that work. 

@williexu can you verify this ask?

**Comment by williexu** [comment]
@tmarkovski I am seeing the X and Y fields populated in the responsebody when using getKey using the current node sdk. 
Can you show me the response you are seeing? 
Keep in mind the fields should only be present for a key of type "EC".

**Comment by tmarkovski** [comment]
Thanks for looking into this @williexu 
Here's the response from the .NET SDK version 2.4.0-preview

`{"kid":"https://ethkeyvault.vault.azure.net/keys/testEcKey/7e2226fb16e64ca3b4014dc5170e2e5e","kty":"EC-HSM","key_ops":["sign","verify"],"crv":"SECP256K1","x":"p_nQhgFE_By0kk7DXVNoC05XwrVhupieM8msSm-FVck","y":"HYibcS2fRFO-s-2ur8u8RlmPbp-bpcqoRtyEBRaPVWw"}`

And here's the same key query using the Node SDK version azure-keyvault@2.0.1-preview

`{"key":{"kid":"https://ethkeyvault.vault.azure.net/keys/testEcKey/7e2226fb16e64ca3b4014dc5170e2e5e","kty":"EC-HSM","keyOps":["sign","verify"]},"attributes":{"enabled":true,"created":"2018-01-28T22:11:52.000Z","updated":"2018-01-28T22:11:52.000Z"}}`

I'm using "EC-HSM" key type instead "EC" as I need keys with SECP256K1 curve for Ethereum key support.

**Comment by williexu** [comment]
@tmarkovski we had some changes in our keyvault sdk including [this](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/keyVault/lib/models/keyBundle.js#L41-L42), that we did not publish to npm. 
I created a pr, https://github.com/Azure/azure-sdk-for-node/pull/2400, to bump our sdk version and I will publish an updated package to npm later today that should fix this issue.
Sorry for the trouble and thanks for pointing this out :)

**Comment by amarzavery** [comment]
@tmarkovski 2.0.2-preview version of azure-keyvault has been published. Please install the latest version and let us know if you see further problems.

**Comment by tmarkovski** [comment]
@amarzavery @williexu Works like a charm. Thank you so much for your prompt response!

**Comment by tomalex0** [comment]
I have uploaded  a private pem file to `keys` and tried below  function to get the data using `"azure-keyvault": "^3.0.0-preview",`

```
client.getKey(vaultUri, keyName, keyVersion,  {maxresults : 10}, function(err, result)  {
    if (err) throw err;
    
    console.log(result,'-----------key-');
    
} )
```
### result
```
{ key:
    { 
	 kid: 'https://test.vault.azure.net/keys/test/1123123123lksldkf',
     kty: 'RSA',
     keyOps: [ 'sign', 'verify', 'wrapKey', 'unwrapKey', 'encrypt', 'decrypt' ],
     n: <Buffer  ... >,
     e: <Buffer > 
	},
	attributes: { enabled: true,
     created: 2016-02-09T08:48:27.000Z,
     updated: 2016-02-09T08:48:27.000Z,
     recoveryLevel: 'Purgeable'
	} 
} 
```

How can i download the pem file from the `result` ,  any help is much appreciated.

**Comment by williexu** [comment]
What did you use to upload your pem file?

**Comment by Rayzworld** [comment]
> What did you use to upload your pem file?

I had similar result like tomalex0.I want to get keys to used on jwt.sign().How do i work it out?Thanks.

**Comment by ramya-rao-a** [comment]
The `azure-keyvault` package is deprecated in favor of individual packages for keys, secrets and certificates. Please use the newer @azure/keyvault-keys, @azure/keyvault-secrets or @azure/keyvault-certificates and log any issues you see at https://github.com/azure/azure-sdk-for-js

The new packages were written following the [new guidelines for Azure SDKs](https://azure.github.io/azure-sdk/typescript_introduction.html)

You can follow the work done as part of this effort at https://azure.github.io/azure-sdk/

cc @sadasant for any follow up needed here.

**Comment by sadasant** [comment]
Hello everybody!

I am not sure if I'm understanding things correctly.

Using the new client, let's say we create a KeyVault key, with something like the following:

```ts
async function main() {
```

**Comment by sadasant** [comment]
Hello everybody!

I am not sure if I'm understanding things correctly.

Using the new client, let's say we create a KeyVault key, with something like the following:

```ts
import { ClientSecretCredential } from "@azure/identity";
import { KeyClient } from "@azure/keyvault-keys";

async function main() {
  const credential = await new ClientSecretCredential(
    process.env.AZURE_TENANT_ID,
    process.env.AZURE_CLIENT_ID,
    process.env.AZURE_CLIENT_SECRET
  );

  const keyVaultUrl = `https://myKeyVault.vault.azure.net`;
  const client = new KeyClient(keyVaultUrl, credential);

  // Creating the KeyVault Key
  const keyName = "myKeyName";
  const keyVaultKey = await client.createKey(keyName, "RSA");
}

await main();
```

Using the same credentials, and the just created key, we can use the cryptography client to sign and verify some data, as follows:

```ts
import { ClientSecretCredential } from "@azure/identity";
import { KeyClient, CryptographyClient } from "@azure/keyvault-keys";
import { createHash, publicEncrypt } from "crypto";

async function main() {
  const credential = await new ClientSecretCredential(
    process.env.AZURE_TENANT_ID,
    process.env.AZURE_CLIENT_ID,
    process.env.AZURE_CLIENT_SECRET
  );

  const keyVaultUrl = `https://myKeyVault.vault.azure.net`;
  const client = new KeyClient(keyVaultUrl, credential);

  // Creating the KeyVault Key
  const keyName = "myKeyName";
  const keyVaultKey = await client.createKey(keyName, "RSA");

  const cryptoClient = new CryptographyClient(keyVaultKey.id!, credential);

  // Defining a value to sign
  const signatureValue = "my value";

  // Creating a hash
  const hash = createHash("sha256");
  hash.update(signatureValue);
  const digest = hash.digest();

  // Signing some data
  const signature = await cryptoClient.sign("RS256", digest);

  // Verifying the result
  const verifyResult = await cryptoClient.verify("RS256", digest, signature.result);
  console.log(verifyResult) // Should be true.
}

await main();
```

I'll make another comment regarding PEM files.

**Comment by sadasant** [comment]
For certificates we have the [`@azure/keyvault-certificates`](https://www.npmjs.com/package/@azure/keyvault-certificates) package now. It will let you create, import and use certificates in various ways. I will provide some useful links:

- [The keyvault-certificate's readme](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/keyvault/keyvault-certificates/README.md), of course.  
  Keep in mind that our readme has information that could be extra relevant for you, for example:
  - How to [get a Key Vault certificate](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/keyvault/keyvault-certificates/README.md#getting-a-key-vault-certificate).
  - How to [get the full information of a certificate](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/keyvault/keyvault-certificates/README.md#getting-the-full-information-of-a-certificate).
  - And on handling [certificates in PEM format](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/keyvault/keyvault-certificates/README.md#certificates-in-pem-format).
- [Our current samples](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/keyvault/keyvault-certificates/samples) in both JavaScript and TypeScript.
- A test that can be used to see how to import a PEM-encoded certificate: https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/keyvault/keyvault-certificates/test/mergeAndImport.test.ts#L67-L94 . There we're using an existing PEM certificate inside of a KeyVault, but through specifying the `contentType: "application/x-pem-file"` on the given policy, you can pase a Uint8Array copy of your PEM certificate and things should work fine. Please report to us if this is not the case.
