### ISSUE TITLE
The api-version used for notificationhub/servicebus is outdated.

### ISSUE THREAD

**Issue by tony-gutierrez** [Azure/azure-sdk-for-node#2407]
CURRENT_API_VERSION: '2013-07' 

used for servicebus/notification hub is over 4 years old. Can you please update it to use the slightly less antiquated value of "2016-07" ??? 

Some per message telemetry requires notifications be sent with the newer api version.

**Comment by amarzavery** [comment]
@ankurkul - Can you take a look at this issue?

**Comment by tony-gutierrez** [comment]
This has been updated in the latest release. Closing.
