### ISSUE TITLE
Node SDK tasks

### ISSUE THREAD

**Issue by amarzavery** [Azure/azure-sdk-for-node#2409]
- [x] Work with Laurent/Martin Strobel to dish out the rest api specs to SDK pipeline.

- [ ] NodeJS code generator changes
   - [x] We can make some subtle non breaking changes to the nodejs code generator. These changes need to be made to the way the client is exported from the client file in a given sdk. We would also need to make some changes in the generated d.ts file as well. This will help us in making it easy to move to the TS code generator. It basically removes the only breaking change that we would have, thus making the move seamless.
   - [ ] Make changes to the nodejs codegenerator to set package name and version as a constant in the generated code. Today we traverse the filesystem to get the package.json. From the package.json we get the packageName and the packageVersion. This info is then sent in the user-agent string to track for telemetry purposes. At times we are not able to find the right package.json and we end up sending No-package/0.0 in the user-agent string. This messes up the telemetry. It would be nice if we autogenerate a new file called `packageInfo.json` which contains `{name: "", version: "" }`. This should solve the problem.
- [ ] Work with the doc team to improve documentation of the models for a given sdk. The [source code for a given model class](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/storageManagement2/lib/models/storageAccount.js#L22) provides documentation but the [doc site](https://docs.microsoft.com/en-us/javascript/api/azure-arm-storage/storageaccount?view=azure-node-latest) only documents the empty constructor and the mapper function.. Issue filed by doc team over [here](https://github.com/Azure/autorest/issues/2848).
/cc @salameer

**Comment by daschult** [comment]
I broke this issues out into several new issues, so I'm closing this one.
