### ISSUE TITLE
[Help Wanted] Can I create an ACI using node sdk?

### ISSUE THREAD

**Issue by jdneo** [Azure/azure-sdk-for-node#2410]
Looks like currently we only support `list`, is that true?

**Comment by amarzavery** [comment]
Can you be a little more specific about what do you want to achieve? If you are talking about Azure Container Instance then we support a bunch of operations https://github.com/Azure/azure-sdk-for-node/tree/master/lib/services/containerinstanceManagement/lib/operations

**Comment by amarzavery** [comment]
We have published an update to azure-arm-containterinstance. Let me know if that solves the problem.

**Comment by jdneo** [comment]
@amarzavery Thank you for the information. Yes it solved my problem.
