### ISSUE TITLE
Cors issue when attempting to login?

### ISSUE THREAD

**Issue by meds** [Azure/azure-sdk-for-node#2413]
I have the following set up:

```
var msRestAzure = require('ms-rest-azure');
var graphRbacManagementClient = require('azure-graph');
var clientId = 'application id from B2C';
var secret = 'generated key from b2c keys blade';
msRestAzure.loginWithServicePrincipalSecret(clientId, secret, tenantId, 
{ tokenAudience: 'graph' }, function (err, credentials, subscriptions) {
    if (err) console.log(err);
    var ok = 0;
});
```

Running in Chrome on localhost:3000 I get an error:

> Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

I suspect it might be a CORS issue related to the Azure AD B2C I'm trying to connect to but I'm not sure. The Azure Functions App I've tied to the B2C directory works fine and has CORS setup for the localhost address but I can't find where to do it for the AD B2C application itself which leads me to believe it might not be the issue but something else?

**Comment by amarzavery** [comment]
This library is not meant to be run in the browser, it can run on the server side (node.js environment, console app). We are working on a different project that will make the library isomorphic. 
If you want to use browser specific authentication then you need to use adal-js https://github.com/AzureAD/azure-activedirectory-library-for-js

**Comment by meds** [comment]
Looks like that library only works with angular which sadly means it won't work for my purposes :(

I guess I'll try to roll my own with azure functions.

**Comment by amarzavery** [comment]
Take a look at this repo [ms-rest-jsauth](https://github.com/balajikris/ms-rest-jsauth). We have played with the adal-js library and created a sample using pure javascript. Do take a look at the sample and the instructions in the README.
