### ISSUE TITLE
Content-Type set to json when request payload/body is null

### ISSUE THREAD

**Issue by nagpal** [Azure/azure-sdk-for-node#2414]
Hi

When [associating an API product to a API group](http://azure.github.io/azure-sdk-for-node/azure-arm-apimanagement/latest/ProductGroup.html#createOrUpdate) or when [associating an API product to an API](http://azure.github.io/azure-sdk-for-node/azure-arm-apimanagement/latest/ProductApi.html#createOrUpdate), the requests fail with the Azure WAF switched on with all OWASP 3.0 rules enabled.

After a bit of digging around, it seems the culprit is the Content-Type header that is set to 'application/json; charset=utf-8' even though there is no body/payload in the http PUT request.

I am no expert when it comes to HTTP headers, but it seems semantically incorrect to set the Content-Type HTTP header when the request body is null. This seems to trip Azure WAF (which probably tries to parse the payload/body as JSON).

-Vijay

**Comment by amarzavery** [comment]
@nagpal - I do not see any issues with this. I tried the following and everything worked well

```javascript
var msRestAzure = require('ms-rest-azure');
var apiManagement = require("azure-arm-apimanagement");

// Interactive Login
// It provides a url and code that needs to be copied and pasted in a browser and authenticated over there. If successful, 
// the user will get a DeviceTokenCredentials object.
msRestAzure.interactiveLogin(function (err, credentials) {
  let client = new apiManagement(credentials, 'subscriptionId');
  client.productApi.createOrUpdate('testrg', 'testapiMgmt', 'starter', 'test-api').then((apiContract) => {
    console.log('API Contract');
    console.dir(apiContract, { depth: null, colors: true });
  }).catch((err) => {
    console.log('An error ocurred');
    console.dir(err, { depth: null, colors: true });
  });
});
```

This is the output:
```json5
API Contract
{ id: '/subscriptions/testsubscription/resourceGroups/testrg/providers/Microsoft.ApiManagement/service/testapiMgmt/products/starter/apis/test-api',
  name: 'test-api',
  type: 'Microsoft.ApiManagement/service/products/apis',
  apiRevision: '1',
  isCurrent: true,
  displayName: 'Test API',
  serviceUrl: 'http://testapi.cloudapp.net/api',
  path: 'test' }
```

- Can you provide your sample script and the detailed error from the server?
- Did you try removing the content-type and did that work for you?

**Comment by nagpal** [comment]
@amarzavery I should have been more specific. We have a App Gateway in front of the API management service. So the request really goes to WAF (on appgateway) ==> App Gateway ==> API management service. 

These commands work fine with the WAF turned off on the App Gateway. 

It is only when the WAF is switched on that the two API mentioned above do not work. We get back a 500 Internal Server error from the WAF and the error logs indicate JSON parse errors - which I think is because of Content-Type set to 'application/json'. 

Removing the 'Content-Type' header through an external REST client like Postman worked. So for now we do not use node-sdk for these 2 calls, instead using the REST API without the 'Content-Type' header.

This is how we create the client
```
const authToken = generateAuthToken(apiIdentifier, apiPrimaryKey);
const credentials = new TokenCredentials(authToken, 'SharedAccessSignature');
const client = new ApiManagement(credentials, subscriptionId, apiManagementBaseUri);
```

We first create the product like so:
```
const productDetails = await jsonFromFile('product.json');
await client.product.createOrUpdate(resourceGroupName, serviceName, productId,  productDetails);
```

and then associate the product with the developers group (that comes out of the box)
```
await client.productGroup.createOrUpdate(resourceGroupName, serviceName, productId, groupId);
```

Here is the snapshot of the Firewall log from Log Analytics

![image](https://user-images.githubusercontent.com/332066/36025037-978b8fa4-0d89-11e8-8f57-4874feea7aa2.png)

**Comment by amarzavery** [comment]
@nagpal - I see thanks for explaining. I think initializing `httpRequest.body = null;` could also be the culprit. Can you please comment [this line](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/apimanagement/lib/operations/productApi.js#L394) in the sdk code and try making the sdk call with WAF `on`?

This change would still set the content-type as-is but the request object will not have a body property at all (In javascript null and undefined have different semantics). We had a similar problem for GET and HEAD requests where the body was being set to null and Firefox v45 browser did not like it. Hence want to know if this problem fits into the same bucket.

**Comment by amarzavery** [comment]
I wasn't aware about WAF. Little bit of googling and I found this [doc](https://docs.microsoft.com/en-us/azure/application-gateway/application-gateway-web-application-firewall-overview). So this could be that the Web Application Firewall Gateway is too strict? 

/cc @johanste @olydis - Have you guys known about this as an HTTP rule ?

**Comment by amarzavery** [comment]
An [SO link](https://stackoverflow.com/questions/29784398/should-content-type-header-be-present-when-the-message-body-is-empty) for reference.

**Comment by johanste** [comment]
[RFC2616](https://tools.ietf.org/html/rfc2616#section-7.2.1) specifies that content-type **should** be sent (note should, not must) *if* a message body is included. It does *not* explicitly mention what to do if a message body is *not* included. Additionally, given that an empty string/content-length = 0 (as opposed to a string with two quotes/content-length = 2) is not valid json, I can see why some applications would find the payload problematic for content-type = application/json, and thus why WAF would consider it as a valid case to block for a PUT/PATCH/POST request without a message body. 

On the other hand, a HEAD response **should** include the content type even though, in that case, the response body should be empty/content-length set to 0. So in that case, if WAF were to block the request, I would consider it incorrect.

**Comment by nagpal** [comment]
Yes @johanste I read the RFC for Content-Type before raising this issue. Unfortunately it is not really helpful for when the body is empty. Maybe what I can do it set the Content-Length to 0 and see if the firewall is happy with the request.

@amarzavery give me some time, I'll remove the line of code that explicitly sets the body to null and test with that. I'll report my findings soon.

**Comment by amarzavery** [comment]
I'll remove the line of code that explicitly sets the body to null and test with that. I'll report my findings soon.
@nagpal - Any updates with the ask?
