### ISSUE TITLE
GetMessageAsync for node

### ISSUE THREAD

**Issue by ArturPrzybysz** [Azure/azure-sdk-for-node#2415]
I am looking for a way to detect new messages in azure queue. I have found in .NET sdk getMessageAsync, which fits perfectly but sadly i cannot find its equivalent in nodes sdk. 

Am I missing something and its available, or its simply not implemented?

**Comment by amarzavery** [comment]
We are working on a newer service bus library. The current library `azure-sb` is not being actively maintained.

**Comment by tony-gutierrez** [comment]
Is there a url for the newer library?

**Comment by amarzavery** [comment]
It is not yet ready. The new library that is being developed is based on amqp protocol. As soon as we have something ready we will share the early bits with you.

**Comment by amarzavery** [comment]
@tony-gutierrez The current sbus sdk `azure-sb` is an http based library. It is much slower than an amqp based library. That is the prime reason we are working on building a better amqp based library. 
I saw that you have been looking at  [node-amqp10](https://github.com/noodlefrenzy/node-amqp10). 

Did you ever get a chance to look at [rhea](https://github.com/grs/rhea)?

**Comment by tony-gutierrez** [comment]
Haven't looked at it. I gave it a quick try but ran into 
```
[connection-1] error on read: ProtocolError: Invalid AMQP protocol id 2 expecting: 0  (buffer:0x41,0x4d,0x51,0x50,0x02,0x01,0x00,0x00)
[connection-1] error: Error: read ECONNRESET
```

Also amqp10 is by one of your colleagues!

**Comment by amarzavery** [comment]
Oh! amqp10 is written by one of my colleagues. However there is some history to it. It was written by him when he was actively working on that project, while he was not an MS employee. He and his other colleague have moved on to other projects and the library isn't actively being maintained yet. Some teams in azure took a dependency on amqp10 library and found multiple issues with the way the library manages the states of link, session, connection. 

As a part of developing an amqp based node.js library for servicebus we are evaluating all the options along the vertical stack w.r.t it's stability, performance and active maintenance.

I got rhea working for a simple send receive with sbus. Here is the [script](https://gist.github.com/amarzavery/0a386db40c6d436cbf1d62cec8662018).
```
node test.js Endpoint=amqps://<foo>.servicebus.windows.net;SharedAccessKeyName=<KeyName>;SharedAccessKey=<keyValue> <queueName>
```

**Comment by tony-gutierrez** [comment]
I gave a try to send the sas token to $cbs but I cant even get it to connect to the service bus in anonymous mode.

**Comment by tony-gutierrez** [comment]
@amarzavery Do you by any chance know anything about posting to notification hub with amqp? If I can do that I can get rid of the last vestige of the azure api.

We have had a lot of issues with the linux app service network being super slow to reach the http post endpoints for both NH and SB. Times out about 60% of the time sometimes. MS is on that issue, but I'd love to be full AMQP.

**Comment by amarzavery** [comment]
I have not played with notification hubs. I am playing with eventhubs right now.

For $cbs, i was able to connect. However, I am getting an error in the end. I am messing up somewhere. I am trying to send `put-token` and get the initial response. 

For SASL anonymous, only provide the username while connecting, do not provide the password. Then rhea will automatically apply sasl anonymous. you can enable `set DEBUG=rhea*` and see the debug logs. You will see that while negotiating SASL mechanism it is using the "ANONYMOUS" performative.
I see an error like this:
```
rhea:events Link got event: message +25ms
rx:  {"correlation_id":"bda886b0-28b8-4de8-ba1a-34b099783030","application_properties":{"status-code":500,"status-description":"The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101","error-condition":"amqp:internal-error"}}
```
Hopefully will be able to figure out something by tomorrow for $cbs.

**Comment by tony-gutierrez** [comment]
For amqp10 that token had to be sent as a special type AMQPval. Not sure how you will tell rhea to force it to that type. Add a listener on $cbs and set the replyTo property on your token message to point to $cbs to aid in debugging. Make sure you have you application_properties on that token message too.

**Comment by amarzavery** [comment]
I got the basic `put-token` request part of cbs auth working for eventhubs. I am sure it would be the same for service bus as well. Here is the [link](https://github.com/pierreca/rhea-samples-azure/blob/master/cbs.js) to the sample.

**Comment by tony-gutierrez** [comment]
@amarzavery Have you gotten any farther in your RHEA implementations? I have to make some changes to SB AQMP code and thought now might be a good time to look at it again. Let me know if you have any newer code samples.

**Comment by JordanLozinski** [comment]
@amarzavery Any updates on that AMQP based service bus library? Also, could I have any guidance on using amqp10 or that rhea script for receiving messages async from SB topics?

**Comment by amarzavery** [comment]
@ArturPrzybysz , @tony-gutierrez - 
Please try the new sdk `npm i @azure/service-bus`. 

Sample for the above mentioned usecase can be found here https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/servicebus/service-bus/samples/typescript/gettingStarted/receiveMessagesStreaming.ts#L33

Please file service bus related issues in the new repo https://github.com/Azure/azure-sdk-for-js

**Comment by tony-gutierrez** [comment]
@amarzavery Does this also cover notification hub?

**Comment by tony-gutierrez** [comment]
The sdk reference doesnt seem to be updated? https://docs.microsoft.com/en-us/javascript/api/azure-sb

**Comment by amarzavery** [comment]
The API docs still need to be updated as we are in the process of creating the API docs for the new sdk. Nope it does not cover notification hubs yet. We have new sdks for EventHubs and ServiceBus.
/cc @ramya-rao-a
