### ISSUE TITLE
Store credentials from interactive login on disk and read them back

### ISSUE THREAD

**Issue by mattiasholmlund** [Azure/azure-sdk-for-node#2416]
I am writing a set of tools to install and run an application on Azure Compute. My tool is a node-program with several sub-commands that you run one after the other to deploy our application. I want it to work like this:

```
sye azure login
sye azure cluster-create test1
sye azure region-add test1 uswest
...
```

I want to use the interactive login feature in the `sye azure login` command, write the retrieved credentials on disk and then read them back and use them in the subsequent commands.

Is this possible to do? I have looked at the DeviceTokenCredentials, but it does not seem to be possible to write that to disk directly and read it back.

**Comment by amarzavery** [comment]
We do not support writing tokens to and reading tokens from the file out of the box. However, it should be doable with little workaround. 
All the `login*` methods take tokenCache as an optional parameter. You can use the utility files from [here](https://github.com/Azure/azure-sdk-for-node/tree/master/lib/util) to read tokens from a file and then provide the token cache. Once the authentication is successful in the callback you can serialize and save the token cache to the file.

We were using this concept for the old CLI 1.0 which is node.js based. You can take a look at some sample code over [here](https://github.com/Azure/azure-xplat-cli/tree/dev/lib/util/authentication).

**Comment by amarzavery** [comment]
@yugangw-msft - Do we need to take care of anything else apart from what i suggested in the above comment?

**Comment by mattiasholmlund** [comment]
Thank you for the pointers. I have implemented a very simple tokenCache in the following program:

```javascript
import * as MsRest from 'ms-rest-azure'

process.on('unhandledRejection', (reason, p) => {
    console.log('Unhandled Rejection at:', p, 'reason:', reason)
})

class MyTokenCache {
    private tokens: any[] = []
    constructor() {}

    isSecureCache() {
        console.log('isSecureCache')
        return true
    }

    add(entries: any, cb: any) {
        console.log('add', entries)
        this.tokens.push(...entries)
        cb()
    }

    remove(entries: any, cb: any) {
        console.log('remove', entries)
        this.tokens = this.tokens.filter((e) => {
            return !(Object.keys(entries[0]).every( key => e[key] === entries[0][key] ))
        })
        cb()
    }

    clear(cb: any) {
        console.log('clear')
        this.tokens = []
        cb()
    }

    find(query, cb) {
        console.log('find', query)
        let result = this.tokens.filter((e) => {
            return Object.keys(query).every( key => e[key] === query[key] )
        })
        console.log(result)
        cb(null, result)
    }
}

let tokenCache = new MyTokenCache()

async function getCredentials() {
    console.log('login1')
    console.log('login1 result', await MsRest.interactiveLogin({tokenCache}))
    console.log('login2')
    console.log('login2 result', await MsRest.interactiveLogin({tokenCache}))
    console.log('done')
    process.exit()
}

getCredentials()
```

When the login is finished I get calls to add, find and remove for the tokenCache, but I don't get any calls to the tokenCache before the `To sign in, use a web browser...` text is printed on the console. In my program, I expected the second call to interactiveLogin() to use the data in the tokenCache to login and not ask the user for credentials again. How can I make the login use the information in the tokenCache to login and/or access the azure API?

**Comment by amarzavery** [comment]
> but I don't get any calls to the tokenCache before the To sign in, use a web browser... text is printed on the console.

I assume you intended to say that you don't get calls to the tokenCache before the second call to interactive login..

Interactive login call is designed to call adal to get the device code. Take a look at the source code over [here](https://github.com/Azure/azure-sdk-for-node/blob/master/runtime/ms-rest-azure/lib/login.js#L197).

If you compare `interactiveLogin()` to other calls `loginWithUsernamePassword()`, `loginWithServicePrincipalSecret`, they ask for username and clientId respectively. This can be used to find out whether you have tokens for the respective user in the token cache, and if they are not expired then let's use them. However, that is not possible in the interactive flow, since everything happens in the browser. After successful authentication, adal provides us the username of the entity that was logged in from the browser.

Let us assume that you have the tokenCache stored in a file at a particular location (somewhere in the user's home profile). Now, you will have to write a convenience method that would accept username as an optional parameter. If the username is provided, you can use that information to query the token cache and if the token is still valid then use that, otherwise, remove the entry from the token cache, call `interactiveLogin()`, let the user authenticate in the browser, which would refresh the token cache.

**Comment by mattiasholmlund** [comment]
I have it figured out now. I can create a DeviceToken from the tokenCache with the following code:

```typescript
        let options: MsRest.DeviceTokenCredentialsOptions = {}
        options.tokenCache = tokenCache
        let token = tokenCache.first()
        options.username = token.userId

        let credentials = new MsRest.DeviceTokenCredentials(options)
```

Thank you for your help! Feel free to close the issue now unless you want to build this functionality directly into the library.

**Comment by amarzavery** [comment]
Awesome. Curious to know, what does `tokenCache.first()` do? Does it give you the first entry from the cache?

**Comment by mattiasholmlund** [comment]
Yes. It seemed that the userId was the same for all entries in the tokenCache anyway, so I just needed one of them. Here is the complete code:

```typescript
import * as fs from 'fs'
import * as MsRest from 'ms-rest-azure'

class MyTokenCache {
    private tokens: any[] = []
    constructor(readonly clusterId: string) {
        this.load()
    }

    isSecureCache() {
        throw 'isSecureCache not implemented'
    }

    add(entries: any, cb: any) {
        this.tokens.push(...entries)
        cb()
    }

    remove(entries: any, cb: any) {
        this.tokens = this.tokens.filter((e) => {
            return !(Object.keys(entries[0]).every( key => e[key] === entries[0][key] ))
        })
        cb()
    }

    clear(cb: any) {
        this.tokens = []
        cb()
    }

    find(query, cb) {
        let result = this.tokens.filter((e) => {
            return Object.keys(query).every( key => e[key] === query[key] )
        })
        cb(null, result)
    }

    //
    // Methods specific to MyTokenCache
    //
    empty() {
        this.deleteOld()
        return this.tokens.length === 0
    }

    first() {
        return this.tokens[0]
    }

    private filename() {
        return `${process.env.HOME}/.sye/${this.clusterId}.tokens.json`
    }
    private load() {
        try {
            this.tokens = JSON.parse(fs.readFileSync(this.filename()).toString())
            this.tokens.map(t => t.expiresOn = new Date(t.expiresOn))
        }
        catch (e) {}
    }

    save() {
        fs.writeFileSync(this.filename(), JSON.stringify(this.tokens))
    }

    private deleteOld() {
        this.tokens = this.tokens.filter( t => t.expiresOn > Date.now() - 5*60*1000)
    }

}

let tokenCache:MyTokenCache

export async function getCredentials(clusterId: string): Promise<MsRest.DeviceTokenCredentials> {
    if(!tokenCache) {
        tokenCache = new MyTokenCache(clusterId)
    }

    if( clusterId !== tokenCache.clusterId ) {
        throw `clusterId ${clusterId} !== ${tokenCache.clusterId}`
    }

    if(tokenCache.empty()) {
        let credentials = await MsRest.interactiveLogin({tokenCache})
        tokenCache.save()
        return credentials
    }
    else {
        let options: MsRest.DeviceTokenCredentialsOptions = {}
        let token = tokenCache.first()
        options.tokenCache = tokenCache
        options.username = token.userId

        let credentials = new MsRest.DeviceTokenCredentials(options)
        return credentials
    }
}
```

The clusterId is a way of having different installations with different azure credentials. Each invocation of our tool only handles one clusterId.

**Comment by amarzavery** [comment]
As long as the same user wants to login as the same entity then this will work. If the user also logs in as a service principal later and then as another active directory user then that logic will fail.

**Comment by mattiasholmlund** [comment]
Yes, I understand that. That is why I use a separate authentication file for each cluster that our tool sets up. When a user works on that cluster he should always use the same credentials to log in to azure. For another cluster he might be using another set of credentials. For each invocation of our tool, it will only work with a single cluster.

We might have to support Service Principal usage in the future, but for that use-case I don't need to store the token-cache on disk at all.

The code will be used in https://github.com/netinsight/sye-tools when I have polished it a bit more.

**Comment by amarzavery** [comment]
I see. Ok that makes sense. Just wanted make sure you know about this scenario. 

You are right about service principal. There is a convenience method [`msRestAzure.loginWithAuthFile()`](https://github.com/Azure/azure-sdk-for-node/blob/master/runtime/ms-rest-azure/lib/login.js#L657) that we have provided for service principal usage that could be useful.

**Comment by amarzavery** [comment]
closing this issue as it has been resolved.
