### ISSUE TITLE
Cannot use a property named "origin" as a brokerProperty 

### ISSUE THREAD

**Issue by paulmarshall** [Azure/azure-sdk-for-node#2418]
Using node in an azure function, I'm attempting to send a BrokeredMessage to a ServiceBus Topic. In this message I want to add "origin" as a property with brokerProperties in order to add a SqlFilter on a subscription.

However, looking at the message using ServiceBusExplorer, the origin property is not there.

If I rename the property, the property appears - so there is something significant about a brokerProperty called "origin".

**Comment by amarzavery** [comment]
Please try out the new servicebus sdk `npm i @azure/service-bus`. 

The sample to send a message to a topic can be found [here](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/servicebus/service-bus/samples/typescript/advancedFeatures/topicFilters.ts#L69).

Source code for the new servicebus sdk can be found [here](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/servicebus/service-bus).

In future please open service bus related issues in the new repo https://github.com/Azure/azure-sdk-for-js
