### ISSUE TITLE
SDK error object format is very inconsistent making error handling difficult

### ISSUE THREAD

**Issue by vjtirumalai** [Azure/azure-sdk-for-node#2424]
I am using 2.2.1-preview version, and have used the resource and compute management client.

Here are my current challenges:
In my code I often try to check if the error returned by azure SDK is a client side or a server side error. Unfortunately based on the type of error scenario, I don't get this code most of the time. Further more an internal error code is also not set all the time.

Here are the **4 forms of error** objects I have seen till now, maybe there are more:
1. Error object with only the message and stack attribute set. There is not status code so I really cannot do much with the object expect for to default to an internal server error.

2. Error object has an additional code attribute set which has the internal error code name. Try it when you use a compute mgmt client to list a non existing VM.

3. Error object does not have the code attribute, but has an embedded JSON error object in its message. Try reproducing using a mgmt client whose credentials are invalid. Here is an example:
'Failed to acquire token for application with the provided secret.\n Error: Get Token request returned http error: 401 and server response: {"error":"invalid_client", "error_description":"AADSTS70002: Error validating credentials. AADSTS50012: Invalid client secret is provided. ...'

**Here I have an internal error code assigned to the error attribute** which could be useful to me to tell end user that the credentials are invalid, but I have to extract this information today.

4. Error object does not have the code attribute, but has **another flavor** of embedded JSON error object in its message. Try reproducing using a resource mgmt client with invalid resource group name. Here is an example:
'"{\"error\":{\"code\":\"ResourceGroupNotFound\", \"message\":\"Resource group \'rgdoesnotexist\' could not be found.\"}}"';

**Here I have an internal error code assigned to the error attribute's code key** which could be useful to me to tell end user that the resource group name is invalid, but I have to extract this information today. Not only that, but the double quotes are escaped which is a bad practice as JSON.parse on client side would fail.

As you can see with such inconsistent, and insufficient information in the error objects, error handling using the SDK is difficult. 

Furthermore I don't see the common REST API error codes documented https://docs.microsoft.com/en-us/rest/api/storageservices/common-rest-api-error-codes anywhere in the code base.  I would strongly recommend doing that and setting these codes while responding with these common errors. I use API documentation to look at error codes and how I would like to handle them in my code. I will adda  separate issue for this request. #2425

**Comment by amarzavery** [comment]
Thanks for filing the issue. We will definitely look into this.

Errors can happen at different levels
1. Serialization error: a required parameter was not provided, invalid type was set for a complex object, correct enum value was not provided, etc. Here the request was never made and the sdk caught these issues during serialization
2. Deserialization error: A request was made, response was received from the server but the sdk was not able to deserialize the response correctly.
3. Authentication errors: Invalid credentials or it could be something else.
4. Errors returned by the service. For example getting a VM that does not exist. Service sends you back a 404. (In this case, we deserialize the error response and set the properties accordingly).


A side note: Using `const azure = require("azure")` is easy to use. However, it is not a recommended approach. It brings you sdks for more than 70 services (in your node_modules). I am pretty sure you would not be using all of them. Moreover the rollup packages are not updated frequently (once in 6 months). In majority of the cases, individual packages (azure-arm-compute, azure-arm-storage, etc.) are updated as and when there is an update to a particular service (new apis added to an existing api-version, or a new api-version all together). Hence I would recommend to take a direct dependency on packages for services that you are interested in. This will keep your app light weight and you will be getting the latest stuff for that service.

**Comment by nli8n** [comment]
what was done to fix it ? Still facing issues in extracting error code and error description
