### ISSUE TITLE
Azure Common REST API codes are not documented and used by the SDK

### ISSUE THREAD

**Issue by vjtirumalai** [Azure/azure-sdk-for-node#2425]
I don't see the common REST API error codes documented https://docs.microsoft.com/en-us/rest/api/storageservices/common-rest-api-error-codes anywhere in the code base. I would strongly recommend doing that and setting these codes while responding with these common errors. I use API documentation to look at error codes and how I would like to handle them in my code. I will add a separate issue for this request. 

See more context in #2424

**Comment by amarzavery** [comment]
@vjtirumalai - The error codes that you are listing are documented for the storage service. These may not be applicable to other services. The "azure" (rollup) package contains a bunch of services. There is no way in which we can standardize the error codes across all the services. Hence we give an error object back which contains more information in it.
