### ISSUE TITLE
blobSvc.createBlockBlobFromBrowserFile is not a function

### ISSUE THREAD

**Issue by rahulraibit** [Azure/azure-sdk-for-node#2429]
Hi I want to upload file from the browser to my azure blob using SAS URL. But when I am using 'createBlockBlobFromBrowserFile ' this method. I am always getting that function does't exist

var azure = require('azure-storage');
var blobSvc = azure.createBlobServiceWithSas('https://XXXXXXXXXX', 'XXXXXXXXX"');

blobSvc.createBlockBlobFromBrowserFile('testmigration', 'taskblob', 'abc.txt', function (error, result, response);
 
ERROR  : blobSvc.createBlockBlobFromBrowserFile is not a function

Your help will be highly appriciated

**Comment by amarzavery** [comment]
Please file an issue in https://github.com/azure/azure-storage-node repo
