### ISSUE TITLE
ContainerInstance Management - wrong method name?

### ISSUE THREAD

**Issue by dgkanatsios** [Azure/azure-sdk-for-node#2455]
Should this method just be called "delete" instead of "deleteMethod"?

https://github.com/Azure/azure-sdk-for-node/blob/3431d0d1a82f920c4a4e826d63b20f32d0815418/lib/services/containerinstanceManagement/lib/operations/containerGroups.js#L1631

Other methods do not contain the 'Method' suffix

**Comment by amarzavery** [comment]
@dgkanatsios - We autogenerate all the control/manangement plane sdks and containerInstance happens to be one of them. There is a rule in the code generator to suffix reserved words in a given language. `delete` happens to be a reserved word in javascript, hence it is suffixed with `Method`. 

Is there any problem with this?

**Comment by dgkanatsios** [comment]
My bad, totally forgot that ‘delete’ is reserved. Thank you!
