### ISSUE TITLE
Provision failed

### ISSUE THREAD

**Issue by Gauravba** [Azure/azure-sdk-for-node#2459]
Provisioning failed. OS Provisioning for VM 'MasAgent' did not finish in the allotted time. The VM may still finish provisioning successfully. Please check provisioning state later.. OSProvisioningTimedOut

hi i am also facing this issue and i am using An image which is present in Azure market place VM didnot came up finally i used ansible scripts for bringing up vm sometimes this vm is getting succesfully deployed sometimes failing what can be done

**Comment by amarzavery** [comment]
@Gauravba - Can you provide the response and it's headers. That will help the service team in finding out what went wrong.

**Comment by huangpf** [comment]
Service API issue, or about better error messaging.

**Comment by huangpf** [comment]
@hyonholee FYI.

**Comment by huangpf** [comment]
@changov may have better explanation and advice on this.

**Comment by huangpf** [comment]
@smotwani for CRP VM API.
