### ISSUE TITLE
Cosmos Db add database

### ISSUE THREAD

**Issue by keodime** [Azure/azure-sdk-for-node#2460]
I'm using azure-arm-cosmos and seems like their's no way to add a database to an existing cosmosDb.
Am I wrong ?
If so, when will we be able to do it ?

**Comment by amarzavery** [comment]
@keodime - What version of the `azure-arm-cosmosdb` are you using? We published an updated version `1.1.0-preview` 12 days ago? Are you using that package version?

**Comment by amarzavery** [comment]
@keodime - It looks like that you need to use the dataplane sdk for cosmosdb (a.k.a documentdb).
- npma package link https://www.npmjs.com/package/documentdb
- Repo link: https://github.com/Azure/azure-documentdb-node

**Comment by mozehgir** [comment]
Looks like the issue has been addressed as per the above comment. If the error persists feel free to re-open this issue in the https://github.com/Azure/azure-sdk-for-js repository .
