### ISSUE TITLE
Work with the doc team to improve documentation of the models for a given sdk

### ISSUE THREAD

**Issue by daschult** [Azure/azure-sdk-for-node#2527]
Work with the doc team to improve documentation of the models for a given sdk. [The source code for a given model class](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/storageManagement2/lib/models/storageAccount.js#L22) provides documentation but the [doc site](https://docs.microsoft.com/en-us/javascript/api/azure-arm-storage/storageaccount?view=azure-node-latest) only documents the empty constructor and the mapper function.. Issue filed by doc team over [here](https://github.com/Azure/autorest/issues/2848).
/cc @salameer

**Comment by chris-armstrong** [comment]
I've been looking into this: it just seems to be a matter of adding `@type` jsdoc lines in the constructor like this example:
https://github.com/Azure/azure-sdk-for-node/compare/master...chris-armstrong:patch-1

Is this the preferred approach, or can we get jsdoc to automatically detect these?

**Comment by RikkiGibson** [comment]
It would be ideal to solve this by tweaking jsdoc config if at all possible because updating the code generator and regenerating all the services is time consuming.
