### ISSUE TITLE
Reference to moment version that can't be installed

### ISSUE THREAD

**Issue by dnwarnock** [Azure/azure-sdk-for-node#2588]
From what I can tell the latest version of moment.js is 2.21.0 not 2.21.1. When I try to `npm install azure-batch` I encounter the following:

`npm ERR! code ETARGET
npm ERR! notarget No matching version found for moment@^2.21.1
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'azure-batch'
npm ERR! notarget`

Line # reference:
https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/batch/package.json#L24

**Comment by RikkiGibson** [comment]
Looks like batch is the only case here. @xingwu1 are you able to bump the version back down and publish a new patch version of azure-batch?

**Comment by RikkiGibson** [comment]
Otherwise I can do it, just don't want to step on any toes

**Comment by xingwu1** [comment]
@RikkiGibson I will fix it now.

**Comment by RikkiGibson** [comment]
Looks like azure-batch@3.1.1 is out which references a proper version of moment.

Thanks for raising the issue @dnwarnock 👍
