### ISSUE TITLE
azure-arm-trafficmanager doesn't work.

### ISSUE THREAD

**Issue by noamokman** [Azure/azure-sdk-for-node#2623]
The sample code for `azure-arm-trafficmanager` doesn't work.
```js
{
	code: 'InvalidResourceType',
    message: 'The resource type \'trafficmanagerprofiles\' could not be found in the namespace \'Microsoft.Network\' for api version \'2017-09-01-preview\'. The supported api-versions are \'2015-04-28-preview,2015-11-01,2017-03-01,2017-05-01,2018-02-01\'.'
}
```

this works:
```js
var client = new trafficManager(credentials, 'your-subscription-id');
client.apiVersion = "2018-02-01";
```

**Comment by amarzavery** [comment]
Looks like the newest api-version is not deployed in all the regions. @noamokman - Which Azure region/location are you using the package for?

@daschult - Can you take a look at this?

**Comment by daschult** [comment]
If it's just a matter of regenerating the SDK and publishing it, then I'm working on it. I'll prioritize trafficmanager today.

**Comment by daschult** [comment]
And it's merged now. I'll publish right now too.

**Comment by daschult** [comment]
And published (https://www.npmjs.com/package/azure-arm-trafficmanager).
