### ISSUE TITLE
Add Container Services API Docs

### ISSUE THREAD

**Issue by bnookala** [Azure/azure-sdk-for-node#2674]
I noted that the NPM module for container services had recently been generated 
by @amarzavery: https://www.npmjs.com/package/azure-arm-containerservice

However, the docs for the module are missing on docs.microsoft.com: https://docs.microsoft.com/en-us/javascript/api/overview/azure/?view=azure-node-latest

**Comment by amarzavery** [comment]
Oops!! thanks for letting us know. We were shipping this previously as a part of azure-arm-compute for historical reasons. However, we just published it as a separate package last week. The docs will be updated soon. 
/cc @daschult 
@dend - Can you please take a look at this?

**Comment by mozehgir** [comment]
This repository is being deprecated. If the error persists feel free to re-open this issue in the https://github.com/Azure/azure-sdk-for-js repository .
