### ISSUE TITLE
Missing curve type in possible parameters for keyvault

### ISSUE THREAD

**Issue by rguikers** [Azure/azure-sdk-for-node#2703]
It is currently not possible to set the curve type for a key with type "EC". The parameter is named crv in the rest documentation. Would be nice to have this added to the standard nodejs client.

Thanks,

**Comment by schaabs** [comment]
@rguikers EC keys are currently in preview.  Support for them is released in our latest preview package [3.0.4-preview](https://www.npmjs.com/package/azure-keyvault).  And the code for this is in the "keyvault" branch of the repo.  We are currently schedule to release 3.0 by June of this year.

**Comment by rguikers** [comment]
@schaabs Thanks Scott, will try this version then.
