### ISSUE TITLE
States while creating a snapshot

### ISSUE THREAD

**Issue by sanjeevsudarshan** [Azure/azure-sdk-for-node#2708]
Hi,

I have been trying to create a snapshot of a managed disk and based on the documentation available, I can see that the snapshot creation has 2 provisioning states, 'Updating' and 'Succeeded'. I dont see a similar value for failure, or any other variable indicating a failure. 

I see that some of the other resources do have a provisioningState of 'Failed'. Are there standard states for this variable thats documented somewhere? . If not, does azure/the sdk throw an error for snapshot failures and not set a state ?

Thanks

**Comment by amarzavery** [comment]
@hyonholee - Can you please take a look at  this issue?

**Comment by huangpf** [comment]
@hyonholee FYI.

**Comment by huangpf** [comment]
Service or documentation issue.

**Comment by huangpf** [comment]
DiskRP team should come to take a look. @yunusm

**Comment by huangpf** [comment]
@vikramd-ms for DiskRP.

**Comment by huangpf** [comment]
@sanjeevsudarshan DiskRP's possible provisioning states should be the same as other resource types under the same Azure Resource Manager design:
https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-async-operations#provisioningstate-values
