### ISSUE TITLE
Where can I get the list of error codes for create/update/delete of Public IP Address resource?

### ISSUE THREAD

**Issue by karungithub** [Azure/azure-sdk-for-node#2772]
I am trying to find out error codes that would  happen when a public IP address resource is created. I could find the link to those error codes. Can you possibly let me know where I can find that information?
In general, I want to know if I can find the error codes for all the resources in Virtual Network (VNET, Subnets, Network Interface).

**Comment by MikhailTryakhov** [comment]
NRP source code
