### ISSUE TITLE
azure-arm-network unsupported api version

### ISSUE THREAD

**Issue by lucadruda** [Azure/azure-sdk-for-node#2810]
Latest version of azure-arm-network uses apiversion='2018-02-01' which is not supported for example when querying VMSS ip configuration (getVirtualMachineScaleSetIpConfiguration).
Manually changing the version in module to be '2018-04-01' or '2017-03-30' make it work.

**Comment by huangpf** [comment]
@hyonholee FYI.

**Comment by huangpf** [comment]
NRP team should take a look.

**Comment by MikhailTryakhov** [comment]
related to https://github.com/Azure/azure-rest-api-specs/issues/1685 
closing this duplication
