### ISSUE TITLE
Update MSI logic for VMs to call 169.254.169.254 instead of localhost

### ISSUE THREAD

**Issue by snobu** [Azure/azure-sdk-for-node#2836]
From https://docs.microsoft.com/en-us/azure/active-directory/managed-service-identity/overview#how-does-it-work:

> Your code running on the VM can request a token from two endpoints that are only accessible from within the VM:
>
> * Azure Instance Metadata Service (IMDS) identity endpoint:
> http://169.254.169.254/metadata/identity/oauth2/token **(recommended)**
>
> * MSI VM extension endpoint:
> http://localhost:50342/oauth2/token **(to be deprecated)**

Probably around here somewhere:

https://github.com/Azure/azure-sdk-for-node/blob/dfcdee4217f681a491d883fbaa16b8e4440632e5/runtime/ms-rest-azure/lib/credentials/msiVmTokenCredentials.js#L38

**Comment by amarzavery** [comment]
Yes, we have to add support for that. @RikkiGibson - Can you please take a look at this?

**Comment by snobu** [comment]
A bit unrelated, and possibly a feature request, is there a method in the SDK that returns whether Managed Service Identity is available on the VM/PaaS instance?

E.g.:
`msRestApi.IsMSI()`

* returns true if MSI endpoint exists
* returns false if MSI is either not enabled or the code is not running in Azure

**Comment by kpajdzik** [comment]
Related issue in TypeScript SDK - https://github.com/Azure/ms-rest-nodeauth/issues/42
