### ISSUE TITLE
(NSP) Memory Exposure vulnerability via tunnel-agent

### ISSUE THREAD

**Issue by jornki** [Azure/azure-sdk-for-node#2850]
## Recreate
* Create a project and add azure `2.2.1-preview` to it
* Run [nsp](https://github.com/nodesecurity/nsp) against the project
* Security warning: https://nodesecurity.io/advisories/598

## Result
* Builds depended on nsp checks break

**Comment by amarzavery** [comment]
It is not recommended to use the rollup `azure` package. Please use packages for individual services.
