### ISSUE TITLE
EnablePartitioning property not working when creating service bus queue

### ISSUE THREAD

**Issue by va20ych** [Azure/azure-sdk-for-node#2877]
Hi team,

I have very simple piece of code and unfortunately it's not working as expected. I want to create queue and enable partitioning:

```
const azure = require('azure-sb');
const { serviceBus: { serviceBusConnectionString } } = require('../config');
const serviceBusService = azure.createServiceBusService(serviceBusConnectionString);

initQueue() {
   const queueOptions = {
       MaxSizeInMegabytes: '1024',
       EnablePartitioning: 'true'
   };
   
   serviceBusService.createQueueIfNotExists(this.queueName, queueOptions, (error, result, response) => {
        if (error) {
            logger.error('Error on create queue', error);
        }
    });
}
```

As a result a queue is created but partitioning is always disabled.
Could you please provide some help? I tried different value types for EnablePartitioning parameter (bool, string) but without success.

**Comment by ramya-rao-a** [comment]
We will have to investigate this one, the problem might be in the API or the way we pass the `EnablePartitioning` flag
