### ISSUE TITLE
azure-sb delete and unlock message ERROR

### ISSUE THREAD

**Issue by StefanoPastore** [Azure/azure-sdk-for-node#2946]
Hi,

I implemented a handler to receive topic messages.

When i complete my business logic I try to delete message if I completed my operations successfully, instead of unlocking it, but I get this error:

`TypeError: Cannot read property 'substr' of undefined at ServiceBusService.unlockMessage (/Users/stefapas/git/topconagricolture/ta-infrastructure/ta-provisioning-nh/node_modules/azure-sb/lib/servicebusservice.js:337:39)`

It is caused by [this line](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/serviceBus/lib/servicebusservice.js#L337), I don't understand why it need to set location param in message.

Is my approach wrong or is it a bug?

Thanks.

**Comment by StefanoPastore** [comment]
I found the problem, my service bus receive messages was set with `isPeekLock: false` this caused the auto delete of the message when it was received.

Now I set service bus receive messages with `isPeekLock: true` and library throws no errors when unlocking or deleting messages.

At this point, it seems that the error i had it's a library bug. I'd expect a handled error to represent the situation.

Can you update the documentation explaining the use cases?

Thanks.

**Comment by amarzavery** [comment]
Hi @StefanoPastore Please use the new service bus sdk `npm i @azure/service-bus`.
The source code and samples for the new sdk can be found here 
https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/servicebus/service-bus

File service bus related issues in the new repo https://github.com/Azure/azure-sdk-for-js.
