### ISSUE TITLE
Creating storage account v2

### ISSUE THREAD

**Issue by Martinsos** [Azure/azure-sdk-for-node#2947]
Hi,
I am using azure-sdk-for-node and I am creating storage account using http://azure.github.io/azure-sdk-for-node/azure-arm-storage/latest/StorageAccounts.html#create . When specifying kind, there are two options, 'Storage' and 'BlobStorage'. I tried using 'Storage' and it creates General Storage v1. Is there any way to create General Storage v2 through this sdk? Thanks!

**Comment by RikkiGibson** [comment]
Are you using azure-arm-storage@5.0.0? It looks like [`'StorageV2'` is supported as an argument for parameters.kind.](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/storageManagement2/lib/operations/storageAccounts.js#L3390)

It looks like these docs are out of date. @amarzavery do you know how we should act on this?

**Comment by amarzavery** [comment]
Latest documentation for storage can be found [here](https://docs.microsoft.com/en-us/javascript/api/azure-arm-storage/storageaccounts?view=azure-node-latest#functions).

azure.github.io is the old documentation site. README.md clearly mentions it over [here](https://github.com/Azure/azure-sdk-for-node#documentation)

**Comment by Martinsos** [comment]
Oh wow thanks, I was using azure.github.io all the time!

I would question if it actually states it clearly, it says that azure.github.io primarily provides sdk docs for A, B and C while the other one primarily provides sdk docs for D and F, but it does not say that any of the docs there are outdated, and word **primarily** does leave space for other stuff being documented there.
Of course, I was also reading it fast and when I found the docs there I did not think they are old, or would be expecting a notice on that page saying that. So maybe it would be good to emphasize this.

Regarding the version, I am using azure@2.2.1-preview (which is the last version), which brings azure-arm-storage@3.1.0 with it. Should I be directly using 5.0.0 version of azure-arm-storage alongside? How does that play with the azure package itself?

**Comment by RikkiGibson** [comment]
Something might be amiss here-- it looks like we've published `azure@2.3.1-preview` containing `azure-arm-storage@^5.0.0`.

**Comment by RikkiGibson** [comment]
This was probably done in response to this issue, but I neglected to update the issue with this information. Sorry about that! Given that, `'StorageV2'` is now a supported account type in the SDK.

**Comment by Martinsos** [comment]
Awesome, thanks a lot!
