### ISSUE TITLE
Implement a "Deploy to WebApp" function

### ISSUE THREAD

**Issue by LudoBoggioTotal** [Azure/azure-sdk-for-node#2948]
We would like to have the capability to deploy a file, ZIP or WAR to a webapp using the SDK (as it is possible to do using CURL, for example : cf. https://docs.microsoft.com/en-us/azure/app-service/app-service-deploy-zip )

**Comment by devigned** [comment]
@amarzavery what do you think about this feature. Seems like it would be quite helpful.

**Comment by amarzavery** [comment]
@devigned - I agree. We should provide this functionality via node sdk. The documentation [here](https://docs.microsoft.com/en-us/azure/app-service/app-service-deploy-zip#rest) suggests that this is a data plane API and the auth mechanism is different as well. 

@davidebbo from the WebApps team, what do you think about this? Is there a list of features/items that one can perform on the data plane side of the Web Apps api? We would love to open that up for our customers in an organic way.

**Comment by amarzavery** [comment]
@kirthik - fyi.

**Comment by davidebbo** [comment]
Yes, I think exposing zipdeploy would make sense. It's the deployment technique that we're increasingly pushing as it's cross platform (unlike msdeploy).

Implementation would be:

- Get the publishing profile via ARM
- Use those creds to call the zipdeploy API

**Comment by LudoBoggioTotal** [comment]
Concerning getting the publishing profile, it looks like it already exists a funciton in the SDK : "webSiteClient.webApps.listPublishingCredentials" :
 * @summary Gets the Git/FTP publishing credentials of an app.
 *
 * Gets the Git/FTP publishing credentials of an app.

(quoted from https://raw.githubusercontent.com/Azure/azure-sdk-for-node/master/lib/services/webSiteManagement2/lib/operations/webApps.js )
