### ISSUE TITLE
Improve the developer experience for polymorphic models in the new TypeScript SDK.

### ISSUE THREAD

**Issue by amarzavery** [Azure/azure-sdk-for-node#2960]
This [issue](https://github.com/Azure/azure-sdk-for-node/issues/2942#issuecomment-395826423) highlights the pain our customers have to go through while using the SDK against polymorphic models.

Multiple things need to be done to solve this problem.
1. The discriminator property should be an `Enum` that provides intellisense for all the possible values one can provide for.
2. The documentation/description of the discriminator property needs to document all the possible values. This ensures a decent experience for customers using JS.
3. We should provide `create()` methods for all our model interfaces. Customers can use this to create models that satisfy the interface definition. This create method will not expose the discriminator property as it knows the value that should be provided for that property. 
_This is a generic solution that can be applied to all the model types_.
```js
export interface Foo {
  name: string;
  odataType: string,
  age: number
}

export namespace Foo {
  export function create(params: FooParams): Foo {
     . . . 
  }
}
```
Creating a separate interface FooParams with all the properties duplicated from Foo would not make sense. 

```
export interface DiscriminatedFoo {
  odataType: string
}

export interface Foo extends DiscriminatedFoo {
  name: string;
  age: number;
}
```

**Comment by RikkiGibson** [comment]
I'd like to try using a tagged union for the parameter type and seeing if that helps the tooling experience at all.

In vscode, if you declare types like so:

```ts
interface Foo {
  kind: "foo";
  foo: number;
}

interface Bar {
  kind: "bar";
  bar: string;
}

function someFunc(arg: Foo | Bar) {
}

someFunc({
  kind: "foo", // as soon as you fill out the "kind", you get intellisense for the polymorphic properties
  foo: 42
})
```
