### ISSUE TITLE
Support XNullable in Node.js SDK

### ISSUE THREAD

**Issue by daschult** [Azure/azure-sdk-for-node#3015]
- We need to add support for `x-nullable: true` in the generator and in the serializer as well. We need to add a check over [here](https://github.com/Azure/azure-sdk-for-node/blob/master/runtime/ms-rest/lib/serialization.js#L231) to make sure that we don't throw error if the property is nullable.
- Add a test if there does not exist one where we want to set a property of a composite model to null and that property with null value should be present in the request body on the wire

**Comment by amarzavery** [comment]
Please make sure to add support for this in the node.js and the TS generator and the respective runtimes.

**Comment by RikkiGibson** [comment]
Where is this extension documented? I don't see it in https://github.com/Azure/autorest/tree/master/docs/extensions
