### ISSUE TITLE
Equivalent call in Azure Storage Node SDK for PutPage REST API

### ISSUE THREAD

**Issue by karungithub** [Azure/azure-sdk-for-node#3017]
Hi,
I am sure I am missing something here: what is the equivalent  node call for PutPage blob service API.
Here is the REST API: https://docs.microsoft.com/en-us/rest/api/storageservices/put-page

I cannot find the equivalent call in in SDK documentation at: 
https://docs.microsoft.com/en-us/javascript/api/azure-storage/BlobService?view=azure-node-latest

Please can you treat this as urgent as we stuck implementing our functionality.

**Comment by karungithub** [comment]
@RikkiGibson  or @XiaoningLiu  - Can one of you help me out here? Is there a node.js implementation of the putpage API?

**Comment by XiaoningLiu** [comment]
@karungithub Please see `createPagesFromStream(container, blob, readStream, rangeStart, rangeEnd, options, callback)`

**Comment by karungithub** [comment]
@XiaoningLiu  - Here is what I am trying to do:
1. I am trying to getpagesrangesdiff between two snapshots
2. Apply these pages on another pageblob.

For step#2, if I am using createPagesFromStream API, the "container" parameter would be the pageblob container where the pages are added, the "blob" would be the name of the blob where the pages are added. What is the readStream paramter? Is the source blob from where the pages are read?
Can you give me an example of usage?

**Comment by karungithub** [comment]
@XiaoningLiu  - can you please respond to my request above or if you can point me to the documentation that can help me?

**Comment by XiaoningLiu** [comment]
Hi @karungithub 

Sorry for the late response, I have tons of GitHub notifications per day : (

For your question:

1. `Put Page` operation needs a body storing the data you want to put. The `readStream` is the stream points to the data you want to put to page(s) between rangeStart and rangeEnd. `createPagesFromStream` doesn't care where is the data from.

2. According to your description. After `getpagesrangesdiff` of 2 snapshots, you will get a *list* of pages. You need to download these pages with methods like `createReadStream(container, blob, options, callback)`, with the options `rangeStart` and `rangeEnd`.
