### ISSUE TITLE
Missing codegen_mapping.json referenced in RegeneratingCode document

### ISSUE THREAD

**Issue by cthrash** [Azure/azure-sdk-for-node#3050]
Doc is [here](https://github.com/Azure/azure-sdk-for-node/blob/master/Documentation/RegeneratingCode.md), referencing a JSON [file](https://github.com/Azure/azure-sdk-for-node/blob/master/codegen_mappings.json) that is not present.  Where does this file come from?

**Comment by RikkiGibson** [comment]
Looks like it was deleted in 2a51250. I think we moved to relying on the naming conventiones in https://github.com/azure/azure-rest-api-specs. @daschult do you mind updating this doc?

**Comment by cthrash** [comment]
While you're there, you might fix the link at the bottom too:

< https://github.com/Azure/adx-documentation-pr/blob/master/clis/azure-cli/guide.md
> https://github.com/Azure/adx-documentation-pr/blob/master/clis/azure-cli-classic/guide.md

Assuming, of course, the instructions are valid
