### ISSUE TITLE
REST API framework for Node.js Require Error

### ISSUE THREAD

**Issue by aseem191** [Azure/azure-sdk-for-node#3056]
I created a RESTful API App using Node.js on Azure, deployed it, and am modifying it using Azure's App Service Editor. Upon npm installing mysql2 and tedious, and then requiring the two modules in my server.js, tedious/lib/tedious.js and mysql2/lib/packets/index.js both cause an error to be thrown by Module. Here are images showing the errors, as well as where the errors are located in the files. 

![azureerr1](https://user-images.githubusercontent.com/18651871/41822984-fbdf63ee-77ac-11e8-9d0d-edf06326e6e2.PNG)
![azureerr2](https://user-images.githubusercontent.com/18651871/41822985-fc0af590-77ac-11e8-804f-52e62c9c2ba1.PNG)
![azureerr3](https://user-images.githubusercontent.com/18651871/41822986-fc2bec1e-77ac-11e8-9123-f7f1d4e1850d.PNG)
![azureerr4](https://user-images.githubusercontent.com/18651871/41823015-803f140e-77ad-11e8-897c-cc6fcca38adb.PNG)

Is there anything wrong with my approach, or is this an issue with Azure's framework? mysql2 and tedious could be successfully required for Azure's Node.js app service framework, but not for its API app framework.

**Comment by aseem191** [comment]
Also, requiring mysql (not mysql2) works for the Node.js API app framework.

**Comment by amarzavery** [comment]
@davidebbo - Can you please take a look at this issue?

**Comment by davidebbo** [comment]
Unless I'm misreading this, this does not seem related to the Azure SDK for Node.

For App Service questions, please use either the [forum](https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=windowsazurewebsitespreview) or StackOverflow.

**Comment by davidebbo** [comment]
Additional note: please always include code as text instead of screenshots, as that makes it significantly easier to work with. Thanks!
