### ISSUE TITLE
How to pass query parameters?

### ISSUE THREAD

**Issue by t-my** [Azure/azure-sdk-for-node#3082]
Hi, I'm having trouble using azure-graph,  passing query parameters.

I'm trying to use following code to get users from AAD, and pass them to my application.

```
var msRestAzure = require('ms-rest-azure');
var graphRbacManagementClient = require('azure-graph');

var options = {
  filter: "startswith(displayName,'User')",
  // how to pass query parameters?
};
 
msRestAzure.loginWithServicePrincipalSecret(clientId, applicationSecret, tenantId, { tokenAudience: 'graph' }, function (err, credentials, subscriptions) {
  if (err) return console.err(err);  
  var client = new graphRbacManagementClient(credentials, tenantId);
  
  client.users.list(options, (err, results, request, response) => {
    if (err) return console.log(err);
    //console.log(request);
    console.log(JSON.parse(response.body).value.length);
  });
    
});
```

I figured out how to pass filter parameter but I can't figure a way to pass down other query parameters (https://developer.microsoft.com/en-us/graph/docs/concepts/query_parameters) like top (/users&$top=1) or select (/users?$select=givenName,surname).

From users.js:

```
  // Construct URL
  let baseUrl = this.client.baseUri;
  let requestUrl = baseUrl + (baseUrl.endsWith('/') ? '' : '/') + '{tenantID}/users';
  requestUrl = requestUrl.replace('{tenantID}', encodeURIComponent(this.client.tenantID));
  let queryParameters = [];
  if (filter !== null && filter !== undefined) {
    queryParameters.push('$filter=' + encodeURIComponent(filter));
  }
  queryParameters.push('api-version=' + encodeURIComponent(this.client.apiVersion));
  if (queryParameters.length > 0) {
    requestUrl += '?' + queryParameters.join('&');
  }
```

Any help?

**Comment by jingbe** [comment]
Did you solve this problem?

**Comment by yugangw-msft** [comment]
@t-my, you looked at MS Graph, while `azure-graph` uses AAD  Graph. I suggest you check out the filter [syntax](https://docs.microsoft.com/en-us/previous-versions/azure/ad/graph/howto/azure-ad-graph-api-supported-queries-filters-and-paging-options#CommonQueries) and use those. Azure CLI uses the [filter](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py#L592-L600) as well.

**Comment by t-my** [comment]
I did solve the problem couple months ago. I’ll try to explain the fix here that others can see it.
