### ISSUE TITLE
bug uploading proxy cert to azure with sdk

### ISSUE THREAD

**Issue by Mortuie** [Azure/azure-sdk-for-node#3109]
I am having problems getting the ApiManagementClient from the Azure node sdk to work. Firstly I have completed a signin with the 
`loginWithServicePrincipalSecrets` method attached to the msRestAzure object. This has completed successfully with no issues and 
no errors thrown. I have then Base64 encoded my .pfx certificate obtained from LetsEncrypt. I then use the `client.apiManagementService.uploadCertificateWithHttpOperationResponse`
with the correct credentials I believe. Again this throws no errors and I get a large json response back from the server. Including my Certificate Thumbprint and the
correct expiration date and domain for which I want this SSL certificate to work. However when I check the custom domains in the azure portal, the certificate does not
seem to be uploaded. I cannot find where my certificate has gone. There are no errors so I assume it has succeeded in uploading, but when I look at the certificate in the 
local domains, it doesn't exist and the old one is still active.

**Comment by amarzavery** [comment]
@solankisamir - Can you please take a look? This looks like a service side issue.

@Mortuie - Can you please provide the request, response? We are interested in seeing the request header, body and response header and body. The headers will contain a client request id that can be used by the service team to track the request.

**Comment by solankisamir** [comment]
@Mortuie the operation `uploadCertificateWithHttpOperationResponse` will be deprecated in future and is not the recommended way to upload ssl certificates. See documentation [here](https://docs.microsoft.com/en-us/javascript/api/azure-arm-apimanagement/apimanagementservice?view=azure-node-latest#uploadcertificatewithhttpoperationresponse-resourcegroupname--servicename--parameters--options-)

You should use the api `createorupdate` [here](https://docs.microsoft.com/en-us/javascript/api/azure-arm-apimanagement/apimanagementservice?view=azure-node-latest#createorupdate-resourcegroupname--servicename--parameters--options--optionalcallback-)
where you provide the bas64 encoded ssl certificate into the `hostnameconfigurations` object.

**Comment by Mortuie** [comment]
@amarzavery hi I will definitely add some info when I get back to looking at the issue on our side tomorrow. But thank you for the response!

@solankisamir I am aware this is being deprecated and I was thinking that this might already be causing the issue. I will try `createOrUpdate` but am unsure of how this will be used to upload a ssl certificate. Do you have an examples of this being used?

**Comment by Mortuie** [comment]
So i've kinda got uploading a certificate working, however now I was wondering if you can download the base64 encoded certificate again or not ?

**Comment by solankisamir** [comment]
@Mortuie  that is great!
No, you cannot download the base64 encoded certificate;

We just provide the `Thumbprint`, `SubjectName` and `ExpirationTime` properties. You can also use a `KeyVault` secret to be in control of the lifecycle.

Reference [here](https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-use-managed-service-identity)

`keyVaultId` [here](https://docs.microsoft.com/en-us/rest/api/apimanagement/apimanagementservice/createorupdate#apimanagementcreatemultiregionservicewithcustomhostname)
