### ISSUE TITLE
delete message takes 10+ seconds

### ISSUE THREAD

**Issue by yuhaii** [Azure/azure-sdk-for-node#3113]
We have an issue which could be a combination with the node sdk (maybe because it is using other protocols than java) and network on kubernetes.

To replicate it simple spin up a aks or acs kubernetes cluster and deploy a service using the node sdk and take off items from the queue.

We have solved it in our end by rewriting our microservice from Node.js to Java.

**Comment by yuhaii** [comment]
[Service bus code 2.zip](https://github.com/Azure/azure-sdk-for-node/files/2191946/Service.bus.code.2.zip)

This is a node.js client code for reference to reproduce this issue.

**Comment by RikkiGibson** [comment]
Thank you for the heads up!

**Comment by amarzavery** [comment]
@yuhaii - Please use the new service bus sdk `npm i @Azure/service-bus`.

You can find the source code and samples over [here](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/servicebus/service-bus).

In the future, please file service bus issues in the new repo: https://github.com/Azure/azure-sdk-for-js
