### ISSUE TITLE
event driven message receipt

### ISSUE THREAD

**Issue by ggb88** [Azure/azure-sdk-for-node#3114]
Hi,

I'm struggling to find out if I can write a node.js service bus queue listener that is event driven rather than polled.  I've successfully written a timer based routine using receiveQueueMessage, but how do I "waitForQueueMessage" with a callback / promise?

Thanks!

**Comment by TacticalSlothmaster** [comment]
Hi, did you find a solution to this?

**Comment by amarzavery** [comment]
Hi @ggb88 , @TacticalSlothmaster - Please use the new service bus sdk `npm i @Azure/service-bus`.

You can find a sample that solves the reported issue over [here](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/servicebus/service-bus/samples/typescript/gettingStarted/receiveMessagesStreaming.ts).

In the future, please file service bus issues in the new repo: https://github.com/Azure/azure-sdk-for-js
