### ISSUE TITLE
 customProperties incorrectly parsing strings into dates

### ISSUE THREAD

**Issue by ocirneaquilina** [Azure/azure-sdk-for-node#3126]
I'm trying to send an object with customProperties which have a label property, wherein I'm passing a string formatted with a full stop, dash and space in the message(".", "-", " "). 

An example of a label string which I passed were:

1. "label.1"

2. "label-1"

3. "label 1"  

These are being received at the receiver and parsed into a date which shouldn't be the case. I did try with a pipe ("|") character and it was successfully parsed, however.

An example of the message I sent is the below.

let label: string = options.label;
label += "." + labelNumber;

let message = {
                    body: JSON.stringify({
                        "message": "I am message " + i,
                        "timestamp": new Date().getTime(),
                    }),
                    customProperties: {
                        "label": label,
                    }
                }

**Comment by amarzavery** [comment]
@eaquilina - Can you tell us which package/sdk you are using and which operation from that package are you using?

**Comment by vIceBerg** [comment]
I saw the same behavior yesterday.

I'm using:
"azure": "^2.3.1-preview",

And it's in the callback of serviceBusService.receiveSubscriptionMessage

Maybe it's also related to my own issu I open yesterday about the / in a string being escape with \ /

**Comment by amarzavery** [comment]
To give you some context: The azure-sb package is currently based on http protocol. It uses `application/atom+xml` as the content-type. Hence it could be possible that escaping the forward slash is happening due to that. This won't be the case with the [new library](https://github.com/azure/azure-service-bus-node) that we are developing based on amqp protocol.  I have a [PR](https://github.com/Azure/azure-service-bus-node/pull/5) out. We expect to release a preview version out in ~1 month from now.

**Comment by eaquilina** [comment]
@amarzavery - Sorry for the delay. 
I'm using:
"azure-sb": "^0.10.6",
 and the method I'm using is the receiveSubscriptionMessage in the message's customProperties.

**Comment by vIceBerg** [comment]
To give you another example, the string:
/aaaaaaaaaaa/bbbbbbbbbbbb/--IMPORT-7632

Was converted into a date

**Comment by amarzavery** [comment]
Please try the new sdk `npm i @azure/service-bus`. 

An example can be found [here](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/servicebus/service-bus/samples/typescript/gettingStarted/sendMessages.ts).

In the future, file new Service bus related issues in the new repo https://github.com/Azure/azure-sdk-for-js
