### ISSUE TITLE
Service Bus - String with / are escaped with \/

### ISSUE THREAD

**Issue by vIceBerg** [Azure/azure-sdk-for-node#3131]
Hi!

I'm using Azure Service bus to communicate between a .NET program (sender) and a NodeJS program (Receiver).

I currently use noodlefrenzy's node-amqp10 node Package which can be found here:
https://github.com/noodlefrenzy/node-amqp10

However, I want to use Azure node SDK to receive the messages and I found a strange difference between the two libraries in the way they process strings.

The C# program sends a message which contains a path in this format:
`{ path: "/my/awsome/path" }`

When I use the needlefrenzy library, the callback gets this:
`{ path: "/my/awsome/path" }`

which is perfect.

When I'm using the Azure Node SDK, the callback gets this:
`{ path: "\/my\/awsome\/path" }`

Is there a switch I can toggle to change this behavior? How can I solve that?

I read some suggestions that I could string.replace() the \ / by / but I find this solution quite messy.

Thanks

VB

**Comment by vIceBerg** [comment]
Hi!

I can run the code locally, but requests sent with Node are not intercepted by Fiddler...

How can i confiure the service bus to use the Fiddler proxy?

Thanks

**Comment by amarzavery** [comment]
```
set NODE_TLS_REJECT_UNAUTHORIZED=0
set HTTPS_PROXY=http://127.0.0.1:8888
```

**Comment by vIceBerg** [comment]
Hi

I did it this way:

		process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';
		process.env.HTTPS_PROXY='http://127.0.0.1:8888';

I can see the request through Fiddler but I have this error:

SSL Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE

**Comment by vIceBerg** [comment]
Ok I got to get it working.

The path I see in fiddler is escaped

![image](https://user-images.githubusercontent.com/2366606/42530415-16ee2f2c-844f-11e8-944f-f4bd25f722b8.png)

**Comment by RikkiGibson** [comment]
And the same in Fiddler? when the request is sent with the C# SDK?

**Comment by RikkiGibson** [comment]
That's really helpful to know. Thank you.

**Comment by vIceBerg** [comment]
Using the Service Bus explorer, the path is OK.
![image](https://user-images.githubusercontent.com/2366606/42530829-3023f048-8450-11e8-8e65-e121a6432564.png)

I'm trying to capture the Send request from C# into fiddler but I can't see it... Like if C# was not using HTTP...

I'll check if I can force a proxy in C#

**Comment by vIceBerg** [comment]
I can see Topic creation and Subscription creation calls in Fiddler, but not the actual send

**Comment by RikkiGibson** [comment]
Interesting...I wonder if there's some url unescaping the service bus library should be doing on the client side. I'm sorry to say but the fastest way to get it working for you will be to do a string replace on the `\/`.

**Comment by vIceBerg** [comment]
All right!

At least, you're aware of this issue. I'll deal with the string replace for now, as I only receive path from there.

VB

**Comment by amarzavery** [comment]
@vIceBerg - Please try the new sdk `npm i @azure/service-bus`. Source code and samples for the new sdk can be found here https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/servicebus/service-bus

In the future, file new Service bus related issues in the new repo https://github.com/Azure/azure-sdk-for-js
