### ISSUE TITLE
receiveSubscriptionMessage throws a lot of errors

### ISSUE THREAD

**Issue by vIceBerg** [Azure/azure-sdk-for-node#3146]
Hi!

The receiveSubscriptionMessage callback receive a lot of errors.
- Error: 500 - The operation cannot be performed because the entity has been closed or aborted.
- Error: read ECONNRESET
- Error: 500 - Error during communication with Service Bus. Check the connection information, then retry.

Here's the code I use:

`			return new Promise((resolve, reject) => {
				const options = {
					timeoutIntervalInS: 300
				};
				serviceBusService.receiveSubscriptionMessage(configurations.config.azureConfig.responsesQueueName, 'backend', options, (error, receivedMessage) => {
					if (error && error === 'No messages to receive') {
						return resolve();
					}
					if (error) {
						logger.log(process.pid, '===> azure sdk RX ERROR: ', error);
						return reject(new Error(error));
					}
					// fire and forget
					logger.log('Received on azure sdk');
					setTimeout(() => processMessage(receivedMessage), 0);
					resolve();
				});
			});`

I have 10 listeners like this one. When my listener returns an error (with reject), my process is killed.

Can I "ignore" those errors? Why they are so many of them?

Thanks

**Comment by amarzavery** [comment]
@vIceBerg - Please take a look at the sample over here
https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/servicebus/service-bus/samples/typescript/advancedFeatures/topicFilters.ts#L85

Try using the new service bus sdk `npm i @azure/service-bus`.

In the future file servicebus related issues over here https://github.com/Azure/azure-sdk-for-js
