### ISSUE TITLE
Computer Vision API Client

### ISSUE THREAD

**Issue by rodsnjr** [Azure/azure-sdk-for-node#3162]
Hello.

I'm using the 'azure-cognitiveservices-computervision' API, within my ES2016 Typescript Project.

Whenver I build te *.ts project I keep getting the following error:

> azure-cognitiveservices-computervision/lib/computerVisionAPIClient.d.ts(1284,32): error TS2503: Cannot find namespace 'stream'.

Seems like the Definition file, does not have imported the **stream** namespace.

`import { ServiceClient, ServiceClientOptions, ServiceCallback, HttpOperationResponse, ServiceClientCredentials } from 'ms-rest';
import * as models from "./models";`

Here's my tsconfig

`
{
    "compilerOptions": {
      "target": "es6",
      "outDir": "dist",
      "lib": ["es2017", "dom"],
      "types": ["reflect-metadata"],
      "module": "commonjs",
      "moduleResolution": "node",
      "experimentalDecorators": true,
      "emitDecoratorMetadata": true,
      "sourceMap": true
    },
    "include": [
      "src/**/*.ts",
      "src/**/*.json"
    ],
    "exclude": [
      "node_modules"
    ]
}
`

**Comment by daschult** [comment]
Hi @rodsnjr. Are you still having this issue?

**Comment by daschult** [comment]
At some point in the near future we will be deprecating the packages in [azure-sdk-for-node](https://github.com/Azure/azure-sdk-for-node) and asking everyone to move to the packages in [azure-sdk-for-js](https://github.com/Azure/azure-sdk-for-js). You can find the JavaScript (Node.js and browser compatible) version of the ComputerVision package [here](https://www.npmjs.com/package/@azure/cognitiveservices-computervision).

**Comment by daschult** [comment]
@danang-id, please comment on this issue and let me know if using the new package solves your problem.
