### ISSUE TITLE
New web container doesn't fit your validation

### ISSUE THREAD

**Issue by andrew-st-angelo-77media** [Azure/azure-sdk-for-node#3170]
Azure's Storage Accounts allow for hosting static web files (hooray!!).  However, they setup a default container by the name of `$web`.   This, however, throws an error when passed through your `validate.js:containerNameIsValid()` method.  I would assume there needs to be some acceptance of special characters, especially if Azure is auto-creating this container.  As far as I know, there's no way to specify another container for the web access to serve up.

https://github.com/Azure/azure-sdk-for-node/blob/aad7fe39b574a169c698a712e6903aacc9375fa6/lib/common/lib/util/validate.js#L273-L275

**Comment by RikkiGibson** [comment]
@XiaoningLiu any idea what should be done for this special case? Maybe we can loosen the validation?
