### ISSUE TITLE
Is it possible to connect to azure storage emulator from a Mac?

### ISSUE THREAD

**Issue by baoshan** [Azure/azure-sdk-for-node#32]
Hi, there

I'm planning to use a virtual machine to host the azure emulator, while developing the app on a Mac.

Is it possible to make a connection to azure storage emulator? Any examples available?

Thanks.

**Comment by marcel-silva** [comment]
what is the solution? link is dead!

**Comment by pabloarista** [comment]
Here's the archived page (if anyone is interested):
https://web.archive.org/web/20120826081909/http://www.infosysblogs.com/cloud/2011/03/accessing_azure_development_st.html

Just in case it gets deleted, I copied over the text here:

Configuring Azure development storage for team development scenarios

While developing applications in a team environment, it is important that the development team has access to a shared data store. And if you are building cloud applications targeting the Windows Azure platform, dev fabric along with the dev storage are the key components which stimulate the Azure platform aka cloud on the local development environment. However, as far as the dev storage goes, the default storage endpoints are configured to listen for requests received to the local host (127.0.0.1). As a result of which the dev storage is not accessible from remote locations.

By default the Azure development fabric is configured as follows:

•Blob Service: http://127.0.0.1:10000
•Queue Service: http://127.0.0.1:10001
•Table Service: http://127.0.0.1:10002

To access the Azure development storage from another machine, follow these steps:

1.Open the devstore configuration file ~Program Files\Windows Azure SDK\v1.3\bin\devstore\DSService.exe.config:
<services>
  <service name="Blob" url="http://[IPAddress]:10000/"/>
  <service name="Queue" url="http://[IPAddress]:10001/"/>
  <service name="Table" url="http://[IPAddress]:10002/"/>
</services>

2.Update "IPAddress" tag of the Blob,Queue and Table URLs, pointing to the machine running the devstorage
<services>
  <service name="Blob" url="http://202.75.100.89:10000/"/>
  <service name="Queue" url="http://202.75.100.89:10001/"/>
  <service name="Table" url="http://202.75.100.89:10002/"/>
</services>

3. Shutdown / Start the Development Fabric

The development team is now in a position to access a shared dev storage from their local development environments.

Note: Check the devstore on the remote machine is in a "Running" state before trying to access it from your application.

**Comment by shawnHartsell** [comment]
Thanks for this @pabloarista !

The only thing that was different for me was that my emulator was installed to  __C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator__. That may b/c I installed the stand alone version 😐

**Comment by cougit** [comment]
After searching about an answer to this question I was so glad when I ran across this post. But I still do not understand how this really works. While I can change the IP address to that of the VM, the VM is the remote location actually running the emulator. This means the 127.0.0.1 makes sense to the store when starting on the VM. But what I want to do is access that specific store using the IP for the VM (say 10.10.1.100).

**Comment by Fang3s** [comment]
It's recommended to use port forwarding because of the instability of Azure Emulator. However, it doesn't work when `connectaddress` is 127.0.0.1 using the built-in tool `netsh` on my windows 7 (see for detail: [problem with adding a portproxy using netsh](https://social.technet.microsoft.com/Forums/windowsserver/en-US/e794910b-9325-4ef9-be82-3e57925e6586/problem-with-adding-a-portproxy-using-netsh?forum=winservergen&prof=required#6e55ec40-75a1-4707-aba5-1eabe917fbfc)). I search and find [PassPort port forwarding utility Win XP](https://sourceforge.net/projects/pjs-passport/) to help me with port forwarding.

**Comment by amarzavery** [comment]
The source code for azure-storage has moved to a different repo https://github.com/Azure/azure-storage-node and there is a dedicated team for that which can help you with your queries. Please file an issue over there.
