### ISSUE TITLE
The current Azure Graph API models limit the usage of Graph API

### ISSUE THREAD

**Issue by PeterL1n** [Azure/azure-sdk-for-node#3215]
The current azure-graph package uses model mappers to map given JSON objects before sending the HTTP request. I don't know what is the benefit of doing so, but it is not covering the whole spectrum of properties allowed in the Azure endpoint and limiting developer's ability.

For example, if I try to do client.users.update('some-id', { 'jobTitle': 'new job' }) The 'jobTitle' property is not specified in the UserCreateParameters class, and so it will be removed before sending the HTTP request, resulting sending a HTTP request with empty {} body.
The Azure endpoint supports 'jobTitle' and many more properties, so this library should support it as well

I believe we should just remove the modal mapping because Azure now supports extension property, so technically a user should be able to put in custom properties that do not exist in mapper preset

**Comment by RikkiGibson** [comment]
Mappers convert the HTTP message bodies between their wire and user-facing formats and perform validation based on the [API spec](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/graphrbac/data-plane/stable/1.6). Those aren't going anywhere :)

It seems like we're failing to respect the [`additionalProperties` attribute defined on the `UserBase`](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/graphManagement/lib/models/userBase.js#L48), which UserCreate/UpdateParameters inherits from. This should allow you to pass additional properties and have them get serialized. I'll try and look into this when I get the chance.

**Comment by PeterL1n** [comment]
@RikkiGibson Thanks for your response.
