### ISSUE TITLE
Getting property of local blob container created by Azure Storage Emulator never returns when emulator is off

### ISSUE THREAD

**Issue by JasonYeMSFT** [Azure/azure-sdk-for-node#3257]
To reproduce the bug:
1. use Azure Storage Emulator to create a local blob container and get its connection string and its container name.
2. Create a blob service by `new azureStorage.BlobService(connectionString)`
3. On that blob service, call `getContainerProperties(container, someCallBack)` with someCallBack as a function that either does something with the response and deal handle the error

Expected behavior:
When emulator is on, it passes the properties of the container to the callback. When emulator is off, it passes an error that will be handled to the callback.

Actual behavior:
When emulator is on, it is working as expected. When emulator is off, the last function call never enters the callback. This is a confusing behavior and we hope it can fixed.

**Comment by RikkiGibson** [comment]
My guess is that the networking stack/OS is taking a long time to time out the connection to the emulator. It looks like the BlobService object allows you to set a [defaultTimeoutIntervalInMs](https://github.com/Azure/azure-storage-node/blob/master/lib/services/blob/blobservice.core.js#L81). You may wish to set a timeout like 1000ms or so.

**Comment by RikkiGibson** [comment]
This issue appears to apply to https://github.com/Azure/azure-storage-node. It will be easier to get in touch with the maintainers of the library by opening an issue over there.

**Comment by JasonYeMSFT** [comment]
Thanks. I will get in touch with them.
