### ISSUE TITLE
Serice Bus Topic Listener Issue

### ISSUE THREAD

**Issue by shiwaniB** [Azure/azure-sdk-for-node#3286]
Hi

I am implementing service bus topic listener in Nodejs.
Sample code:-

```
var azure = require('azure');
var serviceBusService = azure.createServiceBusService("service_bus_url");
serviceBusService.createSubscription('topicName','AllMessages',function(error, subscriber){
        if(!error){
        serviceBusService.receiveSubscriptionMessage('topicName', 'AllMessages', function(error, receivedMessage){
			console.log(error);
			console.log(receivedMessage);
		});
    }
});
```
But seems that Its not working as a listener. It reads message once and stop receiving messages.
I am manually calling a above function in interval to get messages continuously.

But I want a listener which will continuously listen to incoming messages on service bus.
Any help will be appreciated.

Thanks,
Shiwani

**Comment by TacticalSlothmaster** [comment]
Hi, did you find a solution to this?

**Comment by amarzavery** [comment]
hi @shiwaniB , @TacticalSlothmaster - Please use the new service bus sdk `npm i @azure/service-bus`.
A sample that solves the reported problem can be found here 
https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/servicebus/service-bus/samples/typescript/advancedFeatures/topicFilters.ts#L85

File service bus related issues in the new repo https://github.com/Azure/azure-sdk-for-js.
