### ISSUE TITLE
beginRunCommand - Can I specify a script instead of set of command with this VM node.js API

### ISSUE THREAD

**Issue by karungithub** [Azure/azure-sdk-for-node#3341]
Hi,
I am trying to run a script on the VM to mount and unmount certain volumes. Is it possible to have all these command in script and specify the script file in beginRunCommand to be executed. The script that I have is little bit too long to provide all the commands in the API.
Also, do you have any tests that show the usage of the beginRunCommand().

Thanks,
-Karun

**Comment by karungithub** [comment]
Can anyone comment on this one?

**Comment by RikkiGibson** [comment]
It looks like we don't have tests for this method.

You may wish to create the `parameters.script` array using [fs.readFile](https://nodejs.org/api/fs.html#fs_fs_readfile_path_options_callback) (possibly splitting on newlines, if the API requires that for multi-line scripts).
