### ISSUE TITLE
TokenCloudCredentials no longer valid - what to use?

### ISSUE THREAD

**Issue by mjyeaney** [Azure/azure-sdk-for-node#3353]
Team - recently updated to the latest modules, and was disappointed to find that apparently the Credentials that used to work mostly universally now don't. I'm working with the KeyVault data plane modules, and used to pass a TokenCloudCredentials instance to KeyVaultClient. However, now I'm getting the following error:

```
Error: credentials must be one of: ApplicationTokenCredentials, UserTokenCredentials, DeviceTokenCredentials, MSITokenCredentials
```

This is fine, but none of the docs I can find reflect this change, or how to deal with it (Note that TokenCloudCredentials still works with the ARM management plane). 

So a few issues:

* If this changed, can the docs reflect it? 
* What is the correct pattern now for using KeyVaultClient, and is it uniform across the SDK modules?
* Lots of references to ms-rest / ms-rest-azure, but I can't find doc's on these either...resorting to looking through source. Are there missing doc's somewhere?

**Comment by RikkiGibson** [comment]
@williexu any idea why this change happened and how we can improve the experience of moving to the new usage pattern?

**Comment by williexu** [comment]
Its a result of this code: https://github.com/Azure/azure-sdk-for-node/blob/master/runtime/ms-rest-azure/lib/credentials/keyVaultCredentials.js#L35-L64

For some context, keyvault used to require users to define their own authentification callback. The change was done to abstract that away from developers and allow them to simply use the returned credentials from a login. Unfortunately, we only took care of the four types of credentials listed in the error.

I'm not familiar with the TokenCloudCredentials type but a solution could be to expand the list of accepted creds. Docs still only retain the old flow: https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/keyVault/README.md#authentication

Here's a sample utilizing the newer method: https://github.com/Azure-Samples/key-vault-node-deploy-certificates-to-vm/blob/master/index.js#L61-L67

**Comment by mjyeaney** [comment]
While it would be easy to be selfish and advocate for the method that fixes my code :-), it's much more important that we're heading towards a consistent pattern for leveraging the modules. 

Is the ms-rest code referenced in the newer method now the *preferred* way for all data-plane operations across services, and are all service modules using this? As mentioned before, the documentation around the ms-rest module is nearly non-existent; hopefully this is being addressed? Given how much this low-level module seems to be popping up as required for many other modules, I would think these docs need to be front-and-center.

As mentioned - the changes are fine, but I'm hoping we're not heading towards having each service implementing its' own Auth pattern / types. One benefit of the previous method is that the TokenCloudCredentials flow worked almost universally - so much that we've organized code modules around that boundary/behavior (i.e., abstracted ADAL code into a module that returned tokens via callback, and pass those into various service clients).

**Comment by amarzavery** [comment]
@myagley - Just to be clear. Are you talking about [TokenCloudCredentials](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/common/lib/services/credentials/tokenCloudCredentials.js) or [TokenCredentials](https://github.com/Azure/azure-sdk-for-node/blob/master/runtime/ms-rest/lib/credentials/tokenCredentials.js)?

If it is Token**Cloud**Credentials then that is way too old. It is a part of the `"azure-common"` package which is the runtime for `ASM` based services. `"ms-rest"` and `"ms-rest-azure"` are runtimes for `ARM` based services and also for some of the data plane services.

You can find documentation for common libraries over [here](https://azure.github.io/azure-sdk-for-node/). Scroll down the left panel and you would find ms-rest, ms-rest-azure and azure-common in the common libs section.

@RikkiGibson We should add support for `TokenCredentials` as one of the valid credentials. 

@mjyeaney - Please take a look at the sample links provided by @williexu . We have simplified the auth process a lot. You wouldn't need any kind of abstraction over adal. ms-rest-azure does that for you.

**Comment by mjyeaney** [comment]
Thanks @amarzavery - and I think I see what's going on now.

Regarding the docs, seems we have 2 sources that are available to customers - from the main ACOM site, users are linked to this page for NodeJS SDK docs: https://docs.microsoft.com/en-us/javascript/api/overview/azure/?view=azure-node-latest - which contains hardly anything about the common/ms-rest packages. 

Any chance of collapsing these so we have a single, authoritative reference?

**Comment by mjyeaney** [comment]
Definitely think the documentation links need cleaned up - for example, the SDK README references 2 different locations (see https://github.com/Azure/azure-sdk-for-node#documentation), one of which doesn't contain nearly enough information around the common patterns yet is supposed to the be the "newer" reference for the ARM data plane.

Thoughts?

**Comment by amarzavery** [comment]
Yes, we are in the process of cleaning up the API reference docs.
@dend (from the docs team) - Can you please take a look at this problem?

**Comment by amarzavery** [comment]
@myagley - One more alternative to finding documentation is using vscode or any other ide. We have provide Typescript definitions for all the packages. The definitions also contain documentation along with it. vscode will still try to show documentation if you are developing in js instead of ts. Just thought of letting you know about it. This in no way means that the problems you raised about documentation should not be solved by us.

**Comment by amarzavery** [comment]
![screen shot 2018-08-16 at 7 39 46 pm](https://user-images.githubusercontent.com/4521223/44245176-55191280-a18c-11e8-9a40-0b619c8f647d.png)
![screen shot 2018-08-16 at 7 40 49 pm](https://user-images.githubusercontent.com/4521223/44245177-564a3f80-a18c-11e8-8c72-b6cdd77d69f0.png)

**Comment by mjyeaney** [comment]
Agreed - very helpful. That said, what we need to get front and center are the concepts / patterns used throughout the SDK (as you pointed out). No small feat for sure, but that's the secret sauce to a great dev experience. 

Appreciate the insights!
