### ISSUE TITLE
Should include LUIS runtime example for typescript as well.

### ISSUE THREAD

**Issue by chrimc62** [Azure/azure-sdk-for-node#3370]
The example is for node.  There should also be one for typescript.

**Comment by amarzavery** [comment]
@chrimc62 - IMO, the current sample for node.js is good enough. The TS sample wouldn't be radically different. We already using async/await feature and other stuf available in node.js 8.x.
/cc @kpajdzik

**Comment by daschult** [comment]
Closing this issue. Feel free to open if you feel there is more to add.
