### ISSUE TITLE
azure-sb swallows 503 errors from Service Bus REST api? 

### ISSUE THREAD

**Issue by tony-gutierrez** [Azure/azure-sdk-for-node#3374]
In application insights I can see that my premium SB is returning 503 errors. However these never come back from the SDK. The only way I noticed them in my node code is because I have a timeout on SB operations that gets triggered.

I am not sure if the swallowing is happening in azure-sb or in the azureCommon.ExponentialRetryPolicyFilter. The phrase "503" is not existent in the azure SDK code.
Testing without the retry filter now.

**Comment by tony-gutierrez** [comment]
@amarzavery

**Comment by tony-gutierrez** [comment]
I can see the 503 errors when not using a retry policy.

**Comment by amarzavery** [comment]
@ramya-rao-a - One more issue that will be fixed automatically when there is a new SB SDK for ATOM based HTTP APIs

**Comment by ramya-rao-a** [comment]
So is the problem that the retry policy never stops retrying or that it doesnt surface the errors once it stops retrying?

**Comment by amarzavery** [comment]
I think the retry filter should give all the errors as seen in the source code over [here](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/common/lib/services/filters/exponentialretrypolicyfilter.js#L106).

It retries upto 3 times with max retry interval set to 90 seconds. 
Guess: May be the operation timeout implemented by the customer happens sooner than that and he never sees those errors

**Comment by tony-gutierrez** [comment]
It's been a while since I reported this, but I had logging despite the
timeout, and was never able to see the errors. My thought was that they
were being swallowed entirely.
