### ISSUE TITLE
404 Link in npm repository 

### ISSUE THREAD

**Issue by gprossliner** [Azure/azure-sdk-for-node#3407]
Hello,
on the page "https://www.npmjs.com/package/azure-servicefabric" the repository link "https://github.com/azure/azure-sdk-for-node/lib/services/serviceFabric" seems to be invalid.

**Comment by RikkiGibson** [comment]
Thanks for catching this. Will update the link.

**Comment by RikkiGibson** [comment]
Attempting to address in Azure/azure-rest-api-specs#3759 but there are some configuration hangups.
