### ISSUE TITLE
Error: connect EACCES 40.90.139.2:443 - Local (undefined:undefined) error is thrown continuously when we try to translate the fields using the Translator Text Api and our input has around 2800 entries. 

### ISSUE THREAD

**Issue by shmisra** [Azure/azure-sdk-for-node#3418]
Error: connect EACCES 40.90.139.2:443 - Local (undefined:undefined) error is thrown continuously when we try to translate the fields using the Translator Text Api and our input has around 2800 entries. 

This is encountered while translating the csv fields in the response file that comes as a result of the azure functions developed using node.js

Stack Trace of the error is :

{'name':'RequestError','message':'Error: connect EACCES 40.90.139.2:443 - Local (undefined:undefined)','cause':{'code':'EACCES','errno':'EACCES','syscall':'connect','address':'40.90.139.2','port':443},'error':{'code':'EACCES','errno':'EACCES','syscall':'connect','address':'40.90.139.2','port':443},'options':{'method':'POST','uri':'https://api.cognitive.microsofttranslator.com/translate?api-version=3.0&to=en','body':[{'Text':'Ninguna'}],'json':true,'simple':true,'resolveWithFullResponse':false,'transform2xxOnly':false}} 'Error: connect EACCES 40.90.139.2:443 - Local (undefined:undefined)' 'RequestError: Error: connect EACCES 40.90.139.2:443 - Local (undefined:undefined)\\n at new RequestError (D:\\home\\site\\wwwroot\\nodemodules\\request-promise-core\\lib\\errors.js:14:15)\\n at Request.plumbing.callback (D:\\home\\site\\wwwroot\\nodemodules\\request-promise-core\\lib\\plumbing.js:87:29)\\n at Request.RP$callback [as callback] (D:\\home\\site\\wwwroot\\nodemodules\\request-promise-core\\lib\\plumbing.js:46:31)\\n at self.callback (D:\\home\\site\\wwwroot\\nodemodules\\request\\request.js:186:22)\\n at emitOne (events.js:96:13)\\n at Request.emit (events.js:188:7)\\n at Request.onRequestError (D:\\home\\site\\wwwroot\\nodemodules\\request\\request.js:878:8)\\n at emitOne (events.js:96:13)\\n at ClientRequest.emit (events.js:188:7)\\n at TLSSocket.socketErrorListener (httpclient.js:310:9)\\n at emitOne (events.js:96:13)\\n at TLSSocket.emit (events.js:188:7)\\n at emitErrorNT (net.js:1277:8)\\n at combinedTickCallback (internal/process/nexttick.js:80:11)\\n at process.tickCallback (internal/process/nexttick.js:104:9)' 

Is this due to concurrent/parallel requests to the API or is there something to be done with establishing the connection itself?

**Comment by shmisra** [comment]
Here its pointing to Qualtrics but still failing to connect to 23.75.225.97.
This is the latest error from translate:

{"name":"RequestError","message":"Error: connect EACCES 40.90.139.2:443 - Local (undefined:undefined)","cause":{"code":"EACCES","errno":"EACCES","syscall":"connect","address":"40.90.139.2","port":443},"error":{"code":"EACCES","errno":"EACCES","syscall":"connect","address":"40.90.139.2","port":443},"options":{"method":"POST","uri":"https://api.cognitive.microsofttranslator.com/translate?api-version=3.0&to=en","body":[{"Text":"Não assisto tv!"}],"json":true,"headers":{"Content-Type":"application/json","X-ClientTraceId":"e2940443-1a15-48f0-828c-d7c6118cf5da"},"simple":true,"resolveWithFullResponse":false,"transform2xxOnly":false}} "Error: connect EACCES 40.90.139.2:443 - Local (undefined:undefined)" "RequestError: Error: connect EACCES 40.90.139.2:443 - Local (undefined:undefined)\n    
at new RequestError (D:\home\site\wwwroot\nodemodules\request-promise-core\lib\errors.js:14:15)\n    
at Request.plumbing.callback (D:\home\site\wwwroot\nodemodules\request-promise-core\lib\plumbing.js:87:29)\n    
at Request.RP$callback [as callback] (D:\home\site\wwwroot\nodemodules\request-promise-core\lib\plumbing.js:46:31)\n   
 at self.callback (D:\home\site\wwwroot\nodemodules\request\request.js:186:22)\n    
at emitOne (events.js:96:13)\n    at Request.emit (events.js:188:7)\n    
at Request.onRequestError (D:\home\site\wwwroot\nodemodules\request\request.js:878:8)\n    
at emitOne (events.js:96:13)\n    at ClientRequest.emit (events.js:188:7)\n    
at TLSSocket.socketErrorListener (httpclient.js:310:9)\n    at emitOne (events.js:96:13)\n    
at TLSSocket.emit (events.js:188:7)\n   
at emitErrorNT (net.js:1277:8)\n    at combinedTickCallback (internal/process/

**Comment by amarzavery** [comment]
@shmisra - Can you please let us know which npm package are you using? Are you behind a firewall or something that is blocking the request?

**Comment by shmisra** [comment]
Request promise - Is used to make calls to API.

**Comment by amarzavery** [comment]
@shmisra - I was not clear, in my question. I wanted to know which sdk/package are you using. This repository contains bunch of sdks for different Azure [services](https://github.com/Azure/azure-sdk-for-node/tree/master/lib/services). 

If you are using the SDK, then what is the need to use request-promise? The SDK methods support callback as well as promises.

It looks like there is no sdk for translate APIs. I could find some samples for node.js over [here](https://docs.microsoft.com/en-us/azure/cognitive-services/translator/quickstart-nodejs-translate)

**Comment by amarzavery** [comment]
Is the firewall blocking port 443?
