### ISSUE TITLE
Unable to use `WebsiteManagementClient.listSourceControls()`

### ISSUE THREAD

**Issue by nturinski** [Azure/azure-sdk-for-node#3517]
After upgrading to the new API, '2018-02-01', we are now getting an error that this command is no longer supported.  We were using this to get the OAuth token to use in GitHub REST API requests on behalf of the user.

Is there any chance this command could be supported or if there is an alternative way to retrieve the GitHub token?

**Comment by RikkiGibson** [comment]
Did this happen in `azure-arm-website@4.0.0`?

**Comment by nturinski** [comment]
Yes, that's correct.

**Comment by RikkiGibson** [comment]
I'm looking into it. Hoping @ruslany or @naveedaz from the service team will be able to assist.

**Comment by RikkiGibson** [comment]
@nturinski It sounds like something was misconfigured on the service side. Service team says they've fixed it. Please try again and let us know if the problem is resolved.
