### ISSUE TITLE
userTokenCredentials is swallowing the original error object and raises a new one instead 

### ISSUE THREAD

**Issue by bahatelos** [Azure/azure-sdk-for-node#3533]
The userTokenCredentials function under ms-rest-azure is creating and throwing a new Error and in the process is swallowing the actual error object.

https://github.com/Azure/azure-sdk-for-node/blob/27b47b502fd4d87309d8f538fb2ed57376102a9a/runtime/ms-rest-azure/lib/credentials/userTokenCredentials.js#L123

It would be great if it could maintain the original error object with details like the http error code.
There is already a ServiceError which would fit the bill:

https://github.com/Azure/azure-sdk-for-node/blob/master/runtime/ms-rest/index.d.ts#L83

This would allow for better error handling on the client side as at the moment it requires parsing the error.message to find the error code.

**Comment by amarzavery** [comment]
Please try the new @azure/ms-rest-nodeauth package.
