### ISSUE TITLE
Invalid types on listBlobsSegmented

### ISSUE THREAD

**Issue by chriskuech** [Azure/azure-sdk-for-node#3544]
`listBlobsSegmented`'s TypeScript type interface only accepts `ContinuationToken`, but [the docs](https://docs.microsoft.com/en-us/javascript/api/azure-storage/azurestorage.services.blob.blobservice.blobservice?view=azure-node-latest#listblobssegmented) claim the function can accept `null` or `undefined`.  Type interface should be updated to accept `ContinuationToken | null | undefined` to maintain type safety.

**Comment by amarzavery** [comment]
Yes, you are absolutely right. @XiaoningLiu - Can you please take a look at this?
Btw, this is the repo https://github.com/Azure/azure-storage-node, where you should file this issue.

**Comment by amarzavery** [comment]
closing this in favor of https://github.com/Azure/azure-storage-node/issues/515
