### ISSUE TITLE
ARM modules using wrong baseUrl when signing into AzureUSGovernment

### ISSUE THREAD

**Issue by cshipman** [Azure/azure-sdk-for-node#3749]
I have been trying to use the ARM modules to provision resources in AzureCloud and AzureUSGovernment and I believe I have found a small bug.

I use something like the following to get credentials

```javascript
function azureLogin(options) {
        try {
            let _env = null;

            switch(this._cloud) {
                case 'AzureUSGovernment':
                    _env = MsRestAzure.AzureEnvironment.AzureUSGovernment;
                break;
                default:
                    _env = MsRestAzure.AzureEnvironment.Azure;
            }

            let _options = Object.assign({'environment': _env}, options);
            return MsRestAzure.loginWithServicePrincipalSecret(this._appId[this._cloud], this._secret[this._cloud], this._domain[this._cloud], _options);
        } catch(err) {
            // ...handle error here
        }
    }
```

When I get valid credentials for AzureUSGovernment and pass them into the constructor for any of the arm modules, the module still uses the commercial cloud management url.

I end up having to work around it by doing this

```javascript
let credentials = await akm.azureLogin();
let client = new KeyVaultManagementClient(credentials, 'subscription_id'); 
client.baseUri = credentials.environment.resourceManagerEndpointUrl;
```

It would be nice if the modules could use the correct management url depending on the cloud the credentials are valid for

**Comment by amarzavery** [comment]
@cshipman - Thanks for filing this issue. We are aware about this issue and have fixed this in the newer typescript sdks that we plan to ship by the end of this month. The new sdks are isomorphic (same source code would work in node.js and browser environment). Will let you know, once we have published them to npm.
related issue https://github.com/Azure/azure-sdk-for-node/issues/3280
