### ISSUE TITLE
loginWithAppServiceMSI is valid with only a resource, but typescript does not allow it

### ISSUE THREAD

**Issue by StefanSchoof** [Azure/azure-sdk-for-node#3778]
In [Use Key Vault from App Service with Managed Service Identity and Nodejs](https://azure.microsoft.com/de-de/resources/samples/app-service-msi-keyvault-node/) is the login done with `msRestAzure.loginWithAppServiceMSI({resource: 'https://vault.azure.net'})`. This works for my js code. Try the same in typescript gave me:

```
Argument of type '{ resource: string; }' is not assignable to parameter of type 'MSIAppServiceOptions'.
Property 'msiEndpoint' is missing in type '{ resource: string; }'.
```

I think the `msiEndpoint`  and `msiSecret` in `MSIAppServiceOptions`  need to be optional. Similar to the commit 1183bfeba508de81e4435b540609ad4deeefe007 from @irnc .

**Comment by scott-lin** [comment]
This is blocking our team from using MSI because we cannot specify the resource in our TypeScript code due to compiler error.

**Comment by daschult** [comment]
This got fixed in https://github.com/Azure/azure-sdk-for-node/commit/4b85045b101104487c04fd355f66a01344744950 but hasn't been published yet. I'll work on making that happen today.
