### ISSUE TITLE
mrestAzure loginWithServicePrincipalSecret behind a proxy

### ISSUE THREAD

**Issue by Mattious** [Azure/azure-sdk-for-node#3816]
Hi,

i use on local development the mrestAzure package and the function loginWithServicePrincipalSecret .
My issue is how i can force the package to use my enterprise proxy settings.
When i want to test the package try to connect azure management directly without contacting the proxy.

I've tested multiple solution : set http proxy variable, netsh winhttp to specify proxy, ... But nothing help.

If you can help me :(

regards

**Comment by Mattious** [comment]
Hi,

For info i've tested multiple solution

 - set proxy environment variable : not running
 - use netsh winhttp to set proxy : not running
 - use software proxycap : it runs. But software is not free and can't request to other developper to use it.

Any has an idea ?? Issue is only for request done by the package.
If i use http request to do the request my self, it works :(

Thanks for your help

**Comment by daschult** [comment]
Sorry, we never officially supported proxies in this library. We're also working on deprecating this library in favor of [ms-rest-azure-js](https://www.github.com/azure/ms-rest-azure-js) and [ms-rest-js](https://www.github.com/azure/ms-rest-js), so it isn't likely that we'll get around to supporting it in this library ever.
We don't have proxy support planned for [ms-rest-js](https://www.github.com/azure/ms-rest-js) at this time either. Feel free to file an issue in [ms-rest-js](https://www.github.com/azure/ms-rest-js) asking for proxy support.
