### ISSUE TITLE
BUG: Azure API management user.createOrUpdate does not pass identities array

### ISSUE THREAD

**Issue by gunzip** [Azure/azure-sdk-for-node#3857]
Actually the createOrUpdate op on user object does not pass the "identities" array to post body parameters here:

https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/apimanagement/lib/operations/user.js#L742

That's because identities is set to 'readonly' here:
https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/apimanagement/lib/models/userCreateParameters.js#L72

while it's not. Indeed if you manually call the createOrUpdate API passing identities it works correctly.

This prevents to programmatically create users that have a social or Active Directory identity.

see also https://stackoverflow.com/questions/52769817/creating-a-new-user-in-the-api-management-with-adb2c

**Comment by vetrivelmp** [comment]
this will be fixed by 12th November 2018?

**Comment by daschult** [comment]
In Sprint-127 our team will be focusing on our customer-reported issues, so we'll try to fix as many as we can. Anything that we can't fix will go into Sprint-128. We should be able to at least look at this issue and determine what next steps we need to take.

**Comment by amarzavery** [comment]
Here is the swagger spec that says identities is read-only. Because of which the generated sdk is having identities property as read-only.

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2018-01-01/apimusers.json#L825

**Comment by vetrivelmp** [comment]
We have to programatically create B2C user in APIM. so that we will have our user maintenance in one place and it is criticial for us to select APIM as product for managing APIs. we have some strict deadline to complete this feature. So please let us know when this fix will be done.

**Comment by gunzip** [comment]
we ended up using [patch-package](https://www.npmjs.com/package/patch-package) with this patch here:
https://github.com/teamdigitale/digital-citizenship-onboarding/blob/custom-portal/patches/azure-arm-apimanagement%2B2.1.1-preview.patch

**Comment by amarzavery** [comment]
This PR fixes it https://github.com/Azure/azure-sdk-for-node/pull/4076/files

**Comment by amarzavery** [comment]
@gunzip - New package 4.3.0-preview has been published to npm. https://www.npmjs.com/package/azure-arm-apimanagement . Let us know if you still see any issues.

**Comment by vetrivelmp** [comment]
did the change also implement in Microsoft.Azure.Management.ApiManagement.dll (.net version)?
Url:
https://www.nuget.org/packages/Microsoft.Azure.Management.ApiManagement/

**Comment by solankisamir** [comment]
not yet. That might take some time, a week possibly.

**Comment by solankisamir** [comment]
Nuget is out with the fix https://www.nuget.org/packages/Microsoft.Azure.Management.ApiManagement/4.0.6-preview

**Comment by daschult** [comment]
Since the NPM and Nuget packages have both been updated with the fix, I'm going to close this issue.
