### ISSUE TITLE
azure-sb: Unable to recover from errors such as ECONNRESET

### ISSUE THREAD

**Issue by ruhkopf** [Azure/azure-sdk-for-node#3871]
Hi,

We're polling our queue with `serviceBusClient.receiveQueueMessage(this._queueName, { isPeekLock: true }` every second. Occasionally (typically after 20 hours or so), the connection fails with `ECONNRESET`. It wouldn't be much of an issue if the SDK would just retry / or we could retry ourselves. However, when this happens, all further polling attempts fail - even when creating a new SB service instance. The only way to fix this seems to restart the NodeJS process.

Is this a known issue? Is there a fix or a workaround that I could implement?

Thanks,
Patrick

**Comment by amarzavery** [comment]
@ramya-rao-a - This will be fixed easily when the team decides to reimplement this package with a dependency on the new runtime.

**Comment by ramya-rao-a** [comment]
@amarzavery How will the new runtime help here? And which new runtime are you referring to?

**Comment by amarzavery** [comment]
@ruhkopf - Please try the new https://www.npmjs.com/package/@azure/service-bus package that is implemented using the AMQP protocol for sending/receiving messages to/from the queue.

@ramya-rao-a - Sorry for the confusion. 


The `azure-sb` package depends on the super old runtime `azure-common` (written ~6 years ago) which uses the `request` library underneath and has it's own retry policies. When the library is re-implemented and written on the new `core-http` library, I guess the problem may not persist for HTTP based CRUD operations on SB.
