### ISSUE TITLE
BUG: graph management - cannot create ADB2C user

### ISSUE THREAD

**Issue by gunzip** [Azure/azure-sdk-for-node#3916]
Actually it is not possible to create Azure Active Directory B2C user using azure-graph.

According to the docs here:
https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/active-directory-b2c/active-directory-b2c-devquickstarts-graph-dotnet.md#create-consumer-user-accounts

with ADB2C you must pass a "creationType" parameter and the "signInNames" array but this cannot be done actually as the UserCreateParameters model does not contain the properties here:
https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/graphManagement/lib/models/userCreateParameters.js
(same states for the relative class). 

Moreover "userPrincipalName" must not be required when using ADB2C.

I've manually tested that it works if you pass through the two params and omit "userPrincipalName".

**Comment by amarzavery** [comment]
The graph package does not support Azure AD B2C scenarios. I think you may want to use [this](https://github.com/microsoftgraph/msgraph-sdk-javascript) library instead.

@sureshja - If your team can add support for this in the [AD Graph swagger spec](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/graphrbac/data-plane/stable/1.6/graphrbac.json), then the current sdk can support those scenarios.
