### ISSUE TITLE
Azure DNS Alias Record Support

### ISSUE THREAD

**Issue by GavinOsborn** [Azure/azure-sdk-for-node#3932]
Azure DNS [recently announced](https://azure.microsoft.com/en-au/blog/announcing-alias-records-for-azure-dns/) the general availability of Alias records.

When can we expect support for this feature to be available in the node sdk?

**Comment by daschult** [comment]
We automatically update the Node.js packages based on the OpenAPI specifications in the [azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs) repository. As soon as the service team updates their specification, then we will publish a new package.
We just published a new azure-arm-dns package about a week ago: https://www.npmjs.com/package/azure-arm-dns/v/3.2.0. I'm guessing that has the functionality you're interested in.
