### ISSUE TITLE
azure-sb Send notifications with TAGs not working

### ISSUE THREAD

**Issue by CollapsedMetal** [Azure/azure-sdk-for-node#3935]
Hello!

Im using azure sdk for nodejs to send notifications to some mobile devices. 
I am using tags to identify mobile devices and associate them with users.

I was using this logic to send notifications to specific users.

```
var azure = require('azure-sb'); //or require('azure')
var notificationHubService = azure.createNotificationHubService('MyHub', 'Endpoint=sb://mynotificationnamespace.servicebus.windows.net/;SharedAccessKeyName=DefaultFullSharedAccessSignature;SharedAccessKey=xxxxxx=');
var payload = {
  data: {
    message: (new Date()).toJSON().slice(0, 19).replace(/[-T]/g, ':')
  }
};

notificationHubService.gcm.send("(RUTEmpresa_76658481-0 && ID_2 && UsrOEmpl_USR)", payload, function (error) {
  if (!error) {
    console.log("Notification Sent!")
  }
});
```

It worked perfectly until someday (this week), it suddenly stopped working.

Iv'e checked through azure notification hub "Test Send" with same Tags. It Worked!, but not anymore with azure sdk for nodejs.

![image](https://user-images.githubusercontent.com/5317311/47381640-dc2bbf00-d6d6-11e8-9b52-d0acddb9ed88.png)

If I send notifications without tags through nodejs it works perfect with the same code above.

Iv'e also tested using Microsoft.Azure.NotificationHubs and C# Console App, same bad result.

Any ideas?

**Comment by CollapsedMetal** [comment]
It's very strange.... Now everything is working just fine. I did not change anything, just re-tried now.
Maybe some service went down?
You guys maybe want to lookup forward on this subject.
Thanks in advance!

**Comment by daschult** [comment]
Glad everything is working for you again.
