### ISSUE TITLE
returning password in credentials

### ISSUE THREAD

**Issue by ajpyoungViseo** [Azure/azure-sdk-for-node#4159]
Using a sample code 

```var msRestAzure = require('ms-rest-azure');

var username = 'msoffice email here';
var password = 'msoffice password here';

msRestAzure.loginWithUsernamePassword(username, password, function(err, credentials) {
    if (err)
    {
        console.log("ERROR!!!!");
    }else{
        console.log('credentials');
        console.log(credentials);
    } 
    
  });
```

The credentials return the password of the user... is this not a security risk? The return payload includes the password of the user?

**Comment by amarzavery** [comment]
Well you are setting the password value in the variable either in the app or via environment variable. Someone can also read the environment variable values.

There is an in memory token cache as well. If someone gets access to it then that can be problematic as well. There would be some sort of risk at every step.

How  and where do you plan to use the credential object, is key to the problem at hand.

**Comment by ajpyoungViseo** [comment]
In reality, I'm just using this to validate employees using our in-house applications. We use MS online services heavily and was tasked to bypass our internal login in favor of login validation from online MS/Outlook/Azure.

When I found out about credentials return structure, I thought it might be of concern, although I'm not a security expert. If you guys think it's ok then I guess there's no problem 

Thanks for the quick reply

**Comment by amarzavery** [comment]
It is uncommon for a user to share his/her username/password creds with other people to login. So if the credentials are not shared in that sense then everything should be ok.
