### ISSUE TITLE
azure-arm-network virtualnetworks checkIPAddressAvailability returns a blank object

### ISSUE THREAD

**Issue by sachin11nov** [Azure/azure-sdk-for-node#4176]
I am using azure-arm-network node package, but for some reason checkIPAddressAvailability always return a blank result.

The document seems to be of not much use from here: https://docs.microsoft.com/en-us/javascript/api/azure-arm-network/virtualnetworks?view=azure-node-latest#checkipaddressavailability-string--string--string--object-

What am I missing?

`    'use strict';

    const msRestAzure = require('ms-rest-azure');
    const NetworkManagementClient = require('azure-arm-network');
    const config = require('./config.json');
    const model = "virtualNetworks";

    var credentials = new msRestAzure.ApplicationTokenCredentials(config.applicationId, config.activeDirectoryId, config.authenticationKey);
    var client = (new NetworkManagementClient(credentials, config.subscriptionId))[model];

    var rg = "my0rg";
    var vnet = "my-vnet";
    var ip = "10.0.9.5";

    client.checkIPAddressAvailability(rg, vnet, {ipAddress:ip},function(err, result, request, response) {
	if (err) {
	    console.log("Error:", JSON.stringify(err));
	} else {	
		console.log("checkIPAddressAvailability...result: ",JSON.stringify(request), err, JSON.stringify(result));
	}
    });`

**Comment by amarzavery** [comment]
@MikhailTryakhov - Please  take a look at this issue.

**Comment by MikhailTryakhov** [comment]
@number213  @EvgenyAgafonchikov  please review

**Comment by number213** [comment]
[This PR](https://github.com/Azure/azure-sdk-for-node/pull/4002) updated a lot of things, including parameters for checkIPAddressAvailability. It should be called this way (also you don't need to stringify err):

```js
client.checkIPAddressAvailability(rg, vnet, ip, function(err, result, request, response) {
  if (err) {
    console.log("Error:", err);
  } else {
    console.log("checkIPAddressAvailability...result: ", JSON.stringify(result));
  }
});

PS D:\Temp\issue> node .\script.js
checkIPAddressAvailability...result:  {"available":true}
```

**Comment by amarzavery** [comment]
Closing this for now. Feel free to create an issue in https://github.com/azure/azure-sdk-for-js repo and use the new `@azure/arm-network` package.
