### ISSUE TITLE
Cannot find module'azure-arm-datalake-store' after npm install

### ISSUE THREAD

**Issue by Liamdelee** [Azure/azure-sdk-for-node#4177]
Hi

I am trying to get the azure-arm-datalake-store node module going but for some reason this one is not working at all. I installed other once like azure-arm-website, async, adal-node azure-common and they all just load fine. 
However once i installed this one (no errors btw) i just get the cannot find module 'azure-arm-datalake-store' error.
Can somebody please help me with this? Thanks!

**Comment by chengtan2016** [comment]
Hi,
I ran into the same issue as well. Seems the `main` property in package.json file is not set to the name of script being exported from module. I have to downgrade to version 3.0.0 too.
