### ISSUE TITLE
Bug: API Management SDK unable to add more than 41 external groups. 

### ISSUE THREAD

**Issue by alexjchapman** [Azure/azure-sdk-for-node#4178]
When adding groups to an APIM instance from Active Directory I see the following error: "Failed to query Azure Active Directory graph due to error: An error occurred while processing this request."
We've seen this on version 4.0.0-preview and version 4.4.0-preview, using version 8.10.0 of Node.

This (repeatably) only happens when we have more than 41 groups registered in APIM, and doesn't happen when manually adding groups through the portal. 

We've found a work around that using the management.azure.com API works fine.

**Comment by amarzavery** [comment]
Please use the new package https://www.npmjs.com/package/@azure/arm-apimanagement. This repository will be deprecated soon in favor of https://github.com/azure/azure-sdk-for-js
