### ISSUE TITLE
API version can be accessed from resource or client

### ISSUE THREAD

**Issue by patchmeifyoucan** [Azure/azure-sdk-for-node#4370]
I am using the NodeJS client libraries for any kind of deployment. 
Sometimes a generic handling of resources is needed, e.g. deleting a dependency resource after the parent resource was deleted. 

The azure-arm-resource@7.2.1 client has a property apiVersion defined, even though it is not documented (so i think it's a bug). Other clients, such as azure-arm-compute|network|storage|sql are missing this property, just as documented. 

The azure-arm-resource client can delete a resource by its ID, additionally providing the API version used. It is a very convenient way to generically perform an operation on a resource. The problem now is that is impossible to find the used API version from the data model. Neither the resource itself nor the client reports the used API version (except the, let's call it "buggy", ResourceManagementClient). 

Even though the HTTP requests can be accessed which gives the ability to parse the API version from the request URL, I think the used API version should be a property of some object, since client versions also change their API version in newer versions.

A better solution (IMHO) would be to report the used API version from the resources's data model. This seems to be bigger change for me than introducing an apiVersion property for a client or a specific resource type. The clients seem to "know" which API version to use.

Is there any change that this will be introduces in the upcoming releases?

**Comment by daschult** [comment]
Hi @patchmeifyoucan. I think the SDKs aren't completely clear about the relationship between resources and API versions. API versions are associated with operations, not resources. For example, let's say that you create a new resource (let's call it R1) using a create operation and a specific API version (API1). If the Resource Provider releases a new API version (AP2), you should still be able to access R1 using both API1 and API2, right? There are some very rare cases where this isn't the case (They're so rare I can't even think of any specific ones right now), but for 99% of the cases this is true. In this scenario, the resource (R1) isn't bound to either of the API versions (API1 or API2), but operations can be performed against it using either API1 or API2. Does this clear this up?
Let's now talk about your specific scenario. You're issue description didn't mention whether you had any problems with deleting resources; just that you had some confusion about the purpose of the API version  property in the ResourceManagementClient. Hopefully my previous parameter has helped to explain the purpose of the API version property. This API version isn't the API version of the resource being operated on. It's actually the API version that will be sent to the ARM Resource Provider to indicate which version of the delete operation to use.
Does this clear things up?

**Comment by patchmeifyoucan** [comment]
Hello Dan,

thanks for the quick response. I now have a better understanding of the API versions. You are right, I did not mention a particular problem with deleting resources. I will try to explain why opened this issue in the first place. I also looked at the HTTP requests and responses, what follow is basically a question how to handle this type of behavior.

Currently, I use the latest client libraries for
compute@9.1.0 and
resource@7.2.1

The compute client creates a managed disk using API version 2018-06-01. The resource client which seems to be a bit older uses API version 2018-05-01 for the DELETE operation, which causes the API to send back this response:
"No registered resource provider found for location 'westeurope' and API version '2018-05-01' for type 'disks'. The supported api-versions are '2016-04-30-preview, 2017-03-30, 2018-04-01, 2018-06-01, 2018-09-30'."

It is easy to understand what the issue is. 
What I would like to do is, for example, tag resources bound to a specific virtual machine (disks, nics, ...) and delete them if any error occurs during deployment. I can use a non-generic workaround by saving deployed resources with their clients somewhere (which I don't like that much because it makes a simple step somewhat complicated). This procedure does not capture resources I did not create, e.g. managed OS disks. What I would have to do is to 
1. know which additional resources are created
2. find the correct client (in this case compute)
3. find an API version that supports deletion of this resource

Step 1 and 2 are very unlikely to change. Step 3 might change with every client version update. 

The generic deleteById method seems a bit useless to me (in an automated environment) if there is no chance to automagically find out which API version supports the operation (since the ID can be ANY resource provider). It still would be my preferred way to delete resources since I would have to care less about internals. 

Do you have any recommendations on this? Is there anything I am not aware of?

Thanks for the effort. :)

**Comment by daschult** [comment]
Okay, I think I understand your scenario a little better. So the problem is that after creating a managed disk using the [ComputeManagementClient](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/computeManagement2/lib/computeManagementClient.js#L26).[disks](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/computeManagement2/lib/computeManagementClient.js#L90) [client](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/computeManagement2/lib/operations/disks.js#L2148), you're now not able to delete the managed disk using the generic [ResourceManagementClient ](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/resourceManagement/lib/resource/resourceManagementClient.js#L26) because you don't know what version number to provide to the [delete method](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/resourceManagement/lib/resource/operations/resources.js#L4286).
This isn't a complete fix, but have you tried providing one of the API versions that the error message indicated when you call the delete method? It appears to me that the delete method does take an API version as an argument. A better solution would be if we exposed the API version that each client used for its operations, but before I make that change I'd like you to verify for me that using a correct API version argument for the delete method has the result you want.

**Comment by patchmeifyoucan** [comment]
If I provide a "correct" API version, everything works fine. The deletion as such works without any problems, I just have to manullay provide or parse the API version, which seems a bit tedious to me. 
So having an apiVersion property would solve my problem for resources I created myself.

That leaves the remaining problem for resources I did not create. From your first reply I understood that API versions have some "backwards compatibility". Or even without quotes. If this is the case, I also could request the latest API version and perform delete operations always with this version. Would this work?
This would be the "most generic" approach to me, since I would have to care about the API version exactly once (except those very rare cases you mentioned earlier, I guess I wont't see one of these any time soon).

**Comment by daschult** [comment]
I just asked around and it looks like there are two options:
1. I think it would be a good idea if each client exposed its API version as a property that could be used for this type of scenario. I can't guarantee when this can be worked on, but it's a good idea.
2. There already exists an [operation](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/resourceManagement/lib/resource/operations/providers.js#L1040-L1094) that returns a [Provider](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/resourceManagement/lib/resource/models/provider.js#L36-L86) object, which contains an array of [ProviderResourceType](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/resourceManagement/lib/resource/models/providerResourceType.js#L37-L112), which contains an array of [API versions](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/resourceManagement/lib/resource/models/providerResourceType.js#L81-L94). It requires a network call, but it looks like if you provide the resource provider's namespace ("Microsoft.Compute", I believe), then you should be able to get the API versions supported by that particular's resource provider's resource type. That can certainly unblock you now, but I think we'll still consider adding option 1 at some time in the future.

**Comment by patchmeifyoucan** [comment]
Adding option 1 sounds great. Thanks for providing the links. 👍 I'll look into it. 

Are we leaving this open to track progress?

**Comment by daschult** [comment]
I've created those two issues above (one for our Node.js generator and one for our TypeScript/JavaScript generator). Let's keep this issue open until you've confirmed that option 2 works for you. I can't guarantee when we'll get around to implementing these changes, so I'd look into option 2 for now.

**Comment by patchmeifyoucan** [comment]
Alright. I will be able to look into it next monday. Currently out of office.

**Comment by patchmeifyoucan** [comment]
I was not able to look into this earlier. But your proposed solution works. 👍 
The behavior concerning new vs. old API version is correct. I can delete any resource using a provider's latest API version. 
While option 1 is still a bit easier, option 2 is pretty easy as well.

Thanks a lot.
