### ISSUE TITLE
KeyVault tests are flaky on Node6 and Node8

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-node#4376]
The KeyVault tests have failed several times on our Azure Pipelines agents.  So far, the failures have all been on Node versions 6 and 8.

### https://dev.azure.com/azure-sdk/public/_build/results?buildId=1105
```
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: getaddrinfo ENOTFOUND testacc5018.vault.azure.net testacc5018.vault.azure.net:443
```

### https://dev.azure.com/azure-sdk/public/_build/results?buildId=1165
```
No obvious error in log
```

### https://dev.azure.com/azure-sdk/public/_build/results?buildId=1224
```
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Authentication failed. The 'Authorization' header is missing.
```

### https://dev.azure.com/azure-sdk/public/_build/results?buildId=1287
```
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Long running operation failed with error: "Invalid status code with response body "{"error":{"code":"AuthenticationFailed","message":"Authentication failed. The 'Authorization' header is missing."}}" occurred when polling for operation status.".
```

### https://dev.azure.com/azure-sdk/public/_build/results?buildId=1411
```
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: getaddrinfo ENOTFOUND testacc5018.vault.azure.net testacc5018.vault.azure.net:443
```

### https://dev.azure.com/azure-sdk/public/_build/results?buildId=1133
```
UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND testacc5018.vault.azure.net testacc5018.vault.azure.net:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
```

### https://dev.azure.com/azure-sdk/public/_build/results?buildId=1271
```
No obvious error in log
```

### https://dev.azure.com/azure-sdk/public/_build/results?buildId=1338
```
No obvious error in log
```

### https://dev.azure.com/azure-sdk/public/_build/results?buildId=1313
```
No obvious error in log
```

CC: @schaabs

**Comment by amarzavery** [comment]
Since new package is being developed in azure-sdk-for-js, I think this issue can be closed.
