### ISSUE TITLE
[Azure Bot Service] Register Bot channel via API

### ISSUE THREAD

**Issue by fmaker** [Azure/azure-sdk-for-node#4379]
This is supported in the .NET SDK, but not nodejs yet: https://github.com/Microsoft/BotBuilder/issues/4701

**Comment by avarabyeu** [comment]
Are there any updates? Using Golang SDK, but bot channel registration fails with:
![image](https://user-images.githubusercontent.com/1565439/54092688-1d7bed00-43a0-11e9-9560-a55645adb238.png)

**Comment by EugeneFoo** [comment]
Same here.

Postman sample URL:

https://management.azure.com/subscriptions/[subscription-id]/resourceGroups/ChatBot/providers/Microsoft.BotService/botServices/[bot-name]/channels/FacebookChannel?api-version=2018-07-12

Result:
{
    "error": {
        "code": "InternalServerError",
        "message": "Encountered internal server error. Please try again."
    }
}

**Comment by amarzavery** [comment]
Thanks for raising the issue. There is a [swagger specification](https://github.com/Azure/azure-rest-api-specs/tree/master/specification/botservice/resource-manager) for Azure Bot Service but we do not have a node or JS sdk. We will create a JS sdk for Azure Bot Service and publish one to npm in the coming week.

On a side note: We are deprecating the node sdk in favor of our new JS sdk. https://github.com/azure/azure-sdk-for-js where the sdk with TypeScript definitions can work in the browser and also on the server side (node.js). We will be publishing the sdk in the coming week and let you know about it.

/cc @daschult, @kpajdzik .

**Comment by amarzavery** [comment]
https://github.com/Azure/azure-sdk-for-js/issues/2538

**Comment by amarzavery** [comment]
@fmaker @avarabyeu @EugeneFoo 

New package [@azure/arm-botservice](https://www.npmjs.com/package/@azure/arm-botservice) has been published to npm.
```
npm i @azure/arm-botservice
```

Please feel free to file issues in the new repo https://github.com/azure/azure-sdk-for-js

**Comment by EugeneFoo** [comment]
Thanks @amarzavery
