### ISSUE TITLE
Incompatible API version for azure-arm-containerservice

### ISSUE THREAD

**Issue by zommarin** [Azure/azure-sdk-for-node#4388]
When using the current version of the npm modules azure-arm-containerservice (version 6.1.0) API calls to Azure to create Kubernetes clusters fail with the message:

```
Error: No registered resource provider found for location 'eastus2' and API version '2018-08-01-preview' for type 'managedClusters'.
The supported api-versions are '2017-08-31, 2018-03-31'.
The supported locations are 'eastus, westeurope, centralus, canadacentral, canadaeast, uksouth, westus, westus2, australiaeast, northeurope, japaneast, eastus2, southeastasia, ukwest, southindia, eastasia'
```

Downgrading the npm package to version 5.0.2 resolves the issue (version 6.0.0 does not work either) and then the API calls to Azure are done using the `2018-03-31` API version.

**Comment by amarzavery** [comment]
Please try the new package `@azure/arm-containerservice`
