### ISSUE TITLE
Error: interval must be of type moment.duration.

### ISSUE THREAD

**Issue by kochevRisto** [Azure/azure-sdk-for-node#4402]
I receive "Error: interval must be of type moment.duration." when I'm using moment.duration() as interval in metrics.list in azure-arm-monitor. The moment versions that I'm using is 2.22.2.  If I comment out the validation for the duration ( if(interval && !moment.isDuration(interval)) ) in the metrics I receive the correct response.

**Comment by daschult** [comment]
If you revert moment to 2.21.0 does the problem go away? It's frustrating that packages having breaking changes when they only bump the minor version, but it does happen occasionally, so that might be happening here.

**Comment by kochevRisto** [comment]
No, the previous versions are not working.
