### ISSUE TITLE
notificationhubservice.createOrUpdateInstallation doc incorrect 

### ISSUE THREAD

**Issue by Powerhelmsman** [Azure/azure-sdk-for-node#4438]
The issue was created by @gerhardcit from https://github.com/MicrosoftDocs/feedback/issues/301
notificationhubservice node-sdk documentation
The docs at https://docs.microsoft.com/en-us/javascript/api/azure-sb/notificationhubservice?view=azure-node-latest
are missing lots of details and some parameters are incorrect.
Documentation details
function createOrUpdateInstallation(installation, options, callback)
Indicated installation as a string.
Code details
But the code:
https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/serviceBus/lib/notificationhubservice.js
The code tests for installation.installationId which means installation is an object.
The installation object is not describe neither is the options.

**Comment by Deagler** [comment]
Made a [pull request](https://github.com/Azure/azure-sdk-for-node/pull/4548) to resolve this.
