### ISSUE TITLE
[azure-arm-eventhub] Incorrect payload returned when namespace list has no results

### ISSUE THREAD

**Issue by princjef** [Azure/azure-sdk-for-node#4453]
When using the namespace list API of the `azure-arm-eventhub` package, the API returns an object instead of an array when the subscription has no namespaces. This problem also appears to exist in the `azure-arm-sb` package.

Example code:

```ts
import { EventHubManagementClient } from 'azure-arm-eventhub';

const client = new EventHubManagementClient(credentials, subscriptionId);
const eventHubs = await client.namespaces.list();
Array.isArray(eventHubs) // false, result is { value: [] }
```

I did some digging into this and the issue appears to be related to the deserialization logic and/or mapper for this call. I tested this out by setting a breakpoint on [this line](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/eventHubManagement/lib/operations/namespaces.js#L295).

When I call the API using a subscription that contains namespaces, the value of `parsedResponse` looks like this:

```json
{
    "value": [
        {
            "sku": {
                "name": "Basic",
                "tier": "Basic",
                "capacity": 1
            },
            "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/test/providers/Microsoft.EventHub/namespaces/eh1",
            "name": "eh1",
            "type": "Microsoft.EventHub/Namespaces",
            "location": "West US",
            "tags": {},
            "properties": {
                "isAutoInflateEnabled": false,
                "maximumThroughputUnits": 0,
                "kafkaEnabled": false,
                "provisioningState": "Succeeded",
                "metricId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx:eh1",
                "createdAt": "2018-08-23T22:28:43.37Z",
                "updatedAt": "2018-08-23T22:29:07.183Z",
                "serviceBusEndpoint": "https://eh1.servicebus.windows.net:443/",
                "status": "Active"
            }
        },
        {
            "sku": {
                "name": "Standard",
                "tier": "Standard",
                "capacity": 1
            },
            "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/test/providers/Microsoft.EventHub/namespaces/eh2",
            "name": "eh2",
            "type": "Microsoft.EventHub/Namespaces",
            "location": "West US",
            "tags": {},
            "properties": {
                "isAutoInflateEnabled": false,
                "maximumThroughputUnits": 0,
                "kafkaEnabled": false,
                "provisioningState": "Succeeded",
                "metricId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx:eh2",
                "createdAt": "2018-08-23T22:28:43.37Z",
                "updatedAt": "2018-08-23T22:29:07.183Z",
                "serviceBusEndpoint": "https://eh2.servicebus.windows.net:443/",
                "status": "Active"
            }
        }
    ]
}
```

However, when I call with a subscription that has no such namespaces, `parsedResponse` is simply an empty object:

```json
{}
```

In the normal scenario, the `deserialize()` call pulls out the array from the `value` property, but in the empty case, it instead returns `{ value: [] }` back up to the caller, which is incorrect (should be `[]` instead).

**Comment by princjef** [comment]
Any word on this?

**Comment by daschult** [comment]
Unfortunately we're spending less and less time in the azure-sdk-for-node repository and we're trying to get everyone to move over to azure-sdk-for-js. Most of the time the change should be pretty minimal. In your case, I'd recommend depending on @azure/arm-eventhub instead of azure-arm-eventhub. That may be a better option for you than waiting for us to fix things in this repository.

**Comment by princjef** [comment]
Ah okay thanks for the information! I was unaware that a parallel package had been created under the `@azure` scope. I'll take that for a spin and follow up with anything I find over in that repo.

**Comment by princjef** [comment]
It looks like this is still a problem in the new packages, so I opened an issue over there as well: https://github.com/Azure/azure-sdk-for-js/issues/911

**Comment by amarzavery** [comment]
The issue has been fixed in `@azure/arm-event-hub`
