### ISSUE TITLE
SERVICE_BUS_NOTIFICATION_APNS_EXPIRY value is wrong

### ISSUE THREAD

**Issue by MiyoAlpizar** [Azure/azure-sdk-for-node#4496]
The constant value for SERVICE_BUS_NOTIFICATION_APNS_EXPIRY: 'ServiceBusNotification-ApnsExpiry' it´s wrong it must be SERVICE_BUS_NOTIFICATION_APNS_EXPIRY: 'ServiceBusNotification-Apns-Expiry', because the expiration date is not working when u send a push notification.

**Comment by Jegannathan** [comment]
Is this issue fixed ?

**Comment by ajithpoison** [comment]
@MiyoAlpizar This issue has been fixed. Please refer #5103 
@amarzavery Can you please close this.
