### ISSUE TITLE
Unable to send CustomProperties to Azure Topic from Nodejs

### ISSUE THREAD

**Issue by MeiyappanKannappa** [Azure/azure-sdk-for-node#4509]
Hi,

I tried to push message to Azure topic with custom properties as suggested by below website:

https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-nodejs-how-to-use-topics-subscriptions

Topic explorer has two windows in it, one is Message Text and another one is custom properties.
As per the documentation, properties added in customproperties should land on custom properties window, instead the message that I am sending to topic is landing on 1st window(Message Text) with body and customproperties.

It is properly working when I use BrokeredMessage in Java.

**Message:** 
const messageToTopic = {
    body: request.body,
    customProperties: {
        prop1: 'value1',
        prop2: 'value2'
    }
};

**Sending my message to topic using below code.**
var serviceBusServiceClient = azureSb.createServiceBusService(connectionString);
serviceBusServiceClient.sendTopicMessage(topicName, JSON.stringify(messageToTopic), function(error) {}

Azure package used : "azure-sb": "0.10.6",

Please suggest me any solution to achieve my requirement.

Thank You.

_Originally posted by @mlmk34 in https://github.com/Azure/azure-sdk-for-node/issues/1754#issuecomment-451475078_

**Comment by amarzavery** [comment]
@MeiyappanKannappa - Please use the new service bus package `npm i @azure/service-bus`.
The sample to send a message to a topc can be found [here](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/servicebus/service-bus/samples/typescript/advancedFeatures/topicFilters.ts#L69).

Source code for the new servicebus sdk can be found [here](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/servicebus/service-bus).

Moving forward, please file new issues over here https://github.com/Azure/azure-sdk-for-js.
