### ISSUE TITLE
Getting dependency issue in azure-keyvault with angular 7

### ISSUE THREAD

**Issue by SibinSivanand** [Azure/azure-sdk-for-node#4536]
We are trying to use azure-keyvault and ms-rest-azure packages for our angular 7 application.

How ever with **npm install** and **ng serve** I end up getting following dependency error. 

Any work around for the issue?

Adding my project versions if that helps:

Angular CLI: 7.1.4
**Node: 8.11.3
npm: 6.3.0**
OS: win32 x64
Angular: 7.2.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... http, language-service, material, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.11.4
@angular-devkit/build-angular     0.11.4
@angular-devkit/build-optimizer   0.11.4
@angular-devkit/build-webpack     0.11.4
@angular-devkit/core              7.1.4
@angular-devkit/schematics        7.1.4
@angular/cli                      7.1.4
@ngtools/webpack                  7.1.4
@schematics/angular               7.1.4
@schematics/update                0.11.4
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.28.3
**azure-keyvault                3.0.4**

`
WARNING in ./node_modules/ms-rest/lib/serviceClient.js 441:19-43
Critical dependency: the request of a dependency is an expression

ERROR in ./node_modules/adal-node/lib/cache-driver.js
Module not found: Error: Can't resolve 'crypto' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\adal-node\lib'
ERROR in ./node_modules/aws-sign2/index.js
Module not found: Error: Can't resolve 'crypto' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\aws-sign2'
ERROR in ./node_modules/aws4/aws4.js
Module not found: Error: Can't resolve 'crypto' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\aws4'
ERROR in ./node_modules/ecc-jsbn/index.js
Module not found: Error: Can't resolve 'crypto' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\ecc-jsbn'
ERROR in ./node_modules/http-signature/lib/verify.js
Module not found: Error: Can't resolve 'crypto' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\http-signature\lib'
ERROR in ./node_modules/http-signature/lib/signer.js
Module not found: Error: Can't resolve 'crypto' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\http-signature\lib'
ERROR in ./node_modules/jwa/index.js
Module not found: Error: Can't resolve 'crypto' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\jwa'
ERROR in ./node_modules/oauth-sign/index.js
Module not found: Error: Can't resolve 'crypto' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\oauth-sign'
ERROR in ./node_modules/request/lib/hawk.js
Module not found: Error: Can't resolve 'crypto' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\request\lib'
ERROR in ./node_modules/request/lib/helpers.js
Module not found: Error: Can't resolve 'crypto' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\request\lib'
ERROR in ./node_modules/request/lib/oauth.js
Module not found: Error: Can't resolve 'crypto' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\request\lib'
ERROR in ./node_modules/sshpk/lib/identity.js
Module not found: Error: Can't resolve 'crypto' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\sshpk\lib'
ERROR in ./node_modules/sshpk/lib/certificate.js
Module not found: Error: Can't resolve 'crypto' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\sshpk\lib'
ERROR in ./node_modules/sshpk/lib/dhe.js
Module not found: Error: Can't resolve 'crypto' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\sshpk\lib'
ERROR in ./node_modules/sshpk/lib/fingerprint.js
Module not found: Error: Can't resolve 'crypto' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\sshpk\lib'
ERROR in ./node_modules/sshpk/lib/key.js
Module not found: Error: Can't resolve 'crypto' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\sshpk\lib'
ERROR in ./node_modules/sshpk/lib/private-key.js
Module not found: Error: Can't resolve 'crypto' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\sshpk\lib'
ERROR in ./node_modules/sshpk/lib/signature.js
Module not found: Error: Can't resolve 'crypto' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\sshpk\lib'
ERROR in ./node_modules/sshpk/lib/utils.js
Module not found: Error: Can't resolve 'crypto' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\sshpk\lib'
ERROR in ./node_modules/sshpk/lib/formats/openssh-cert.js
Module not found: Error: Can't resolve 'crypto' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\sshpk\lib\formats'
ERROR in ./node_modules/sshpk/lib/formats/ssh-private.js
Module not found: Error: Can't resolve 'crypto' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\sshpk\lib\formats'
ERROR in ./node_modules/sshpk/lib/formats/pem.js
Module not found: Error: Can't resolve 'crypto' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\sshpk\lib\formats'
ERROR in ./node_modules/ms-rest-azure/lib/login.js
Module not found: Error: Can't resolve 'fs' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\ms-rest-azure\lib'
ERROR in ./node_modules/ms-rest/lib/serviceClient.js
Module not found: Error: Can't resolve 'fs' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\ms-rest\lib'
ERROR in ./node_modules/request/lib/har.js
Module not found: Error: Can't resolve 'fs' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\request\lib'
ERROR in ./node_modules/forever-agent/index.js
Module not found: Error: Can't resolve 'http' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\forever-agent'
ERROR in ./node_modules/http-signature/lib/signer.js
Module not found: Error: Can't resolve 'http' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\http-signature\lib'
ERROR in ./node_modules/request/request.js
Module not found: Error: Can't resolve 'http' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\request'
ERROR in ./node_modules/tunnel-agent/index.js
Module not found: Error: Can't resolve 'http' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\tunnel-agent'
ERROR in ./node_modules/tunnel/lib/tunnel.js
Module not found: Error: Can't resolve 'http' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\tunnel\lib'
ERROR in ./node_modules/forever-agent/index.js
Module not found: Error: Can't resolve 'https' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\forever-agent'
ERROR in ./node_modules/ms-rest/lib/filters/proxyFilter.js
Module not found: Error: Can't resolve 'https' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\ms-rest\lib\filters'
ERROR in ./node_modules/request/request.js
Module not found: Error: Can't resolve 'https' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\request'
ERROR in ./node_modules/tunnel-agent/index.js
Module not found: Error: Can't resolve 'https' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\tunnel-agent'
ERROR in ./node_modules/tunnel/lib/tunnel.js
Module not found: Error: Can't resolve 'https' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\tunnel\lib'
ERROR in ./node_modules/forever-agent/index.js
Module not found: Error: Can't resolve 'net' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\forever-agent'
ERROR in ./node_modules/tough-cookie/lib/cookie.js
Module not found: Error: Can't resolve 'net' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\tough-cookie\lib'
ERROR in ./node_modules/tunnel-agent/index.js
Module not found: Error: Can't resolve 'net' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\tunnel-agent'
ERROR in ./node_modules/tunnel/lib/tunnel.js
Module not found: Error: Can't resolve 'net' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\tunnel\lib'
ERROR in ./node_modules/adal-node/lib/util.js
Module not found: Error: Can't resolve 'os' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\adal-node\lib'
ERROR in ./node_modules/ms-rest/lib/filters/msRestUserAgentFilter.js
Module not found: Error: Can't resolve 'os' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\ms-rest\lib\filters'
ERROR in ./node_modules/mime-types/index.js
Module not found: Error: Can't resolve 'path' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\mime-types'
ERROR in ./node_modules/ms-rest/lib/serviceClient.js
Module not found: Error: Can't resolve 'path' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\ms-rest\lib'
ERROR in ./node_modules/ms-rest/lib/utils.js
Module not found: Error: Can't resolve 'path' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\ms-rest\lib'
ERROR in ./node_modules/assert-plus/assert.js
Module not found: Error: Can't resolve 'stream' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\assert-plus'
ERROR in ./node_modules/combined-stream/lib/combined_stream.js
Module not found: Error: Can't resolve 'stream' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\combined-stream\lib'
ERROR in ./node_modules/delayed-stream/lib/delayed_stream.js
Module not found: Error: Can't resolve 'stream' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\delayed-stream\lib'
ERROR in ./node_modules/duplexer/index.js
Module not found: Error: Can't resolve 'stream' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\duplexer'
ERROR in ./node_modules/isstream/isstream.js
Module not found: Error: Can't resolve 'stream' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\isstream'
ERROR in ./node_modules/jws/lib/data-stream.js
Module not found: Error: Can't resolve 'stream' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\jws\lib'
ERROR in ./node_modules/jws/lib/verify-stream.js
Module not found: Error: Can't resolve 'stream' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\jws\lib'
ERROR in ./node_modules/jws/lib/sign-stream.js
Module not found: Error: Can't resolve 'stream' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\jws\lib'
ERROR in ./node_modules/request/request.js
Module not found: Error: Can't resolve 'stream' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\request'
ERROR in ./node_modules/sshpk/lib/ed-compat.js
Module not found: Error: Can't resolve 'stream' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\sshpk\lib'
ERROR in ./node_modules/through/index.js
Module not found: Error: Can't resolve 'stream' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\through'
ERROR in ./node_modules/forever-agent/index.js
Module not found: Error: Can't resolve 'tls' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\forever-agent'
ERROR in ./node_modules/tunnel-agent/index.js
Module not found: Error: Can't resolve 'tls' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\tunnel-agent'
ERROR in ./node_modules/tunnel/lib/tunnel.js
Module not found: Error: Can't resolve 'tls' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\tunnel\lib'
ERROR in ./node_modules/request/request.js
Module not found: Error: Can't resolve 'zlib' in 'D:\AngularRepo\Azure\AzureUIPOC\node_modules\request'`

**Comment by mb590721** [comment]
Hi,

We have the same issue when using Angular 7 with the `@azure/event-hubs:1.0.8` dependency.

<pre>
WARNING in ./node_modules/ms-rest/lib/serviceClient.js 441:19-43
Critical dependency: the request of a dependency is an expression

ERROR in ./node_modules/adal-node/lib/cache-driver.js
Module not found: Error: Can't resolve 'crypto' in 'C:\Users\mbarbin\Documents\Azure_IA\azure-mastermind-visualization\node_modules\adal-node\lib'
ERROR in ./node_modules/aws-sign2/index.js
Module not found: Error: Can't resolve 'crypto' in 'C:\Users\mbarbin\Documents\Azure_IA\azure-mastermind-visualization\node_modules\aws-sign2'
ERROR in ./node_modules/aws4/aws4.js
......
......
......
</pre>

**Comment by amarzavery** [comment]
@SibinSivanand - The node sdk is not designed to be used for browser. I would recommend using the new key vault sdk that should work in node.js (Server side) and the browser as well.

Take a look at the sample [here](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/keyvault/keyvault#browser---authentication-client-creation-and-getkey--as-an-example-written-in-javascript)
