### ISSUE TITLE
Cannot login to Azure account.  Seemed to be same issue as #1953 which was closed without resolution.

### ISSUE THREAD

**Issue by Straightly** [Azure/azure-sdk-for-node#4542]
WS-Trust RST request returned http error: 500 and server response: AUTH ERROR 1003

It seemed to be the same issue as "User Can Login to Azure Portal and has full access but SDK can't acquire token #1953".  That issue was closed as the reporter abandoned his effort.

**Comment by amarzavery** [comment]
This is an issue with the underlying https://www.npmjs.com/package/adal-node package. Multiple issues have been filed with some workarounds over here https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/search?q=ws-trust&type=Issues
