### ISSUE TITLE
[azure-arm-timeseriesinsights] Leaking types from moment

### ISSUE THREAD

**Issue by BrandonColl** [Azure/azure-sdk-for-node#4551]
When using the current version of the npm module azure-arm-timeseriesinsights (Version 1.1.0) there is a type dependency on moment at this line:

https://github.com/Azure/azure-sdk-for-node/blob/05140d5ac6b9e16b72053d50ebece28c956efcf6/lib/services/timeseriesinsightsManagement/lib/models/index.d.ts#L186

Moment is not included in azure-arm-timeseriesinsights package.json as a required dependency. This requires it to be manually installed by the library consumer.

**Comment by amarzavery** [comment]
Thanks for reporting the issue. We will be deprecating the current node sdk in favor of the new JS sdk that can work in the browser and also on the server side (node.js). You can find the new sdk over [here](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/timeseriesinsights/arm-timeseriesinsights).

In the new sdk, we are not taking a dependency on moment. The sdk will return the duration as a string. It is upto you to use moment or any other package to convert the string to a Duration like object.
