### ISSUE TITLE
Generating credential object using OAuth access token/auth code

### ISSUE THREAD

**Issue by matpadikar** [Azure/azure-sdk-for-node#4585]
There doesn't seem to be an option to generate 'credential' using access-token/auth-code received using OAuth 2 in https://www.npmjs.com/package/ms-rest-azure.

Is there anything I am missing here?

**Comment by bora89** [comment]
Any news? Microsoft?

**Comment by sidvip** [comment]
> There doesn't seem to be an option to generate 'credential' using access-token/auth-code received using OAuth 2 in https://www.npmjs.com/package/ms-rest-azure.
> 
> Is there anything I am missing here?

One way is to use the rest URI related to your specific service and make a call using access token in the header. I think this may fix your concern. As credentials object has a lot of information in it like metadata which is associated with your user information when you use login methods. But when you use OAuth mechanism it is somewhat related to your specific scope which you want to use and where to use. So I think to get the creds object will be quite roundabout a job which is easily resolved by getting the URI related to service.

**Comment by matpadikar** [comment]
> 
> One way is to use the rest URI related to your specific service and make a call using access token in the header. I think this may fix your concern. As credentials object has a lot of information in it like metadata which is associated with your user information when you use login methods. But when you use OAuth mechanism it is somewhat related to your specific scope which you want to use and where to use. So I think to get the creds object will be quite roundabout a job which is easily resolved by getting the URI related to service.

@sidvip that can always be done, but the issue here is the pre-built node packages for Azure can't be leveraged in that case.

**Comment by amarzavery** [comment]
> There doesn't seem to be an option to generate 'credential' using access-token/auth-code received using OAuth 2 in https://www.npmjs.com/package/ms-rest-azure.

[TokenCredentials](https://github.com/Azure/azure-sdk-for-node/blob/master/runtime/ms-rest/lib/credentials/tokenCredentials.js) in [ms-rest](https://www.npmjs.com/package/ms-rest) the base package that **ms-rest-azure** depends on can be used to create a Credential object if you already have the access token.

**Comment by matpadikar** [comment]
@amarzavery, thanks! I will look into the TokenCredentials package.

In my use case our OAuth micro-service handles the generation of access token from the auth code (From user logging for the first time where they save their authorization. They are not asked to login further and can use the saved authorization).
