### ISSUE TITLE
Feature Request: Service Bus Queue Message Notifier

### ISSUE THREAD

**Issue by imalao** [Azure/azure-sdk-for-node#4601]
The Node.js sample has the consumer check the queue for new messages (https://github.com/Azure/azure-sdk-for-node/tree/master/lib/services/serviceBus#how-to-use). 

It'd be great to have a feature to deliver messages as they come into the queue or for the consumer to be notified that there are new messages. 

I believe the .NET Azure SDK has this feature through its `onMessage` method (https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.queueclient.onmessage?view=azure-dotnet)

**Comment by junsaw** [comment]
Do we have any update on this feature request ?

**Comment by amarzavery** [comment]
Yes. We have a new sdk "npm i @azure/service-bus" that solves this issue. The new sdk is in the new repo over [here](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/servicebus/service-bus).

You can find a sample that solves the reported issue over [here](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/servicebus/service-bus/samples/typescript/gettingStarted/receiveMessagesStreaming.ts#L33).

Moving forward, please file new service bus related issues in the new repo https://github.com/Azure/azure-sdk-for-js.
