### ISSUE TITLE
StorageManagementClient fails to sign requests when authenticated using Service Principal

### ISSUE THREAD

**Issue by amclin** [Azure/azure-sdk-for-node#4649]
`StorageManagementClient.storageAccounts.checkNameAvailability()` fails when authenticated using a Service Principle

### Example code
```
const msRestAzure = require('ms-rest-azure')
const { StorageManagementClient } = require('@azure/arm-storage')

const clientId = process.env.CLIENT_ID
const tenantId = process.env.TENANT_ID
const resourceGroupName = process.env.AZURE_RESOURCE_GROUP_NAME
const secret = process.env.APPLICATION_SECRET
const subscriptionId = process.env.AZURE_SUBSCRIPTION_ID

msRestAzure.loginWithServicePrincipalSecret(clientId, secret, tenantId)
  .then((credentials) => {
    const client = new StorageManagementClient(credentials, subscriptionId)
    return Promise.resolve(storageClient)
  })
  .then((client) => {
    return client.storageAccounts.checkNameAvailability('sample-name')
  })
  .catch((err) => {
    console.error(err)
  })
```

### Error thrown
`callback is not a function`

### Root cause
There appears to be a mismatch in the interfaces between the different packages. Specifically:

`applicationTokenCredentials.signRequest()` in `ms-rest-azure` expects a callback parameter. That parameter is required, and an error is thrown if that is missing.
https://github.com/Azure/azure-sdk-for-node/blob/master/runtime/ms-rest-azure/lib/credentials/applicationTokenCredentials.js#L157-L170

However StorageManagementClient is using `ms-rest-js`, and when the signingPolicy makes the call to the authentication provider via `signingPolicy.signRequest()` it does not provide a callback:
https://github.com/Azure/ms-rest-js/blob/master/lib/policies/signingPolicy.ts#L23-L25

**Comment by amclin** [comment]
This also fails for the same reason if I use `interactiveLogin()` instead of `loginWithServicePrincipalSecret()`

This only works if I create the StorageManagementClient using the "azure" package instead:
```
const Azure = require('azure')
....
const client = Azure.createStorageManagementClient(credentials, subscriptionId)
....
```

Why does ```azure createStorageManagementClient``` not do the same thing as new ```@azure/arm-storage new StorageManagementClient```

The inconsistencies in the SDKs are maddening. The explicit example in the documentation doesn't work: https://azure.github.io/azure-sdk-for-node/azure-arm-storage/latest/

**Comment by amarzavery** [comment]
You are mixing two packages. You need to use `@azure/ms-rest-nodeauth` with `@azure/arm-storage`
