### ISSUE TITLE
[Service Bus] There is no obvious way to retrieve messages from the dead letter queue

### ISSUE THREAD

**Issue by MLoughry** [Azure/azure-sdk-for-node#4660]
Currently, there's no available method on the [`ServiceBusService` object](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/serviceBus/lib/servicebusservice.js), not any other mechanism I can find, to read messages from a dead letter queue.

Doing some quick research on the .NET client, it seems that all `QueueClient.FormatDeadLetterPath()` does is simply append `/$DeadLetterQueue`, so I can probably send a quick PR out for this. However, this isn't documented in the [Service Bus dead-letter queue docs](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-dead-letter-queues).

**Comment by amarzavery** [comment]
@MLoughry - Please try out the new servicebus sdk `npm i @azure/service-bus`. The sdk has been moved to https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/servicebus/service-bus . The specific example of receiving messages from a DeadLetter Queue can be found [here](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/servicebus/service-bus/samples/typescript/advancedFeatures/processMessageFromDLQ.ts).

In future please open service bus related issues in the new repo https://github.com/Azure/azure-sdk-for-js
