### ISSUE TITLE
SchemaContract value field is not being populated when calling apiSchema.get

### ISSUE THREAD

**Issue by awaldow** [Azure/azure-sdk-for-node#4718]
https://github.com/Azure/azure-sdk-for-node/blob/d662a286e16b44eed6f968478c15b53cc14aa93e/lib/services/apimanagement/lib/models/schemaContract.js#L79-L81

I was attempting to use the apiManagementClient to pull down the schema for one of my APIs and noticed the returned response did not contain the document itself, just the metadata. Upon further investigation, I noticed that deep down in the _get call for apiSchema.js the document is indeed being returned, but after a pass through serialization.js it is being stripped because (I think) the serializedName in the schema contract is not valid. It is looking for properties.document.value but there is just properties.document and properties.document.definition et al once it passes through a JSON.parse here:

https://github.com/Azure/azure-sdk-for-node/blob/d662a286e16b44eed6f968478c15b53cc14aa93e/lib/services/apimanagement/lib/operations/apiSchema.js#L568-L572

**Comment by awaldow** [comment]
To provide some additional context, the following screenshots tell the story around line 570 of apiSchema.js.

First, the responseBody object as it is before it's been parsed:
![apischema responsebody](https://user-images.githubusercontent.com/418567/53185850-1c377b80-35bd-11e9-9da4-7c46db241e0b.PNG)

Though I could not show the whole thing, if you were to look through the document object further you would see nothing beyond the definitions child. 

Then, the parsedResponse at line 570 looks as follows:
![apischema parsedresponse](https://user-images.githubusercontent.com/418567/53185941-4a1cc000-35bd-11e9-910b-27682678470e.PNG)

documents contains no value object.

And then, the result object being returned on line 574 after deserializing:
![apischema result](https://user-images.githubusercontent.com/418567/53185993-63257100-35bd-11e9-8f69-6e1ea5750f28.PNG)

The document object has disappeared in its entirety. I had entertained the notion that maybe a .value at the end of a serializedName just meant "give me this object" but I see nothing in serialization.js to support that assertion. I should also note that apiSchema.listByApi suffers from this issue as well.

**Comment by awaldow** [comment]
So just to test, I went into my node_modules and removed the '.value' part of the serializedName so it was just 'properties.document'. I was then able to get a json reconstruction of the definitions of the schema. I am wondering how to get the YAML definition in its entirety but sending Content-Type 'application/vnd.oai.openapi' doesn't seem to change anything, I always just get the definitions, but that's a separate issue from this, though I would like some answer as to how one would get that.

**Comment by awaldow** [comment]
Is there a better place to raise this issue? It seems like the return content type is going to dictate whether you have this issue or not and with no mechanism to change that to get around it my project is essentially on hold.

**Comment by amarzavery** [comment]
@solankisamir  from the api management team can help you in this issue.

**Comment by solankisamir** [comment]
yes.. this is an issue in the Contract. The schema document should just be `properties.document`

We also support Wsdl (SOAP) based APIs. For those apis the schema document is accessible at `properties.document.value`

**Comment by solankisamir** [comment]
@awaldow we are working on fixing it, give it a week to reach to all clients.

**Comment by awaldow** [comment]
Thanks guys, this will help me a ton

**Comment by solankisamir** [comment]
Try this package https://www.npmjs.com/package/azure-arm-apimanagement/v/5.1.0
 
The `properties.Document` is now a JObject and you should be able to retrieve it.
https://docs.microsoft.com/en-us/rest/api/apimanagement/apischema/createorupdate#schemacontract
