### ISSUE TITLE
List all Virtual Machines limited to 50

### ISSUE THREAD

**Issue by ffclaranet** [Azure/azure-sdk-for-node#4769]
I' using the Azure node SDK to get all virtual machines for the subscription :
`var computeClient = new computeManagementClient.ComputeManagementClient(credentials, subscriptionId);
    var clientNetworkManagement = new NetworkManagementClient(credentials, subscriptionId);

        computeClient.virtualMachines.listAll(function (err, result) {  
            returnResult(result);
        });`

But I have subscription with more than 50 vm's and that call only return 50 vm's max.

It's possible to get more than 50 vms with this function computeClient.virtualMachines.listAll ?

Thx

**Comment by amarzavery** [comment]
I am sorry for the confusion. The name of the method is indeed confusing. The result will have a property called nextLink. Please provide that to 

```js
const result = await computeClient.virtualMachines.listAll();
const next page  = await computeClient.virtualMachines.listAllNext(result.nextLink);
```

**Comment by fbsanchez** [comment]
When `const result = await computeClient.virtualMachines.listAll();
`


`(node:7279) UnhandledPromiseRejectionWarning: Error: callback cannot be null.
`
