### ISSUE TITLE
Long-running Streaming Listener stops receiving/de-queuing messages after a while

### ISSUE THREAD

**Issue by lululeon** [Azure/azure-sdk-for-node#4819]
I have a listener that follows this pattern: https://github.com/Azure/azure-sdk-for-js/blob/master/packages/%40azure/servicebus/data-plane/examples/javascript/gettingStarted/receiveMessagesStreaming.js

The `receiver.receive()` call happens in my app at startup, and it works... but after a period of time (or maybe a period of _idle_ time... not sure which), the connection to servicebus doesn't work anymore and messages are stuck in the bus and not de-queued. These are the console messages when that happens:

![image](https://user-images.githubusercontent.com/6601801/53833492-a933ea80-3f56-11e9-924f-c1150ff8e22b.png)

I can't find any tutorials or documents illustrating a different receiving paradigm that either 1) polls Sbus or 2) keeps the connection alive and working regardless of up-time, so I'm inclined think this is a bug in the receive() behavior.

**Comment by amarzavery** [comment]
closing in favor of https://github.com/Azure/azure-sdk-for-js/issues/2540
