### ISSUE TITLE
Incomplete response from provider.getAvailableStacks() call

### ISSUE THREAD

**Issue by nturinski** [Azure/azure-sdk-for-node#5068]
The response from Azure when using the sdk does not include the majorVersions array that contains all the versions and display names available for web apps.

The expected response returns when making a call to this endpoint `https://management.azure.com/providers/Microsoft.Web/availableStacks?osTypeSelected=Linux&api-version=2018-02-01`.

**Comment by amarzavery** [comment]
@nturinski - Can you provide the response received from the sdk and the response received via making the REST request to get a clear picture of the difference?

**Comment by nturinski** [comment]
@amarzavery Thanks for your reply.  Sure thing!

This is from the sdk using `provider.getAvailableStacks()`

![image](https://user-images.githubusercontent.com/5290572/56926249-1ca13680-6a86-11e9-9fa8-2e7d3959f0d3.png)

This is by using the REST API after parsing the JSON string

![image](https://user-images.githubusercontent.com/5290572/56926295-4c503e80-6a86-11e9-9689-c00b0e354f20.png)

**Comment by amarzavery** [comment]
Please use the new `@azure/arm-appservice` package.
