### ISSUE TITLE
Deploying an exported template fails

### ISSUE THREAD

**Issue by yaron-idan** [Azure/azure-sdk-for-node#5073]
I'm exporting ARM templates of our resource groups for the sake of backup.
I'm using the `azure-arm-resource` (v7.3.0) npm module, exporting the template using the `.resourceGroups.exportTemplate` method.
The JSON file created by the method seems fine, but when I try to create a new deployment using the az cli (v2.0.62) I'm getting the following error - 
```
Azure Error: InvalidRequestContent
Message: The request content was invalid and could not be deserialized: 'Could not find member 'template' on object of type 'Template'. Path 'properties.template.template', line 1, position 40.'.
```
Any idea what could be the problem?

The issue can be reproduced by exporting any resource group template and trying to deploy the template on a blank resource group.

**Comment by amarzavery** [comment]
@yaron-idan Can you provide a sample deployment template that was exported?
@yugangw-msft - From the AZ CLI team can provide more info on the issue.

**Comment by yaron-idan** [comment]
I've worked things out with azure support.
It turns out that the object created by the exportTemplate method is storing the template under the key `template`. Seems redundant IMO but I'm guessing there were good reasons to do this.

Amyway once I've tried deploying the value of the template key instead of the entire object things worked like a charm.
