### ISSUE TITLE
Serializing payload for Face.identify() in azure-cognitiveservices-face - Error "mapper.constraints[constraintType].split is not a function"

### ISSUE THREAD

**Issue by amallecourt** [Azure/azure-sdk-for-node#5086]
I encountered an error while using the nodejs sdk for Face in Azure's Cognitive Services.
More precisely, it happen when using the function **face.identify()** :
`identify(faceIds: string[], options?: Object)`

The sdk version I use is : 
`"azure-cognitiveservices-face": "^3.0.0"`

It returns me : 
`Error: Error "mapper.constraints[constraintType].split is not a function" occurred in serializing the payload - {
  "faceIds": [
    "ba51e736-ce9b-4c40-9758-139c0ba047fd",
    "d25951c9-d076-45d4-a61b-b9c1c905cd64"
  ],
  "personGroupId": "test",
  "maxNumOfCandidatesReturned": 1,
  "confidenceThreshold": 0.5
}. `

Whereas it respects the expected format, here is the exemple in the documentation : 
`{
    "personGroupId": "sample_group",
    "faceIds": [
        "c5c24a82-6845-4031-9d5d-978df9175426",
        "65d083d4-9447-47d1-af30-b626144bf0fb"
    ],
    "maxNumOfCandidatesReturned": 1,
    "confidenceThreshold": 0.5
}`

And here is my function call : 
`		client.face.identify(faceIds, { "personGroupId": personGroupId, "maxNumOfCandidatesReturned ": 1, "confidenceThreshold": 0.5})
		.then((result) => {
			console.log(result);
			resolve(result);
		}).catch((err) => {
			console.dir(err, {depth: null, colors: true});
			reject(err);
		});	`

I didn't encountered problem when using other functions as face.detectWithStream(), face.detectWithUrl() or personGroupPerson.list().

**Comment by amallecourt** [comment]
When going deeper into the problem, it seems to find it's origin between the identifyRequest class defined in identifyRequest.js of the azure-cognitiveservices-face package, and, the serialization.js file of the node module **ms-res**. 

The error is : 
`TypeError: mapper.constraints[constraintType].split is not a function` at node_modules/ms-rest/lib/serialization.js:160:60
So what seems to occur is that, during the request, the format of the personGroupId I give has to be verified following the **Pattern** given in the class mapper. The Pattern is **_/^[a-z0-9-_]+$/_**. But in the serialization.js, a split() is tried on the value, and as a regex it's doesn't implement this method (on the contrary to a string).

So it's seems to be necessary to modify the property `IdentifyRequest.mapper().type.modelProperties.personGroupId.constraints.Pattern`

**Comment by amallecourt** [comment]
For exemple, you could change the value : 
`/^[a-z0-9-_]+$/`
with : 
`'^[a-z0-9-_]+$'`

It worked !

**Comment by amallecourt** [comment]
Fixed in v2.5.1 of **ms-rest** : https://www.npmjs.com/package/ms-rest/v/2.5.1
Look at #5087 

Now need to change dependencies value in package.json of ms-rest : 
from `^2.5.0` to `^2.5.1`

**Comment by amarzavery** [comment]
@amallecourt - [npm follows semantic versioning](https://docs.npmjs.com/about-semantic-versioning#using-semantic-versioning-to-specify-update-types-your-package-can-accept). Since this is a patch version update you should be able to install the latest version without any changes to the package.json. Make sure to delete the node_modules folder and package-lock.json before installing everything again in your app.
