### ISSUE TITLE
Kusto SDK expects 202 for long running update cluster 'patch' operations, but gets 201.

### ISSUE THREAD

**Issue by sushilraje** [Azure/azure-sdk-for-node#5095]
The update cluster operation in Kusto SDK fails with foll. error. Unexpected polling status code from long-running operation "201" for method "PATCH". The update is used to scale up the cluster vertically, by updating Azure Sku. The update fails as SDK client expects response code other than 201 for its long-running PATCH operation.

**Comment by amarzavery** [comment]
@sushilraje - Please use the new version of the kusto sdk `@azure/arm-kusto` instead of the current `azure-arm-kusto`.
