### ISSUE TITLE
Needs an example for options.filter with UTC time value

### ISSUE THREAD

**Issue by jeffrey008** [Azure/azure-sdk-for-node#5096]
I am using `azure-arm-consumption` and came across this file for detailed usage: [file](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/consumptionManagement/lib/operations/usageDetails.js)

What format should I put into `properties/usageStart` and `properties/usageEnd`?
I tried this format but it doesn't work.
` filter: "properties/resourceGroup eq 'myGroup' and properties/usageStart gt '2019-07-07T00:00:00Z' ",
`

**Comment by amarzavery** [comment]
@kjeur @panda-wang @shbha  - Can  you please provide an example of how to provide the value for filter query parameter?
