### ISSUE TITLE
Is it available of certificates object in IoTHubClient class??

### ISSUE THREAD

**Issue by sw-tt-janvivakotar** [Azure/azure-sdk-for-node#5098]
Hello,
i have to upload root certificate in azure iot hub..

var client = new IoTHubClient(credentials, 'your-subscription-id'); //for connect iothub
It gives in return of object, it contains like credentials,iotHubResource,operations etc..but its not gives me certificates..

so how can i upload root certificate using Microsoft Azure SDK for Node.js??

**Comment by amarzavery** [comment]
@rkmanda  - Can you please take a look at this issue?
