### ISSUE TITLE
Broken package (azure-arm-datalake-store)

### ISSUE THREAD

**Issue by zbitname** [Azure/azure-sdk-for-node#5108]
https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/datalake.Store/package.json
Main file is `./lib/dataLakeStore.js` from `package.json`.
And this file is not exists (https://github.com/Azure/azure-sdk-for-node/tree/master/lib/services/datalake.Store/lib).
Consequently I see error `Error: Cannot find module 'azure-arm-datalake-store'` while trying to use this package.

**Comment by michaeljqzq** [comment]
@zbitname Could you try the latest version of the package https://www.npmjs.com/package/azure-arm-datalake-store ?
