### ISSUE TITLE
Support Authentication via Pod Identity

### ISSUE THREAD

**Issue by marty2bell** [Azure/azure-sdk-for-node#5111]
Are there any plans to add support for authentication using pod identity / managed Identities to the node SDK?  

It looks like it's supported in the GO SDK and would be consistent with the use of other features like flex volumes to have a common authentication scheme for pods and avoid service principal credentials having to be managed within the clusters?

**Comment by michaeljqzq** [comment]
Hi @marty2bell , node sdk is going to be deprecated. All the new features will go to https://github.com/Azure/azure-sdk-for-js

**Comment by marty2bell** [comment]
OK, thanks for the head up!
