### ISSUE TITLE
Azure Function: Credentials not working in keyVault class

### ISSUE THREAD

**Issue by saikrishnav** [Azure/azure-sdk-for-node#5117]
I am writing an AzureFunction where the function has access to key vault. In the function, I am trying to retrieve the secrets from the keyvault. 

While doing that, I am getting below error:
`Exception: Error: credentials must be one of: ApplicationTokenCredentials, UserTokenCredentials, DeviceTokenCredentials, MSITokenCredentials
Stack: Error: credentials must be one of: ApplicationTokenCredentials, UserTokenCredentials, DeviceTokenCredentials, MSITokenCredentials
    at KeyVaultCredentials.authenticator (D:\home\site\wwwroot\node_modules\azure-keyvault\node_modules\ms-rest-azure\lib\credentials\keyVaultCredentials.js:65:16) `

My Azure Function Trigger Code is this:
` 
import { AzureFunction, Context, HttpRequest } from "@azure/functions";
import * as msrestazure from "ms-rest-azure";
import * as keyvault from "azure-keyvault";

const httpTrigger: AzureFunction = async function (context: Context, req: HttpRequest): Promise<void> {
    context.log('HTTP trigger function processed a request.');
    const name = (req.query.name || (req.body && req.body.name));
    if (name) {
        const keyVaultName = req.query.name;
        const secretName = req.query.key;
        const vaultUri =  https://${keyVaultName}.vault.azure.net/;

        let keyVaultClient: any;
        if (process.env.APPSETTING_WEBSITE_SITE_NAME){
            let credentials = await msrestazure.loginWithAppServiceMSI();
            keyVaultClient = new keyvault.KeyVaultClient(credentials);
          } else {
            let credentials = await msrestazure.loginWithServicePrincipalSecret(process.env["CLIENT_ID"], 
                process.env["CLIENT_SECRET"], process.env["TENANT_ID"]);
            keyVaultClient = new keyvault.KeyVaultClient(credentials);
          }
        const secretBundle = await keyVaultClient.getSecret(vaultUri, secretName, "");
        const secretValue = secretBundle.value;
        context.log(secretValue);

        context.res = {
            // status: 200, /* Defaults to 200 */
            body: "Hello " + secretValue
        };
    }
    else {
        context.res = {
            status: 400,
            body: "Please pass a name on the query string or in the request body"
        };
    }
};

export default httpTrigger;`

My TSConfig is set to "ES6" 
Here's package.json:
`{
  "name": "",
  "version": "1.0.0",
  "description": "",
  "dependencies": {
    "azure-keyvault": "^3.0.4",
    "ms-rest-azure": "^3.0.0"
  },
  "devDependencies": {
    "@azure/functions": "^1.0.2-beta2",
    "typescript": "^3.3.3"
  }
}
`

**Comment by michaeljqzq** [comment]
Actually for the keyvault service, the node SDK is going to be deprecated and won't have new feature and releases. Instead, the new versions are released here: https://www.npmjs.com/package/@azure/keyvault-secrets https://www.npmjs.com/package/@azure/keyvault-keys . You can have a try with the new SDK. And feel free to give feedback if that won't work or have further issues.
