### ISSUE TITLE
I have a user object id how I can able to get the particular role assign to the user.

### ISSUE THREAD

**Issue by durgadp** [Azure/azure-sdk-for-node#5120]
I have a user object id how I can able to get the particular role assign to the user. I have just your library function in node modules there is not function created to access this data but you appRoles model can you please let me know how I can able to access the roles of the user using approles models.  I just google for this issue this API will provide us role for that user
GET    https://graph.microsoft.com/beta/users/{id | userPrincipalName}/appRoleAssignments
but the problem is how I can use it in your functions

**Comment by michaeljqzq** [comment]
Please provide following information
* the package name you use
* the version
* the sample code

**Comment by durgadp** [comment]
Please provide the following information

Package Name: azure-graph
Version  "azure-graph": "^4.3.0",
`
```javascript
 msRestAzure.loginWithUsernamePassword(data.email, data.password, { tokenAudience: 'graph', domain: tenantId }, async (err, credentials, subscriptions) => {
                if (err){
                    //console.log(err);
                    send_data = { status : false, message : "Invalid username or password or please reset your passport from azure account."};
                    res.status(500).json(send_data);   
                }else{
                    client = new graphRbacManagementClient(credentials, tenantId);
                    value = await client.signedInUser.get();
                    // I need to find current sign in user role here       
                                      
                }
````

**Comment by michaeljqzq** [comment]
For the SDK, you can get following properties in user object:

id | The unique identifier for the user.
businessPhones | The user's phone numbers.
displayName | The name displayed in the address book for the user.
givenName | The first name of the user.
jobTitle | The user's job title.
mail | The user's email address.
mobilePhone | The user's cellphone number.
officeLocation | The user's physical office location.
preferredLanguage | The user's language of preference.
surname | The last name of the user.
userPrincipalName | The user's principal name.

However, the property `appRoleAssignments` is not yet included in the SDK.
[Ref doc](https://docs.microsoft.com/en-us/graph/api/resources/users?view=graph-rest-1.0)

**Comment by durgadp** [comment]
For appRoleAssignments is there any pipeline set by you. So we can able to access the role of particular user or meanwhile time if any another way to get this guide me and send the link of documentation so I will able to implement it for now.

**Comment by michaeljqzq** [comment]
Is there an API to fetch the RoleAssignment ?

**Comment by durgadp** [comment]
Please check https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-add-app-roles-in-azure-ad-apps

**Comment by ramya-rao-a** [comment]
Apologies for the late response here @durgadp 

Based on the what you have shared in the issue description, it looks like you are targeting `graph.microsoft.com` endpoint which is for the newer [Microsoft Graph API](https://developer.microsoft.com/graph)

The package `azure-graph` you are using is for the older [Azure AD Graph API](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-graph-api).

Please use the [@microsoft/microsoft-graph-client](https://www.npmjs.com/package/@microsoft/microsoft-graph-client) package instead and log any issues you find with it in https://github.com/microsoftgraph/msgraph-sdk-javascript.

**Comment by ramya-rao-a** [comment]
cc @willmtemple to add additional insights if any
