### ISSUE TITLE
Job info parameter in user model

### ISSUE THREAD

**Issue by durgadp** [Azure/azure-sdk-for-node#5122]
I need a job title and the department under job information. I checked your model file where i can see these fields in it.

**Comment by ruowan** [comment]
Please provide the following information

+ the package name you use
+ the version
+ the sample code

**Comment by durgadp** [comment]
Please provide the following information

Package Name: azure-graph
Version "azure-graph": "^4.3.0",
`

 msRestAzure.loginWithUsernamePassword(data.email, data.password, { tokenAudience: 'graph', domain: tenantId }, async (err, credentials, subscriptions) => {
                if (err){
                    //console.log(err);
                    send_data = { status : false, message : "Invalid username or password or please reset your passport from azure account."};
                    res.status(500).json(send_data);   
                }else{
                    client = new graphRbacManagementClient(credentials, tenantId);
                    value = await client.signedInUser.get();
                    // I need to find current sign in user role here       
                                      
                }

**Comment by ruowan** [comment]
Hi, @durgadp The node SDK library is going to be deprecated. You can try to use this new one https://www.npmjs.com/package/@azure/graph which directly returns HTTP response. It may work well for you.

**Comment by ramya-rao-a** [comment]
@durgadp We will be closing this issue as we havent heard back from you in a while.
If you have issues using the newer https://www.npmjs.com/package/@azure/graph package, then please log an issue at https://github.com/Azure/azure-sdk-for-js/
