### ISSUE TITLE
Computer Vision SDK - Person Group Create fail

### ISSUE THREAD

**Issue by wiazur** [Azure/azure-sdk-for-node#5126]
I was debugging code to get a person group, but when I try to create one, it crashed on the create() function. With debugging I found that the endpoint sent in the request body was not for a person group but for a person group person. Not sure how that is possible, but somehow or another, it was mixing up the endpoints.

```
Error:
(node:13976) UnhandledPromiseRejectionWarning: Error: Request body is invalid.
    at new RestError (C:\Users\v-wiazur\Desktop\Face\node_modules\@azure\ms-rest-js\dist\msRest.node.js:2400:28)
    at C:\Users\v-wiazur\Desktop\Face\node_modules\@azure\ms-rest-js\dist\msRest.node.js:3544:37
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I debugged further and saw in the `node_modules\@azure\cognitiveservices-face\src\operations\personGroupOperations.ts` file, the area of error was with the `createOperationSpec` constant. Hovering over the values, the httpMethod is `
POST https://westus.api.cognitive.microsoft.com/face/v1.0/persongroups/{personGroupId}/persons`, but in the API console online, The REST version works fine and has a different endpoint:
`
PUT https://westus.api.cognitive.microsoft.com/face/v1.0/persongroups/{personGroupId} HTTP/1.1`

![person group url](https://user-images.githubusercontent.com/38537084/66694232-26021200-ec66-11e9-8da6-35642447f5b0.PNG)

Looking at the options in the side bar, I see there are several different `createOperationSpec` constants. The first one (no number) is for the person group persons call, while the 2nd one (with a $1) is for person group call (the one I should have but don't). So perhaps these are getting mixed up?

![create specs](https://user-images.githubusercontent.com/38537084/66694369-75950d80-ec67-11e9-9425-1d89250e6b4a.png)

In any case, to reproduce the problem, run this method, it crashes at the response line:

```
    // Create empty Person Group. Returns a Promise<RestResponse>. 
    await client.personGroup.create(PERSON_GROUP_ID)
        .then((response)=> {
            console.log(response)
        }).catch((err) => {
            throw err
        })
```

**Comment by qiaozha** [comment]
@wiazur  Could please share with me which package and version you are using? Thanks

**Comment by wiazur** [comment]
Sorry @qiaozha, I just got your response. I believe the issue was resolved, not entirely sure how but the sample now works. Thanks.
