### ISSUE TITLE
Websocket from containerExecResponse accepts only 50 chars

### ISSUE THREAD

**Issue by elweilando** [Azure/azure-sdk-for-node#5127]
We trying to build an azure container instance automation. We can create and start a new container with http://azure.github.io/azure-sdk-for-node/azure-arm-containerinstance/latest/ContainerGroups.html#createOrUpdateWithHttpOperationResponse and we can start powershell with executeCommandWithHttpOperationResponse from https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/containerinstanceManagement/lib/operations/containerOperations.js

After that we receive a websocket uri and a password.
After authorization we can start some commands in powershell thru websocket, but there seems a limitation of 50 chars for sending commands thru the websocket.

Or are there specific escape-signs for sending commands thru websocket?

**Comment by qiaozha** [comment]
@elweilando hi, do you mean that the powershell cut off the command you typed? or the interface has a limitation of the parameters that you passed? Also, what the version of powershell as well as the node package?

**Comment by elweilando** [comment]
@qiaozha I can send thru the websocket a command to the powershell within the docker container which I started with executeCommandWithHttpOperationResponse.
If i send a command thru websocket, I can send only commands up to 50 chars. 
I think the websocket interface which is provided from azure has this limitation.
You can reproduce this also in the ACI console interface in the azure portal. Try to start a new Windows ACI and connect to powershell.
Then copy a command with more than 50 chars to this powershell web-gui. Only the first 50 chars appear after the copy in the gui.

**Comment by qiaozha** [comment]
@elweilando  Hi, sorry for the delay reply. the package azure-arm-containerinstance is being deprecated. you may try to use the package  @azure/arm-containerinstance  to see if the problem still exists.

**Comment by elweilando** [comment]
@qiaozha I changed the package but I receive now this issue
```
    TypeError: this.client.npsendLRORequest is not a function
    at ContainerGroups.beginCreateOrUpdate (/Users/el/develop/gitlab-runner-azure-function/node_modules/@azure/arm-containerinstance/dist/arm-containerinstance.js:1750:32)
    at ContainerGroups.createOrUpdate (/Users/el/develop/gitlab-runner-azure-function/node_modules/@azure/arm-containerinstance/dist/arm-containerinstance.js:1690:25)
    at /Users/el/develop/gitlab-runner-azure-function/index.js:275:28
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by qiaozha** [comment]
@elweilando I install the package and found at line 1750 it uses this.client.sendLRORequest. my version is 5.4.0. Can you double check the package you installed and share with me your version if problem still exists?

**Comment by elweilando** [comment]
Sorry. There was a typo. The issue is

```
TypeError: this.client.sendLRORequest is not a function
    at ContainerGroups.beginCreateOrUpdate (/Users/el/develop/gitlab-runner-azure-function/node_modules/@azure/arm-containerinstance/dist/arm-containerinstance.js:1750:32)
    at ContainerGroups.createOrUpdate (/Users/el/develop/gitlab-runner-azure-function/node_modules/@azure/arm-containerinstance/dist/arm-containerinstance.js:1690:25)
    at /Users/el/develop/gitlab-runner-azure-function/index.js:275:28

```

I can't find in this package a function named sendLRORequest.

**Comment by qiaozha** [comment]
Can you show me you code of how you use it? I am using it like this client.containerGroups.createOrUpdate(resourceGroupName, containarGroupName, containerGroup) it works fine.

**Comment by elweilando** [comment]
```

const msRestAzure = require('ms-rest-azure');
const armACI = require('@azure/arm-containerinstance');
msRestAzure.loginWithServicePrincipalSecret(clientId, secret, domain).then((creds) => {
    let client = armACI.ContainerInstanceManagementClient(creds, subscriptionId);
    let containerprops = {
        "command": [],
        "environmentVariables": [
            {
                "name": "ACCEPT_EULA",
                "value": "Y"
            },
            {
                "name": "username",
                "value": "admin"
            },
            {
                "name": "password",
                "value": "admin"
            },
        ],
        "image": "mcr.microsoft.com/businesscentral/onprem:de",
        "ports": [
            {
                "protocol": "TCP",
                "port": 443
            },
            {
                "protocol": "TCP",
                "port": 8080
            },
            {
                "protocol": "TCP",
                "port": 7049
            },
            {
                "protocol": "TCP",
                "port": 7048
            },
            {
                "protocol": "TCP",
                "port": 80
            }
        ],
        "resources": {
            "requests": {
                "cpu": 2,
                "memoryInGB": 14
            }
        },
        "name": containerName
    };
    let props = {
        "location": "westeurope",
        "containers": [
            containerprops
        ],
        "osType": "Windows",
        "dnsNameLabel": containerDNS,
        "volumes": [],
        "ipAddress": {
            "type": "Public",
            "ports": [
                {
                    "protocol": "TCP",
                    "port": 443
                },
                {
                    "protocol": "TCP",
                    "port": 8080
                },
                {
                    "protocol": "TCP",
                    "port": 7049
                },
                {
                    "protocol": "TCP",
                    "port": 7048
                },
                {
                    "protocol": "TCP",
                    "port": 80
                }
            ]

        }
    };
    client.containerGroups.createOrUpdate(resourceGroupName, containerGroupName, props).then((result) => {
```

**Comment by qiaozha** [comment]
I create the client like this way in typescript.
 `import { ContainerInstanceManagementClient } from '@azure/arm-containerinstance
  let client = new ContainerInstanceManagementClient(creds, subscriptionId);
` 
I compared the js code generated by tsc, 
the difference is the way you create a client. you may use `let client = new armACI.ContainerInstanceManagementClient(creds, subscriptionId); `  to solve your problem. 
Hope that helps

**Comment by elweilando** [comment]
Thank you. Can you please provide me an example of documentation for a login with Service Principal and secret?
Actually I don't know to login with client Id, secret and domain.

**Comment by qiaozha** [comment]
you may refer to this document  https://github.com/Azure/azure-sdk-for-js/blob/master/documentation/Node.jsAuth.md#service-principal-authentication

**Comment by elweilando** [comment]
I used this example before (please see line 3 in my code example above). I updated now the node-package ' ms-rest-azure' to the latest version. But now I receive this error. This error raises in 

`msRestAzure.loginWithServicePrincipalSecret(clientId, secret, domain).then((creds) => {`

```
    at /Users/el/develop/gitlab-runner-azure-function/node_modules/ms-rest-azure/lib/credentials/applicationTokenCredentials.js:168:14
    at /Users/el/develop/gitlab-runner-azure-function/node_modules/ms-rest-azure/lib/credentials/applicationTokenCredentials.js:152:16
    at /Users/el/develop/gitlab-runner-azure-function/node_modules/ms-rest-azure/lib/credentials/applicationTokenCredentials.js:52:16
    at /Users/el/develop/gitlab-runner-azure-function/node_modules/adal-node/lib/token-request.js:162:7
    at /Users/el/develop/gitlab-runner-azure-function/node_modules/adal-node/lib/cache-driver.js:366:7
    at CacheDriver._refreshEntryIfNecessary (/Users/el/develop/gitlab-runner-azure-function/node_modules/adal-node/lib/cache-driver.js:340:5)
    at /Users/el/develop/gitlab-runner-azure-function/node_modules/adal-node/lib/cache-driver.js:365:10
    at /Users/el/develop/gitlab-runner-azure-function/node_modules/adal-node/lib/cache-driver.js:231:5
    at /Users/el/develop/gitlab-runner-azure-function/node_modules/adal-node/lib/cache-driver.js:163:5
    at MemoryCache.find (/Users/el/develop/gitlab-runner-azure-function/node_modules/adal-node/lib/memory-cache.js:89:3)
```

**Comment by qiaozha** [comment]
Seems the examples are wrong, You can try this way
`const { loginWithServicePrincipalSecret } = require("@azure/ms-rest-nodeauth"); 
 loginWithServicePrincipalSecret(clientId, secret, domain).then((creds) => {
 });
`

**Comment by elweilando** [comment]
Thank you very much. This works now with the new package.
But it remains sadly the same limitation of 50 chars.

**Comment by qiaozha** [comment]
@elweilando which operation are you trying with JS sdk ? because I can't find executeCommandWithHttpOperationResponse in JS sdk now. Also, Could you please open another issue in this https://github.com/Azure/azure-sdk-for-js repo and provide what package versions you are currently using and what kind of resources is related. So that it can route to related teams when necessary. 
But I think this is something wrong with PowerShell web gui. because I don't see where the command has been cut-off, so it must have been cut-off before the SDK handle it.
cc @RodgeFu

**Comment by elweilando** [comment]
I use this package: @azure/arm-containerinstance
maybe there was a missunderstanding. I don't use executeCommandWithHttpOperationResponse anymore. I use know the corresponding function from the @azure/arm-containerinstance package.

```
const armACI = require('@azure/arm-containerinstance');
let client = new armACI.ContainerInstanceManagementClient(creds, subscriptionId);
client.containerGroups.createOrUpdate(resourceGroupName, containerGroupName, props).then((result) => {
...snipp...snapp..
    let execCommandProps = {
        command: execCommand,
        terminalSize : {
            rows: 400,
            cols: 400
        }
    };

client.container.executeCommand(resourceGroupName, containerGroupName,containerName,execCommandProps).then((result) => {
...snipp...snapp..
```
then I connect to the websocket. 
I think also, that the issue comes from the PowerShell web gui. I'dont know if this has a relation to this issue, but If you are in azure portal and you connect thru the portal to the container, you can also paste commands just with a maxima length of 50 chars.

**Comment by qiaozha** [comment]
Hi, Did you start PowerShell web-gui from https://docs.microsoft.com/en-us/azure/cloud-shell/quickstart-powershell?view=azps-3.1.0#code-try-0 here? 
Also, I am quite confused how do you run js code in powershell? What exactly the `a websocket uri and a password` looks like ? Is it the container resource?

**Comment by elweilando** [comment]
I'dont run js code in powershell. In my example I send 

```
    let execCommandProps = {
        command: 'powershell',
        terminalSize : {
            rows: 400,
            cols: 400
        }
    };
```
to the container instance and I receive a ContainerExecResponse. 
https://github.com/Azure/azure-sdk-for-js/blob/3402edc5e3d78f6590c81ed3f821ecc7fcc6a868/sdk/containerinstance/arm-containerinstance/src/models/mappers.ts#L1370

Then I can connect to this websocket and I can execute powershell commands thru this websocket on the container instance. But I can send only commands up to 50 chars to the container instance.

I don't know if it's the same web-gui. You can start a new container instance from here: https://portal.azure.com/#blade/HubsExtension/BrowseResourceBlade/resourceType/Microsoft.ContainerInstance%2FcontainerGroups. If the container instance is running you can connect to this container instance with a powershell. Maybe it's also the web-gui.

**Comment by qiaozha** [comment]
Hi, Now I've created the container and get the webSocketUri and password, but how to connect to the container with web-gui by using webSocketUri and password?

**Comment by elweilando** [comment]
I connect with a websocket-client

```
    let ws = new WebSocketClient()
    ws.on('connectFailed', function(error) {
        console.log('Connect Error: ' + error.toString());
    });
    ws.on('connect', function(connection) {
        console.log('WebSocket Client Connected');
        connection.send(result.password);
        connection.on('error', function(error) {
            console.log("Connection Error: " + error.toString());
        });
        connection.on('close', function() {
            console.log('echo-protocol Connection Closed');
        });
        connection.on('message', function(message) {
            if(message.utf8Data === 'PS C:\\> ' ){
                    connection.send('powershell commands...');
            }
            console.log(message);
        });
    });
    ws.connect(result.webSocketUri);
```

**Comment by qiaozha** [comment]
Did you mean you are using this websocket-client package? but the WebSocketUri that executeCommand returned starts with "wss://" and seems this package doesn't support wss? You can refer to line 473  to 489 of lib/websocket.js in this package. Also, this package doesn't have WebSocketClient? Shouldn't the last line of ws.connect in your code be put at the top of the other operations?
I tried other npm packages like "ws", but it has different operations about WebSocket. but I don't know how to connect the socket with a password.

**Comment by elweilando** [comment]
I use this package: https://www.npmjs.com/package/websocket
`var WebSocketClient = require('websocket').client;`

I define first the events that I want to listen to. After that I connect to the wss://. On connect I send first the password and then the commands.

My procedure based on this blog entry https://blog.mastykarz.nl/office-365-cloud-shell/

**Comment by qiaozha** [comment]
It seems that the messages I received from the server are cut into smaller pieces
 
![image](https://user-images.githubusercontent.com/55688292/70383344-3d7c2380-19a7-11ea-8aba-40fc1d44c1e3.png)

**Comment by elweilando** [comment]
Yes. That's what I mean.

**Comment by qiaozha** [comment]
I've submitted a issue in the JS repo and add tags of related service to follow up.

**Comment by elweilando** [comment]
Thank you very much!

**Comment by RodgeFu** [comment]
Close this one as issue 6487 is created in JS SDK repo to follow up. Thanks.
