### ISSUE TITLE
Types for `KeyVaultCredentials` class can be improved

### ISSUE THREAD

**Issue by ernieturner** [Azure/azure-sdk-for-node#5128]
When trying to consume the `KeyVaultCredentials` class from within the `azure-keyvault` dependency in a TypeScript project, I noticed that the types for this classes constructor are pretty weak and could be greatly improved. The current types are

```
constructor(authenticator: (challenge: object, callback: any) => any, credentials: object);
```

From using the code, my `challenge` argument is of the shape `{authorization: string; resource: string}`. I don't know if there are other shapes this object can take, but using just `object` as the type makes it very difficult to type properly since it has no default shape of its own.

Secondly, from looking at the code it appears that either the `authenticator` or the `credentials` are required, but not both. The types don't reflect this as you have to provide an argument for both which isn't how the code is supposed to work. This could be improved by either having multiple constructors with different arguments or just making each of them optional. 

Here's an example of what I think the types could look like

```
constructor(authenticator?: (challenge: {authorization: string; resource: string}, callback: any) => any, credentials?: object);
```

Again, I'm not sure if this type covers all the various use cases, but it's certainly a move in the right direction. Ideally it'd be nice to get rid of all the `any`s that this type still uses, but incremental steps would be nice.

**Comment by qiaozha** [comment]
@ernieturner  Thanks for your advice. In fact, we are now moving to azure-sdk-for-js repo. this one is currently being deprecated and you may refer to the folder sdk/keyvault of azure-sdk-for-js repo.  Also, I take a look at the Authenticator type. it's still taking the object challenge as its parameter. but I have a second thought probably they consider for compatibility. if a previous object type is restricted to a string type, it might cause a previous version not working. What do you think?

**Comment by ernieturner** [comment]
If there's a need to support previous types that are a string, that can also be done by just doing something like `challenge: {authorization: string; resource: string} | string` to signify that it can support two different types. However, since the current types specify that it has to be an `object` I think you've already broken the old version compatibility of it being a string so it might not matter all that much to let it support the string type too.

**Comment by qiaozha** [comment]
Thanks for your advice. but I think that's actually a new feature requirement. we probably need to get relavant team involved in this issue.
cc @RodgeFu  for awareness.

**Comment by ramya-rao-a** [comment]
The `azure-keyvault` package is deprecated in favor of individual packages for keys, secrets and certificates. Please use the newer @azure/keyvault-keys, @azure/keyvault-secrets or @azure/keyvault-certificates and log an issues you see at https://github.com/azure/azure-sdk-for-js

The new packages were written following the [new guidelines for Azure SDKs](https://azure.github.io/azure-sdk/typescript_introduction.html)

You can follow the work done as part of this effort at https://azure.github.io/azure-sdk/

**Comment by ramya-rao-a** [comment]
cc @sadasant in case any follow up is needed here
