### ISSUE TITLE
How to use Azure Key Vault from npmjs.com doesn't work

### ISSUE THREAD

**Issue by erick-thompson** [Azure/azure-sdk-for-node#5130]
I am attempting to use Azure Key Vault from typescript/node. The npmjs.com page (https://www.npmjs.com/package/azure-keyvault) has:

```
  const credentials = await msRestAzure.interactiveLogin();
  const client = new KeyVault.KeyVaultClient(credentials);
```
This code shows the browser devicelogin code. When I login with the device code and attempt to perform any actions with the client, the following error is thrown.

message:"credentials must be one of: ApplicationTokenCredentials, UserTokenCredentials, DeviceTokenCredentials, MSITokenCredentials"

**Comment by erick-thompson** [comment]
I was able to get it to work by uninstalling the ms-rest-azure npm package. The repetition of these credentials classes is very confusing.

**Comment by qiaozha** [comment]
@erick-thompson  you may try @azure/arm-keyvault,  it's from https://github.com/Azure/azure-sdk-for-js.  it use @azure/ms-rest-nodeauth to do the login. The node SDK is  being deprecated.

**Comment by avoidwork** [comment]
@qiaozha what's it being replaced with? this isn't communicated on the README nor in npm via a deprecation warning; i ran into this error while developing a new feature based on this SDK...

**Comment by qiaozha** [comment]
@avoidwork  I think it depends on how you use it. if you use it to manage your key vault resource you can replace it with `@azure/arm-keyvault` the detail is in here https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/keyvault. 
But just for this error. I think you may try to downgrade the credential related package version. Can you provide me with what packages and which version you're using?

**Comment by ramya-rao-a** [comment]
The `azure-keyvault` package is deprecated in favor of individual packages for keys, secrets and certificates. Please use the newer @azure/keyvault-keys, @azure/keyvault-secrets or @azure/keyvault-certificates and log an issues you see at https://github.com/azure/azure-sdk-for-js

The new packages were written following the [new guidelines for Azure SDKs](https://azure.github.io/azure-sdk/typescript_introduction.html)

You can follow the work done as part of this effort at https://azure.github.io/azure-sdk/

cc @sadasant for any follow up needed here.
