### ISSUE TITLE
Issue in Event Grid Subscription creation (endpointUrl property missing in the destination model)

### ISSUE THREAD

**Issue by kamesh95** [Azure/azure-sdk-for-node#5134]
According to the REST API docs for creating or updating event subscriptions, the request body should have endpointUrl in the destination object. [Link to Docs](https://docs.microsoft.com/en-us/rest/api/eventgrid/eventsubscriptions/createorupdate#eventsubscriptions_createorupdateforresource)
When I try to create a event subscription without that, it gives me an error that properties cannot be null or empty in the destination object. I checked this model file **https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/eventgridManagement/lib/models/eventSubscriptionDestination.js** and I can see that there's no endpointUrl property specified here as well so it will strip out that propertry even though I give it in my main eventSubscriptionInfo object. Can you please confirm if this is a bug?

**Comment by qiaozha** [comment]
@kamesh95  Thank you for the question. as you can see from eventSubscriptionDestination definition there is a polymorphic mechanism. And as you can see from the document, the endpointType is WebHook. which means it actually will use an object of class WebHookEventSubscriptionDestination as the parameter. Here the endpointUrl is defined in WebHookEventSubscriptionDestination class which extends EventSubscriptionDestination 
 https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/eventgridManagement/lib/models/webHookEventSubscriptionDestination.js. Hope that helps.

**Comment by kamesh95** [comment]
@qiaozha Thanks for the quick reply. That does make sense, I modified my event Subscription Info object accordingly and it works now. Thank you very much :)

**Comment by qiaozha** [comment]
Glad it solves your problem. Also we are deprecated this repo with https://github.com/Azure/azure-sdk-for-js  you may try @azure/arm-eventgrid as well.
