### ISSUE TITLE
Event Grid - No failure case when publishing events

### ISSUE THREAD

**Issue by mustafababil** [Azure/azure-sdk-for-node#5137]
Hi,

I am using nodejs library for Event Grid (azure-eventgrid).

If I provide wrong values for Topic Endpoint or Access Key parts, publishing events doesn't fail as expected. It doesn't output anything for neither `then` or `catch` part.

I am using this in a **Azure Functions** component.

```javascript
let topicCreds = new msRestAzure.TopicCredentials(EVENT_GRID_ACCESS_KEY);
let egClient = new eventGrid(topicCreds);
let topicUrl = url.parse(EVENT_GRID_TOPIC_ENDPOINT, true);
let topicHostName = topicUrl.host;

egClient.publishEvents(topicHostName, events).then((result) => {
    context.log.info('Published all events to Event Grid!')
}).catch((err) => {
    context.log.error('Event Grid publishing events error: ' + err);
});
```

How can I fetch failure cases?

**Comment by qiaozha** [comment]
@ramya-rao-a  Is it an issue for data-plane?

**Comment by ramya-rao-a** [comment]
Yes, thanks @qiaozha 

@chradek Can you take a look at this?

**Comment by chradek** [comment]
@mustafababil 
Sorry for the delayed response.
Can you share what the timeout for your Azure Function is? I ran a similar sample locally and noticed that with invalid parameters I get an ECONNREFUSED error when attempting to connect to the service. The library will attempt to retry up to 3 times with exponential backoff. I noticed the 1st retry took about 30 seconds, then 2nd took about 90 seconds, and the 3rd even longer. It's possible that the delay between retries is longer than your functions max time. I do notice that the catch handler is eventually called when I run it locally.

One thing you can try to test this is to turn off retries. You can do this when instantiating your event grid client:
```javascript
const client = new EventGridClient(topicCreds, {
  noRetryPolicy: true
});
```

Let us know if this helps!

**Comment by mustafababil** [comment]
@chradek Thank you for your response.

Function Timeout is set to 5-minute. I turned off the retries as defined, and tested the following sample snippet on both local and cloud. Unfortunately, it didn't work. It looks like execution of functions stops immediately.

```js
const uuid = require('uuid').v4;
const msRestAzure = require('ms-rest-azure');
const eventGrid = require('azure-eventgrid');
const url = require('url');

const EVENT_GRID_TOPIC_ENDPOINT = 'https://<TEST>.westeurope-1.eventgrid.azure.net/api/events';
const EVENT_GRID_ACCESS_KEY = '<KEY>';
const EVENT_GRID_PUBLISH_EVENT_TYPE = 'location.process';

module.exports = async function (context, timer) {
  if (timer.IsPastDue) {
    context.log.info('This function is running late!');
  }

  var events = [];

  let event = {
    id: uuid(),
    subject: 'LocationProcess',
    dataVersion: '1.0',
    eventType: EVENT_GRID_PUBLISH_EVENT_TYPE,
    eventTime: new Date().toJSON(),
    data: {
      correlationId: uuid(),
      locationId: 'myLoc',
      targetDate: 'tomorrow',
    },
  };

  events.push(event);

  context.log.info('Ready to send events');

  // Send events to EventGrid
  if (events.length > 0) {
    let topicCreds = new msRestAzure.TopicCredentials(EVENT_GRID_ACCESS_KEY);
    let egClient = new eventGrid(topicCreds, { noRetryPolicy: true });
    let topicUrl = url.parse(EVENT_GRID_TOPIC_ENDPOINT, true);
    let topicHostName = topicUrl.host;

    egClient.publishEvents(topicHostName, events).then((result) => {
      let message = `Published all events to Event Grid with Event Type '${EVENT_GRID_PUBLISH_EVENT_TYPE}'.`;
      context.log.info(message);
    }).catch((error) => {
      let message = `Error in publishing events to Event Grid: ${error}`;
      context.done(message);
    });
  } else {
    context.log.info('No event to publish!');
  }
  context.log.info('Events should be sent');
  context.done();
};
```

Console output from cloud instance:
```bash
2020-02-12T15:52:49.101 [Information] Executing 'Functions.<FUNC_NAME>' (Reason='This function was programmatically called via the host APIs.', Id=bcb96684-7847-4f90-a09c-2e6c5dd5d8ce)
2020-02-12T15:53:38.740 [Information] Ready to send events
2020-02-12T15:53:38.747 [Information] Events should be sent
2020-02-12T15:53:38.749 [Information] Executed 'Functions.<FUNC_NAME>' (Succeeded, Id=bcb96684-7847-4f90-a09c-2e6c5dd5d8ce)
```

**Comment by chradek** [comment]
@mustafababil 
I believe the issue is because you're calling `context.done()` at the bottom of your function outside of your `publishEvents` call. Since `publishEvents` is non-blocking, execution will continue to the end of your function before your `then` or `catch` handlers are invoked.

Since you're already using an `async` function, you can use `await` with publishEvents instead to get the affect you want:

```typescript
try {
  const result  = await egClient.publishEvents(topicHostName, events);
  let message = `Published all events to Event Grid with Event Type '${EVENT_GRID_PUBLISH_EVENT_TYPE}'.`;
  context.log.info(message);
} catch (err) {
  let message = `Error in publishing events to Event Grid: ${error}`;
  context.done(message);
}
```

**Comment by mustafababil** [comment]
Thank you @chradek. Now I got what I expect. Thanks for your time.
@ramya-rao-a I am closing the issue as @chradek helped me a lot.
