### ISSUE TITLE
Azure Consumption Usage List

### ISSUE THREAD

**Issue by sauravmndl** [Azure/azure-sdk-for-node#5139]
Hi,
I was using this sdk to use [consumption usage list api](https://docs.microsoft.com/en-gb/rest/api/consumption/usagedetails/list). Can you please help me in understanding [filter](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/consumptionManagement/lib/operations/usageDetails.js#L28) parma values.

I have a sample code as follows

`
const msRestAzure = require("ms-rest-azure");
const {ConsumptionManagementClient} = require("azure-arm-consumption");

async function getUsage(){

  try{
    const creds = await msRestAzure.loginWithServicePrincipalSecret(clientId, clientSecret, tenantId);
    const client = new ConsumptionManagementClient(creds, subscriptionId);
    console.log('Time:',new Date(),"API Veersion: ",client.apiVersion);
    const result = await client.usageDetails.list({expand: 'meterDetails', filter:'tags eq \'key:val\' and usageStart eq \'2020-01-01T00:00:00.000Z\''});
    return result;
  }catch(err) {
    console.log('An error occurred:');
    console.dir(err, {depth: null, colors: true});
  }
}
`
The tags in filter works but  'usageStart' not working. Can you please provide sample code for the same?
azure-arm-consumption:6.3.0
ms-rest-azure:3.0.0

**Comment by qiaozha** [comment]
@sauravmndl  Could you try `@azure/arm-consumption` this package from https://github.com/Azure/azure-sdk-for-js/ this repo to see the problem still exists? this azure-sdk-for-node repo is planing to be deprecated.

**Comment by sauravmndl** [comment]
Hi @qiaozha ,

Thank you for your reply. Using the other library, result is same. 

1. I want to see the example how to filter using **usageStart**   and **usageEnd**. 
2. Also I want data hourly basis. 

Below filter doesn't work.

` 'usageStart eq \'2020-02-02T00:00:00.000Z\' and usageEnd eq \'2020-02-03T00:00:00.000Z\'`

Could you please mention the document where the sample is given. I couldn't find one.

Best Regards,
Saurav

**Comment by qiaozha** [comment]
How about try this way `"filter": "usageDate ge '2020-02-02' AND usageDate le '2020-02-03'"`. Sorry, The document is a little missing right now and we are working on this.  but I think for your problem the filter column should be usageDate? 
You may also find the original example here https://github.com/Azure/azure-rest-api-specs/tree/master/specification/consumption/resource-manager/Microsoft.Consumption/stable/2019-10-01/examples

**Comment by sauravmndl** [comment]
Thanks for  replying @qiaozha . It's working. I wanted usage details hourly basis. But getting 'daily' basis.

Req:

`client.usageDetails.list({expand: 'meterDetails', filter:'tags eq \'xxx:yyy\'  AND properties/usageStart ge \'2020-02-08T00:00:00.000Z\' AND properties/usageEnd le \'2020-02-08T01:00:00.000Z\''`

Response:

{
...
usageStart: 2020-02-08T00:00:00.000Z,
usageEnd: 2020-02-08T23:59:59.000Z,
....

}

**Comment by qiaozha** [comment]
Thanks for the report. I've submitted this issue https://github.com/Azure/azure-sdk-for-js/issues/7303 to track this and get service team involved.

**Comment by ramya-rao-a** [comment]
@qiaozha Based on https://github.com/Azure/azure-sdk-for-js/issues/7303#issuecomment-585904515, this feature is not supported by the service currently and is in their backlog. Once they do support it, they will need to update their apis and the packages will have to be re-generated.

Given that new features will only be added to the newer `@azure/arm-consumption`, can we close this issue and keep https://github.com/Azure/azure-sdk-for-js/issues/7303 open?

**Comment by faisquinha** [comment]
Hello people. Is it possible to return a json? Now return an object.
Thanks

#Consumption management client provides access to consumption resources for Azure Enterprise Subscriptions
consumption_client = ConsumptionManagementClient(credentials, subscription_id, base_url=None)

results = consumption_client.usage_details.list(scope = '/subscriptions/' + subscription_id +'/', expand='properties/meterDetails, properties/additionalInfo', filter="""properties/usageStart ge '2020-05-14' and properties/usageEnd le '2020-05-14'""")

for result in results:
    print(result)

**Comment by qiaozha** [comment]
Hi, Did you mean the original http response?  which should be able to found result._response.bodyAsText;

**Comment by qiaozha** [comment]
> @qiaozha Based on [Azure/azure-sdk-for-js#7303 (comment)](https://github.com/Azure/azure-sdk-for-js/issues/7303#issuecomment-585904515), this feature is not supported by the service currently and is in their backlog. Once they do support it, they will need to update their apis and the packages will have to be re-generated.
> 
> Given that new features will only be added to the newer `@azure/arm-consumption`, can we close this issue and keep [Azure/azure-sdk-for-js#7303](https://github.com/Azure/azure-sdk-for-js/issues/7303) open?

Sure, if there's no more following question in this issue in one week, I will close it.

**Comment by qiaozha** [comment]
close this issue as no response in one week and for furthur question please go to https://github.com/Azure/azure-sdk-for-js/issues/7303
