### ISSUE TITLE
Uncaught Exception at: undefined error: TypeError: Cannot read property '_process' of undefined

### ISSUE THREAD

**Issue by frabbidgdean** [Azure/azure-sdk-for-node#5142]
Our project is using Azure service-bus and it is running into this uncaught exception which we have not faced before:

msg: Uncaught Exception at: undefined
error: TypeError: Cannot read property '_process' of undefined
at Connection._process (/app/node_modules/rhea/lib/connection.js:687:39)
at process._tickCallback (internal/process/next_tick.js:61:11)

Node version: v10.16.3
rhea version: 1.0.12
Azure version: 2.3.1-preview

**Comment by ramya-rao-a** [comment]
@frabbidgdean Can you share the name of the package you are using to communicate with Service Bus?

**Comment by ramya-rao-a** [comment]
Assuming you are using the `@azure/service-bus` package, we would recommend you upgrade to the latest version 1.1.6 which we shipped last week. This update has improvements on connection reliability in general.

Also, for future issues and feedback, please log an issue in https://github.com/Azure/azure-sdk-for-js which is the home for the `@azure/service-bus` package
