### ISSUE TITLE
request is deprecated

### ISSUE THREAD

**Issue by Richienb** [Azure/azure-sdk-for-node#5146]
See https://github.com/microsoft/appcenter-cli/issues/761

**Comment by qiaozha** [comment]
@nickzhums  How should we fix the dependency deprecated in node sdk now?

**Comment by nickzhums** [comment]
@Richienb Hi, Node.JS SDK is deprecated and we encourage you to use the JavaScript SDK:

https://github.com/Azure/azure-sdk-for-js

We will only do major security fixes for Node.JS SDK in the meantime, maybe you could share more context in this dependency update?

Thanks

**Comment by lirenhe** [comment]
Close it as there is no update for a year. Please use JavaScript SDK.
