### ISSUE TITLE
release new version of ms-rest

### ISSUE THREAD

**Issue by forsen** [Azure/azure-sdk-for-node#5147]
Please release a new version of `ms-rest`. The current version includes a malformed json file which breaks flow on our CI. 

The current version on NPM: 2.5.3 released "9 months ago"
Fix for the json file: October 2019 (~ 4 months ago)

The file with error: https://github.com/Azure/azure-sdk-for-node/blob/bffb85b3faac7ff0a2074ab8abb17f67e5eb46b9/runtime/ms-rest/.vscode/launch.json

The file after fix: https://github.com/Azure/azure-sdk-for-node/runtime/ms-rest/.vscode/launch.json

**Comment by qiaozha** [comment]
we have already released ms-rest 2.5.4. This problem should've been fixed now.

**Comment by forsen** [comment]
It is, thanks!
