### ISSUE TITLE
connect ETIMEDOUT serviceBusError at receiveMessages

### ISSUE THREAD

**Issue by catch2kk** [Azure/azure-sdk-for-node#5150]
Reading messages from service bus queue using "@azure/service-bus" in Azure function with node js. Some times getting error **connect ETIMEDOUT** error.  So how to  solve this issue.  

Exception: ServiceBusError: ServiceUnavailableError: connect ETIMEDOUT 40.116.115.21:4671
Stack: ServiceBusError: ServiceUnavailableError: connect ETIMEDOUT 40.116.115.21:4671
    at serviceBusQueueReader.getMessageReceiver.receiveMessages.then.catch.error

**Comment by ramya-rao-a** [comment]
Thanks for reporting @catch2kk 

Please use the latest version i.e 1.1.6 of the `@azure/service-bus` package which was shipped last week. This has improvements on connection reliability in general.

Also, for future issues and feedback, please log an issue in https://github.com/Azure/azure-sdk-for-js which is the home for the `@azure/service-bus` package

The ServiceUnavailableError points at network issues, so the recommendation would be to have retries from your end
