### ISSUE TITLE
[AzureStack]-azure-keyvault dataplane client does not honor custom cloud settings like login endpoint / TokenAudience

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-sdk-for-node#5151]
azure-keyvault package is not hornoring custom cloud settings like login endpoint and token audience. Azurestack has different endpoints and  token audience for each cloud deployments. Adfs enviornment has a diiferent URL for login as well.

Package version
    "azure-keyvault": "^3.0.5",

To repro 
git clone https://github.com/jongio/storage-node-resource-provider-getting-started.git
cd storage-node-resource-provider-getting-started
npm install
---set azurestack related environmental variables
node index.js

The following is how we call in to keyvault API

https://github.com/jongio/storage-node-resource-provider-getting-started/blob/master/index.js#L113

The call fails with 

(node:626212) UnhandledPromiseRejectionWarning: Error: Instance Discovery request returned http error: 400 and server response: {"error":"invalid_instance","error_description":"AADSTS50049: Unknown or invalid instance.\r\nTrace ID: 6aab0d52-a5d8-4822-9072-94417b7b0a00\r\nCorrelation ID: acacf856-857f-4cc7-9a37-116b5a66a0ca\r\nTimestamp: 2020-04-28 22:56:43Z","error_codes":[50049],"timestamp":"2020-04-28 22:56:43Z","trace_id":"6aab0d52-a5d8-4822-9072-94417b7b0a00","correlation_id":"acacf856-857f-4cc7-9a37-116b5a66a0ca","error_uri":"https://login.windows.net/error?code=50049"}
    at Logger.createError (D:\github3\storage-node-resource-provider-getting-started\node_modules\adal-node\lib\log.js:216:13)
    at Request._callback (D:\github3\storage-node-resource-provider-getting-started\node_modules\adal-node\lib\util.js:130:25)
    at Request.self.callback (D:\github3\storage-node-resource-provider-getting-started\node_modules\request\request.js:187:22)
    at Request.emit (events.js:189:13)
    at Request.<anonymous> (D:\github3\storage-node-resource-provider-getting-started\node_modules\request\request.js:1044:10)
    at Request.emit (events.js:189:13)
    at IncomingMessage.<anonymous> (D:\github3\storage-node-resource-provider-getting-started\node_modules\request\request.js:965:12)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:626212) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:626212) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Azurestack supports only 2016-10-01 api version for keyvault data plane and we are in need of using the azure-keyvault package. We cannot use any of the newer packages.

**Comment by jongio** [comment]
We got this working with azure-keyvault v1.0.0 and setting validateAuthority to false
```
"dependencies": {
    "azure-keyvault": "^1.0.0"
  }
var KeyVault = require("azure-keyvault");
var AuthenticationContext = require("adal-node").AuthenticationContext;
 
var clientId = "";
var clientSecret = "";
var vaultUri =
  "https://testkv.adminvault.redmond.azurestack.corp.microsoft.com/";
 
// Authenticator - retrieves the access token
var authenticator = function (challenge, callback) {
  // Create a new authentication context.
  var context = new AuthenticationContext(challenge.authorization, false);
 
  // Use the context to acquire an authentication token.
  return context.acquireTokenWithClientCredentials(
    challenge.resource,
    clientId,
    clientSecret,
    function (err, tokenResponse) {
      if (err) throw err;
      // Calculate the value to be set in the request's Authorization header and resume the call.
      var authorizationValue =
        tokenResponse.tokenType + " " + tokenResponse.accessToken;
 
      return callback(null, authorizationValue);
    }
  );
};
 
var credentials = new KeyVault.KeyVaultCredentials(authenticator);
var client = new KeyVault.KeyVaultClient(credentials);
client.createKey(vaultUri, "mykey", "RSA", function (err, keyBundle) {
  // Retrieve the key
  console.log(err);
  console.log(keyBundle);
});
```

**Comment by ramya-rao-a** [comment]
Thanks @jongio 

Closing this issue with two takeaways
- To support Keyvault service api versions older than v7, one needs to use v1 of azure-keyvault as the later versions of the package only support v7 of the service api
- For auth, one needs to use the `KeyvaultCredentials` when creating the client instead of the credentials from any of the normal login methods of `ms-rest-azure`.  #5153 tracks the need to clarify this in the package readme
