### ISSUE TITLE
Cannot find module 'moment' when using azure-arm-resource package

### ISSUE THREAD

**Issue by caleteeter** [Azure/azure-sdk-for-node#5154]
When using the [azure-arm-resource](https://www.npmjs.com/package/azure-arm-resource) package in my typescript project, I am now getting exceptions that the moment module cannot be found.

```
node_modules/azure-arm-resource/lib/feature/models/index.d.ts:10:25 - error TS2307: Cannot find module 'moment'.

10 import * as moment from "moment";
                           ~~~~~~~~

node_modules/azure-arm-resource/lib/link/models/index.d.ts:10:25 - error TS2307: Cannot find module 'moment'.

10 import * as moment from "moment";
                           ~~~~~~~~

node_modules/azure-arm-resource/lib/lock/models/index.d.ts:10:25 - error TS2307: Cannot find module 'moment'.

10 import * as moment from "moment";
                           ~~~~~~~~

node_modules/azure-arm-resource/lib/management/models/index.d.ts:13:25 - error TS2307: Cannot find module 'moment'.

13 import * as moment from 'moment';
                           ~~~~~~~~

node_modules/azure-arm-resource/lib/policy/models/index.d.ts:10:25 - error TS2307: Cannot find module 'moment'.

10 import * as moment from "moment";
                           ~~~~~~~~

node_modules/azure-arm-resource/lib/resource/models/index.d.ts:10:25 - error TS2307: Cannot find module 'moment'.

10 import * as moment from "moment";
                           ~~~~~~~~

node_modules/azure-arm-resource/lib/subscription/models/index.d.ts:10:25 - error TS2307: Cannot find module 'moment'.

10 import * as moment from "moment";
                           ~~~~~~~~
```

Looking a bit deeper at this, the moment reference is not used in these typings files which are generated from AutoRest Code Generator.  

To test I removed these references to moment in each of the typing files manuallly and the issue is resolved.  Can we have this code generated output fixed to remove packages that are not used?

**Comment by caleteeter** [comment]
Appears to be a break from moment v2.25.0, reverting back to v2.24.0 works fine.

**Comment by qiaozha** [comment]
Thanks for reporting this, I will follow up on this.

**Comment by qiaozha** [comment]
Hi, I notived that the latest version of azure-mgmt-resource is 7.3.0, when I run npm install. the moment package will be include in the package-lock.json Can you give it a try to see if it works?

**Comment by qiaozha** [comment]
@caleteeter Hi,  I have removed the invalid reference in latest release. https://www.npmjs.com/package/azure-arm-resource/v/7.4.0 You may have a try and see if it works.

**Comment by ramya-rao-a** [comment]
@qiaozha, Can we close this now that https://github.com/Azure/azure-sdk-for-node/pull/5173 is merged?

**Comment by qiaozha** [comment]
Yeah. I think so
