### ISSUE TITLE
xmlbuilder 0.4.3 is prone to security vulnerabilities

### ISSUE THREAD

**Issue by darshanhs90** [Azure/azure-sdk-for-node#5159]
We use msportalfx-test node package for our UI Unit testing, which has azure-common as a dependency.
As Azure-common uses the following node package (xml-builder @0.4.3) , we are getting flagged for security vulnerabilitities associates with this package.

Can this be updated to any latest versions of this library?

**Comment by qiaozha** [comment]
Thanks for reporting this, I will take a look at this ASAP.

**Comment by ramya-rao-a** [comment]
@qiaozha, Can we close this now that we have updated the version of xml-builder being used in this repo?

**Comment by qiaozha** [comment]
Yeah. I think so. @darshanhs90  Feel free to reopen the issue if the new package still has problem.
