### ISSUE TITLE
ms-rest-azure changelog

### ISSUE THREAD

**Issue by deasems** [Azure/azure-sdk-for-node#5161]
Where can the changelog for releases be found? I'm looking for what changed in the 3.0.0 release but not finding anything in the releases tab or changelog file.

**Comment by qiaozha** [comment]
@ramya-rao-a  Hi， Is this  ms-rest-azure supported by data-plane team?

**Comment by ramya-rao-a** [comment]
@deasems, 
You can find the changelog for ms-rest-azure at https://github.com/Azure/azure-sdk-for-node/blob/master/runtime/ms-rest-azure/Changelog.md

@qiaozha, 
https://github.com/Azure/azure-sdk-for-node/pull/5165 brings the changelog up to date. Can you review and merge?

**Comment by qiaozha** [comment]
> @deasems,
> You can find the changelog for ms-rest-azure at [/runtime/ms-rest-azure/Changelog.md@`master`](https://github.com/Azure/azure-sdk-for-node/blob/master/runtime/ms-rest-azure/Changelog.md) [](/Azure/azure-sdk-for-node/blob/HEAD@{2020-05-26T05:20:12Z}/runtime/ms-rest-azure/Changelog.md)
> 
> @qiaozha,
> #5165 brings the changelog up to date. Can you review and merge?

Sure, I will review it.

**Comment by ramya-rao-a** [comment]
The PR has been merged, thanks @qiaozha
