### ISSUE TITLE
No support for aeg-sas-token

### ISSUE THREAD

**Issue by Tubbie** [Azure/azure-sdk-for-node#5162]
I am working with Event grid and want to authenticate the publisher with SAS token. There is no support for this in the library.

**Comment by qiaozha** [comment]
@Tubbie  Hi, Could you tell me which sdk package are you using?

**Comment by Tubbie** [comment]
Hi @qiaozha Thanks for the reply.
Sorry I am bit late to answer.
I have created a PR - https://github.com/Azure/azure-sdk-for-node/pull/5178
And I have referred  this for the code:
https://docs.microsoft.com/en-us/azure/event-grid/security-authentication

**Comment by qiaozha** [comment]
@ramya-rao-a hi, Looks like this PR is about ms-rest-azure. Could you take a look at it?

**Comment by qiaozha** [comment]
> @ramya-rao-a hi, Looks like this PR is about ms-rest-azure. Could you take a look at it?

After you approve this PR. I can help to merge it.

**Comment by ramya-rao-a** [comment]
Thanks for reporting @Tubbie 

Looks like what you have in your PR can be used in your application as a workaround as well i.e create the class `TopicSASCredentials` extending `ApiKeyCredentials`.

Both `ms-rest-azure` and the `azure-eventgrid` packages are in a maintainence mode where we are doing bug & security fixes only.

The `@azure/eventgrid` package is the replacement for `azure-eventgrid`. We have just started working on the next version of `@azure/eventgrid` where we will ensure that both `aeg-sas-token` and `aeg-sas-key` are supported. https://github.com/Azure/azure-sdk-for-js/issues/9685 is the issue I have logged which you can subscribe to for further updates.

For now, I would recommend using what you have in the PR as a workaround in your code.

Thanks again for the links and the PR, it helped in clarifying the issue

**Comment by Tubbie** [comment]
Hi @ramya-rao-a That's what exactly I did and hence the PR. Thank you for the reply and clarification. 
Thank you @qiaozha for quick action on it. :)

**Comment by ramya-rao-a** [comment]
Hello!

We have recently released a new beta for the Event Grids package. 
Please see [Introducing the new Azure Event Grid Client Libraries with CloudEvents v1.0 Support](https://devblogs.microsoft.com/azure-sdk/event-grid-client-libraries/) for the broader announcement

Also,  https://github.com/Azure/azure-sdk-for-js/issues/9685 is now closed as the latest beta does support the aeg-sas-token that is being talked about in this issue.

Please try out the new [`@azure/eventgrid` version 3.0.0-beta.1](https://www.npmjs.com/package/@azure/eventgrid/v/3.0.0-beta.1) and share any feedback you have via issues in the https://github.com/Azure/azure-sdk-for-js repo
