### ISSUE TITLE
Is there any sample code for generating thumbnails?

### ISSUE THREAD

**Issue by Jason446620** [Azure/azure-sdk-for-node#5163]
Microsoft has official .net sample code for generating thumbnails. I carefully read the source code of azure-sdk-for-node. I only see models that define JpgImage and PngImage, but there is no code for generating thumbnails. (Azure-Media-Service, Not Compute Vision)

If there are related documents or codes, I hope to update them. Thank you.

**Comment by qiaozha** [comment]
@nickzhums  Can you take a look at this issue? Thanks

**Comment by nickzhums** [comment]
@Jason446620 could you share the link of .NET sample for generating thumbnails? 
Did you also check the Azure REST API ? (https://docs.microsoft.com/en-us/rest/api/azure/)

**Comment by Jason446620** [comment]
@nickzhums  I have read the link (computer vision) you given before I ask the question.  .NET sample for generating thumbnails.  https://docs.microsoft.com/en-us/azure/media-services/previous/media-services-dotnet-generate-thumbnail-with-mes

**Comment by nickzhums** [comment]
I believe these docs are maintained by Azure Media Services and not us, I will route them instead @Jason446620

**Comment by akucer** [comment]
@Jason446620 - It is not clear what exactly you are looking for. There are the following Media Services samples that illustrate how to create thumbnails (the first v2 one that you already identified).
Here is a [V2 example](https://docs.microsoft.com/en-us/azure/media-services/previous/media-services-dotnet-generate-thumbnail-with-mes) of generating thumbnails.
Here is a [V2 sprite](https://docs.microsoft.com/en-us/azure/media-services/previous/generate-thumbnail-sprite) example for generating thumbnails.
Here is a [V3 example](https://docs.microsoft.com/en-us/azure/media-services/latest/customize-encoder-presets-how-to) of generating both thumbnails and MBR content.

Thumbnails are typically just individual image files (Jpg, png, etc.)

Please provide additional context if this doesn't answer your question.
