### ISSUE TITLE
Missing docs for azure-sb package

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-node#5180]
`azure-sb` is the legacy package for Service Bus

Interestingly, it has code to support the Notification Hubs service as well, and therefore is not legacy on that front.

We plan to copy out the Notification Hubs code from this package to a separate package soon. But meanwhile, API reference docs for this package needs to show up under [Notification Hubs](https://docs.microsoft.com/en-us/javascript/api/overview/azure/notification-hubs?view=azure-node-latest) for current users of `azure-sb`

If possible, reference docs for `azure-sb` should show up under "Service Bus" but under the "Legacy" moniker.

cc @scbedd

**Comment by scbedd** [comment]
@ramya-rao-a thanks for the early heads up. I'm reading two requests here.

1. Are you asking that I move `azure-sb` under `Notification Hubs` under the `latest` moniker right now?
2. Add `azure-sb` under `Service Bus` under `legacy` moniker.

**Comment by ramya-rao-a** [comment]
On second thoughts...

Let's go with 2) for now.
The splitting of Notification Hubs code from azure-sb to a new package should happen sooner than later. So, you can skip 1)

I'll log a separate request once the new package is out to get the ref docs generated for it under Notification Hubs

**Comment by scbedd** [comment]
I have added `azure-sb` to legacy CI, and added it to the ToC in [this commit](https://github.com/MicrosoftDocs/azure-docs-sdk-node/commit/e6e69e233646a4cfebd0adb0310d5fe496b20f90) as well. I'd very much like to include the legacy `readme`. 

@ramya-rao-a Can you show me where `azure-sb` last published from so I can grab the readme and add it manually once?

**Comment by ramya-rao-a** [comment]
Package link: https://www.npmjs.com/package/azure-sb
Source code readme: https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/serviceBus/README.md

**Comment by scbedd** [comment]
Added `azure-sb` readme in [this commit](https://github.com/MicrosoftDocs/azure-docs-sdk-node/commit/6724e68cc208096052b4b2d73b70fac90bab0188)

**Comment by scbedd** [comment]
Updates merged for this.

**Comment by ramya-rao-a** [comment]
Thanks @scbedd!

I can see the docs at https://docs.microsoft.com/en-us/javascript/api/azure-sb/?view=azure-node-legacy
