### ISSUE TITLE
v0.9.23 published to NPM an hour ago introduces: Cannot find module 'xmlbuilder/lib/XMLBuilder'

### ISSUE THREAD

**Issue by freshlogic** [Azure/azure-sdk-for-node#5181]
Error: Cannot find module 'xmlbuilder/lib/XMLBuilder'
Require stack:
- /azure-common/lib/util/patch-xmlbuilder.js

**Comment by freshlogic** [comment]
Reproduction created here: https://github.com/Azure/azure-sdk-for-node/pull/5179#issuecomment-662212263

**Comment by rnpramasamy** [comment]
Yesterday azure-sb was working and Installed this package again in the new package, I got below error

Error: Cannot find module 'xmlbuilder/lib/XMLBuilder'

**Comment by ChuckLangford** [comment]
+1 on this issue

**Comment by ramya-rao-a** [comment]
@qiaozha Can we close this issue now that you have reverted the change that introduced this bug and released an update?

**Comment by qiaozha** [comment]
sure  https://www.npmjs.com/package/azure-common/v/0.9.24
