### ISSUE TITLE
The link is broken

### ISSUE THREAD

**Issue by amit12cool** [Azure/azure-sdk-for-node#5191]
Please update the link below:-
https://github.com/Azure/azure-sdk-for-node/blob/master/Documentation/DummyCerts.md

**Comment by qiaozha** [comment]
@ramya-rao-a Do you have any idea what that link might be?

**Comment by ramya-rao-a** [comment]
No idea..

@amit12cool Can you share where you found the above link?

**Comment by amit12cool** [comment]
@ramya-rao-a I don't remember now. Will try to go nd.

**Comment by lirenhe** [comment]
Close it as there is no update since last year.
