### ISSUE TITLE
How to get az-cli context or az-PowerShell context?

### ISSUE THREAD

**Issue by cveld** [Azure/azure-sdk-for-node#5199]
How can we get the current az-cli context or az-PowerShell context from within a nodejs Azure workload?

https://azure.github.io/azure-sdk-for-node/Documentation/Authentication.md currently gives a 404.

https://github.com/Azure/azure-sdk-for-node/blob/master/Documentation/Authentication.md does not describe a way to reuse the existing contexts.

Related: Can we run nodejs workloads within Azure Pipelines using an Azure Service Connection?

```
child_process.exec('az account get-access-token', (error, stdout, stderr) => {
    if (error) {
        console.log(`error: ${error.message}`);
        return;
    }
    if (stderr) {
        console.log(`stderr: ${stderr}`);
        return;
    }
    console.log(`stdout: ${stdout}`);
    var json = JSON.parse(stdout);
    console.log(`accessToken: ${json.accessToken}`)
    main(json.accessToken);
});
```

I am able to fetch the access token. But how do I initialize the library with this?

_update_

I read the docs on https://github.com/Azure/ms-rest-nodeauth and there actually is a built-in feature to work with the az-cli!

```typescript
import { AzureCliCredentials } from "@azure/ms-rest-nodeauth";
const creds = await AzureCliCredentials.create();
const client = new ServiceClient(creds);
```

Remaining question:
How to get the currently selected subscriptionId?

**Comment by ramya-rao-a** [comment]
Thanks for the question @cveld and apologies for not responding sooner.

Have you figured out how to get the currently selected subscriptionId or do you still need help with that?

**Comment by lirenhe** [comment]
No update for 1 month. Close this item and @cveld, please let us know if you have more information for this ask.
