### ISSUE TITLE
Usage of SDK vs REST API in NodeJS Azure Function

### ISSUE THREAD

**Issue by cpatil7** [Azure/azure-sdk-for-node#5204]
Using Azure SDK for enabling managed identity in the NodeJS function app. These SDKs increased the size of our function app by almost 3mb, which resulted in a high startup time. We then moved to using REST API to make calls for managed identity. Question is are these SDK libraries optimized for size?

**Comment by ramya-rao-a** [comment]
Thanks for reporting @cpatil7 and apologies for not responding sooner.

Can you share which Azure SDK did you end up using in the function app?

**Comment by lirenhe** [comment]
@cpatil7, we didn't get your response for some time and we will close this item.
Feel free to reopen it if you have more information. Thanks

**Comment by ramya-rao-a** [comment]
Hello @cpatil7 

As part of https://github.com/Azure/azure-sdk-for-js/issues/14346, we are moving the `@azure/identity` features that have native dependencies separate extension packages. This should help with the package size. You can try out the new v2 of the slimmed down `@azure/identity`, but please note that it is still in beta. It should go GA in the coming months
