### ISSUE TITLE
Azure-storage leaking all of dom

### ISSUE THREAD

**Issue by alexrecuenco** [Azure/azure-sdk-for-node#5206]
I am developing using the azure storage and since you are using `/// ... lib="dom"` it leaks all of the dom.

We had some oustanding issues because of that, unable to have our linters catch issues ahead of time

**Comment by ramya-rao-a** [comment]
Can you clarify the name of the package you are using?

The storage packages in this repository are deprecated. Please use the below packages instead
- `@azure/arm-storage` for managing your Storage account
- `@azure/storage-blob` for working with Storage Blob
- `@azure/storage-queue` for working with Storage Queue

If you are not able to upgrade for any reason, please feel free to send a pull request to fix the issue you are facing.
