### ISSUE TITLE
Fix for underscore vulnerability

### ISSUE THREAD

**Issue by skhilliard** [Azure/azure-sdk-for-node#5208]
We are currently using the latest version (0.11.1) of the azure-sb library (https://www.npmjs.com/package/azure-sb).   There is now an underscore vulnerability (via the paths azure-sb > underscore, azure-sb > azure-common > underscore) that needs to be addressed (https://npmjs.com/advisories/1674).

Are there any plans to update this library to patch this?

Thanks,
Kelly

**Comment by lirenhe** [comment]
cc @nickzhums

**Comment by dw511214992** [comment]
@skhilliard please use the latest package. thanks

**Comment by skhilliard** [comment]
@dw511214992 Thank you, I have.  I appreciate everyone's efforts in resolving this issue!
