### ISSUE TITLE
ReDoS vulnerability in validator js

### ISSUE THREAD

**Issue by naveentej** [Azure/azure-sdk-for-node#5215]
Regular Expression Denial of Service (ReDoS) in validator@9.4.1 => fixed in version 13.7.0.

https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090599
https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090600
https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090601
https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090602

azure-common needs an update.

**Comment by qiaozha** [comment]
close it as resolved with latest release. Thanks
