### ISSUE TITLE
Critical Component Governance Vulnerability in json-schema 0.2.3 in ms-rest

### ISSUE THREAD

**Issue by WilliamMichelMSFT** [Azure/azure-sdk-for-node#5218]
My team got a critical security alert from component governance about json-schema 0.2.3. 

There are no suggestions for mitigation, and we are using the latest version of ms-rest (2.5.4)

Can this dependency issue be mitigated on the library side?

**Comment by WilliamMichelMSFT** [comment]
![image](https://user-images.githubusercontent.com/82683212/141860743-a784dc7b-953f-481e-8e20-253c7856cf9f.png)

**Comment by qiaozha** [comment]
close it as resolved with latest release. Thanks
