### ISSUE TITLE
I want to generate a video meeting link. Does this lib supports video calling?

### ISSUE THREAD

**Issue by tahir-jamil** [Azure/azure-sdk-for-node#5219]

**Comment by qiaozha** [comment]
@tahir-jamil Could you be more specific about your question ? which package in npm are you refering to ? 
Please note that all the packages inside this repo have been deprecated in favor of [azure-sdk-for-js repo](https://github.com/Azure/azure-sdk-for-js), it's not recommend to use packages inside this repo.
