### ISSUE TITLE
Vulnerability - Json Schema Prototype Pollution

### ISSUE THREAD

**Issue by naveentej** [Azure/azure-sdk-for-node#5221]
https://snyk.io/vuln/SNYK-JS-JSONSCHEMA-1920922

Dependency chain => azure-common@0.9.26,request@2.88.2,http-signature@1.2.0,jsprim@1.4.1,json-schema@0.2.3

**request** is now deprecated and http-signature has an update that addresses this vulnerability (fixed by json schema @0.4.0)

**Comment by qiaozha** [comment]
close it as resolved with latest release. Thanks

**Comment by rodrigorodriguez** [comment]
@qiaozha, same for ms-rest-azure > request@2.88.2: request has been deprecated, see request/request#3142. Would you update?
