### ISSUE TITLE
Vulnerability -  Inefficient Regular Expression Complexity in validator.js

### ISSUE THREAD

**Issue by skhilliard** [Azure/azure-sdk-for-node#5222]
Moderate        Inefficient Regular Expression Complexity in validator.js     

  Package         validator                                                     

  Patched in      >=13.7.0                                                      

  Dependency of   azure-sb                                                      

  Path            azure-sb > azure-common > validator                           

  More info       https://github.com/advisories/GHSA-qgmg-gppg-76g5

**Comment by qiaozha** [comment]
close it as resolved with latest release. Thanks

**Comment by DavidTMann** [comment]
> close it as resolved with latest release. Thanks

This vulnerability was not resolved in the azure-sb library, will this fix be scheduled in there?
