### ISSUE TITLE
CDK for infrastructure as code

### ISSUE THREAD

**Issue by sjuarezgx** [Azure/azure-sdk-for-node#5226]
I've searched on the documentation and I didn't see any solution for infrastructrure as code, such as the AWS CDK.
I know there is Bicep - a declarative language - but we would like to you have a CDK to use a programming language familiar with us ,like node.
I'd like to know if there are any plans of having a CDK and what are your recommendations.

Thanks

**Comment by sjuarezgx** [comment]
We need something like [AWS CDK](https://aws.amazon.com/cdk/) or [CDK for Terraform](https://github.com/hashicorp/terraform-cdk), by Azure. 
Just to use any programming language that we are familiar with, like .Net, Typescript, etc, for our IaC
The problem of Bicep is that it uses declaratives instructions, and we cannot invest in learning a new language now, among other benefits that we'd have by using an imperative language for IaC instead of a declarative language.

**Comment by alex-frankel** [comment]
As of now, there are no plans to build a CDK equivalent for Azure deployments. If you are comfortable using .NET, you might be interested in the [Farmer project](https://github.com/CompositionalIT/farmer), which allows you to describe your infra in C# or F#.

**Comment by sjuarezgx** [comment]
OK, thanks for your reply
What are your recommendations about the [CDK for Terraform](https://learn.hashicorp.com/tutorials/terraform/cdktf)?

**Comment by sjuarezgx** [comment]
Ok, thanks.
