### ISSUE TITLE
data-model-dependency-telemetry does not support type: "ServiceBus" 

### ISSUE THREAD

**Issue by vinutha93bnvs** [Azure/azure-sdk-for-node#5229]
My application is a micro-service architecture based Node JS application. 
Using Azure SB SDK & AppInsights SDK to monitor.

Application 1 sends messages to Application 2 via Service Bus.
there is no dependency tracking in appInsights to understand the request tracking. 
 Neither operation ID is being tracked to understand the Application 1 --> ServiceBus --> Application 2

**Comment by lirenhe** [comment]
Looks this is a data-plane ask, @qiaozha, could you help to find the correct owner?
