### ISSUE TITLE
npm audit reported about a vulnerability in "async" dependency

### ISSUE THREAD

**Issue by AntonTimiskov** [Azure/azure-sdk-for-node#5230]
async  <2.6.4
Severity: high
Prototype Pollution in async - https://github.com/advisories/GHSA-fwr7-v2mv-hh25

How to fix: update the dependency to the latest version.

**Comment by bwateratmsft** [comment]
The pinning to exactly 2.6.0 of `async` is preventing us in the Azure Account extension for VSCode from fixing this.

**Comment by lirenhe** [comment]
@qiaozha, could you help to take a look?
