### ISSUE TITLE
Local git deployment does not synchronously delete files (Linux webapp)

### ISSUE THREAD

**Issue by lc-lc0304** [Azure/azure-sdk-for-node#5245]
Hi Team:
We have encountered a difficulty, please assist.

We are using the Linux app service and the development language is node. After deleting a file locally and deploying it to the cloud, it will not be deleted in real time. We are very confused.
Using the Windows app service, after deleting a file locally, it is deleted in real-time on the cloud.

Please tell us the reason. Thank you very much. Cheers!

**Comment by lc-lc0304** [comment]
Hi Deyaaeldeen:

Thank you for your reply. Our App service name is dnitest deployment, and we are using the development language PHP, version 8.0, and Linux system

Thanks!

**Comment by deyaaeldeen** [comment]
Thanks for sharing! Could you please open an Azure ticket? https://azure.microsoft.com/en-us/support/create-ticket/
I will close this issue for now since it seems unrelated to the Azure SDK for JS.

**Comment by lc-lc0304** [comment]
Hi:

We have already raised the work order, and the engineers over there have also encountered the same problem during testing. Does our Linux app service not support real-time synchronization of Git? Windows is fine, thank you.

**Comment by deyaaeldeen** [comment]
Thanks for sharing. This issue is best tracked in the Azure ticket. Please let us know if you have any SDK questions.
