### ISSUE TITLE
Local git deployment does not synchronously delete files (Linux webapp)

### ISSUE THREAD

**Issue by lc-lc0304** [Azure/azure-sdk-for-node#5246]
Hi Team:
We have encountered a difficulty, please assist.

We are using the Linux app service and the development language is php. After deleting a file locally and deploying it to the cloud, it will not be deleted in real time. We are very confused.
Using the Windows app service, after deleting a file locally, it is deleted in real-time on the cloud.

We have already raised the ticket, and the engineers over there have also encountered the same problem during testing. Does our Linux app service not support real-time synchronization of Git? Windows is fine, thank you.

Please tell us the reason. Thank you very much. Cheers!

**Comment by deyaaeldeen** [comment]
Thanks for sharing. This issue is best tracked in the Azure ticket. Please let us know if you have any SDK questions.
