### ISSUE TITLE
cspack.js

### ISSUE THREAD

**Issue by glennblock** [Azure/azure-sdk-for-node#733]
Dev Estimate: 20
Test Estimate: 0

**Comment by matiaslarsson** [comment]
+1

**Comment by gscott** [comment]
It seems like at this point we're all "overtaken by events."

if you want the full Microsoft easy deploy, proprietary "magic in a box" experience, do [web apps] (https://azure.microsoft.com/en-us/documentation/scenarios/web-app/). You'll get that end-to-end Visual Studio + Cloud warm Microsofty feeling.

If you were driving the Paas/cloud services at a lower layer like I am (and thus why I  wanted cspack to run on something non-Windows so I could use, say, Travis or another Linux-based platform for cloud service deployment) then we really should move on.   Look into switching your app packaging approach from the proprietary cspack to a container approach.    By dropping cloud services for containers you open up all kinds of deployment tools and technologies for cluster management and scheduling of container deployment, including the upcoming Azure Container Service.    

But yes it's all super new and it's a new learning curve, so it's not an overnight thing.

**Comment by matiaslarsson** [comment]
@gscott Well spoken! I need to use other ports than port 80 so I need to deploy to an Azure Cloud Service. It seems unnecessary hard to do, even when the code is in a Visual Studio Online Git. Your container suggestion sure makes sense.
