### ISSUE TITLE
Add SAS creation support for more than blobs

### ISSUE THREAD

**Issue by gluwer** [Azure/azure-sdk-for-node#759]
At the moment SDK allows to create SAS for blobs, but the Azure Table/Queue Storage and Azure Service Bus also supports it. It would be nice to have it build in, as this is very error prone to create (all \n, naming etc.). At the moment the only possibility is to write the whole SAS creation procedure from scratch using REST API documentation as a guideline.

<p><a href="https://github.com/Azure/azure-sdk-for-node/issues/759">https://github.com/Azure/azure-sdk-for-node/issues/759</a></p>

**Comment by tony-gutierrez** [comment]
This is still an issue.
