### ISSUE TITLE
When sending notifications to GCM or APNS, the notification never comes through to the device even though the Notification Hub returns a success code

### ISSUE THREAD

**Issue by andrerod** [Azure/azure-sdk-for-node#970]
{"isSuccessful":true,"statusCode":201,"body":"","headers":{"transfer-encoding":"chunked","content-type":"application/xml; charset=utf-8","server":"Microsoft-HTTPAPI/2.0","date":"Thu, 15 Aug 2013 07:12:03 GMT"}}

The devices in question can receive push notifications from other sources, and in fact they can successfully receive push notifications from the push.apns/push.gcm modules used by my Mobile Service. The only problem is receiving the notification through the Notification Hub. I have verified that the Notification Hub settings are identical to the push settings in the Mobile Service (Apple push certificate, GCM API key).

**Comment by rbpinheiro** [comment]
I am reproducing this today.
If I send the push via manage.windowsazure.com it gets to the device.
If I send it via nodejs code it doesn't.

But I always get a success message:
{ isSuccessful: true,
  statusCode: 201,
  body: '',
  headers:
   { 'transfer-encoding': 'chunked',
     'content-type': 'application/xml; charset=utf-8',
     server: 'Microsoft-HTTPAPI/2.0',
     date: 'Tue, 27 Oct 2015 16:17:19 GMT' },
  md5: undefined }
