### ISSUE TITLE
ServiceBus.receiveQueueMessage() keeps failing to retrieve messages and causes MaxDeliveryCountExceeded exception

### ISSUE THREAD

**Issue by UzEE** [Azure/azure-sdk-for-node#983]
I'm polling for new messages on a Service Bus Queue after every couple of seconds. I retrieve messages with ```isPeekLock``` set to **true** and delete them once my processing is complete.

However, after the script runs for a certain amount of time, it stops retrieving new messages and keeps returning ```No messages to receive``` error, while the delivery count on the message keeps incrementing. This naturally causes the message to be moved to the Dead Letter queue since ```MaxDeliveryCountExceeded``` exception occurs.

This behavior is consistent even when I'm using a simple script separately just to debug this issue, though I'm sometimes able to retrieve the messages using the [Service Bus Explorer](http://code.msdn.microsoft.com/windowsazure/Service-Bus-Explorer-f2abca5a).

Here's the simple snippet of the method I'm using to check for new messages and it gets called by a **setTimeout()** timer every 5 seconds unless a message is found which is passed to the callback instead. The process again starts looking for new messages once the callback finishes processing the message.

```javascript
checkForMessages = function (callback) {

	self.sbService.receiveQueueMessage(processedQueue.name, { isPeekLock: true }, function (err, lockedMessage) {
		
		if (err) {

			if (err == &quot;No messages to receive&quot;) {
				winston.notice(err);
			}

			callback(err);

		} else {
			// Message received and locked
			callback(null, lockedMessage);
		}
	});
};
```

Also I haven't been able to find a documentatoin for a lot of features which are available on other platforms. Isn't the Node.js SDK at feature parity with other versions?<p><a href="https://github.com/Azure/azure-sdk-for-node/issues/983">https://github.com/Azure/azure-sdk-for-node/issues/983</a></p>

**Comment by vvo** [comment]
@andrerod @bradygaster @guangyang @azuresdkci any input?

**Comment by projectweekend** [comment]
I'm having a similar problem. Using a `stream.Readable` that calls `receiveQueueMessage` in its `_read` method. When I start piping the data, I get a message on the first pull, but then every call after that returns "No messages to receive".

**Comment by jacoscaz** [comment]
Same problem here using node 0.10.21 (old, I know, but that's a client-side requirement).

**Comment by vvo** [comment]
Issue about a "receiveQueueMessage" not receiving messages not updated by microsoft since newarly 2 years. NICE

**Comment by jtmilne** [comment]
@matt-gibbs @azuresdkci Any update on this issue?

**Comment by projectweekend** [comment]
Seriously

**Comment by djrosanova** [comment]
Are you ever completing the message? If you don't complete the message before the lock expires then the delivery count increments every time the message is re-read (and it will be placed back on the queue after the lock expires).

**Comment by jacoscaz** [comment]
Hey everyone. I know it's not ideal but you can access the queue via the amqp10 module and it works just fine.

**Comment by djrosanova** [comment]
Woa! Awesome. AMQP is a way better runtime experience from a latency perspective. Any blogs about this anywhere?

**Comment by jacoscaz** [comment]
Nope, and I haven't had the time to write a post of my own. Anyway, it's
pretty straightforward. Just `receive()` from
`/<topic-name>/Subscriptions/<sub-name>` and you're all set. You can build
a receive loop in 3 locs.


--

Jacopo Scazzosi
Developer
http://www.jacoscaz.com

**Comment by djrosanova** [comment]
I don't think the error is in the SDK here it is in the way the timeout is being used. This code works fine.

**Comment by tony-gutierrez** [comment]
How do you connect to SB with AQMP and using a SAS token?
