### ISSUE TITLE
Add Active Directory Graph API support

### ISSUE THREAD

**Issue by andrerod** [Azure/azure-sdk-for-node#997]
<p><a href="https://github.com/Azure/azure-sdk-for-node/issues/997">https://github.com/Azure/azure-sdk-for-node/issues/997</a></p>

**Comment by szarouski** [comment]
@yugangw-msft @guangyang @azuresdkci @andrerod what happened to active directory graph api support? I'm not sure what comment above means.
Thank you.

**Comment by amarzavery** [comment]
@szarouski - The graph library is out there. Please take a look at this [link](https://github.com/Azure/azure-sdk-for-node/tree/master/lib/services/graphManagement). Hope this helps.
